### ISSUE TITLE
Invalid type for parameter serviceCode, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

### ISSUE THREAD

**Issue by rracterr** [cloud-custodian/cloud-custodian#1814]
running:

    - name: ec2-tag-fix-env
      resource: ec2
      comment: |
         ec2-service-tag-value-to-lower
      query:
        - instance-state-name: running
      filters:
        - "tag:env": present
      actions:
        - type: rename-tag
          old_key: env
          new_key: environment

unhandled exception:

2017-11-20 18:06:57,246: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 337, in run
    results = a.process(resources)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/resources/account.py", line 564, in process
    ccEmailAddresses=self.data.get('notify', []))
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 579, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 634, in _convert_to_request_dict
    api_params, operation_model)
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter serviceCode, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
2017-11-20 18:06:57,496: c7n_org:ERROR Exception running policy:account-service-limits account:entsys-qa region:us-west-2 error:Parameter validation failed:
Invalid type for parameter serviceCode, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
> /root/custodian/local/lib/python2.7/site-packages/botocore/validate.py(291)serialize_to_request()
-> raise ParamValidationError(report=report.generate_report())

**Comment by kapilt** [comment]
the traceback here is against a different policy then the one referenced.
