### ISSUE TITLE
KeyError: u'flaggedResources'

### ISSUE THREAD

**Issue by gerardlynch-vmdb** [cloud-custodian/cloud-custodian#2402]
I've never used cloud-custodian before, and am attempting to follow the getting started guide with account-service-limits policy.

When attempting to do a dryrun I am getting a stackdump ending with `KeyError: u'flaggedResources'`

```
$ custodian version
0.8.28.2
$ cat custodian.yml
policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        threshold: 50
    actions:
      - type: request-limit-increase
        percent-increase: 25
```

```
$ export AWS_PROFILE=...
$ custodian run --dryrun --output-dir=. custodian.yml
018-05-15 17:47:25,372: custodian.commands:ERROR Error while executing policy account-service-limits, continuing
Traceback (most recent call last):
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/commands.py", line 237, in run
    policy()
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 703, in __call__
    resources = PullMode(self).run()
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 222, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 66, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/manager.py", line 90, in filter_resources
    resources = f.process(resources, event)
  File "/Users/9200779/git/bitbucket.org/vmdb/custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 432, in process
    checks['flaggedResources'] = [r for r in checks['flaggedResources']
KeyError: u'flaggedResources'
```

I have attempted python3 and python2, no change.

Any suggestions?

**Comment by thisisshi** [comment]
does your profile have access to Trusted Advisor?

**Comment by thisisshi** [comment]
this is odd actually, per the [docs](https://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeTrustedAdvisorCheckResult.html) flaggedResources should exist within the json response. I'm thinking this might be a permissions error

**Comment by kapilt** [comment]
which service limit are you trying to increase, i don't think we support just increasing all of them.

**Comment by gerardlynch-vmdb** [comment]
Thanks for the prompt responses.

My profile has AdministratorAccess, though I'm not sure we've got the license in place for Trusted Advisor yet (I will check that).  

I was just trying the example from the docs, http://capitalone.github.io/cloud-custodian/docs/usecases/accountservicelimit.html?highlight=resource%20limit  which states "The following example policy will find any service in your region that is using more than 50% of the limit and raise the limit for 25%." - to me that means it'll find any and all resources that are above the threshold and will try and bump them - Am I misinterpreting?

**Comment by kapilt** [comment]
I just ran your policy without issue in us-east-1 without issue.

two questions then, 

 - Do you have aws support enabled on the account (I think these apis require at least business level support)?
 - Which region are you executing against?

```
$ custodian run -c limits.yml -s out -v --dryrun
2018-05-16 06:58:23,130: custodian.commands:DEBUG Loaded file limits.yml. Contains 1 policies
2018-05-16 06:58:23,131: custodian.aws:DEBUG using default region:us-east-1 from boto
2018-05-16 06:58:23,374: custodian.output:DEBUG Storing output with <DirectoryOutput to dir:out/account-service-limits>
2018-05-16 06:58:23,374: custodian.policy:DEBUG Running policy account-service-limits resource: account region:us-east-1 c7n:0.8.28.2
2018-05-16 06:58:23,880: custodian.resources.account:DEBUG Filtered from 1 to 1 account
2018-05-16 06:58:23,880: custodian.policy:INFO policy: account-service-limits resource:account region:us-east-1 count:1 time:0.51
2018-05-16 06:58:23,880: custodian.output:DEBUG metric:ResourceCount Count:1 policy:account-service-limits restype:account scope:policy
2018-05-16 06:58:24,749: custodian.policy:INFO policy: account-service-limits action: requestlimitincrease resources: 1 execution_time: 0.87
```
