### ISSUE TITLE
C7N_Mailer attempting to resolve ldap when it isnt configured

### ISSUE THREAD

**Issue by jacob-kinzer** [cloud-custodian/cloud-custodian#2705]
We currently do not have our mailer setup to use ldap and our current configuration is:
```
queue_url: QUEUEURL
from_address: cloudcustodian-noreply@email.com
region: eu-west-1
debug: true
role: IAMROLE
contact_tags:
    - customTag:resource-owner
dead_letter_config:
 TargetArn: QUEUEARN
```
And we have some problems since we have added some new policies when the sqs messages comes in with sqs_message['resources']:
```
Traceback (most recent call last):
  File "/opt/c7n_mailer/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 176, in main
    processor.run()
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 126, in run
    self.process_sqs_message(sqs_message)
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 159, in process_sqs_message
    to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 234, in get_to_addrs_email_messages_map
    to_addrs_to_resources_map = self.get_email_to_addrs_to_resources_map(sqs_message)
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 213, in get_email_to_addrs_to_resources_map
    resource
  File "/opt/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 157, in get_resource_owner_emails_from_resource
    (uid) for uid in non_email_ids]))
AttributeError: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'
```
Sidenote: the line numbers are off from whats in the repository mainly cause i have some debug lines in the code currently so sorry about that

It looks like when the sqs messages has values for sqs_message['resources'] in *sqs_queue_processor.process_sqs_message* it ends up getting into *email_delivery.get_resource_owner_emails_from_resource* which ends up trying to call *.get_email_to_addrs_from_uid* on *self.ldap* which in our use case is set to None because we do not provide a *ldap_uri*.

It does seem to only happen on certain policies such as when we report absent tags on S3 buckets, but I'm not sure what dictates when a policy sends an SQS message to the queue with 'resources' or when it doesn't.

**Comment by jacob-kinzer** [comment]
@sri321 

We have a fork of CloudCustodian on our side that we just made a change to that seemed to fix the issue. But we never got around to digging too deep into if this was the 'correct' solution or not so we never asked for a merge back. The change we made was in email_delivery.py

````python
    def get_resource_owner_emails_from_resource(self, sqs_message, resource):
        if 'resource-owner' not in sqs_message['action']['to']:
            return []
        resource_owner_tag_keys = self.config.get('contact_tags', [])
        resource_owner_tag_values = get_resource_tag_targets(resource, resource_owner_tag_keys)
        explicit_emails = self.get_valid_emails_from_list(resource_owner_tag_values)

        # resolve the contact info from ldap
        non_email_ids = list(set(resource_owner_tag_values).difference(explicit_emails))
        if self.config.get('ldap_uri'):
            ldap_emails = list(chain.from_iterable([self.ldap_lookup.get_email_to_addrs_from_uid
                                                (uid) for uid in non_email_ids]))
        else:
            ldap_emails = []

return list(chain(explicit_emails, ldap_emails))
````

But like i said while this fixed our issue i dont know if its the correct way to go about fixing the problem. I just havent spent the time in the code to figure that out.

**Comment by cbarensfeld** [comment]
Can org_domain also be added to resource-owner like it is for event-owner?

```python
  # resolve the contact info from ldap
  non_email_ids = list(set(resource_owner_tag_values).difference(explicit_emails))

  if self.config.get('ldap_uri'):
      ldap_emails = list(chain.from_iterable([self.ldap_lookup.get_email_to_addrs_from_uid
                                          (uid) for uid in non_email_ids]))
  else:
      ldap_emails = []

  org_emails = []
  if self.config.get('org_domain', False):
      org_domain = self.config.get('org_domain', False)
      for id in non_email_ids:
          self.logger.debug('adding email %s to targets.', id + '@' + org_domain)
          explicit_emails.append(id + '@' + org_domain)

  return list(chain(explicit_emails, ldap_emails, org_emails))
```
