### ISSUE TITLE
requirements.txt needs to add setuptools>=24.3 in order to install on AmazonLinux2

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#2909]
As AmazonLinux2 will only install setuptools 0.9.8 via normal packaging, following the c7n install steps will result in failure, however upgrading setuptools past 24.3 solves the problem

**Comment by kapilt** [comment]
```
Downloading/unpacking python-dateutil>=2.1,<3.0.0 (from botocore>=1.10.48->c7n)
  Downloading python-dateutil-2.7.3.tar.gz (302kB): 302kB downloaded
  Running setup.py egg_info for package python-dateutil
    /c7n/build/python-dateutil/setup.py:19: UserWarning: python_requires requires setuptools version > 24.3
      UserWarning)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/c7n/build/python-dateutil/setup.py", line 86, in <module>
        "test": Unsupported
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/c7n/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/c7n/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 10, in version_keyword
      File "build/bdist.linux-x86_64/egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
    Complete output from command python setup.py egg_info:
    /c7n/build/python-dateutil/setup.py:19: UserWarning: python_requires requires setuptools version > 24.3```

tried it in a docker image for amazonlinux, and was able to reproduce.

**Comment by kapilt** [comment]
works out of the box if using python3 with amazonlinux2

```
$ yum install python3-pip python3-devel
$ pip install c7n
```
