### ISSUE TITLE
c7n-org | invalid resource type (all)

### ISSUE THREAD

**Issue by getsec** [cloud-custodian/cloud-custodian#2991]
Hello.

Anytime i invoke a custodian policy with c7n. I get the following trace:
```
$ c7n-org run -c accounts.yml  -u ../policies/operational/iam.yml  -s ../output/ --dryrun
2018-10-15 08:19:46,730: c7n_org:WARNING Error running policy in awsaccount-root @ ca-central-1 exception: Invalid resource type: iam-role
Traceback (most recent call last):
  File "C:\Python27\Scripts\c7n-org-script.py", line 11, in <module>
    load_entry_point('c7n-org==0.4.1', 'console_scripts', 'c7n-org')()
  File "c:\python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\c7n_org\cli.py", line 553, in run
    for p, count in f.result().items():
  File "c:\python27\lib\site-packages\concurrent\futures\_base.py", line 455, in result
    return self.__get_result()
  File "c:\python27\lib\site-packages\concurrent\futures\_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ValueError: Invalid resource type: iam-role
```

here is my policy:
```
policies:
- name: iam-roles-with-inline-policies
  resource: iam-role
  filters:
    - type: has-inline-policy
      value: True
```

and here is my config file:
```
accounts:
- account_id: '12345'
  email: awsaccount-root@company.com
  name: awsaccount-root
  regions:
  - ca-central-1
  role: arn:aws:iam::12345:role/AllowSecurityReadOrg
```

I can provide more information, I'm just not sure why this is happening. The policy invokes fine with custodian:
```
 custodian validate ../policies/operational/iam.yml
2018-10-15 08:22:39,704: custodian.commands:INFO Configuration valid: ../policies/operational/iam.yml

$ custodian run ../policies/operational/iam.yml  -s ../output/
2018-10-15 08:23:11,522: custodian.policy:INFO policy: iam-roles-with-inline-policies resource:iam-role region:ca-central-1 count:8 time:7.44
```

**Comment by kapilt** [comment]
its a little bit unclear if the issue here is related to windows, i ran that same policy locally with c7n-org without issue. i'd suggest trying to run it with `--debug` on windows which will remove the multi-process concurrency, alternatively use linux/osx/docker to run.

```
$ c7n-org run -c ~/accounts.yml -u iam.yml -s out -a app-dev --debug -v -r us-east-1
2018-10-18 00:41:58,052: c7n_org:DEBUG Running policy:iam-roles-with-inline-policies account:app-dev region:us-east-1
2018-10-18 00:42:22,057: c7n_org:INFO Ran account:app-dev region:us-east-1 policy:iam-roles-with-inline-policies matched:55 time:24.01
2018-10-18 00:42:22,058: c7n_org:INFO Policy resource counts Counter({'iam-roles-with-inline-policies': 55})
```

**Comment by getsec** [comment]
@kapilt  Weird story, I moved to an ec2 with virutalenv and the command run fine. Must have been a wierd issue with windows. I know i didnt find the issue to the underlying problem, but I'm working now.

**Comment by ebickle** [comment]
Ran into this on Windows as well. Running --debug showed a different underlying exception - "Unable to locate credentials".

It appears as though c7n-org is returning an "invalid resource type" error in situations where it can't authenticate with AWS. I suspect when @getsec moved to ec2 it started to work because c7n-org inherited the role from the instance.

In my case, I'm writing policies on my local machine and wanting to assume a role. Adding a "--profile" command line argument similar to c7n would help here. That way I could specify which AWS profile to use when running c7n-org and assume the various roles using that initial profile.
