### ISSUE TITLE
C7N_Mailer - Azure - Slack Delivery Issues

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3118]
### Description:
When trying to add slack delivery for specific policies in mailer.yml, resulting output shows an empty dictionary of slack recipients, and no notifications actually being sent to slack.

### Scrubbed Terminal Output:
```
2018-11-07 16:30:18,624: custodian.policy:INFO policy: azure-notify action: notify resources: 7 execution_time: 0.97
2018-11-07 16:30:19,964 - custodian-mailer - INFO - Downloading messages from the Azure Storage queue.
2018-11-07 16:30:20,193 - custodian.azure.session - INFO - Creating session with Service Principal Authentication
2018-11-07 16:30:20,193 - custodian.azure.session - INFO - Session using Subscription ID: XXXX
2018-11-07 16:30:21,194 - custodian-mailer - INFO - Sending account:XXXX policy:azure-notify azure.resourcegroup:7 email:slack to {}
2018-11-07 16:30:21,214 - custodian-mailer - INFO - No messages left on the azure storage queue, exiting c7n_mailer.
```
### Mailer.yml
```
queue_url: asq://samplequeue.queue.core.windows.net/samplequeue
sendgrid_api_key: sendgrid_key
from_address: me@myemail.com
slack_token: slack_token
```
### Sample Policy Being Run: 
```
policies:
  - name: azure-notify
    resource: azure.resourcegroup
    description: example policy
    actions:
      - type: notify
        template: slack
        priority_header: '2'
        subject: hello from the mailer
        to:
          - slack://myorganization.slack.com/#azure_alerts
        transport:
          type: asq
          queue: https://samplequeue.queue.core.windows.net/samplequeue
```
### Expected outcome:
- Better documentation on how to use slack as a message delivery mechanism with custodian, specifically in Azure
- Delivery of notifications to Slack from Cloud Custodian

**Comment by jdogg89** [comment]
Another note, it doesn't specify anywhere in the c7n_mailer documentation but it appears that from utils_email.py, Azure only support slack integration using a slack token based off of this function and it looking to see if the target starts with 'slack:' 
```
def is_email(target):
    if target is None:
        return False
    if target.startswith('slack://'):
        logger.debug("Slack payload, not an email.")
return False
```

**Comment by logachev** [comment]
Hi Justin,

Can you please double check if you have latest c7n_mailer installed?
Your configuration should work except for the `myorganization.slack.com/` part, its not required. 

`- slack://#azure_alerts` should be enough

**Comment by jdogg89** [comment]
@logachev @aluong (Tagging Andy as I've conversed with him on Gitter) Yes, I just setup a new virtual environment and installed the latest mailer from source. Here's the output from the run with using "slack://#azure_alerts":

```
custodian run --output-dir=. policy.yml && c7n-mailer --config mailer.yml --run
custodian.azure.session:INFO Creating session with Service Principal Authentication
custodian.azure.session:INFO Session using Subscription ID: mysubscriptionID
custodian.policy:INFO policy: azure-notify resource:azure.resourcegroup region: count:X time:0.57
custodian.azure.session:INFO Creating session with Service Principal Authentication
custodian.azure.session:INFO Session using Subscription ID: mysubscriptionID
custodian.actions:INFO sent message:XXXXXX policy:azure-notify template:default count:X
custodian.policy:INFO policy: azure-notify action: notify resources: X execution_time: 1.48
custodian-mailer - INFO - Downloading messages from the Azure Storage queue.
custodian.azure.session - INFO - Creating session with Service Principal Authentication
custodian.azure.session - INFO - Session using Subscription ID: mysubscriptionID
custodian-mailer - INFO - Sending account:mysubscriptionID policy:azure-notify azure.resourcegroup:X slack:slack_default to azure_alerts
custodian-mailer - INFO - Sending account:mysubscriptionID policy:azure-notify azure.resourcegroup:X email:default to {}
custodian-mailer - INFO - No messages left on the azure storage queue, exiting c7n_mailer.
```
Here is the output when trying to send it to ```https://hooks.slack.com/services/XXXX```:
```
custodian.azure.session - INFO - Session using Subscription ID: mysubscriptionID custodian-mailer - INFO - Sending account:mysubscriptionID policy:azure-notify azure.resourcegroup:X slack:slack_default to https://hooks.slack.com/services/xxxxx Traceback (most recent call last):
  File "lib/python3.7/site-packages/c7n_mailer/azure/azure_queue_processor.py", line 92, in process_azure_queue_message
    slack_delivery.slack_handler(queue_message, slack_messages)
  File "lib/python3.7/site-packages/c7n_mailer/slack_delivery.py", line 111, in slack_handler
    self.send_slack_msg(key, payload)
  File "lib/python3.7/site-packages/c7n_mailer/slack_delivery.py", line 180, in send_slack_msg
    self.logger.info("Error in sending Slack message: %s" % response.json())
  File "lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
custodian-mailer - INFO - Sending account:mysubscriptionID policy:azure-notify azure.resourcegroup:X email:default to {}
custodian-mailer - INFO - No messages left on the azure storage queue, exiting c7n_mailer.
```
I'm very confident my slack token is correct in the mailer file, let me know your thoughts, Thanks

**Comment by logachev** [comment]
Resolving after we fixed an issue with default slack template: https://github.com/cloud-custodian/cloud-custodian/pull/3199
