### ISSUE TITLE
ec2 onhour - instance changed state during policy execution, causing failure

### ISSUE THREAD

**Issue by dlut2** [cloud-custodian/cloud-custodian#3143]
What I found in CloudTrail, after reviewing the following custodian-run.log, is that the instance causing the failure was terminated at 12:18 GMT.  What I think I can tell from ec2.py is that custodian is making efforts to ensure the start action is only attempted on stopped instances, but in this case, the ClientError on the terminated instance resulted in the rest of the onhour instances remaining un-started.

2018-11-15 12:21:32,933 - custodian.policy - DEBUG - Running policy ec2-start-xonhours-est-parent resource: ec2 region:us-east-1 c7n:0.8.32.0
2018-11-15 12:21:35,127 - custodian.cache - DEBUG - Using cache file /root/.cache/cloud-custodian.cache
2018-11-15 12:21:35,127 - custodian.resources.ec2 - DEBUG - Using cached c7n.resources.ec2.EC2: 3347
2018-11-15 12:21:39,402 - custodian.filters - INFO - InstanceOnHour 253 of 409 instances
2018-11-15 12:21:39,423 - custodian.resources.ec2 - DEBUG - Filtered from 3347 to 253 ec2
2018-11-15 12:21:39,423 - custodian.policy - INFO - policy: ec2-start-xonhours-est-parent resource:ec2 region:us-east-1 count:253 time:6.49
2018-11-15 12:21:39,494 - custodian.actions - INFO - Start 253 of 253 instances
2018-11-15 12:21:41,093 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 273, in run
    results = a.process(resources)
  File "/src/c7n/resources/ec2.py", line 844, in process
    fails = self.process_instance_set(client, batch, itype, izone)
  File "/src/c7n/resources/ec2.py", line 863, in process_instance_set
    retry(client.start_instances, InstanceIds=instance_ids)
  File "/src/c7n/utils.py", line 360, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-xxxxxx' is not in a state from which it can be started.

**Comment by kapilt** [comment]
there's some logic in the start action for batching and starting instances in smaller blocks, and on a particular set of errors retrying, and on failure to continue and then. in this case i think we could extend that logic to at least raise on incorrect state errors, that would still continue but fail the batch.  going to more fine grained at instance level would need error string parsing from the instance id.
