### ISSUE TITLE
Azure - App Service Plan - Resizing errors

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3210]
### Description: 
I’m only able to resize ASP’s that are based on windows OS, this is failing when trying to resize a linux plan, testing on MacOS and a ubuntu docker image:
 
### Output:
```
2018-12-03 10:40:58,835: custodian.actions:ERROR Failed to resize app_service_plan.  Inner exception: {'additional_properties': {'Message': 'You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.', 'Code': 'BadRequest', 'Innererror': None, 'Target': None, 'Details': [{'Message': 'You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.'}, {'Code': 'BadRequest'}, {'ErrorEntity': {'ExtendedCode': '59315', 'MessageTemplate': 'You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.', 'Parameters': [], 'Code': 'BadRequest', 'Message': 'You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.'}}]}, 'error': None}
2018-12-03 10:40:58,835: custodian.actions:ERROR Execution failed with error: Operation returned an invalid status code 'Bad Request'
2018-12-03 10:40:58,837: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "virtualenv/lib/python3.7/site-packages/c7n/policy.py", line 273, in run
    results = a.process(resources)
  File "virtualenv/lib/python3.7/site-packages/c7n_azure/actions.py", line 51, in process
    self.handle_exceptions(exceptions)
  File "virtualenv/lib/python3.7/site-packages/c7n_azure/actions.py", line 58, in handle_exceptions
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "virtualenv/lib/python3.7/site-packages/c7n_azure/resources/appserviceplan.py", line 89, in process_resource_set
    client.app_service_plans.update(plan['resourceGroup'], plan['name'], model)
  File "virtualenv/lib/python3.7/site-packages/azure/mgmt/web/operations/app_service_plans_operations.py", line 465, in update
    raise models.DefaultErrorResponseException(self._deserialize, response)
azure.mgmt.web.models.default_error_response_py3.DefaultErrorResponseException: Operation returned an invalid status code 'Bad Request'
  ```
While the output doesn’t outright say this, I’m assuming that it’s trying to resize this linux plan as a windows plan of the size I’m specifying in the policy? Perhaps ‘kind’ on line 34 in https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_azure/c7n_azure/resources/appserviceplan.py is defaulting to windows and causing this? 

### Policy:
``` 
policies:
  - name: azure-resize-plan
    resource: azure.appserviceplan
    filters:
     - type: 'value'
       key: 'name'
       op: 'eq'
       value_type: 'normalize'
       value: 'myappplan'
    actions:
     - type: resize-plan
       size: F1
 ```

**Comment by stefangordon** [comment]
It is super weird for sure - I believe I was testing exclusively with linux ones too but clearly something is off here.  We'll have to do some more testing.  

As a note to whoever is debugging this (if it is not me) - I believe our implementation is basically the same as the Azure CLI implementation, but if we can reproduce in custodian and not in the CLI then we'll want to revisit the differences between the two....

**Comment by stefangordon** [comment]
Oh.... I just looked and there is no F1 size for linux... so that would explain it.

**Comment by aluong** [comment]
So it appears that we may need a different mapping for Linux vs Windows App plans.

**Comment by stefangordon** [comment]
We just don't offer free linux machines - but otherwise should all be the same.   I don't think we can do much about it in the schema but if its hard to differentiate between the two types of plans so you can be smart about this in your policy then we might need to consider a new filter.

**Comment by jdogg89** [comment]
Thanks for the insight. I'm not sure what the general Azure population's knowledge is on App service plan sizes but I wasn't aware Linux lacked that free tier. If its generally understood that it isn't a tier this can be closed off IMO.
