### ISSUE TITLE
Error when running ebs-snapshots delete policy

### ISSUE THREAD

**Issue by dlut2** [cloud-custodian/cloud-custodian#3217]
This is in a busy account that has a very large number of snapshots.  The policy runs okay in other accounts.  Below is a representative policy, but almost all policies against the ebs-snapshot resource are failing in this account.  When the failure occurs, no resources.json is created.
```yaml
 - name: ec2-delete-snapshot
    resource: ebs-snapshot
    comments: |
      Get rid of old snapshots created by backup tools
    filters:
      - type: skip-ami-snapshots
        value: true
      - type: value
        key: 'SnapshotId'
        value_from:
          url: *accounts-list
          format: json
          expr: accounts."{account_id}".ebs.snapshots.*[][]
        op: ni
      - type: value
        key: 'SnapshotId'
        value_from:
          url: *exemptions
          format: json
          expr: exemptions.["ebs-snapshot"][].snapshot.["SnapshotId"][].*[].*[]
        op: ni
      - type: age
        days: 21
      - or:
          - "tag:Project": BKUP
          - "tag:InstanceId": not-null
    actions:
      - delete
```

```
Run Log:
2018-12-07 03:44:50,901 - custodian.policy - DEBUG - Running policy ec2-delete-snapshot resource: ebs-snapshot region:us-east-1 c7n:0.8.32.0
2018-12-07 03:44:52,444 - custodian.cache - DEBUG - Using cache file /root/.cache/cloud-custodian.cache
2018-12-07 03:50:03,805 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 241, in run
    resources = self.policy.resource_manager.resources()
  File "/src/c7n/resources/ebs.py", line 85, in resources
    return super(Snapshot, self).resources(query=query)
  File "/src/c7n/query.py", line 421, in resources
    resources = self.source.resources(query)
  File "/src/c7n/query.py", line 215, in resources
    return self.query.filter(self.manager, **query)
  File "/src/c7n/query.py", line 82, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/src/c7n/query.py", line 59, in _invoke_client_enum
    data = pager(results, retry)
  File "/src/c7n/query.py", line 330, in pager
    page = retry(next, iterator)
  File "/src/c7n/utils.py", line 360, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
```

**Comment by dlut2** [comment]
All policies for the resource: ebs-snapshot are failing in this account.  ec2 backups appear to have a problem too.

**Comment by kapilt** [comment]
What version of custodian?

**Comment by thisisshi** [comment]
so i've taken a closer look at this and it looks like there's some potential optimizations we can do in custodian to define limits for maxresults per page and maxresults total

perhaps something like:

```policies:
  - name: ebs-snapshots
    resource: ebs-snapshot
    pagination-per-page: 1000
    pagination-total: 100000
```

or as env vars? `C7N_PAGINATION_TOTAL`, `C7N_PAGINATION_PER_PAGE_TOTAL`

that way the policy would be able to chip away at it over time

The modifications would be made in c7n/query.py:

```python
class ResourceQuery(object):

    def __init__(self, session_factory):
        self.session_factory = session_factory

    @staticmethod
    def resolve(resource_type):
        if not isinstance(resource_type, type):
            raise ValueError(resource_type)
        else:
            m = resource_type
        return m

    def _invoke_client_enum(self, client, enum_op, params, path, retry=None):
        if client.can_paginate(enum_op):
            p = client.get_paginator(enum_op)
            params['MaxResults'] = self.max_results # max resources per page
            results = p.paginate(**params, {PaginationConfig={'MaxItems': self.max_items}) # or perhaps an arg passed into the function, max_items
            if retry:
                p.PAGE_ITERATOR_CLS = RetryPageIterator
            data = results.build_full_result()
        else:
            op = getattr(client, enum_op)
            data = op(**params)

        if path:
            path = jmespath.compile(path)
            data = path.search(data)

        return data
```

**Comment by dlut2** [comment]
I would prefer whatever patch would allow us to keep our policies unchanged.  Perhaps custodian could switch to using paginated read of 1000 at a time after the current method fails with "ReadTimeout", or simply always use paginated read to prevent the error?

**Comment by kapilt** [comment]
@thisisshi not really a fan of that, feels a bit hacky and low level to force into end users hands imo.  @dlut2 fwiw, the previous fix around retry ended up having an issue that wasn't fully addressed till #3291 . its also worth noting that custodian retries are in addition to sdk retries, which can be configured separately. @dlut2 i'm curious what sort of cardinalities we're talking about, is this 7 figure land? is that cardinality figure a steady state, or is this a one time cleanup scenario, if the later, its worth considering a one off script to bring the population under control, if thats steady state that would also be useful to understand to help guide solutions.

**Comment by kapilt** [comment]
actually just re-read the original, this is on a read timeout error, which possibly implies a network path issue (among others). Its not considered a retryable error by custodian. Is custodian accessing the api endpoints via a vpc endpoint, direct internet access, or some form of network middleware? The issue on network path issues is they can be happening on any api access, and isn't per se anything custodian can address.  Its also worth noting that the sdks have some configuration options here, the default for read_timeout is 60s, you can set up in your ~/.aws/config file for extending to see if that helps.

@thisisshi as an alternative, how about exposing server side queries for ebs snapshots, which maps to existing capabilities and configuration.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_snapshots

**Comment by dlut2** [comment]
@kapilt, the actual number of snapshots in the account was over 1.6 million when I brought up this issue.  I performed a manual cleanup over the course of several days, due to limits of my scripting and Rate limits for deletesnapshot calls.  My custodian cleanup policy continued to run daily during this time, and I observed that custodian was not able to successfully process the snapshots in this account until the number was under 100K.  
Before deciding to perform a manual cleanup, I asked AWS to increase API limits to help address this, but the AWS response was to the effect that custodian needs to paginate the read operation when dealing with large numbers of resources, because AWS is simply not able to reply with all the results within the baked-in time limits of the API.

**Comment by kapilt** [comment]
thanks for the numbers, thats helpful. so we do paginate, I think the final fix for retries on pagination wasn't till #3291 which is in 0.8.33.0 which got released on New Years, however those retries are not going to take into account ReadTimeouts you posted initially, which we regard as either a network hiccup or the service endpoint not responding in a timely fashion. We could add in read timeout to retry specific for ebs snapshot fetching as a known service api issue at scale. It would be helpful to understand the network connectivity model though to know if this was a service endpoint issue (ie. non responsive for 60s) or a problem with a middle ware in the network egress path, as the later may mean that using a vpc endpoint for ec2 will alleviate.

**Comment by thisisshi** [comment]
@kapilt sounds good re: exposing ability to do server side queries on ebs snapshots.

**Comment by circa10a** [comment]
@kapilt I'm hitting this issue when trying to delete 250K snapshots, is there a documented policy for this anywhere?

**Comment by kapilt** [comment]
@circa10a ensuring you have direct access to the api is helpful if your going through proxies or intermediaries, vpc endpoint can help, you can control retry policy through sdk environment variables.

  AWS_RETRY_MODE=adaptive
  AWS_STS_REGIONAL_ENDPOINTS=regional
  AWS_MAX_ATTEMPTS=6

**Comment by circa10a** [comment]
@kapilt No dice

```bash
❯ export AWS_RETRY_MODE=adaptive; export AWS_STS_REGIONAL_ENDPOINTS=regional; export AWS_MAX_ATTEMPTS=6

~/Desktop/code/terraform/account-infrastructure main* ⇣
❯ custodian run  policies/delete-old-snapshots.yaml --region us-west-2 -s . -v --dry-run
2021-06-17 15:29:31,124: custodian.commands:DEBUG Loaded file policies/delete-old-snapshots.yaml. Contains 1 policies
2021-06-17 15:29:31,724: custodian.output:DEBUG Storing output with <LogFile file://./ebs-delete-old-ebs-snapshots/custodian-run.log>
2021-06-17 15:29:31,734: custodian.policy:DEBUG Running policy:ebs-delete-old-ebs-snapshots resource:ebs-snapshot region:us-west-2 c7n:0.9.11
2021-06-17 15:35:52,782: custodian.output:DEBUG metric:PolicyException Count:1 policy:ebs-delete-old-ebs-snapshots restype:ebs-snapshot
2021-06-17 15:35:52,783: custodian.output:DEBUG metric:ApiCalls Count:0 policy:ebs-delete-old-ebs-snapshots restype:ebs-snapshot
2021-06-17 15:35:52,783: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 314, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='ec2.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.9/site-packages/c7n/resources/ebs.py", line 71, in resources
    return super(Snapshot, self).resources(query=query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 514, in resources
    resources = self.source.resources(query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 223, in resources
    return self.query.filter(self.manager, **query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 75, in filter
    return self._invoke_client_enum(
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 56, in _invoke_client_enum
    data = results.build_full_result()
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 744, in _make_request
    return self.retry(self._method, **current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/c7n/utils.py", line 444, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 156, in _send_request
    raise exception
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 349, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-west-2.amazonaws.com/"
2021-06-17 15:35:52,804: custodian.commands:ERROR Error while executing policy ebs-delete-old-ebs-snapshots, continuing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 314, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='ec2.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n/commands.py", line 271, in run
    policy()
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 1178, in __call__
    resources = PullMode(self).run()
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.9/site-packages/c7n/resources/ebs.py", line 71, in resources
    return super(Snapshot, self).resources(query=query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 514, in resources
    resources = self.source.resources(query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 223, in resources
    return self.query.filter(self.manager, **query)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 75, in filter
    return self._invoke_client_enum(
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 56, in _invoke_client_enum
    data = results.build_full_result()
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/c7n/query.py", line 744, in _make_request
    return self.retry(self._method, **current_kwargs)
  File "/usr/local/lib/python3.9/site-packages/c7n/utils.py", line 444, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 156, in _send_request
    raise exception
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.9/site-packages/botocore/httpsession.py", line 349, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-west-2.amazonaws.com/"
2021-06-17 15:35:52,808: custodian.commands:ERROR The following policies had errors while executing
 - ebs-delete-old-ebs-snapshots
 ```

**Comment by kapilt** [comment]
What's your network egress path to the api endpoints? Are you going through proxies, vpns, internet, vpc endpoints? Are you operating from an ec2 instance against the same region or cross region?

**Comment by circa10a** [comment]
Just purely going through the internet from my workstation(Texas, USA)

**Comment by robbie-demuth** [comment]
Our organization is evaluating using Cloud Custodian to clean up old snapshots in several large accounts - some with over 100k snapshots. I'm finding this to be an issue as well. FWIW, this looks related to https://github.com/cloud-custodian/cloud-custodian/issues/5174

**Comment by robbie-demuth** [comment]
Did a bit of digging and opened a new issue that I think better describes the root cause of this one

https://github.com/cloud-custodian/cloud-custodian/issues/6873
