### ISSUE TITLE
C7N execution error - mugc.py

### ISSUE THREAD

**Issue by mukavik** [cloud-custodian/cloud-custodian#3273]
Hi I am getting the following error while running mugc.py. I tried on current and 0.8.31.2 version. 

```
Traceback (most recent call last):
 File "mugc.py", line 153, in <module>
 main()
 File "mugc.py", line 146, in main
 resources.load_resources()
 File "/usr/local/lib/python2.7/site-packages/c7n/resources/__init__.py", line 36, in load_resources
 import c7n.resources.asg
 File "/usr/local/lib/python2.7/site-packages/c7n/resources/asg.py", line 44, in <module>
 from .ec2 import deserialize_user_data
 File "/usr/local/lib/python2.7/site-packages/c7n/resources/ec2.py", line 32, in <module>
 from c7n.actions.securityhub import PostFinding
 File "/usr/local/lib/python2.7/site-packages/c7n/actions/securityhub.py", line 24, in <module>
 from c7n.resources.ec2 import EC2
ImportError: cannot import name EC2
```

**Comment by mukavik** [comment]
I am running this using AWS CodeBuild and CodeDeploy, thus this is doing
fresh install every time. In the Buildspec file i have the following:
pip install aws cli
pip install c7n==0.8.32.1
mugc.py
Custodian policy files....

Strangely when i run through my local machine it runs just fine.

**Comment by kapilt** [comment]
whats the base image on the buildspec, can you paste the relevant and anon portion of the spec here?

**Comment by mukavik** [comment]
`version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install awscli
      - pip install c7n==0.8.31.2
  build:
    commands:
        #cleanup old lambda functions
        - python mugc.py -c iam-root-ak-notify.yml`

**Comment by mukavik** [comment]
I supplied the mugc.py file (attached)
[buildspec.yml.zip](https://github.com/cloud-custodian/cloud-custodian/files/2739182/buildspec.yml.zip)

CodeBuild Image - aws/codebuild/python:2.7.12
Environment type - Linux

 I tried using version 0.8.33.1 and here is the new traceback

`[Container] 2019/01/09 03:02:26 Running command python mugc.py -c iam-user-unused-disable.yml
Traceback (most recent call last):
 File "mugc.py", line 153, in <module>
 main()
 File "mugc.py", line 148, in main
 policies = load_policies(options)
 File "mugc.py", line 31, in load_policies
 collection = policy_load(options, f)
 File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 68, in load
 collection = PolicyCollection.from_data(data, options)
 File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 87, in from_data
 for p in data.get('policies', ())]
 File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 686, in __init__
 self.ctx = ExecutionContext(self.session_factory, self, self.options)
 File "/usr/local/lib/python2.7/site-packages/c7n/ctx.py", line 50, in __init__
 self.metrics = metrics_outputs.select(self.options.metrics_enabled, self)
AttributeError: 'Namespace' object has no attribute 'metrics_enabled'
 [Container] 2019/01/09 03:02:27 Command did not exit successfully python mugc.py -c iam-user-unused-disable.yml exit status 1`

**Comment by kapilt** [comment]
your using a mugc copy thats in your local repo, that does not correspond to the version of custodian your using, the version your codebuild setup appears to be quite old. As a separate issue, your also manually downloading older versions of custodian and then manually matching from trunk, thats not sane. Use a released version of custodian, or use an updated version of mugc from upstream repo.
