### ISSUE TITLE
generate_arn on resource=aws.support-case results in AttributeError

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3388]
The following error
```
2019-01-18 02:34:48,434: custodian.policy:INFO policy: support-tag-compliance-import-findings resource:aws.support-case region:us-east-1 count:2 time:0.47
2019-01-18 02:34:48,440: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/policy.py", line 264, in run
    results = a.process(resources)
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/actions/securityhub.py", line 202, in process
    resource_set, finding_id, created_at, updated_at)
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/actions/securityhub.py", line 312, in get_finding
    finding_resources.append(self.format_resource(r))
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/actions/securityhub.py", line 353, in format_resource
    'Id': self.manager.get_arns([r])[0],
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/query.py", line 500, in get_arns
    arns.append(self.generate_arn(_id))
  File "/home/ec2-user/environment/cloud-custodian/.tox/py37/lib/python3.7/site-packages/c7n/query.py", line 513, in generate_arn
    resource_type=self.get_model().type,
AttributeError: type object 'resource_type' has no attribute 'type'
```
can be reproduced from the following policy:
```
policies:
  - name: support-tag-compliance-import-findings
    resource: aws.support-case
    description: |
      Find all support cases
    filters:
      - type: value
        key: "status"
        value: not-null
    actions:
      - type: post-finding
        severity_normalized: 1
        types:
        - "Software and Configuration Checks/AWS Security Best Practices"
```

**Comment by coingraham** [comment]
Since support cases don't have an arn, should the support object return a fake arn like the account object?  Something like:

```    @classmethod
    def get_arns(self, resources):
        return ["arn:::{caseId}".format(**r) for r in resources]```
