### ISSUE TITLE
KMS keys example for "key-rotation-status" doesn't work

### ISSUE THREAD

**Issue by skgbox** [cloud-custodian/cloud-custodian#3398]
```
(custodian) root@ip-172-31-1-84:~# custodian schema aws.kms-key.filters.key-rotation-status
Help
----
Filters KMS keys by the rotation status
:example:
.. code-block:: yaml
        policies:
          - name: kms-key-disabled-rotation
            resource: kms-key
            filters:
              - type: key-rotation-status
                key: KeyRotationEnabled
                value: false
Schema
------
.....................

(custodian) root@ip-172-31-1-84:~# cat kms_keys_no_rotation.yml
policies:
  - name: kms-key-disabled-rotation
    resource: kms-key
    filters:
      - type: key-rotation-status
        key: KeyRotationEnabled
        value: false
(custodian) root@ip-172-31-1-84:~# custodian run --output-dir=. kms_keys_no_rotation.yml
2019-01-21 08:53:42,050: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/query.py", line 399, in resources
    return self.filter_resources(resources)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/resources/kms.py", line 122, in process
    list(w.map(_key_rotation_status, query_resources))
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/resources/kms.py", line 108, in _key_rotation_status
    KeyId=resource['KeyId'])
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
UnsupportedOperationException: An error occurred (UnsupportedOperationException) when calling the GetKeyRotationStatus operation: arn:aws:kms:us-east-1:335325095793:key/577c7d73-6e63-4b6a-936c-106cfc02546a origin is EXTERNAL which is not valid for this operation.
2019-01-21 08:53:42,052: custodian.commands:ERROR Error while executing policy kms-key-disabled-rotation, continuing
Traceback (most recent call last):
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 237, in run
    policy()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 870, in __call__
    resources = mode.run()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/query.py", line 399, in resources
    return self.filter_resources(resources)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/resources/kms.py", line 122, in process
    list(w.map(_key_rotation_status, query_resources))
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/root/custodian/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/custodian/local/lib/python2.7/site-packages/c7n/resources/kms.py", line 108, in _key_rotation_status
    KeyId=resource['KeyId'])
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
UnsupportedOperationException: An error occurred (UnsupportedOperationException) when calling the GetKeyRotationStatus operation: arn:aws:kms:us-east-1:335325095793:key/577c7d73-6e63-4b6a-936c-106cfc02546a origin is EXTERNAL which is not valid for this operation.
(custodian) root@ip-172-31-1-84:~#
```

**Comment by kapilt** [comment]
not sure what origin external means in the context of kms, that policy works fine for me locally, you may have to filter out keys with origin external prior to they key rotation filter.

**Comment by kapilt** [comment]
it looks like origin external means they key material is being managed outside of kms so the rotation has no meaning.

adding this filter will filter out those keys
```
- Origin: AWS_KMS
```

**Comment by skgbox** [comment]
```
Thanks for your support, kapilt.

The following policy works fine for me :
policies:
  - name: kms-key-disabled-rotation
    resource: kms-key
    filters:
      - and:
        - type: value
          key: KeyManager
          value: CUSTOMER
          op: eq
        - type: value
          key: KeyState
          value: Enabled
          op: eq
        - type: value
          key: Origin
          value: AWS_KMS
          op: eq
        - type: key-rotation-status
          key: KeyRotationEnabled
          value: false
          op: eq
```
