### ISSUE TITLE
Securityhub alerts wont work via Lambda function

### ISSUE THREAD

**Issue by Eerk1975** [cloud-custodian/cloud-custodian#3401]
When we run the following policy:

```
policies:
  - name: awt_man_nn_cust_015_s3_encryption
    resource: s3
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      execution-options:
        metrics_enabled: true      
    filters:
      - type: bucket-encryption
        state: False
    actions:
      - type: post-finding
        severity_normalized: 30
        types:
          - "Software and Configuration Checks/Industry and Regulatory Standards"
```

Lambda reports: 

```iot1click-devices, iot1click-projects, iotanalytics, kinesis, kinesis-video-archived-media, kinesis-video-media, kinesisanalytics, kinesisvideo, kms, lambda, lex-models, lex-runtime, lightsail, logs, machinelearning, macie, marketplace-entitlement, marketplacecommerceanalytics, mediaconvert, medialive, mediapackage, mediastore, mediastore-data, mediatailor, meteringmarketplace, mgh, mobile, mq, mturk, neptune, opsworks, opsworkscm, organizations, pi, pinpoint, polly, pricing, rds, redshift, rekognition, resource-groups, resourcegroupstaggingapi, route53, route53domains, s3, sagemaker, sagemaker-runtime, sdb, secretsmanager, serverlessrepo, servicecatalog, servicediscovery, ses, shield, sms, snowball, sns, sqs, ssm, stepfunctions, storagegateway, sts, support, swf, transcribe, translate, waf, waf-regional, workdocs, workmail, workspaces, xray: UnknownServiceError
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 8, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 105, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 832, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 510, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 264, in run
    results = a.process(resources)
  File "/var/task/c7n/actions/securityhub.py", line 184, in process
    "securityhub", region_name=region_name)
  File "/var/runtime/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/var/runtime/botocore/session.py", line 885, in create_client
    client_config=config, api_version=api_version)
  File "/var/runtime/botocore/client.py", line 69, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/var/runtime/botocore/client.py", line 102, in _load_service_model
    api_version=api_version)
  File "/var/runtime/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/var/runtime/botocore/loaders.py", line 378, in load_service_model
    known_service_names=', '.join(sorted(known_services)))
botocore.exceptions.UnknownServiceError: Unknown service: 'securityhub'. Valid service names are: acm, acm-pca, alexaforbusiness, apigateway, application-autoscaling, appstream, appsync, athena, autoscaling, autoscaling-plans, batch, budgets, ce, cloud9, clouddirectory, cloudformation, cloudfront, cloudhsm, cloudhsmv2, cloudsearch, cloudsearchdomain, cloudtrail, cloudwatch, codebuild, codecommit, codedeploy, codepipeline, codestar, cognito-identity, cognito-idp, cognito-sync, comprehend, config, connect, cur, datapipeline, dax, devicefarm, directconnect, discovery, dlm, dms, ds, dynamodb, dynamodbstreams, ec2, ecr, ecs, efs, eks, elasticache, elasticbeanstalk, elastictranscoder, elb, elbv2, emr, es, events, firehose, fms, gamelift, glacier, glue, greengrass, guardduty, health, iam, importexport, inspector, iot, iot-data, iot-jobs-data, iot1click-devices, iot1click-projects, iotanalytics, kinesis, kinesis-video-archived-media, kinesis-video-media, kinesisanalytics, kinesisvideo, kms, lambda, lex-models, lex-runtime, lightsail, logs, machinelearning, macie, marketplace-entitlement, marketplacecommerceanalytics, mediaconvert, medialive, mediapackage, mediastore, mediastore-data, mediatailor, meteringmarketplace, mgh, mobile, mq, mturk, neptune, opsworks, opsworkscm, organizations, pi, pinpoint, polly, pricing, rds, redshift, rekognition, resource-groups, resourcegroupstaggingapi, route53, route53domains, s3, sagemaker, sagemaker-runtime, sdb, secretsmanager, serverlessrepo, servicecatalog, servicediscovery, ses, shield, sms, snowball, sns, sqs, ssm, stepfunctions, storagegateway, sts, support, swf, transcribe, translate, waf, waf-regional, workdocs, workmail, workspaces, xray

END RequestId: a1dae475-f1ed-46f3-bcfc-135c99f81a8f
REPORT RequestId: a1dae475-f1ed-46f3-bcfc-135c99f81a8f	Duration: 8103.45 ms	Billed Duration: 8200 ms 	Memory Size: 512 MB	Max Memory Used: 116 MB	

```
when I use this policy without the periodic mode (interactivly) the function works and sends alerts to Securityhub.

could any one help me out?

**Comment by kapilt** [comment]
its due to the stale boto3 libraries in the python lambda runtime environment. on trunk we switch out to python3 default as that it appears to have more up to date libraries. anytime your using recent boto features, the best to ensure their availability in lambda is to package them up with your lambda policy by
adding `packages` attribute to the mode like this

```
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      packages: [boto3, botocore, urllib]
      execution-options:
        metrics_enabled: true  
```

that will provision your local copies of the those libraries into the lambda.

**Comment by Eerk1975** [comment]
thanks, that solved the problem!
