### ISSUE TITLE
Modifying security groups errors when modifying an ENI created by ECS

### ISSUE THREAD

**Issue by schledererj** [cloud-custodian/cloud-custodian#3406]
I'm trying to use c7n to attach a security group to my entire EC2 inventory, and I'm stumbling on a situation where when the policy runs, it errors and exits due to an AuthError when modifying an ENI, even when running with admin/root-like credentials. From what I can tell, this only happens on ENIs that were created and attached to an instance by an ECS cluster/service. The other ENI on the box, i.e., the one that gets added by default at instance creation, can be modified just fine.

I'm thinking that the easiest fix for this is to add exception handling for the ENIs that can't be modified, such that the entire policy doesn't bomb out just because one/some can't be modified. My thought is that during ENI enumeration in the `modify-security-groups` action in `c7n/resources/ec2.py`, the actual call to the boto client's `modify_network_interface_attribute` function could be wrapped in a try/except block, which would properly log the ENI ID and skip to the next in case of an error. I feel like this would be useful in more actions than just this one.

Alternatively, if this behavior was indeed by design, it would be nice to have a cmd line flag to disable this behavior, i.e., `--ignore-client-errors`.

**Comment by thisisshi** [comment]
interesting, can you post the traceback?

**Comment by schledererj** [comment]
Sure thing.
```
An error occurred (AuthFailure) when calling the ModifyNetworkInterfaceAttribute operation: You do not have permission to access the specified resource.: ClientError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 105, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 837, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 516, in run
return PullMode.run(self)
File "/var/task/c7n/policy.py", line 273, in run
results = a.process(resources)
File "/var/task/c7n/resources/ec2.py", line 1273, in process
Groups=groups[idx])
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AuthFailure) when calling the ModifyNetworkInterfaceAttribute operation: You do not have permission to access the specified resource.
```

Just to reiterate, this runs in an IAM role that has admin-like credentials. It is basically root, minus some permissions to change some VPC resources like subnets and VPGs.

**Comment by kapilt** [comment]
hypothesizing.. this is an artifact of how aws works, if you want to target ecs/eni in this context, you should be targeting the service/task definition. ie. the eni isn't actually owned by the account in that scenario, its owned by a different service account and attached to the target account's vpc. ie that's effectively the basis of things like shared vpcs etc. you can filter out those enis using the OwnerId attribute ala `OwnerId: {account_id}`

**Comment by schledererj** [comment]
That was my exact thought as well, wrt Amazon actually "owning" the ENI. I can give the `OwnerId` filter a shot, but I'm wary because my `resources.json` output has all the applicable EC2 instances with ENIs whose `OwnerId`s are invariably my account number.

I'll report back with what I find. Thanks!

**Comment by schledererj** [comment]
I've done a bit of testing on our hypothesis, and I've concluded that the ENIs that are created by ECS are indeed "owned" by another Amazon service account, but their `OwnerId` attribute within a `describe-instances` or `describe-network-interfaces` call is the customer's account number. However, I also discovered that in an ENI's describe object, there are two attributes `RequesterManaged` and `RequesterId`. Those seem to determine if the ENI is managed by another AWS service and what the ID of that service is, respectively. I guess I could switch my policy to use the `aws.eni` resource type instead of the `aws.ec2` resource type and filter out all where `RequesterManaged = true`. 

I still think this is an issue, though, as it causes the `security-group` filter type on the `ec2` resource type to bomb out if any instance has one of these RequesterManaged ENIs attached. I'm thinking maybe the solution now is to, instead of just skipping over ENIs that error, filtering out the ENIs on each instance that are RequesterManaged, and apply the security group to the rest. Let me know what you think.

**Comment by kapilt** [comment]
Fwiw, in general implicit filtering is always a bit questionable versus having the policy author filter explicitly, else the author things something is working fine, when in fact it wasn't doing anything. We do do it on occasion, but its pretty targeted to transient state issues (stop on terminating ec2 instance for example) or particular classes of permanent issues. This does seem to fall into the later, and i think it your suggestion around a remedy is worth implementing.

**Comment by schledererj** [comment]
Yeah, I completely agree that hard-coding filters can be confusing to the user/policy-writer. If we added that implicit filter, it might be useful to note it somewhere in the documentation for the `modify-security-groups` action.

**Comment by schledererj** [comment]
Just opened a PR with some preliminary code for this issue. But, after more testing, I've discovered that the RequesterManaged and RequesterId keys are only present on the ENI objects on a `describe-network-interfaces` call, not on `describe-instances`, which is what the action currently does. So, we'd need to request the ENI details for every applicable ENI, which would be a considerable refactor and would probably make the action take much longer. I'll defer to you if you have any suggestions.

**Comment by erikpaasonen** [comment]
Thank you @kapilt  @schledererj for the discussion around implicit policy filters. I'm running into an issue modifying security groups in a shared VPC owned by another account. I was about to open an issue suggesting that filtering on the current account be the default. After reading this discussion maybe it's best to leave it the way it is, especially with the suggested policy filter. Thanks for the help!

It's too bad this issue got stuck.

**Comment by kapilt** [comment]
@erikpaasonen i tried to say in my first reply, that trying to manage at eni level is not the right way to think about this, because it wont work and risks breaking higher level automation from various managed services. you can report on eni stuff, but if you want to manage/modify things you need to do it at the managed resource level that owns the eni. those resources also have the correct information wrt to tags etc. ecs on ec2 with vpc networking is a distinct issue though that we should look at doing something better with.

**Comment by schledererj** [comment]
Circling back around to this after a nice, short sabbatical 🙂

I'm thinking that in order to get this to work properly, we'll need to call a `describe_network_interfaces` on all the interfaces attached to the applicable instances, and then from there we can filter out those that are RequesterManaged. Something like this:

```python
eni_details = client.describe_network_interfaces(
    NetworkInterfaceIds=[x["NetworkInterfaceId"] for x in interfaces])
interfaces = [x for x in interfaces if not ("RequesterManaged" in eni_details[x["NetworkInterfaceId"]] and
              eni_details[x["NetworkInterfaceId"]]["RequesterManaged"])]
```

...and then call `modify_network_interface_attribute` on those. I initially thought that `describe_network_interfaces` had to be called on each ENI, but we can batch them, so that reduces the number of AWS API round-trips. I know it's been a while, but when you can, let me know what you think of this approach.
