### ISSUE TITLE
Azure - Permission denied when publishing function from Windows

### ISSUE THREAD

**Issue by joescars** [cloud-custodian/cloud-custodian#3457]
**Environment**
Windows 10 Enterprise, elevated command prompt or PowerShell
(works perfectly in WSL)

**Issue**
Attempting to run a script locally which publishes an Azure Function results in ```PermissionError: [Errno 13] Permission denied```

Policy I'm trying to publish:
```yaml
policies:
    - name: tag-resource-group-creator
      resource: azure.resourcegroup
      mode:
        type: azure-event-grid
        events: [{
            resourceProvider: 'Microsoft.Resources/subscriptions/resourceGroups',
            event: 'write'
          }]
      filters:
        - "tag:CreatorEmail": null
      actions:
        - type: auto-tag-user
          tag: CreatorEmail       
```

Full output below:
```
Traceback (most recent call last):
  File "c:\code\cloud-custodian\c7n\commands.py", line 248, in run
    policy()
  File "c:\code\cloud-custodian\c7n\policy.py", line 878, in __call__
    resources = mode.provision()
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\policy.py", line 255, in provision
    FunctionAppUtilities.publish_functions_package(self.function_params, package)
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\functionapp_utils.py", line 152, in publish_functions_package
    FUNCTION_CONSUMPTION_BLOB_CONTAINER, blob_name, package.pkg.path)
  File "c:\code\custodian\lib\site-packages\azure\storage\blob\blockblobservice.py", line 447, in create_blob_from_path
    with open(file_path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\[username]\\AppData\\Local\\Temp\\tmp4u4cpc8l'
```

Currently troubleshooting this as the root cause (from what I can determine) is that the temp file is actually being deleted before the following code is called:
https://github.com/cloud-custodian/cloud-custodian/blob/a8e89539d4e5e23d5cb7988eab226aae9ae1bfd8/tools/c7n_azure/c7n_azure/policy.py#L250-L255

Working on a possible resolution which I will submit via PR

@aluong

**Comment by joescars** [comment]
With the help of @logachev I've corrected the root cause. Will be testing more and submitting PR for this tomorrow.
