### ISSUE TITLE
ami.py 'remove-launch-permissions' bug introduced with update

### ISSUE THREAD

**Issue by joh08266** [cloud-custodian/cloud-custodian#3468]
It appears in the update of the ami.py file there was a misnamed function calls in the 'remove-launch-permissions'. This breaks when you attempt to use the remove-launch-permissions functionality in a policy. It will give the error:

Traceback (most recent call last):
File "/codebuild/output/src751369243/src/cloud-custodian/tests/test_tr_ami.py", line 59, in test_tr_ami_depermission
resources = p.run()
File "/codebuild/output/src751369243/src/cloud-custodian/c7n/policy.py", line 880, in call
resources = mode.run()
File "/codebuild/output/src751369243/src/cloud-custodian/c7n/policy.py", line 264, in run
results = a.process(resources)
File "/codebuild/output/src751369243/src/cloud-custodian/c7n/resources/ami.py", line 129, in process
self.process(client, i)
TypeError: process() takes exactly 2 arguments (3 given)

This PR is to revert the name back to 'process_image' to fix this bug.
Pull request #3467

**Comment by kapilt** [comment]
merged, thanks
