### ISSUE TITLE
ami unused filter fails with auto scaling group using launch template vs launch config

### ISSUE THREAD

**Issue by six-arm** [cloud-custodian/cloud-custodian#3483]
I'm seeing this traceback for an ami resource policy using the unused:true filter.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.5/dist-packages/c7n/resources/ami.py", line 60, in resources
    return super(AMI, self).resources(query=query)
  File "/usr/local/lib/python3.5/dist-packages/c7n/query.py", line 413, in resources
    resources = self.filter_resources(resources)
  File "/usr/local/lib/python3.5/dist-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.5/dist-packages/c7n/filters/core.py", line 270, in process
    resources = f.process(resources, events)
  File "/usr/local/lib/python3.5/dist-packages/c7n/resources/ami.py", line 250, in process
    images = self._pull_ec2_images().union(self._pull_asg_images())
  File "/usr/local/lib/python3.5/dist-packages/c7n/resources/ami.py", line 239, in _pull_asg_images
    lcfgs = set(a['LaunchConfigurationName'] for a in asgs)
  File "/usr/local/lib/python3.5/dist-packages/c7n/resources/ami.py", line 239, in <genexpr>
    lcfgs = set(a['LaunchConfigurationName'] for a in asgs)
KeyError: 'LaunchConfigurationName'
```
The query of autoscaling groups is returning resources using launch templates, not launch configs.  The launch template resource has no 'LaunchConfigurationName' key.

```
{
    "AutoScalingGroups": [
        {
            "HealthCheckGracePeriod": 300,
            "DesiredCapacity": 1,
            "DefaultCooldown": 300,
            "AvailabilityZones": [
                "us-east-2a"
            ],
            "ServiceLinkedRoleARN": "arn:aws:iam::<account>:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling",
            "CreatedTime": "2018-10-07T12:27:48.977Z",
            "EnabledMetrics": [],
            "AutoScalingGroupName": "test-app-asg",
            "TerminationPolicies": [
                "Default"
            ],
            "AutoScalingGroupARN": "arn:aws:autoscaling:us-east-2:<account>:autoScalingGroup:50f5-4673-ac27-94e6be7a61:autoScalingGroupName/test-app-asg",
            "HealthCheckType": "ELB",
            "Instances": [
                {
                    "ProtectedFromScaleIn": false,
                    "AvailabilityZone": "us-east-2a",
                    "HealthStatus": "Healthy",
                    "LifecycleState": "InService",
                    "InstanceId": "i-029395942a39f",
                    "LaunchTemplate": {
                        "LaunchTemplateName": "test-app-launch-template",
                        "LaunchTemplateId": "lt-03358423448c4",
                        "Version": "5"
                    }
                }
            ],
            "MaxSize": 1,
            "NewInstancesProtectedFromScaleIn": false,
            "LoadBalancerNames": [],
            "VPCZoneIdentifier": "subnet-0e8b85423443",
            "SuspendedProcesses": [],
            "Tags": [
            ],
            "TargetGroupARNs": [
                "arn:aws:elasticloadbalancing:us-east-2:<account>:targetgroup/test-app-lb-target-group/754eeffc"
            ],
            "MinSize": 1,
            "LaunchTemplate": {
                "LaunchTemplateName": "test-app-launch-template",
                "LaunchTemplateId": "lt-03358423",
                "Version": "$Latest"
            }
        }
]

```
custodian version: 0.8.32.1

**Comment by kapilt** [comment]
This also came up in #3252, although perusing through launch template docs, i'm not convinced that the solution there is correct, nor does it address this. Unfortunately there's quite a bit of ambiguity with launch templates wrt to versions and defaults that needs to be unwound to get to a known good state. 

my default consideration here would be to consider all extant usages of launch template versions, but that may well consider amis that are referenced by unused template versions as unused.

**Comment by six-arm** [comment]
Checking all versions of the launch template is the safe thing to do.  I don't have a good feel for launch template management, but it seems reasonable to expect one to age out template versions if the want to act on related resources.

Thanks for being on this issue so quickly.
