### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'tracer'

### ISSUE THREAD

**Issue by ssteo** [cloud-custodian/cloud-custodian#3494]
Traceback (most recent call last):
  File "/var/task/custodian_shared.py", line 403, in policy_processor
    run_policy(aws_account_id, region_name, policy_name)
  File "/var/task/custodian_shared.py", line 549, in run_policy
    verbose=None))
  File "/var/task/c7n/commands.py", line 63, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/var/task/c7n/policy.py", line 68, in load
    collection = PolicyCollection.from_data(data, options)
  File "/var/task/c7n/policy.py", line 87, in from_data
    for p in data.get('policies', ())]
  File "/var/task/c7n/policy.py", line 87, in <listcomp>
    for p in data.get('policies', ())]
  File "/var/task/c7n/policy.py", line 686, in __init__
    self.ctx = ExecutionContext(self.session_factory, self, self.options)
  File "/var/task/c7n/ctx.py", line 54, in __init__
    self.tracer = tracer_outputs.select(self.options.tracer, self)
AttributeError: 'Namespace' object has no attribute 'tracer'

BTW, I'm running on Python 3.7.. the version 0.8.31.2 didn't have such issue.

**Comment by ssteo** [comment]
@kapilt  I see, thanks. I'll switch to use c7n.config then.
