### ISSUE TITLE
lambdas get launched with python 3.7 and error out

### ISSUE THREAD

**Issue by yuriydee** [cloud-custodian/cloud-custodian#3499]
After upgrading to the c7n version 0.8.40.0, c7n-org is launching lambdas with Python 3.7. Every lambda function has this error now:

```
[ERROR] AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/custodian_policy.py", line 1, in <module>
    from c7n import handler
  File "/var/task/c7n/handler.py", line 43, in <module>
    load_resources()
  File "/var/task/c7n/resources/__init__.py", line 31, in load_resources
    import c7n.resources.account
  File "/var/task/c7n/resources/account.py", line 25, in <module>
    from c7n.actions import ActionRegistry, BaseAction
  File "/var/task/c7n/actions/__init__.py", line 16, in <module>
    from .core import Action, EventAction, BaseAction, ActionRegistry
  File "/var/task/c7n/actions/core.py", line 22, in <module>
    from c7n.executor import ThreadPoolExecutor
  File "/var/task/c7n/executor.py", line 109, in <module>
    executors.load_plugins()
  File "/var/task/c7n/registry.py", line 113, in load_plugins
    from pkg_resources import iter_entry_points
  File "/var/task/pkg_resources.py", line 1545, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
```

The fix is to manually revert it to Python 2.7. c7n-mailer has no issues so far.

**Comment by yuriydee** [comment]
Sure im using `CentOS Linux release 7.6.1810 (Core)` with `Python 2.7.5` as the default with `pip 19.0.1.` 

This is the policy I had issues with:

```
policies:
  - name: ec2-tag-compliance
    resource: ec2
    mode:
      type: periodic
      schedule: "cron(*/30 * * * ? *)"
      execution-options:
        output_dir: s3://my-bucket/
    comment: |
      Report on total count of non compliant instances
    filters:
    - or:
      - "tag:Asset": absent
      - "tag:Application": absent
      - "tag:Environment": absent
      - "tag:Name": absent
    actions:
    - type: mark-for-op
      op: stop
      hours: 2
    - type: notify
      template: default.html
      priority_header: 1
      subject: "EC2 - Missing Required Tags - [custodian {{ account }} - {{ region }}]"
      violation_desc:  |
         These instances are missing required tags:
      action_desc: |
        Please add the following tags to your resources:
        Application, Asset, Environment, Name
      to:
        - resource-owner 
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-custodian-email-queue
        region: us-east-1
```

**Comment by kapilt** [comment]
fwiw, i tried this in a centos 7.6 docker container, and it did work out of the box.

roughly what i did to try and reproduce

```
docker run -ti centos:centos7.6.1810 /bin/bash
$ yum install -y python-virtualenv
$ virtualenv c7n
$ source c7n/bin/activate
$ pip install c7n
# manually added yaml file
$ custodian run -c tag.yml -s out --assume role_arn
```

manually invoke the periodic lambda, all worked out of the box, so thats a cross push from python 2.7 cli to 3.7 lambda without issue on centos7.6

wrt to the actual issue i would double check that your virtualenv includes the latest pip and that custodian is installed there and that its active when running the cli, googling that error shows its common if your picking up an older pkg_resources say from the host.

**Comment by yuriydee** [comment]
Yep I had to uninstall pip and reinstall it again and now it works properly with Python 3.7. I was using pip to directly install c7n and running the commands without a virtualenv. Something mustve gotten broken during the upgrade. After checking, Ive narrowed it down to having an older version of "setuptools" package.
