### ISSUE TITLE
Custodian policies not working in AWS Stockholm region. 

### ISSUE THREAD

**Issue by nitinitare** [cloud-custodian/cloud-custodian#3503]
Hi All,

I tried to run the  custodian policies in the AWS Stockholm region but it's not working.
Is there a work around or currently it doesn't support in Stockholm region.

Please help me out with the issue.

Thanks.

**Comment by kapilt** [comment]
This issue needs a lot more information to be useful from a diagnostic perspective. What version of custodian, what policies?, what's the traceback or issue when you say not working.

**Comment by Mazhar404** [comment]
2019-02-11 10:55:25,344: c7n.policies:WARNING policy:list-stopped-ec2 resources:ec2 not available in region:eu-north-1
2019-02-11 10:55:25,344: custodian.commands:WARNING Empty policy file(s).  Nothing to do.

**Comment by Mazhar404** [comment]
policies:
- name: list-stopped-ec2
  resource: ec2
  comment: |
    Report stopped instances.
  filters:
     - "State.Name": running

**Comment by Mazhar404** [comment]
Command Used : 
custodian run -s out oldstoppedins.yml --region eu-north-1

**Comment by Mazhar404** [comment]
Same command and policy is running well and fine for all AWS regions but for Stockholm( eu-north-1) its showing the above error . Please help me on this

**Comment by kapilt** [comment]
try upgrading your version of boto3, `pip install -U boto3`


```
$ custodian run -c ec2.yml -s out -v -r eu-north-1
2019-02-11 07:04:49,444: custodian.commands:DEBUG Loaded file ec2.yml. Contains 1 policies
2019-02-11 07:04:49,456: custodian.aws:DEBUG using default region:eu-north-1 from boto
2019-02-11 07:04:49,585: custodian.output:DEBUG Storing output with <LogFile file://out/viking-ships/custodian-run.log>
2019-02-11 07:04:49,598: custodian.policy:DEBUG Running policy viking-ships resource: ec2 region:eu-north-1 c7n:0.8.40.0
2019-02-11 07:04:49,598: custodian.cache:DEBUG Using cache file /Users/kapilt/.cache/cloud-custodian.cache
2019-02-11 07:04:50,316: custodian.resources.ec2:DEBUG Filtered from 0 to 0 ec2
2019-02-11 07:04:50,316: custodian.policy:INFO policy: viking-ships resource:ec2 region:eu-north-1 count:0 time:0.72
2019-02-11 07:04:50,317: custodian.output:DEBUG metric:ResourceCount Count:0 policy:viking-ships restype:ec2 scope:policy
2019-02-11 07:04:50,317: custodian.output:DEBUG metric:ApiCalls Count:1 policy:viking-ships restype:ec2
```

**Comment by Mazhar404** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 450, in provision
    role=self.policy.options.assume_role)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 275, in publish
    func, role, s3_uri, qualifier=alias)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 394, in _create_or_update
    existing = self.get(func.name, qualifier)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 501, in get
    self.client.get_function, **params)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 506, in resource_exists
    return op(*args, **kw)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDeniedException) when calling the GetFunction operation: User: arn:aws:sts::215492xxxxxx:assumed-role/AmazonEC2RunCommandRoleForManagedInstances/mi-0f8df43e5fc880d94 is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:eu-north-1:215492984267:function:custodian-ec2-tag-compliance
2019-02-11 12:26:08,533: custodian.commands:ERROR Error while executing policy ec2-tag-compliance, continuing
Traceback (most recent call last):
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/commands.py", line 237, in run
    policy()
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 705, in __call__
    resources = mode.provision()
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/policy.py", line 450, in provision
    role=self.policy.options.assume_role)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 275, in publish
    func, role, s3_uri, qualifier=alias)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 394, in _create_or_update
    existing = self.get(func.name, qualifier)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 501, in get
    self.client.get_function, **params)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/c7n/mu.py", line 506, in resource_exists
    return op(*args, **kw)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/CloudCustodian/custodian/local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AccessDeniedException) when calling the GetFunction operation: User: arn:aws:sts::215492xxxxxx:assumed-role/AmazonEC2RunCommandRoleForManagedInstances/mi-0f8df43e5fc880d94 is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:eu-north-1:215492984267:function:custodian-ec2-tag-compliance
