### ISSUE TITLE
Error when using lambda-layer, transit-attachment or transit-gateway resources

### ISSUE THREAD

**Issue by ssteo** [cloud-custodian/cloud-custodian#3510]
2019-02-07 07:12:58,394 - custodian.commands - ERROR - Error while executing policy lambda-layer, continuing
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 412, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 226, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 88, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/var/task/c7n/query.py", line 62, in _invoke_client_enum
    if client.can_paginate(enum_op):
  File "/var/runtime/botocore/client.py", line 744, in can_paginate
    actual_operation_name = self._PY_TO_OP_NAME[operation_name]
KeyError: 'list_layers'

2019-02-07 07:14:51,901 - custodian.commands - ERROR - Error while executing policy transit-attachment, continuing
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 412, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 226, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 145, in filter
    parent_ids = [p[parents.resource_type.id] for p in parents.resources()]
  File "/var/task/c7n/query.py", line 412, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 226, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 88, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/var/task/c7n/query.py", line 62, in _invoke_client_enum
    if client.can_paginate(enum_op):
  File "/var/runtime/botocore/client.py", line 744, in can_paginate
    actual_operation_name = self._PY_TO_OP_NAME[operation_name]
KeyError: 'describe_transit_gateways'

2019-02-07 07:14:52,331 - custodian.commands - ERROR - Error while executing policy transit-gateway, continuing
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 412, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 226, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 88, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/var/task/c7n/query.py", line 62, in _invoke_client_enum
    if client.can_paginate(enum_op):
  File "/var/runtime/botocore/client.py", line 744, in can_paginate
    actual_operation_name = self._PY_TO_OP_NAME[operation_name]
KeyError: 'describe_transit_gateways'

Version 0.8.40.0

**Comment by kapilt** [comment]
AWS lambda has gone AWOL on updating sdks in lambda. You'll have to include the packages into the lambda policies, via

```
mode:
   type: cloudtrail
   packages:
     - botocore
     - boto3
     - urllib3
```

**Comment by ssteo** [comment]
Thanks!
