### ISSUE TITLE
GovCloud- location constraint is incompatible for the region specific endpoint this request was sent to

### ISSUE THREAD

**Issue by fidelito** [cloud-custodian/cloud-custodian#3523]
This is cli only I am not using lambda.

Running policy cloudtrail-enable-GovCloud.yml against account ACCOUNT

17:36:46			2019-02-13 22:36:46,765: custodian.policy:INFO policy: cloudtrail-enable resource:account region:us-gov-west-1 count:1 time:0.99
17:36:47			2019-02-13 22:36:47,440: custodian.output:ERROR Error while executing policy
17:36:47			Traceback (most recent call last):
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
17:36:47			    results = a.process(resources)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 702, in process
17:36:47			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
17:36:47			    return self._make_api_call(operation_name, kwargs)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
17:36:47			    raise error_class(parsed_response, operation_name)
17:36:47			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource
17:36:47			2019-02-13 22:36:47,441: custodian.commands:ERROR Error while executing policy cloudtrail-enable, continuing
17:36:47			Traceback (most recent call last):
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 237, in run
17:36:47			    policy()
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 870, in __call__
17:36:47			    resources = mode.run()
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
17:36:47			    results = a.process(resources)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 702, in process
17:36:47			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
17:36:47			    return self._make_api_call(operation_name, kwargs)
17:36:47			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
17:36:47			    raise error_class(parsed_response, operation_name)
17:36:47			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource
17:36:49			2019-02-13 22:36:49,621: custodian.policy:INFO policy: cloudtrail-enable resource:account region:us-gov-east-1 count:1 time:0.83
17:36:49			2019-02-13 22:36:49,919: custodian.output:ERROR Error while executing policy
17:36:49			Traceback (most recent call last):
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
17:36:49			    results = a.process(resources)
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 692, in process
17:36:49			    raise ce
17:36:49			ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The us-gov-west-1 location constraint is incompatible for the region specific endpoint this request was sent to.
17:36:49			2019-02-13 22:36:49,920: custodian.commands:ERROR Error while executing policy cloudtrail-enable, continuing
17:36:49			Traceback (most recent call last):
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 237, in run
17:36:49			    policy()
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 870, in __call__
17:36:49			    resources = mode.run()
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
17:36:49			    results = a.process(resources)
17:36:49			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 692, in process
17:36:49			    raise ce
17:36:49			ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The us-gov-west-1 location constraint is incompatible for the region specific endpoint this request was sent to.

The Policy:
policies:
  - name: "cloudtrail-enable"
    resource: account
    comments: |
      This policy will determine if cloudtrail is enabled on the
      account and enable it if it isnt.
    filters:
      - type: check-cloudtrail
        #global-events: true
        multi-region: true
        running: true
    actions:
      - type: enable-cloudtrail
        trail: cc-trail
        bucket: "${ACCOUNT}-cloudtrail"
        bucket-region: us-gov-west-1

**Comment by kapilt** [comment]
hmm.. so which region was the lambda executing in? was it executing in the same region and partition (gov-cloud) that it was trying to create the bucket in? typically within a partition  (say default), you can address and create buckets across regions with location constraint afaicr. However cross partition addressing typically doesn't work.  its possible we need to explicitly construct an s3 client to the end point destination for the bucket, but the default region (if the lambda was executing in the target region) should have also worked, hence the questions.

**Comment by fidelito** [comment]
Hi Kapil,

I am not using lambda at all. I am executing via c7n cli to both region us-gov-west-1 us-gov-east-1
The s3 bucket lives in  us-gov-west-1

I also notice that GovCloud is very picky and needs region_name if I was generating the STS token via script.  

conn = boto3.client('sts', region_name=region)
iam = boto3.client('iam', aws_access_key_id=token['Credentials']['AccessKeyId'],
                aws_secret_access_key=token['Credentials']['SecretAccessKey'],
                aws_session_token=token['Credentials']['SessionToken'], region_name=region)

My custodian version is 0.8.33.1 I haven't updated to the latest yet. I can if you think thats the issue.

**Comment by kapilt** [comment]
there are some other govcloud compatibility changes in trunk (mostly taking into account partitions when doing arn generation), but that wouldn't affect the issue that your seeing here. so in this context when the error happens, is it executing in us-gov-east-1 when it throws the error, if you execute against just us-gov-west-1 does it error. What's the cli command your using here (no account ids pls)?

**Comment by fidelito** [comment]
Hi Kapil,

I made the script execute on one of the GovCloud and region  us-gov-west-1 I used the same policy as I mention at the beginning. it looks like it creates the s3 bucket fine as I can see it in s3 but then fails to create the trail.

custodian run --profile ${ACCOUNT} --region ${REGION} --cache ${CACHE_DIR}/${POLICY_NAME}/${ACCOUNT}-cache.file --output-dir ${OUTPUT_DIR}/${POLICY_NAME}/${ACCOUNT} <(ACCOUNT=${ACCOUNT} envsubst < ${POLICY_DIR}/${POLICY})


Running policy cloudtrail-enable-GovCloud.yml against account ACCOUNT
07:48:02			2019-02-14 12:48:02,369: custodian.policy:INFO policy: cloudtrail-enable resource:account region:us-gov-west-1 count:1 time:0.89
07:48:03			2019-02-14 12:48:03,043: custodian.output:ERROR Error while executing policy
07:48:03			Traceback (most recent call last):
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
07:48:03			    results = a.process(resources)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 702, in process
07:48:03			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
07:48:03			    return self._make_api_call(operation_name, kwargs)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
07:48:03			    raise error_class(parsed_response, operation_name)
07:48:03			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource
07:48:03			2019-02-14 12:48:03,044: custodian.commands:ERROR Error while executing policy cloudtrail-enable, continuing
07:48:03			Traceback (most recent call last):
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 237, in run
07:48:03			    policy()
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 870, in __call__
07:48:03			    resources = mode.run()
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
07:48:03			    results = a.process(resources)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 702, in process
07:48:03			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
07:48:03			    return self._make_api_call(operation_name, kwargs)
07:48:03			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
07:48:03			    raise error_class(parsed_response, operation_name)
07:48:03			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource

**Comment by kapilt** [comment]
thanks, that's a slightly different issue, and a bit more obvious to rectify, in that when we do our s3 policy gen for the trail bucket it  wasn't using our arn generators (which are now partition aware) but statically defining the s3 arn prefix. I can send a pr later today that can attempt to address both of these issues. for a multi-region trail, I think you'll need mark the policy as being pinned to `region: us-gov-west-1` as a key at the policy level. so that when its not executed against us-gov-east-1.

**Comment by fidelito** [comment]
Kapil,
I am getting the following error now. 
custodian version
0.8.41.0

Running policy cloudtrail-enable.yml against account ACCOUNT
11:16:16			2019-02-19 16:16:16,460: custodian.policy:INFO policy: cloudtrail-enable resource:account region:us-east-1 count:1 time:0.93
11:16:18			2019-02-19 16:16:18,192: custodian.output:ERROR Error while executing policy
11:16:18			Traceback (most recent call last):
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
11:16:18			    results = a.process(resources)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 703, in process
11:16:18			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
11:16:18			    return self._make_api_call(operation_name, kwargs)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
11:16:18			    raise error_class(parsed_response, operation_name)
11:16:18			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Action does not apply to any resource(s) in statement
11:16:18			2019-02-19 16:16:18,193: custodian.commands:ERROR Error while executing policy cloudtrail-enable, continuing
11:16:18			Traceback (most recent call last):
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/commands.py", line 248, in run
11:16:18			    policy()
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 932, in __call__
11:16:18			    resources = mode.run()
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 264, in run
11:16:18			    results = a.process(resources)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/c7n/resources/account.py", line 703, in process
11:16:18			    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
11:16:18			    return self._make_api_call(operation_name, kwargs)
11:16:18			  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
11:16:18			    raise error_class(parsed_response, operation_name)
11:16:18			ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Action does not apply to any resource(s) in statement

**Comment by fidelito** [comment]
Hi Kapil,

I want to add that I am getting the same error when I do it on the GovCloud account used to create the actual GovCloud account. Changing the title.

**Comment by Siddhartha970** [comment]
Hi Kapil,

Im getting same error as fidelito mentioned while creating cloudtrail.


[DEBUG]	2019-06-14T11:52:07.550Z	01ff04f3-1302-4944-8e25-683e956efa7f	Running policy enalbe-cloud-trail resource: account region:us-east-2 c7n:0.8.43.1

[DEBUG]	2019-06-14T11:52:07.694Z	01ff04f3-1302-4944-8e25-683e956efa7f	Filtered from 1 to 1 account

[INFO]	2019-06-14T11:52:07.694Z	01ff04f3-1302-4944-8e25-683e956efa7f	policy: enalbe-cloud-trail resource:account region:us-east-2 count:1 time:0.14

[DEBUG]	2019-06-14T11:52:08.178Z	01ff04f3-1302-4944-8e25-683e956efa7f	metric:ResourceCount Count:1 policy:enalbe-cloud-trail restype:account scope:policy

[DEBUG]	2019-06-14T11:52:08.178Z	01ff04f3-1302-4944-8e25-683e956efa7f	metric:PolicyException Count:1 policy:enalbe-cloud-trail restype:account

[DEBUG]	2019-06-14T11:52:08.178Z	01ff04f3-1302-4944-8e25-683e956efa7f	metric:ApiCalls Count:5 policy:enalbe-cloud-trail restype:account

[ERROR]	2019-06-14T11:52:08.179Z	01ff04f3-1302-4944-8e25-683e956efa7f	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 264, in run
results = a.process(resources)
File "/var/task/c7n/resources/account.py", line 777, in process
s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
File "/var/runtime/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Action does not apply to any resource(s) in statement
[ERROR]	2019-06-14T11:52:08.179Z	01ff04f3-1302-4944-8e25-683e956efa7f	error during policy execution
Traceback (most recent call last):
File "/var/task/c7n/handler.py", line 168, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 909, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 520, in run
return PullMode.run(self)
File "/var/task/c7n/policy.py", line 264, in run
results = a.process(resources)
File "/var/task/c7n/resources/account.py", line 777, in process
s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
File "/var/runtime/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 623, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Action does not apply to any resource(s) in statement
[ERROR] ClientError: An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Action does not apply to any resource(s) in statement
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 909, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 520, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 264, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/account.py", line 777, in process
    s3client.put_bucket_policy(Bucket=bucket_name, Policy=policy_json)
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)
END RequestId: 01ff04f3-1302-4944-8e25-683e956efa7f

`policies:
  - name: enalbe-cloud-trail
    resource: account
    mode:
      type: periodic
      schedule: "cron(0/2 * * * ? *)"
      role: arn:aws:iam::xxxxxxxxxxx
    filters:
      - type: check-cloudtrail
        global-events: true
        running: true
        multi-region: true
    actions:
      - type: enable-cloudtrail
        trail: cc-trail
        bucket: "test-cloudtrailsid"
        bucket-region: us-east-2`
