### ISSUE TITLE
IAM -Delete Policy With Multiple Versions Failing

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#3528]
Using the latest code from master branch we are trying to run the following policy but it is failing to delete our invalid policy.  Here is the error message

```
- name: custodian-iam-no-used-all-all-policy
    resource: iam-policy
    description: Check polices when created if have *.* permissions.
    mode:
      type: cloudtrail
      events:
        - source: iam.amazonaws.com
          event: CreatePolicy
          ids: "responseElements.policy.policyId"
        - source: iam.amazonaws.com
          event: CreatePolicyVersion
          ids: "requestParameters.policyArn"
    filters:
      - type: has-allow-all
      - not:
        - or:
          - type: value
            key: "PolicyName"
            value: AdministratorAccess
          - type: value
            key: "PolicyName"
            value: TEST2
          - type: value
            key: "PolicyName"
            value: TEST1
    actions:
      - type: delete



16:42:13
[DEBUG]	2019-02-15T16:42:13.159Z	ccbfb910-45e5-4295-b12d-83d71115d95c	Deleting policy GodModeDeleteMeC7n

16:42:13
[DEBUG]	2019-02-15T16:42:13.217Z	ccbfb910-45e5-4295-b12d-83d71115d95c	metric:PolicyException Count:1 policy:custodian-iam-no-used-all-all-policy restype:iam-policy

16:42:13
[DEBUG]	2019-02-15T16:42:13.217Z	ccbfb910-45e5-4295-b12d-83d71115d95c	metric:ApiCalls Count:1 policy:custodian-iam-no-used-all-all-policy restype:iam-policy

16:42:13
[ERROR]	2019-02-15T16:42:13.217Z	ccbfb910-45e5-4295-b12d-83d71115d95c	Error while executing policy

16:42:13
Traceback (most recent call last):

16:42:13
File "/var/task/c7n/policy.py", line 476, in run

16:42:13
results = action.process(resources)

16:42:13
File "/var/task/c7n/resources/iam.py", line 719, in process

16:42:13
PolicyArn=r['Arn'])

16:42:13
File "/var/runtime/botocore/client.py", line 320, in _api_call

16:42:13
return self._make_api_call(operation_name, kwargs)

16:42:13
File "/var/runtime/botocore/client.py", line 623, in _make_api_call

16:42:13
raise error_class(parsed_response, operation_name)

16:42:13
botocore.errorfactory.DeleteConflictException: An error occurred (DeleteConflict) when calling the DeletePolicy operation: This policy has more than one version. Before you delete a policy, you must delete the policy's versions. The default version is deleted with the policy.

16:42:13
[ERROR] DeleteConflictException: An error occurred (DeleteConflict) when calling the DeletePolicy operation: This policy has more than one version. Before you delete a 
```

**Comment by kapilt** [comment]
that line number 719 doesn't correspond to master, it looks like your deploying with the old version I would guess
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/iam.py#L719

**Comment by jtroberts83** [comment]
@kapilt I looked at our cloud-custodian/c7n/resources/iam.py and line 719 is that same delete line which is part of the comment block so it makes no sense.

**Comment by jtroberts83** [comment]
Nevermind you are right.  Somehow there is an old custodian build showing up on my new server.  Possibly something old baked into the AMI.  I will investigate.
