### ISSUE TITLE
cli metrics subcommand and azure - throws errors

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#3555]
@kapilt  what should the expected behavior be here?

```
(cloud-custodian) $ custodian metrics policies/policy.yml
2019-02-20 11:19:18,346: custodian.azure.session:INFO Creating session with Azure CLI Authentication
2019-02-20 11:19:18,347: custodian.azure.session:INFO Session using Subscription ID: <my sub redacted>
2019-02-20 11:19:18,347: custodian.commands:INFO Getting <Policy resource: azure.resourcegroup name: delete-empty-resource-groups region: > metrics
Traceback (most recent call last):
  File "/Users/andyluong/Projects/forks/cloud-custodian/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/Users/andyluong/Projects/forks/cloud-custodian/c7n/cli.py", line 368, in main
    command(config)
  File "/Users/andyluong/Projects/forks/cloud-custodian/c7n/commands.py", line 136, in _load_policies
    return f(options, list(policies))
  File "/Users/andyluong/Projects/forks/cloud-custodian/c7n/commands.py", line 491, in metrics_cmd
    data[p.name] = p.get_metrics(start, end, options.period)
  File "/Users/andyluong/Projects/forks/cloud-custodian/c7n/policy.py", line 912, in get_metrics
    return mode.get_metrics(start, end, period)
  File "/Users/andyluong/Projects/forks/cloud-custodian/c7n/policy.py", line 170, in get_metrics
    client = session.client('cloudwatch')
  File "/Users/andyluong/Projects/forks/cloud-custodian/tools/c7n_azure/c7n_azure/session.py", line 148, in client
    service_name, client_name = client.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by aluong** [comment]
Some better docs on what this functionality does would be good too.

**Comment by kapilt** [comment]
So part of this wrapped up in cli compatibility which probably caused more
incompatibility tbh, so -m/—metrics used to be a Boolean to enable multi
cloud support it’s now supporting a provider name after, like aws, whatever
the metrics output was registered with.

**Comment by aluong** [comment]
The following works fine in Azure, ```custodian run --metrics azure://<resource_group_name>/<app_insights_name>```, but I am not sure what is expected when we do ```custodian metrics``` oppose to ```custodian run```.

**Comment by kapilt** [comment]
oh.. i kinda of forgot about that subcommand :-)  looking over it now, its supposed to do api calls to retrieve metrics for a policy and dump json to stdout, but its not particular useful in itself, and its missing any notion of multi-cloud abstraction. i suggest we deprecate it and ditch it. i can't imagine it has many users given how little of use it does, compared to native metrics tooling and dashboarding.  we can poll some users on gitter/chat to double check, but i don't see what utility it provides.

**Comment by kapilt** [comment]
The other way we could do this is to go ahead and wire in the multi-cloud support here, which would effectively become a delegation to the policy mode, and we need some specialization of the default 'poll' there by cloud provider, ie probably via switching modes registration to a tuple of provider, name.

anyways, i'm not really sure theres much value in supporting it going forward, the output format would vary widely by provider, and in some contexts (k8s) there isn't any native notion of a builtin metrics endpoint.

@thisisshi ^ any comments?

**Comment by thisisshi** [comment]
Yeah, I've run into something similar here (not with the metrics command, rather with run) but it's the same failure. delegation to the policy sounds good to me for the `custodian run -m` command, for the metric subcommand I personally haven't used it either, I'd be curious to see if there's any usage in the community as well

**Comment by kapilt** [comment]
to be clear this isn't about custodian run -m ... the reality on issues there is because its not a boolean anymore, it takes a parameter, ie `custodian run -m aws` or azure or gcp. the issue topic is primarily around metrics subcommand.. i pinged the room on chat, i got zero responses wrt, also given its implementation it seems less then useful.
