### ISSUE TITLE
c7n-mailer-replay : Python3 - TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#3656]
Using c7n-mailer-replay under Python3 gives the following trace:
```
Traceback (most recent call last):
  File "HOME/.pyenv/versions/cloud-custodian-3.6/bin/c7n-mailer-replay", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer-replay')()
  File "HOME/CLOUD_CUSTODIAN/SRC/tools/c7n_mailer/c7n_mailer/replay.py", line 134, in main
    json_dump_file=options.json_dump_file
  File "HOME/CLOUD_CUSTODIAN/SRC/tools/c7n_mailer/c7n_mailer/replay.py", line 46, in __init__
    fh.write(raw)
TypeError: write() argument must be str, not bytes
```

I had success with the following change:
```diff
diff --git a/tools/c7n_mailer/c7n_mailer/replay.py b/tools/c7n_mailer/c7n_mailer/replay.py
index b3f5456be..72f63332f 100644
--- a/tools/c7n_mailer/c7n_mailer/replay.py
+++ b/tools/c7n_mailer/c7n_mailer/replay.py
@@ -42,7 +42,7 @@ class MailerTester(object):
             logger.debug('base64-decoding and zlib decompressing message')
             raw = zlib.decompress(base64.b64decode(raw))
             if json_dump_file is not None:
-                with open(json_dump_file, 'w') as fh:
+                with open(json_dump_file, 'wb') as fh:
                     fh.write(raw)
         self.data = json.loads(raw)
         logger.debug('Loaded message JSON')
```

I believe it could be compatible with Python2 also, but it needs some testing.

**Comment by kapilt** [comment]
thanks for the bug report, that looks reasonable, although, we should probably be setting the codec explicitly to utf8 as an alternative.
