### ISSUE TITLE
GCP firewall resource policy fails with AttributeError

### ISSUE THREAD

**Issue by ankitdh7** [cloud-custodian/cloud-custodian#3696]
Hello,

I am trying to create a GCP firewall policy, which will capture and delete all firewall rules (except 2 firewall rule named - firewall1 and firewall2) with ingress/egress open to 0.0.0.0/0. I created below policy for the same but getting error:
```
 policies:
  - name: firewall-ingress
    resource: gcp.firewall
    filters:
      - and:
        - not:
          - or:
            - type: value
              key: name
              value: "firewall1"
            - type: value
              key: name
              value: "firewall2"
        - type: value
          key: sourceRanges[]
          value_type: swap
          op: in
          value: "0.0.0.0/0"

...
```

Expected behavior: firewall rules with 0.0.0.0/0 open should be displayed(except firewall rule- firewall1 & firewall2)

Actual Behaviour:

```
[root@server ~]# custodian run --dryrun -s . policy.yaml --cache-period=0
2019-03-18 18:55:07,262: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/lib/python2.7/site-packages/c7n_gcp/query.py", line 165, in resources
    return self.filter_resources(resources)
  File "/usr/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/usr/lib/python2.7/site-packages/c7n/filters/core.py", line 267, in process
    sweeper = AnnotationSweeper(self.manager.get_model().id, resources)
AttributeError: type object 'resource_type' has no attribute 'id'
2019-03-18 18:55:07,264: custodian.commands:ERROR Error while executing policy firewall-ingress, continuing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/commands.py", line 248, in run
    policy()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 937, in __call__
    resources = PullMode(self).run()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/lib/python2.7/site-packages/c7n_gcp/query.py", line 165, in resources
    return self.filter_resources(resources)
  File "/usr/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/usr/lib/python2.7/site-packages/c7n/filters/core.py", line 267, in process
    sweeper = AnnotationSweeper(self.manager.get_model().id, resources)
AttributeError: type object 'resource_type' has no attribute 'id'

```

Could you please have a look at it and give some advice.

Also, is there any action available to delete the matching GCP firewall rules like we can do for AWS SG?

Thanks

**Comment by kapilt** [comment]
thanks for the bug report, hmm.. yeah i think i had hoped to keep the resource type metadata specific to each provider, but this one in particular (lack of id) seems to be problematic for both reporting and 'or/not' filter block annotation sweeping.

**Comment by ankitdh7** [comment]
Thanks @kapilt for your input. Do you know if this behavior is getting fixed in any upcoming release or if there is any workaround for the same?

**Comment by kapilt** [comment]
just submitted a pull request for this one.

**Comment by ankitdh7** [comment]
Hi @kapilt 

I want to confirm you that changes suggested in your PR are working for me. Thanks a lot for that.

Also want to check if there is any way to remove filtered GCP firewall rules just like we can do for AWS SG? In GCP firewall action section, i see only notify and post-finding but nothing to remove it.

```
[root@server ~]# custodian schema gcp.firewall.actions
gcp.firewall:
  actions:
  - notify
  - post-finding

```

**Comment by kapilt** [comment]
@ankitdh7 gcp resources don't have the same degree of features as aws/azure yet, so there isn't a modify to firewalls yet. Contributions/Pull Requests welcome.
