### ISSUE TITLE
The 'request-limit-increase' action does not work on some of my AWS accounts.

### ISSUE THREAD

**Issue by pstanton237** [cloud-custodian/cloud-custodian#3794]
Hello,
I have multiple AWS accounts and some of which have errors when running the following policy.

```
policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        threshold: 60
    actions:
      - type: request-limit-increase
        percent-increase: 30
```

To be clear, the same policy below works only on some of my accounts. Some accounts run without problems.
I tried to find the difference between the problematic account and the non-problematic account, but there was no difference.
The AWS key I used to run c7n obviously has the 'AdministratorAccess' policy and the Enterprise support is enabled.
I don't know where to look further. Can someone help me?

Thanks!

Below is the result of the account that runs c7n without problems.
```
# custodian run -c policy/limits.yml -s out -v --dryrun --profile=account01 --region=ap-northeast-2
2019-04-11 17:32:55,932: custodian.commands:DEBUG Loaded file policy/limits.yml. Contains 1 policies
2019-04-11 17:32:56,475: custodian.output:DEBUG Storing output with <LogFile file://out/account-service-limits/custodian-run.log>
2019-04-11 17:32:56,526: custodian.policy:DEBUG Running policy account-service-limits resource: account region:ap-northeast-2 c7n:0.8.42.1
2019-04-11 17:32:59,235: custodian.resources.account:DEBUG Filtered from 1 to 1 account
2019-04-11 17:32:59,235: custodian.policy:INFO policy: account-service-limits resource:account region:ap-northeast-2 count:1 time:2.71
2019-04-11 17:32:59,237: custodian.policy:DEBUG dryrun: skipping actions
2019-04-11 17:32:59,239: custodian.output:DEBUG metric:ResourceCount Count:1 policy:account-service-limits restype:account scope:policy
2019-04-11 17:32:59,240: custodian.output:DEBUG metric:ApiCalls Count:2 policy:account-service-limits restype:account
```

Below is the result of the account that runs c7n with problems.
```
# custodian run -c policy/limits.yml -s out -v --dryrun --profile=account02 --region=ap-northeast-2
2019-04-11 17:33:36,531: custodian.commands:DEBUG Loaded file policy/limits.yml. Contains 1 policies
2019-04-11 17:33:37,031: custodian.output:DEBUG Storing output with <LogFile file://out/account-service-limits/custodian-run.log>
2019-04-11 17:33:37,048: custodian.policy:DEBUG Running policy account-service-limits resource: account region:ap-northeast-2 c7n:0.8.42.1
2019-04-11 17:33:38,931: custodian.output:DEBUG metric:PolicyException Count:1 policy:account-service-limits restype:account
2019-04-11 17:33:38,931: custodian.output:DEBUG metric:ApiCalls Count:2 policy:account-service-limits restype:account
2019-04-11 17:33:38,932: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 80, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 514, in process
    checks['flaggedResources'] = [r for r in checks['flaggedResources']
KeyError: u'flaggedResources'
2019-04-11 17:33:38,935: custodian.commands:ERROR Error while executing policy account-service-limits, continuing
Traceback (most recent call last):
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/commands.py", line 248, in run
    policy()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 937, in __call__
    resources = PullMode(self).run()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 80, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 514, in process
    checks['flaggedResources'] = [r for r in checks['flaggedResources']
KeyError: u'flaggedResources'
```

```
# custodian version
0.8.42.1

# python --version
Python 2.7.16
```

**Comment by pstanton237** [comment]
I think the issue below is like my problem.
https://github.com/cloud-custodian/cloud-custodian/issues/2402

**Comment by ryanash999** [comment]
Check the support level in the accounts which do not work.  I think it needs to be some level above "basic".   We have seen it not working with "basic" and working with "enterprise".

**Comment by pstanton237** [comment]
> Check the support level in the accounts which do not work. I think it needs to be some level above "basic". We have seen it not working with "basic" and working with "enterprise".

I've confirmed at the AWS Support center that the support plan for all accounts is Enterprise.

**Comment by kapilt** [comment]
are the accounts where they don't work newer? is it by region?

**Comment by pstanton237** [comment]
I have not used c7n before and I added 'region: us-east-2' to the policy as shown below, and it works.
However, I rarely use the resources of the us-east-2 region.

```
policies:
  - name: account-service-limits
    resource: account
    region: us-east-2
    filters:
      - type: service-limit
        threshold: 60
    actions:
      - type: request-limit-increase
        percent-increase: 30
```

```
# custodian run -c policy/limits.yml -s out -v --dryrun --profile=account02 --region=ap-northeast-2
2019-04-16 09:12:53,960: custodian.commands:DEBUG Loaded file policy/limits.yml. Contains 1 policies
2019-04-16 09:12:55,097: custodian.policy:INFO Skipping policy account-service-limits target-region: us-east-2 current-region: ap-northeast-2
```

So, if I add ap-northeast-2 to the policy and then run it, I can see the error again.
ap-northeast-2 is where most of my aws resources are set up.
```
policies:
  - name: account-service-limits
    resource: account
    region: ap-northeast-2
    filters:
      - type: service-limit
        threshold: 60
    actions:
      - type: request-limit-increase
        percent-increase: 30%
```

```
custodian run -c policy/limits.yml -s out -v --dryrun --profile=account02 --region=ap-northeast-2
2019-04-16 09:17:54,814: custodian.commands:DEBUG Loaded file policy/limits.yml. Contains 1 policies
2019-04-16 09:17:56,008: custodian.output:DEBUG Storing output with <LogFile file://out/account-service-limits/custodian-run.log>
2019-04-16 09:17:56,022: custodian.policy:DEBUG Running policy account-service-limits resource: account region:ap-northeast-2 c7n:0.8.42.1
2019-04-16 09:17:58,109: custodian.output:DEBUG metric:PolicyException Count:1 policy:account-service-limits restype:account
2019-04-16 09:17:58,109: custodian.output:DEBUG metric:ApiCalls Count:2 policy:account-service-limits restype:account
2019-04-16 09:17:58,109: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 80, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 514, in process
    checks['flaggedResources'] = [r for r in checks['flaggedResources']
KeyError: u'flaggedResources'
2019-04-16 09:17:58,111: custodian.commands:ERROR Error while executing policy account-service-limits, continuing
Traceback (most recent call last):
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/commands.py", line 248, in run
    policy()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 937, in __call__
    resources = PullMode(self).run()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 80, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/Users/macbook/Documents/repos/cloud-custodian/custodian/lib/python2.7/site-packages/c7n/resources/account.py", line 514, in process
    checks['flaggedResources'] = [r for r in checks['flaggedResources']
KeyError: u'flaggedResources'
```

So it seems to be a problem only in certain regions.

**Comment by kapilt** [comment]
This filter was originally written a few years ago, since then trusted advisor has effectively deprecated the check we're using  in favor of separate checks per service around limits. This could definitely cause some variations in api behavior by region, since the primary user of those apis (trusted advisor console) is using the newer checks. i was hoping we could defer this till a more permanent solution arrives, but it does look like we'll need to address in the interim.

**Comment by pstanton237** [comment]
> This filter was originally written a few years ago, since then trusted advisor has effectively deprecated the check we're using in favor of separate checks per service around limits. This could definitely cause some variations in api behavior by region, since the primary user of those apis (trusted advisor console) is using the newer checks. i was hoping we could defer this till a more permanent solution arrives, but it does look like we'll need to address in the interim.

Thank you for the update,
One more thing I would like to clarify is that account02 did not work with the service limit check in the 'ap-northeast-2' region, but account01 had no problems with 'ap-northeast-2'.
So I want to make it clear that not all accounts I use have problems with 'ap-northeast-2'.

**Comment by kapilt** [comment]
many thanks to @tjstansell there's now support for newer trusted advisor per service checks.
