### ISSUE TITLE
Azure - c7n-Mailer Errors

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3851]
About 50% of the time mailer runs, the following error results and messages aren't picked up, delivered:
```
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/c7n_mailer/cli.py", line 227, in main
    processor.run()
  File "/usr/local/lib/python3.7/site-packages/c7n_mailer/azure/azure_queue_processor.py", line 62, in run
    if (self.process_azure_queue_message(queue_message) or
  File "/usr/local/lib/python3.7/site-packages/c7n_mailer/azure/azure_queue_processor.py", line 89, in process_azure_queue_message
    SendGridDelivery(self.config, self.logger))
  File "/usr/local/lib/python3.7/site-packages/c7n_mailer/azure/sendgrid_delivery.py", line 29, in __init__
    sendgrid.SendGridAPIClient(apikey=self.config.get('sendgrid_api_key', ''))
TypeError: __init__() got an unexpected keyword argument 'apikey'
```

**Comment by kapilt** [comment]
hmm.. that implies a rev on the send grid api thats hosing delivery

**Comment by kapilt** [comment]
looks like it changed a while ago to be `api_key`  per https://github.com/sendgrid/sendgrid-python/pull/557/files

**Comment by stefangordon** [comment]
I think this still didn't make it to a release? We might have to push mailer.

**Comment by vmpowercli** [comment]
I faced the same issue while configuring the email, can you please provide me the the steps to fix this issue 

Thank you

**Comment by stefangordon** [comment]
@vmpowercli Several changes went in this morning to fix mailer, but you'll need to install all three packages from master

```
$ git clone https://github.com/cloud-custodian/cloud-custodian.git
$ cd cloud-custodian
$ pip install -e .
$ pip install -e tools/c7n_azure
$ pip install -e tools/c7n_mailer
```

That should give you a version of mailer that is working well!

**Comment by vmpowercli** [comment]
No Luck:(, still getting the same error even after runiing the above commands

**Comment by vmpowercli** [comment]
BTW here is the error message

(custodian) [root@ip-10-102-3-159 custodian]#  c7n-mailer --config mailer.yml --update-lambda && custodian run -c test-policy.yml -s .
Traceback (most recent call last):
  File "/root/custodian/bin/c7n-mailer", line 10, in <module>
    sys.exit(main())
  File "/root/custodian/lib/python2.7/site-packages/c7n_mailer/cli.py", line 211, in main
    deploy.provision(mailer_config, functools.partial(session_factory, mailer_config))
  File "/root/custodian/lib/python2.7/site-packages/c7n_mailer/deploy.py", line 88, in provision
    archive = get_archive(config)
  File "/root/custodian/lib/python2.7/site-packages/c7n_mailer/deploy.py", line 50, in get_archive
    'requests', 'urllib3', 'idna', 'chardet', 'certifi'])
TypeError: __init__() got an unexpected keyword argument 'modules'
****

**Comment by justinhauer** [comment]
I just created a fresh virtual environment today, pulled latest from source,installed mailer and ran successfully locally and in a container.....

Are you able to create a new virtual env with no site packages, and run the above? What happens when you try to run mailer locally instead of deploying an azure function for it? it also looks like you're using python 2.7, have you tried running in a python3 venv?
