### ISSUE TITLE
How to append resource tag with some string

### ISSUE THREAD

**Issue by KapilTeotia1** [cloud-custodian/cloud-custodian#3879]
How we can append some content to already exist tag in Cloud Custodian policy.

**Eg:** We have multiple resources where User tag is already defined and having value as "firstname.lastname". We want to send emails to the resource-owner in case of non-compliant resource. The C7Mailer gets failed while sending email to User as User tag don't contain the proper email address and having just "firstname.lastname" .

So we want to append domain like **@gmail.com** to the User tag so that we can send the proper communication to Resource-Owner.

Could you please guide me to implement this in cloud custodian?

**Comment by kapilt** [comment]
See the mailer configuration for org domain, it will suffix the domain on the to user value

https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_mailer/example.yml#L50

**Comment by KapilTeotia1** [comment]
Thanks Kapil for your kind response. But this is still not working.

Please find below the Mailer configuration file that we are using. If I am giving my email id like kapil.teotia@abc.com to a **User** tag in any resource then C7Mailer is working fine and I am getting the email properly. But If I just give firstname.lastname to **User** tag and added **org_domain: abc.com** as you advised in my Mailer configuration then email is not getting delivered and getting the error (Please find below).

Could you please advise if I am doing something wrong here or some other steps also need to taken apart from just defining the variable name in Mailer config file.

**Mailer File:**

queue_url: SQSQUEUE  -- this is variable
role: CUSTODIANROLE -- this is variable
region: REGION -- this is variable
from_address: MK-DDVS-DevOps@abc.com
contact_tags:
  - User 
lambda_tags:    
  Project: cloud-custodian
  Environment: ENVIRONMENT
  Service: DDVS 
  User: kapil.teotia@abc.com
  CostCenter: '12345678'
  Company: abc
  Role: Cloud-Custodian
  Name: ddvs-cloud-custodian
org_domain: abc.com




Error that I am now getting after adding **org_domain: abc.com**

custodian-mailer - INFO - Downloading messages from the SQS queue.
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 227, in main
    processor.run()
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 128, in run
    self.process_sqs_message(sqs_message)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/sqs_queue_processor.py", line 160, in process_sqs_message
    to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 240, in get_to_addrs_email_messages_map
    to_addrs_to_resources_map = self.get_email_to_addrs_to_resources_map(sqs_message)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 219, in get_email_to_addrs_to_resources_map
    resource
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 163, in get_resource_owner_emails_from_resource
    (uid) for uid in non_email_ids]))
AttributeError: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'

**Comment by KapilTeotia1** [comment]
Kapil, could you please provide an update here like how I can implement the required setup?

**Comment by kapilt** [comment]
seems like there is a gap here in mailer here between desired configuration and behavior.

**Comment by KapilTeotia1** [comment]
okay...thanks Kapil!!

Please be informed when we tried to add **org_domain** in mailer configuration as you suggested then domain is getting added to **Cloud trail->event-owner->User**. eg: like if any instance is started through autoscaling policy then User would be "autoscaling" in cloud trail events and org_domain will add domain in the user as "autoscaling@abc.com". And if we use event-owner in cloud custodian policy to notify event owner then email would be delivered to "autoscaling@abc.com".

We want to use bit same behaviour to notify to resource-owner along with event-owner. where the domain could be added to any User tag value. 

so is it possible to achieve the desired result by changing any mailer configuration or something else to add domain on user tag for any resource to notify resource-owner? or this is something that needs to improve and add new feature to achieve this behaviour? 

Kindly suggest?

**Comment by KapilTeotia1** [comment]
Hi Kapil,

Did you get a chance to review above query? Please advise.

**Comment by dvianello** [comment]
Got caught by this as well, we expected `org_domain` to work on tags as well, but it seems it's only added to cloudwatch events, according to the logic [here](https://github.com/cloud-custodian/cloud-custodian/blob/3d98cb0e1f37ee63608b9a59806a71c3f350bd5e/tools/c7n_mailer/c7n_mailer/email_delivery.py#L105). 

We have usernames that match inboxes in our AWS setup and in the tags, but not the full email address, so `org_domain` looked like the perfect fix to our problem. Until we realised it might not work as we (all?) intended.
