### ISSUE TITLE
c7n_mailer sending email issues- seeing the email still in queue

### ISSUE THREAD

**Issue by fidelito** [cloud-custodian/cloud-custodian#3968]
Hi,

below is the error I get when there seems to be an issue with emails that are sent from cloud custodian. I get most of the emails sent but there seems to be some behind in the queue that won't leave the queue.

START RequestId: 0bedb25f-689b-4b5c-997d-565e37c4ca33 Version: $LATEST
14:52:01
[ERROR] 2019-05-07T14:52:01.137Z 0bedb25f-689b-4b5c-997d-565e37c4ca33 Error starting mailer MailerSqsQueueProcessor().
14:52:01
Error: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'
Traceback (most recent call last):
14:52:01
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
14:52:01
mailer_sqs_queue_processor.run(parallel)
14:52:01
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run
14:52:01
self.process_sqs_message(sqs_message)
14:52:01
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 158, in process_sqs_message
14:52:01
to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)
14:52:01
File "/var/task/c7n_mailer/email_delivery.py", line 223, in get_to_addrs_email_messages_map
14:52:01
to_addrs_to_resources_map = self.get_email_to_addrs_to_resources_map(sqs_message)
14:52:01
File "/var/task/c7n_mailer/email_delivery.py", line 202, in get_email_to_addrs_to_resources_map
14:52:01
resource
14:52:01
File "/var/task/c7n_mailer/email_delivery.py", line 147, in get_resource_owner_emails_from_resource
14:52:01
(uid) for uid in non_email_ids]))
14:52:01
File "/var/task/c7n_mailer/email_delivery.py", line 147, in <listcomp>
14:52:01
(uid) for uid in non_email_ids]))
14:52:01
AttributeError: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'
14:52:01
END RequestId: 0bedb25f-689b-4b5c-997d-565e37c4ca33

**Comment by thisisshi** [comment]
are you using ldap? it looks like you may have some sort of ldap configuration enabled with your mailer install

**Comment by fidelito** [comment]
Hi,

this is my config.json of the cloud custodian mailer lambda.

{"datadog_api_key": null, "subnets": "subnet-blah", "queue_url": "https://sqs.REGION.amazonaws.com/ACCOUNTNUMBER/cloud_custodian_west2", "ses_region": null, "from_address": "example@example.com", "ldap_bind_user": null, "region": "REGION", "slack_webhook": null, "slack_token": null, "contact_tags": ["owner_email"], "role": "arn:aws:iam::ACCOUNTNUMBER:role/custodian_lambda", "timeout": 300, "memory": 1024, "ldap_bind_dn": null, "ldap_uri": null, "runtime": "python3.7", "security_groups": "sg-1111111111111", "ldap_bind_password": null, "smtp_server": "1.1.1.1", "smtp_port": 25, "debug": true, "dead_letter_config": {"TargetArn": "arn:aws:sqs:REGION:ACCOUNTNUMBER:cloud-custodian-dead-letter"}}

**Comment by fidelito** [comment]
Hi, here is more relevant trace back.

18:57:01
START RequestId: 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Version: $LATEST

18:57:01
[INFO] 2019-06-04T18:57:01.159Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 c7n_mailer starting...

18:57:01
[DEBUG] 2019-06-04T18:57:01.159Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 debug logging is turned on from mailer config file.

18:57:01
[INFO] 2019-06-04T18:57:01.163Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Downloading messages from the SQS queue.

18:57:01
[DEBUG] 2019-06-04T18:57:01.279Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Messages received 1

18:57:01
[DEBUG] 2019-06-04T18:57:01.279Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Message id: 3b885f68-9e1a-4272-91cb-49475a89ce5f received {'mtype': {'StringValue': 'maidmsg/1.0', 'DataType': 'String'}}

18:57:01
[DEBUG] 2019-06-04T18:57:01.279Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Got account:ACCOUNT message:3b885f68-9e1a-4272-91cb-49475a89ce5f elb:1 policy:elb-tag-owner-check recipients:example@example.com, resource-owner

18:57:01
[ERROR] 2019-06-04T18:57:01.287Z 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Error starting mailer MailerSqsQueueProcessor().

18:57:01
Error: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'

18:57:01
Traceback (most recent call last):

18:57:01
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer

18:57:01
mailer_sqs_queue_processor.run(parallel)

18:57:01
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run

18:57:01
self.process_sqs_message(sqs_message)

18:57:01
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 158, in process_sqs_message

18:57:01
to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(sqs_message)

18:57:01
File "/var/task/c7n_mailer/email_delivery.py", line 223, in get_to_addrs_email_messages_map

18:57:01
to_addrs_to_resources_map = self.get_email_to_addrs_to_resources_map(sqs_message)

18:57:01
File "/var/task/c7n_mailer/email_delivery.py", line 202, in get_email_to_addrs_to_resources_map

18:57:01
resource

18:57:01
File "/var/task/c7n_mailer/email_delivery.py", line 147, in get_resource_owner_emails_from_resource

18:57:01
(uid) for uid in non_email_ids]))

18:57:01
File "/var/task/c7n_mailer/email_delivery.py", line 147, in <listcomp>

18:57:01
(uid) for uid in non_email_ids]))

18:57:01
AttributeError: 'NoneType' object has no attribute 'get_email_to_addrs_from_uid'

18:57:01
END RequestId: 028f3e9d-1cb8-41d1-af98-545f0fc9ff64

18:57:01
REPORT RequestId: 028f3e9d-1cb8-41d1-af98-545f0fc9ff64 Duration: 144.73 ms Billed Duration: 200 ms Memory Size: 1024 MB Max Memory Used: 64 MB



Message ID: 	3b885f68-9e1a-4272-91cb-49475a89ce5f
Size: 	1.8 KB
MD5 of Body: 	894d47abb93e680e7d0e26119430ea2f
Sender Account ID: 	REMOVED
Sent: 	2019-06-03 10:14:16.665 GMT-04:00
First Received: 	2019-06-03 10:14:16.665 GMT-04:00
Receive Count: 	79
Message Attribute Count: 	1

**Comment by ajkerrigan-mdsol** [comment]
Hey @fidelito - based on our discussion in the gitter room I was wondering if this is happening because you don't have complete email addresses in your contact tags.

It looks like for `event-owner`, the mailer has [logic](https://github.com/cloud-custodian/cloud-custodian/blob/82a446ccb306e3513b541c4444ad4cbd77f243b1/tools/c7n_mailer/c7n_mailer/email_delivery.py#L105-L126) that tries to add your org domain and check to see if LDAP is configured before trying a lookup. This seems necessary because AWS event usernames won't come in as email addresses.

`resource-owner` [doesn't have that logic](https://github.com/cloud-custodian/cloud-custodian/blob/82a446ccb306e3513b541c4444ad4cbd77f243b1/tools/c7n_mailer/c7n_mailer/email_delivery.py#L153-L163), presumably because it assumes that your tags will provide a valid email.

@thisisshi Is it worth adding an LDAP warning if the mailer gets resource owner values that aren't complete email addresses, and LDAP isn't configured?
