### ISSUE TITLE
Azure - Functions Broken - Wheel Installation Fails

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4007]
It appears the ability to build an Azure Function stopped working today.

We believe this is a bug introduced in Wheel, thus any newly published dependency breaks us.

https://github.com/pypa/wheel/issues/294

```
2019-05-10 12:46:14,202: custodian.azure.AzureFunctionMode:INFO Building function package for stopped-vm-c7ca6e13
2019-05-10 12:46:14,823: custodian.azure.function_package:INFO Cached packages not found or requirements were changed.
2019-05-10 12:46:14,825: custodian.azure.function_package:INFO Preparing non binary wheels...
2019-05-10 12:46:45,080: custodian.azure.function_package:INFO Downloading wheels...
2019-05-10 12:51:58,082: custodian.azure.function_package:INFO Installing wheels...
2019-05-10 12:52:42,762: distlib.wheel:ERROR installation failed.
Traceback (most recent call last):
  File "c:\users\stefan\anaconda3\envs\cc\lib\site-packages\distlib\wheel.py", line 521, in install
    row = records[u_arcname]
KeyError: 'azure/'
2019-05-10 12:52:42,774: custodian.commands:ERROR Error while executing policy stopped-vm, continuing
Traceback (most recent call last):
  File "c:\users\stefan\anaconda3\envs\cc\lib\site-packages\c7n\commands.py", line 268, in run
    policy()
  File "c:\users\stefan\anaconda3\envs\cc\lib\site-packages\c7n\policy.py", line 945, in __call__
    resources = mode.provision()
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\policy.py", line 221, in provision
    package = self.build_functions_package(target_subscription_ids=self.target_subscription_ids)
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\policy.py", line 204, in build_functions_package
    queue_name=queue_name)
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\function_package.py", line 151, in build
    DependencyManager.install_wheels(wheels_folder, wheels_install_folder)
  File "c:\code\cloud-custodian\tools\c7n_azure\c7n_azure\dependency_manager.py", line 117, in install_wheels
    wheel.install(paths, ScriptMaker(None, None), lib_only=True)
  File "c:\users\stefan\anaconda3\envs\cc\lib\site-packages\distlib\wheel.py", line 521, in install
    row = records[u_arcname]
KeyError: 'azure/'
```

**Comment by stefangordon** [comment]
And distlib bug:
https://bitbucket.org/pypa/distlib/issues/122/distlib-fails-with-latest-wheel-release

**Comment by kapilt** [comment]
not sure if we can pin this, its not actually our dependency/

**Comment by kapilt** [comment]
afaict this is resolved upstream (new wheel release) and we can close this issue, can anyone confirm?

**Comment by stefangordon** [comment]
I believe before functions will package successfully we'll need all packages that were built with the bad version of Wheel to be rebuilt and published.  At a minimum it is Azure IoT Hub SDK, although if that won't be done shortly this morning we could pin an older version.

**Comment by stefangordon** [comment]
This might be all we need unless some other packages released yesterday
https://pypi.org/project/azure-mgmt-iothub/0.8.1/

Probably should just test and then close this

**Comment by Herman-Wu** [comment]
I still got "Failed to download wheels!" when tried to deploy Azure Functions... Any suggestions? Thanks.
Here are the logs:
.......
2019-07-04 18:48:43,023: custodian.azure.function_package:INFO Cached packages not found or requirements were changed.
2019-07-04 18:48:43,029: custodian.azure.function_package:INFO Removing cache folder...
2019-07-04 18:48:43,203: custodian.azure.function_package:INFO Preparing non binary wheels...
2019-07-04 18:48:52,311: custodian.azure.function_package:INFO Downloading wheels...
2019-07-04 18:49:20,592: c7n_azure.dependency_manager:ERROR Failed to download wheels!

**Comment by stefangordon** [comment]
Hey @Herman-Wu  - This may be a new issue due to a bug in the Cosmos SDK which we fixed here https://github.com/cloud-custodian/cloud-custodian/pull/4325

Trying to get that merged right now.  Once you have this if you were to install from master and tell pip to upgrade packages it should be fixed.  `pip install -e tools\c7n_azure -U`

**Comment by michael-chi** [comment]
I am having same issue here, I download latest code from github then did the following 
```
git clone https://github.com/cloud-custodian/cloud-custodian.git
sudo apt update
cd cloud-custodian
sudo apt install python-pip
sudo pip install -e .
sudo pip install -e tools/c7n_azure

curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
az login

export AZURE_TENANT_ID=7xxxxxxxxxxx47
export AZURE_SUBSCRIPTION_ID=e3xxxxxxxxxxxxx394e
export AZURE_CLIENT_ID=599xxxxxxxxxxxxae1a
export AZURE_CLIENT_SECRET=xxxxxxxxxxxxxx
```

then when I tried to deploy Azure Function, I got below error
```
azureuser@custodian-003:~/labs/001-functions$ custodian run --output-dir ./output stopped-vm.yaml  -v
2019-07-05 02:12:36,380: custodian.commands:DEBUG Loaded file stopped-vm.yaml. Contains 1 policies
2019-07-05 02:12:36,492: custodian.azure.session:INFO Creating session with Service Principal Authentication
2019-07-05 02:12:36,492: custodian.azure.session:INFO Session using Subscription ID: e35c484f-2d35-479f-8adb-9fe20c79394e
2019-07-05 02:12:37,115: custodian.azure.utils.ServiceClient.send:DEBUG 200
2019-07-05 02:12:37,116: custodian.azure.utils.ServiceClient.send:DEBUG x-ms-ratelimit-remaining-subscription-reads:11998
2019-07-05 02:12:37,121: custodian.azure.function_app_utils:INFO Found Function Application "stopped-vm-b173732a".
2019-07-05 02:12:38,409: custodian.azure.utils.ServiceClient.send:DEBUG 200
2019-07-05 02:12:38,409: custodian.azure.utils.ServiceClient.send:DEBUG x-ms-ratelimit-remaining-subscription-reads:11998
2019-07-05 02:12:38,410: custodian.azure.AzureFunctionMode:INFO Building function package for stopped-vm-b173732a
2019-07-05 02:12:38,666: pip.vcs:DEBUG Registered VCS backend: git
2019-07-05 02:12:38,689: pip.vcs:DEBUG Registered VCS backend: hg
2019-07-05 02:12:38,743: pip.vcs:DEBUG Registered VCS backend: svn
2019-07-05 02:12:38,743: pip.vcs:DEBUG Registered VCS backend: bzr
2019-07-05 02:12:38,902: custodian.azure.function_package:INFO Cached packages not found or requirements were changed.
2019-07-05 02:12:38,903: custodian.azure.function_package:INFO Removing cache folder...
2019-07-05 02:12:38,908: custodian.azure.function_package:INFO Preparing non binary wheels...
2019-07-05 02:12:38,944: c7n_azure.dependency_manager:DEBUG pip wheel -w /home/azureuser/cloud-custodian/tools/c7n_azure/c7n_azure/cache/wheels --no-binary=:all: --no-dependencies tabulate==0.8.3 PyYAML==5.1.1 pyrsistent==0.15.2 pycparser==2.19
2019-07-05 02:12:42,788: custodian.azure.function_package:INFO Downloading wheels...
2019-07-05 02:12:42,789: c7n_azure.dependency_manager:DEBUG pip download --dest /home/azureuser/cloud-custodian/tools/c7n_azure/c7n_azure/cache/wheels --find-links /home/azureuser/cloud-custodian/tools/c7n_azure/c7n_azure/cache/wheels PyJWT PyYAML>=4.2b4 adal argcomplete azure-common~=1.1 azure-cosmos azure-cosmosdb-table azure-graphrbac azure-keyvault azure-mgmt-apimanagement azure-mgmt-authorization azure-mgmt-batch azure-mgmt-cdn azure-mgmt-cognitiveservices azure-mgmt-compute azure-mgmt-containerregistry azure-mgmt-containerservice azure-mgmt-cosmosdb azure-mgmt-databricks azure-mgmt-datafactory azure-mgmt-datalake-store azure-mgmt-dns azure-mgmt-eventgrid azure-mgmt-iothub azure-mgmt-keyvault azure-mgmt-logic azure-mgmt-managementgroups azure-mgmt-monitor azure-mgmt-network azure-mgmt-nspkg>=2.0.0 azure-mgmt-policyinsights azure-mgmt-redis azure-mgmt-resource==2.1.0 azure-mgmt-sql azure-mgmt-storage azure-mgmt-web azure-storage-blob azure-storage-common~=2.0 azure-storage-file azure-storage-queue backports.functools_lru_cache boto3>=1.9.94 botocore>=1.12.94 certifi jsonpatch>=1.21 jsonpickle jsonschema msrestazure<2.0.0,>=0.4.20 netaddr python-dateutil<3.0.0,>=2.6 requests tabulate>=0.8.2 urllib3 --platform=manylinux1_x86_64 --python-version=36 --implementation=cp --abi=cp36m --only-binary=:all:
2019-07-05 02:12:49,259: c7n_azure.dependency_manager:ERROR Failed to download wheels!
2019-07-05 02:12:49,260: custodian.serverless:DEBUG Created custodian serverless archive size: 0.00mb
```

**Comment by Herman-Wu** [comment]
thanks @stefangordon , that works for me. It saves my day. :)

**Comment by stefangordon** [comment]
@michael-chi The problem is a package conflict between Azure-Cosmos and Azure-Storage and PIP can't really resolve it by itself, but adding the `-U` flag may force it to upgrade to the right version.

`sudo pip install -e tools/c7n_azure -U`

We need to end up with `azure-storage-common~=2.0`.
