### ISSUE TITLE
c7n-mailer --config mailer.yml --update-lambda has stopped working. Error - __init__() got an unexpected keyword argument 'modules'

### ISSUE THREAD

**Issue by ShivaSharm** [cloud-custodian/cloud-custodian#4032]
My CloudCustodian project has been running fine till April. But lately as I checked I have started to get below exception while running "c7n-mailer --config /home/ec2-user/mailer.yml --update-lambda".
I am using "git clone https://github.com/capitalone/cloud-custodian" and Seems something has changed in the cloud-custodian code itself that has broken it.

Could you please have a look at error below and advise if there is something I need to do (may be installing some dependency or something).

+ /usr/local/bin/c7n-mailer --config /home/ec2-user/mailer.yml --update-lambda
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 211, in main
    deploy.provision(mailer_config, functools.partial(session_factory, mailer_config))
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 88, in provision
    archive = get_archive(config)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 50, in get_archive
    'requests', 'urllib3', 'idna', 'chardet', 'certifi'])
TypeError: __init__() got an unexpected keyword argument 'modules'

Note : Nothing has changed in my mailer.yml  from the time it used to run fine.

**Comment by kapilt** [comment]
it seems like your using a new checkout of mailer with an older version of custodian. if your consistent on versions for both of those this should resolve, ie either use custodian and mailer from git or use both from release.

**Comment by kapilt** [comment]
yeah.. thats using an older version of custodian with a trunk version of mailer the way you have that setup.. your also creating a virtualenv but not using it..

`pip install -r requirements.txt -e .`  and you can avoid the develop line. actually easiest is to just do make install in the git checkout.. another answer is just use the docker image.

**Comment by nitrocode** [comment]
I see the same issue in 0.5.3, 0.5.2, different error in 0.5.1, and pinning c7n-mailer to 0.5.0 works.
