### ISSUE TITLE
azure - applicationinsights sdk rev breaks test recordings

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#4033]
Looks like a rev on azure-mgmt-applicationinsights broke the current test recordings:

https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-mgmt-applicationinsights_0.2.0

example fix here: https://github.com/cloud-custodian/cloud-custodian/pull/4015/commits/3873a314a6d3f5bb316a0e5d2257bc3b92cbae56

need to rerecord tests for the new version

```
________ FunctionAppUtilsTest.test_get_application_insights_key_exists _________
[gw0] linux2 -- Python 2.7.15 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/c7n_azure/tests/azure_common.py", line 374, in wrapper
    return func(*args, **kwargs)
  File "/home/vsts/work/1/s/tools/c7n_azure/tests/test_functionapp_utils.py", line 47, in test_get_application_insights_key_exists
    'resource_group_name': CONST_GROUP_NAME})
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/provisioning/deployment_unit.py", line 20, in get
    result = self._get(params)
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/provisioning/app_insights.py", line 16, in _get
    return self.client.components.get(params['resource_group_name'], params['name'])
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/azure/mgmt/applicationinsights/operations/components_operations.py", line 274, in get
    response = self._client.send(request, stream=False, **operation_config)
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/utils.py", line 120, in custodian_azure_send_override
    response = self.orig_send(request, headers, content, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 137, in send
    **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/vcr/stubs/__init__.py", line 237, in getresponse
    self.cassette.record_mode)
CannotOverwriteExistingCassetteException: No match for the request (<Request (GET) https://management.azure.com/subscriptions/ea42f556-5106-4743-99b0-c129bfa71a47/resourceGroups/test_functionapp-reqs/providers/Microsoft.Insights/components/cloud-custodian-test?api-version=2015-05-01>) was found. Can't overwrite existing cassette (u'/home/vsts/work/1/s/tools/c7n_azure/tests/cassettes/FunctionAppUtilsTest.test_get_application_insights_key_exists.json') in your current record mode ('none').
```

**Comment by stefangordon** [comment]
I've updated the test framework to bypass this type of test failure (case insensitive URI matcher), so that we don't need to change cassettes or pin.

**Comment by kapilt** [comment]
Thanks
