### ISSUE TITLE
c7n-trailcreator load-athena error

### ISSUE THREAD

**Issue by Mirage288** [cloud-custodian/cloud-custodian#4049]
Getting this error when trying to use load-athena option for c7n-trailcreator, Any pointers on what if anything that i'm might be doing wrong here? 

https://gist.github.com/Mirage288/8633571c180214bf07528230a3c843ce

c7n-trailcreator load-athena --region us-east-1 --resource-map resourcemap --workgroup primary --athena-db retro-autotagging --db trailcreator.db --month 08/2018 --assume arn:aws:iam::xxxxxxxxxx:role/CloudCustodian --region us-east-1 --account devops-lab
Traceback (most recent call last):
  File "/bin/c7n-trailcreator", line 11, in <module>
    load_entry_point('c7n-trailcreator', 'console_scripts', 'c7n-trailcreator')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: load_athena() got an unexpected keyword argument 'account'

Thank you!

**Comment by kapilt** [comment]
fixed in #5135
