### ISSUE TITLE
c7n-trailcreator fresh install - ModuleNotFoundError: No module named 'c7n_trailcreator'

### ISSUE THREAD

**Issue by atheiman** [cloud-custodian/cloud-custodian#4086]
Following https://cloudcustodian.io/docs/tools/c7n-trailcreator.html, I created a new python 3 virtualenv and installed c7n_trailcreator. Running the help raises `ModuleNotFoundError: No module named 'c7n_trailcreator'`:

```
cloud-custodian $ python3 -m venv ~/tmp/c7n-trailcreator
cloud-custodian $ source ~/tmp/c7n-trailcreator/bin/activate
(c7n-trailcreator) cloud-custodian $ python -V
Python 3.6.2
(c7n-trailcreator) cloud-custodian $ pip freeze
You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(c7n-trailcreator) cloud-custodian $ pip install c7n_trailcreator

...

(c7n-trailcreator) cloud-custodian $ pip freeze
argcomplete==1.10.0
attrs==19.1.0
boto3==1.9.158
botocore==1.12.158
c7n==0.8.43.1
c7n-trailcreator==0.1.2
Click==7.0
docutils==0.14
jmespath==0.9.4
jsonpatch==1.23
jsonpointer==2.0
jsonschema==3.0.1
pyrsistent==0.15.2
python-dateutil==2.8.0
PyYAML==5.1
s3transfer==0.2.0
six==1.12.0
tabulate==0.8.2
urllib3==1.25.3
You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(c7n-trailcreator) cloud-custodian $ c7n-trailcreator --help
Traceback (most recent call last):
  File "/Users/austinheiman/tmp/c7n-trailcreator/bin/c7n-trailcreator", line 11, in <module>
    load_entry_point('c7n-trailcreator==0.1.2', 'console_scripts', 'c7n-trailcreator')()
  File "/Users/austinheiman/tmp/c7n-trailcreator/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/austinheiman/tmp/c7n-trailcreator/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/austinheiman/tmp/c7n-trailcreator/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/austinheiman/tmp/c7n-trailcreator/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'c7n_trailcreator'
```

Full gist: https://gist.github.com/atheiman/a318bc51d273c7e9b13430a3d8febcfc

**Comment by kapilt** [comment]
trail creator won't be supported via pip install till the next release of custodian (next few days), its depends on some unreleased features in c7n-org that are will be part of that release. if you'd like to use c7n_trailcreator prior to that you'll need to checkout and install from git.

**Comment by kapilt** [comment]
resolved with the latest release
