### ISSUE TITLE
azure policy running error

### ISSUE THREAD

**Issue by Shelvey-Kansal** [cloud-custodian/cloud-custodian#4096]
Hey,

I am starting with Azure, following the guide to get started with Azure. I have configured everything but it is still not able to run my policy. The below error keeps on running when I run

custodian run --output-dir=. custodian.yml

`Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 9, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/home/custodian/cloud-custodian/c7n/cli.py", line 373, in main
    command(config)
  File "/home/custodian/cloud-custodian/c7n/commands.py", line 56, in _load_policies
    load_resources()
  File "/home/custodian/cloud-custodian/c7n/resources/__init__.py", line 103, in load_resources
    resources.load_plugins()
  File "/home/custodian/cloud-custodian/c7n/registry.py", line 117, in load_plugins
    f = ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (wheel 0.29.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('wheel==0.30.0'), set(['azure-cli-core']))
`

Please suggest me what I can do

**Comment by kapilt** [comment]
it looks like you have a version conflict locally. it might  be easier to use the docker image. the azure dependency stack is a bit complex. Doing a clean install with a virtualenv might resolve, it looks like your installing things globally. Also azure has a strong preference for python 3.6 for serverless usage.
