### ISSUE TITLE
ec2 filter for less than five security groups.

### ISSUE THREAD

**Issue by innamuriravi1987** [cloud-custodian/cloud-custodian#4120]

**Comment by innamuriravi1987** [comment]
please look at the below policy and suggest me a way forward.

vars:
  state-filter: &state-filter
    - "State.Name": running
    - "State.Name": stopped
policies:

 - name: ec2-SSSG-add
   resource: ec2
   mode:
     type: periodic
     role: arn:aws:iam::XXXXXXXXX:role/XXXXXXXX
     schedule: "cron(0 1 * * ? *)"
   comments: |
     policy to attach SSSG to ec2 instances.
   filters:
     - or: *state-filter
     - type: value
       key: GroupId
       op: not-in
       value: 
         - sg-XXXX
     - type: value
       key: VpcId
       op: equal
       value: vpc-XXX
     - **type: value
       key: security-group
       value_type: resource_count
       op: lt
       value: 5**
   actions:
     - type: modify-security-groups
       add: 
         - sg-XXXX

**Comment by kapilt** [comment]
your value filter filter on group id looks incorrect, your not really explaining why your policy isn't working, I suggest building up it up one filter at a time.

**Comment by innamuriravi1987** [comment]
I am actually trying to filter instances that are attached to less than five SGs.  I am looking for a right filter to do that.
I tried as below.
- type: security-group
  key: GroupId
  value_type: resource_count
  op: lt
  value: 5

**Comment by kapilt** [comment]
and what happened? your not asking questions or stating where your having a problem? i already posted in chat an example of using resource_count with the security-group that works. Again try building your filters one at a time and understanding where you have a problem.  yes resource_count does work, but your original policy has other issues.

**Comment by innamuriravi1987** [comment]
I tried with only one filter, getting the "AttributeError"  . policy file is as below.

policies:
  - name: vpc-sg-count
    resource: vpc
    filters:
     - type: security-group
       value_type: resource_count
       op: less-than
       value: 10000



2019-06-10 13:13:41,798: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/query.py", line 431, in resources
    resources = self.filter_resources(resources)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/related.py", line 101, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/related.py", line 86, in process_resource
    if self.match(robj):
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/core.py", line 497, in match
    r = self.get_resource_value(self.k, i)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/core.py", line 454, in get_resource_value
    if k.startswith('tag:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
2019-06-10 13:13:41,798: custodian.commands:ERROR Error while executing policy vpc-sg-count, continuing
Traceback (most recent call last):
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/commands.py", line 248, in run
    policy()
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/policy.py", line 937, in __call__
    resources = PullMode(self).run()
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/query.py", line 431, in resources
    resources = self.filter_resources(resources)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/manager.py", line 105, in filter_resources
    resources = f.process(resources, event)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/related.py", line 101, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/related.py", line 86, in process_resource
    if self.match(robj):
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/core.py", line 497, in match
    r = self.get_resource_value(self.k, i)
  File "/home/centos/custodian/lib/python2.7/site-packages/c7n/filters/core.py", line 454, in get_resource_value
    if k.startswith('tag:'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kapilt** [comment]
what version of custodian are you using?

**Comment by kapilt** [comment]
```
$> cat vpc.yml 
policies:
  - name: vpc-sg-count
    resource: aws.vpc
    filters:
     - type: security-group
       value_type: resource_count
       op: less-than
       value: 5
$> custodian run vpc.yml -s out
2019-06-10 11:08:07,989: custodian.policy:INFO policy:vpc-sg-count resource:aws.vpc region:us-east-1 count:0 time:0.51
$> custodian version
0.8.43.1
```

**Comment by innamuriravi1987** [comment]
Yes, I was using a lower version, it worked with the current version.
