### ISSUE TITLE
Error when trying to use value_regex

### ISSUE THREAD

**Issue by dineshdh** [cloud-custodian/cloud-custodian#4149]
Getting error when trying to use 
```
  - name: patch-level
    resource: aws.ec2
    filters:
      - type: value
        key: "tag:HIPVersion"
        value_type: expiration
        value_regex: "^.*([0-9]{4}[0-9]{2}[0-9]{2})$"
        op: greater-than
        value: 30
```

Version:
```
custodian version
0.8.43.1
```

Error
```
custodian run --output-dir=./output/policies/aws ./policies/aws.yaml
Traceback (most recent call last):
  File "/Users/p680778/Library/Python/2.7/bin/custodian", line 11, in <module>
    sys.exit(main())
  File "/Users/p680778/Library/Python/2.7/lib/python/site-packages/c7n/cli.py", line 368, in main
    command(config)
  File "/Users/p680778/Library/Python/2.7/lib/python/site-packages/c7n/commands.py", line 64, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/Users/p680778/Library/Python/2.7/lib/python/site-packages/c7n/policy.py", line 66, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy patch-level 
 Error on policy:patch-level resource:aws.ec2
Additional properties are not allowed ('value_regex' was unexpected)

Failed validating u'additionalProperties' in schema[26]:
    {u'additionalProperties': False,
     u'properties': {u'default': {u'type': u'object'},
                     u'key': {u'type': u'string'},
                     u'op': {u'enum': [u'regex',
                                       u'ni',
                                       u'gt',
                                       u'lt',
                                       u'gte',
                                       u'glob',
                                       u'contains',
                                       u'not-equal',
                                       u'equal',
                                       u'greater-than',
                                       u'ne',
                                       u'ge',
                                       u'le',
                                       u'lte',
                                       u'in',
                                       u'intersect',
                                       u'less-than',
                                       u'difference',
                                       u'regex-case',
                                       u'eq',
                                       u'not-in']},
                     u'type': {u'enum': [u'value']},
                     u'value': {u'oneOf': [{u'type': u'array'},
                                           {u'type': u'string'},
                                           {u'type': u'boolean'},
                                           {u'type': u'number'},
                                           {u'type': u'null'}]},
                     u'value_from': {u'additionalProperties': u'False',
                                     u'properties': {u'expr': {u'oneOf': [{u'type': u'integer'},
                                                                          {u'type': u'string'}]},
                                                     u'format': {u'enum': [u'csv',
                                                                           u'json',
                                                                           u'txt',
                                                                           u'csv2dict']},
                                                     u'url': {u'type': u'string'}},
                                     u'required': [u'url'],
                                     u'type': u'object'},
                     u'value_type': {u'enum': [u'age',
                                               u'integer',
                                               u'expiration',
                                               u'normalize',
                                               u'size',
                                               u'cidr',
                                               u'cidr_size',
                                               u'swap',
                                               u'resource_count',
                                               u'expr',
                                               u'unique_size']}},
     u'required': [u'type'],
     u'type': u'object'}

On instance:
    {'key': 'tag:HIPVersion',
     'op': 'greater-than',
     'type': 'value',
     'value': 30,
     'value_regex': '^.*([0-9]{4}[0-9]{2}[0-9]{2})$',
     'value_type': 'expiration'}
```

**Comment by thisisshi** [comment]
Hi @dineshdh have you installed custodian via the developer install? this feature is only on trunk atm, instructions here: https://cloudcustodian.io/docs/developer/installing.html
