### ISSUE TITLE
TypeError: 'unicode' object is not callable on c7n-mailer==0.5.2

### ISSUE THREAD

**Issue by pju-d2si** [cloud-custodian/cloud-custodian#4216]
after redeploy my mailer with update-lambda with c7n-mailer==0.5.2

we have an error when send an slack message with mailer 

Traceback (most recent call last):
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 185, in process_sqs_message
    slack_delivery.slack_handler(sqs_message, slack_messages)
  File "/var/task/c7n_mailer/slack_delivery.py", line 116, in slack_handler
    self.send_slack_msg(key, payload)
  File "/var/task/c7n_mailer/slack_delivery.py", line 189, in send_slack_msg
    response.status_code, response.text())
TypeError: 'unicode' object is not callable

after isolate a function send_slack_msg
line 189 :
response.status_code, response.text()

error fix : response.status_code, response.text

thanks for your support

**Comment by kapilt** [comment]
thanks for the bug report
