### ISSUE TITLE
Azure - Handle AdalError nicely

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4243]
If user has bad principal/expired token/whatever they get this `AdalError` buried in stack trace. 

This is a very common scenario, so if we can just handle `AdalError` here and print out the error body that would be preferable to dumping the stack.

You should be able to reproduce by just putting in an invalid client secret.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 367, in set_token
    self.secret
  File "/usr/local/lib/python3.7/site-packages/adal/authentication_context.py", line 179, in acquire_token_with_client_credentials
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.7/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.7/site-packages/adal/authentication_context.py", line 177, in token_func
    return token_request.get_token_with_client_credentials(client_secret)
  File "/usr/local/lib/python3.7/site-packages/adal/token_request.py", line 315, in get_token_with_client_credentials
    token = self._oauth_get_token(oauth_parameters)
  File "/usr/local/lib/python3.7/site-packages/adal/token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/usr/local/lib/python3.7/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: e380c8af-e1ad-48c3-a921-eb7f2ac94900\r\nCorrelation ID: 1d69ea7c-37bd-4b1e-80d4-01a3b9768a38\r\nTimestamp: 2019-06-24 19:33:04Z","error_codes":[7000215],"timestamp":"2019-06-24 19:33:04Z","trace_id":"e380c8af-e1ad-48c3-a921-eb7f2ac94900","correlation_id":"1d69ea7c-37bd-4b1e-80d4-01a3b9768a38"}

```

**Comment by yayitserica** [comment]
### ACCEPTANCE CRITERIA

1. Identify a good place in the code to "catch" this error.
2. Create a notification that a secret/token has expired.

FYI @stefangordon
