### ISSUE TITLE
c7n-org ImportError: cannot import name get_resource_class

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4313]
Trying multi account.  Ran pip install c7n-org with no errors but --help after gives the below.  Tried to uninstall and install again with same results.  

(custodian) sh-4.2$  c7n-org --help
Traceback (most recent call last):
  File "/usr/bin/c7n-org", line 11, in <module>
    load_entry_point('c7n-org==0.5.3', 'console_scripts', 'c7n-org')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/c7n_org/cli.py", line 41, in <module>
    from c7n.provider import get_resource_class
ImportError: cannot import name get_resource_class

**Comment by vtomardb** [comment]
@martinklie It does not look like an issue with c7n-org its your python issue. Use python3 or use docker image.

**Comment by kapilt** [comment]
Looks like a mixed version install, docker or upgrading both would resolve

**Comment by martinklie** [comment]
Thanks all.  pip3 for the install resolved it.
