### ISSUE TITLE
ci - azure queue message failures

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4363]
its a little unclear how this got into trunk without failing in ci, but its now failing on several pull requests and trunk, which suggests a backwards incompatible dependency change.

```
___________ FunctionTest.test_queue_message_dequeue_count_above_max ____________
[gw1] linux -- Python 3.6.8 /home/vsts/work/1/s/.tox/py36-cov/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/c7n_azure/tests/test_function.py", line 46, in test_queue_message_dequeue_count_above_max
    input = QueueMessage(body=self.body,
NameError: name 'QueueMessage' is not defined
_________ FunctionTest.test_queue_message_dequeue_count_less_than_max __________
[gw1] linux -- Python 3.6.8 /home/vsts/work/1/s/.tox/py36-cov/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/c7n_azure/tests/test_function.py", line 37, in test_queue_message_dequeue_count_less_than_max
    input = QueueMessage(body=self.body,
NameError: name 'QueueMessage' is not defined
```

**Comment by kapilt** [comment]
fixed in #4364
