### ISSUE TITLE
Testing Cloud Custodian with tox is broken

### ISSUE THREAD

**Issue by tuxinaut** [cloud-custodian/cloud-custodian#4425]
# Background

I followed the step by step tutorial [Installing for Developers](https://cloudcustodian.io/docs/developer/installing.html#installing-prerequisites) everything went fine but I can't run tox because of the error below: 

```
(cloud-custodian) ✔  14:56 /tmp/cloud-custodian [ master {origin/master } ↓·13 | ✚ 1 …1 ] $ tox -e py37
GLOB sdist-make: /tmp/cloud-custodian/setup.py
py37 inst-nodeps: /tmp/cloud-custodian/.tox/.tmp/package/1/c7n-0.8.44.2.zip
ERROR: invocation failed (exit code 1), logfile: /tmp/cloud-custodian/.tox/py37/log/py37-4.log
================================================================================================================== log start ==================================================================================================================
Processing ./.tox/.tmp/package/1/c7n-0.8.44.2.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-k7w1rj_4/setup.py", line 14, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-req-build-k7w1rj_4/setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname), encoding='utf-8').read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-k7w1rj_4/README.md'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-k7w1rj_4/

=================================================================================================================== log end ===================================================================================================================
___________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
ERROR:   py37: InvocationError for command /tmp/cloud-custodian/.tox/py37/bin/python -m pip install --no-deps -U .tox/.tmp/package/1/c7n-0.8.44.2.zip (exited with code 1)
```

**Comment by kapilt** [comment]
i've noticed a few issues with tox, albeit with different tracebacks, specifically tox with 3.7 wanted tox installed outside of the virtualenv.

**Comment by kapilt** [comment]
Could you clarify on os version here?

**Comment by tuxinaut** [comment]
@kapilt sorry for the late answer I was on vacation and only now found time to answer.

`OS:` **Ubuntu 16.04**

**Comment by tuxinaut** [comment]
Most likely not relevant anymore, so I'm going to close the issue.
