### ISSUE TITLE
ec2.filter check-permissions usage resulting in list index out of range error

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#4495]
List index out of range error occurring when using the following policy executes in an account with single ec2 instance who's profile does not allow the referenced action.

```
policies:
  - name: ec2-overprivileged
    resource: ec2
    mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/CloudCustodian
    filters:
      - type: check-permissions
        match: allowed
        actions:
        - iam:CreateUser
```

Traceback:
```

12:38:55
[DEBUG] 2019-08-03T16:38:55.896Z a9a26624-94d7-44ef-98ca-ebace890db14 Disabling cache

12:38:55
[INFO] 2019-08-03T16:38:55.897Z a9a26624-94d7-44ef-98ca-ebace890db14 Filtering resources with [<c7n.resources.ec2.ComputePermissions object at 0x7f7a88cb8470>]

12:38:56
[ERROR] 2019-08-03T16:38:56.131Z a9a26624-94d7-44ef-98ca-ebace890db14 error during policy execution

12:38:56
Traceback (most recent call last):

12:38:56
File "/var/task/c7n/handler.py", line 168, in dispatch_event

12:38:56
p.push(event, context)

12:38:56
File "/var/task/c7n/policy.py", line 907, in push

12:38:56
return mode.run(event, lambda_ctx)

12:38:56
File "/var/task/c7n/policy.py", line 704, in run

12:38:56
resources = super(ConfigRuleMode, self).run(event, lambda_context)

12:38:56
File "/var/task/c7n/policy.py", line 445, in run

12:38:56
resources, event)

12:38:56
File "/var/task/c7n/manager.py", line 108, in filter_resources

12:38:56
resources = f.process(resources, event)

12:38:56
File "/var/task/c7n/resources/iam.py", line 447, in process

12:38:56
for arn, r in zip(self.get_iam_arns(resources), resources):

12:38:56
File "/var/task/c7n/resources/ec2.py", line 207, in get_iam_arns

12:38:56
[p[1] for p in profile_arns]))}

12:38:56
File "/var/task/c7n/resources/ec2.py", line 203, in <dictcomp>

12:38:56
for arn, profile in zip(

12:38:56
IndexError: list index out of range

12:38:56
[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/custodian_policy.py", line 4, in run     return handler.dispatch_event(event, context)   File "/var/task/c7n/handler.py", line 168, in dispatch_event     p.push(event, context)   File "/var/task/c7n/policy.py", line 907, in push     return mode.run(event, lambda_ctx)   File "/var/task/c7n/policy.py", l

12:38:56
```

**Comment by FireballDWF** [comment]
Another error with same filter, suspect bug being triggered by a stopped ec2 instance, where stopped instances don't have instance profile's attached.
```
CloudWatchLog Groups/aws/lambda/custodian-ec2-overprivileged2019/08/04/[$LATEST]f1aa78ac2a974fc9bbbcafa7d609ffb0
Row
Text
Time (UTC -04:00)
Message
2019-08-04

09:11:27
START RequestId: 3c557219-ceeb-4e55-ba50-c63020c1544c Version: $LATEST

09:11:27
[INFO] 2019-08-04T13:11:27.685Z 3c557219-ceeb-4e55-ba50-c63020c1544c Processing event

09:11:27
{

09:11:27
"version": "1.0",

09:11:27
"invokingEvent": "{\"configurationItemDiff\":null,\"configurationItem\":{\"relatedEvents\":[],\"relationships\":[{\"resourceId\":\"eni-010981f8b35346077\",\"resourceName\":null,\"resourceType\":\"AWS::EC2::NetworkInterface\",\"name\":\"Contains NetworkInterface\"},{\"resourceId\":\"sg-023623d240f3d0e60\",\"resourceName\":null,\"resourceType\":\"AWS::EC2::SecurityGroup\",\"name\":\"Is associated

09:11:27
"resultToken": "eyJlbmNyeXB0ZWREYXRhIjpbMTEzLC0xMTcsLTU1LDM0LC05NywtMTA3LDU0LDk3LC0xMDQsLTk3LDQwLC0xNiwtMTAwLDQzLC03Miw4NSwxMDcsODIsMjksMTAwLDM5LDYyLDQxLC0zOSw3NCwxMDMsLTY4LC03MSwtMjAsLTEyMiwxMTcsMTgsLTQ0LC00LDg3LDIyLDEwOSwtMTI1LDUsLTExNCwtNzMsLTY1LC0yLC0yNSwtOTAsLTkxLC0xMTQsLTg3LC0zNiw3LDEwLC0xMjMsLTEyLC0xMDEsLTc0LC0xMjEsLTExNywxMjYsLTg4LC03OCwtOTIsOCwzMCwtMTgsNzEsLTE0LC0yMSwtMzAsLTksMywxMSwxMD

09:11:27
"eventLeftScope": false,

09:11:27
"executionRoleArn": "arn:aws:iam::369510138361:role/service-role/config-role-us-east-1",

09:11:27
"configRuleArn": "arn:aws:config:us-east-1:369510138361:config-rule/config-rule-gtretw",

09:11:27
"configRuleName": "custodian-ec2-overprivileged",

09:11:27
"configRuleId": "config-rule-gtretw",

09:11:27
"accountId": "369510138361",

09:11:27
"debug": true

09:11:27
}

09:11:27
[DEBUG] 2019-08-04T13:11:27.909Z 3c557219-ceeb-4e55-ba50-c63020c1544c Disabling cache

09:11:27
[INFO] 2019-08-04T13:11:27.910Z 3c557219-ceeb-4e55-ba50-c63020c1544c Filtering resources with [<c7n.resources.ec2.ComputePermissions object at 0x7f6414900d30>]

09:11:28
[ERROR] 2019-08-04T13:11:28.38Z 3c557219-ceeb-4e55-ba50-c63020c1544c error during policy execution

09:11:28
Traceback (most recent call last):

09:11:28
File "/var/task/c7n/handler.py", line 168, in dispatch_event

09:11:28
p.push(event, context)

09:11:28
File "/var/task/c7n/policy.py", line 907, in push

09:11:28
return mode.run(event, lambda_ctx)

09:11:28
File "/var/task/c7n/policy.py", line 704, in run

09:11:28
resources = super(ConfigRuleMode, self).run(event, lambda_context)

09:11:28
File "/var/task/c7n/policy.py", line 445, in run

09:11:28
resources, event)

09:11:28
File "/var/task/c7n/manager.py", line 108, in filter_resources

09:11:28
resources = f.process(resources, event)

09:11:28
File "/var/task/c7n/resources/iam.py", line 447, in process

09:11:28
for arn, r in zip(self.get_iam_arns(resources), resources):

09:11:28
File "/var/task/c7n/resources/ec2.py", line 197, in get_iam_arns

09:11:28
for r in resources if 'IamInstanceProfile' in r}

09:11:28
File "/var/task/c7n/resources/ec2.py", line 197, in <dictcomp>

09:11:28
for r in resources if 'IamInstanceProfile' in r}

09:11:28
TypeError: 'NoneType' object is not subscriptable

09:11:28
[ERROR] TypeError: 'NoneType' object is not subscriptable Traceback (most recent call last):   File "/var/task/custodian_policy.py", line 4, in run     return handler.dispatch_event(event, context)   File "/var/task/c7n/handler.py", line 168, in dispatch_event     p.push(event, context)   File "/var/task/c7n/policy.py", line 907, in push     return mode.run(event, lambda_ctx)   File "/var/task/c7n
```
