### ISSUE TITLE
EC2 snapshot fails in Lambda but not locally

### ISSUE THREAD

**Issue by leoramirez-mulesoft** [cloud-custodian/cloud-custodian#4540]
Hello guys thank you for such wonderful tool... but I'm afraid I found a bug:

I'm trying to take an EBS snapshot from an EC2 policy:

```
policies:
  - name: ec2-mark
    resource: ec2
    description: |
      Stop standalone EC2 instances and mark for termination
    mode:
      - type: periodic
        schedule: "cron(0 3 ? * 6 *)"
        role: arn:aws:iam::{account_id}:role/my-lambda-role
    filters:
      - or:
        - not:
          - <<: *filter-var-marked-terminate
        - State.Name: "running"
      - "tag:aws:autoscaling:groupName": absent
    actions:
      - type: mark-for-op
        op: terminate
        days: 7
      - type: snapshot   # taking EBS snapshot before stopping
        copy-tags:
          - Name
      - type: stop
```

And it runs locally without mode section, it takes EBS snaps and copy tags to them just as intended.

But it fails when run from Lambda, the policy deploys (CloudWatch rule and Lambda function), but when Lambda runs, it throws the following error (in CloudWatch logs):

```
[ERROR] 2019-08-07T13:00:41.423Z 040797ba-6aa6-4171-8062-b104bb35b0d3 Exception creating snapshot set instance:i-0000000000000000
'EC2' object has no attribute 'create_snapshots'
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 261, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/ec2.py", line 1347, in process
    raise err
  File "/var/lang/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/resources/ec2.py", line 1362, in process_volume_set
    result = self.manager.retry(client.create_snapshots, **params)
  File "/var/runtime/botocore/client.py", line 563, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'EC2' object has no attribute 'create_snapshots'
[ERROR] AttributeError: 'EC2' object has no attribute 'create_snapshots'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 907, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 517, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 261, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/ec2.py", line 1347, in process
    raise err
  File "/var/lang/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/resources/ec2.py", line 1362, in process_volume_set
    result = self.manager.retry(client.create_snapshots, **params)
  File "/var/runtime/botocore/client.py", line 563, in __getattr__
    self.__class__.__name__, item)
```
Although I searched in previous issues and didn't find a similar one, please close if it is a duplicated issue.

Thanks in advance.

**Comment by kapilt** [comment]
this needs a newer sdk then whats in lambda, you'll need to add 
`packages: [boto3, botocore, urllib3]` to the mode section of this policy.

**Comment by leoramirez-mulesoft** [comment]
Thank you very much @kapilt for the explanation and the solution; It makes it now work in lambda :-)
