### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'oneshot'

### ISSUE THREAD

**Issue by miked63017** [cloud-custodian/cloud-custodian#4580]
I briefly searched but could not find any issues related to this, I am running a tag compliance policy and when I run ```custodian run --dryrun -s out tag-compliance.yaml``` I get the following stack trace:

```
Traceback (most recent call last):
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/commands.py", line 269, in run
    policy()
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/policy.py", line 1097, in __call__
    resources = PullMode(self).run()
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/policy.py", line 220, in run
    with self.policy.ctx:
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/ctx.py", line 87, in __enter__
    self.sys_stats.__enter__()
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/output.py", line 198, in __enter__
    self.push_snapshot()
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/output.py", line 133, in push_snapshot
    self.snapshot_stack.append(self.get_snapshot())
  File "/Users/mdonlon/miniconda3/lib/python3.7/site-packages/c7n-0.8.44.2-py3.7.egg/c7n/output.py", line 221, in get_snapshot
    with self.process.oneshot():
AttributeError: 'Process' object has no attribute 'oneshot'
```

Here is my yaml policy:
```
policies:
 - name: tag-compliance
   resource: aws.ec2
   description: |
     Schedule a resource that does not meet tag compliance policies to be stopped in four days. Note a separate policy using the`marked-for-op` filter is required to actually stop the instances after four days.
   filters:
    - State.Name: running
    - "tag:sometag": absent
    - "tag:some_other_tag": absent
   actions:
    - type: mark-for-op
      op: stop
      days: 4
```

Running version from github master I cloned yesterday, and did a fresh pull(and re-installed) against this morning. Anyone have any ideas?

**Comment by miked63017** [comment]
Also get the same error if I use an even simpler yaml like described in the docs:
```
(base) ip-192-168-1-194:cloud-custodian-jobs mdonlon$ cat custodian.yaml
policies:
  - name: my-first-policy
    resource: aws.ec2
    filters:
      - "tag:Custodian": present
```

**Comment by miked63017** [comment]
Got it working by creating a new env and pip in stalling c7n rather than python setup.py install
