### ISSUE TITLE
ci - docker build failure due to azure dependency stack

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4593]
```
Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111031 sha256=cb0e06c36862a18b6fa7044663a6d6134f51732890f1c8befc0df551f7dd7154
Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built c7n-azure distlib yarl wrapt antlr4-python3-runtime pycparser
ERROR: azure-cosmosdb-table 1.0.5 has requirement azure-storage-common~=1.1, but you'll have azure-storage-common 2.1.0 which is incompatible.
```

**Comment by stefangordon** [comment]
https://pypi.org/project/azure-storage-common/#history

The conflict was there with 2.0.0 but perhaps the change to 2.1.0 caused a problem.  

Where can we see the docker CI builds/logs?  I only see the status report for them in the commit history but the details links don't work.

**Comment by kapilt** [comment]
the actual build failure might be the one further down, you must be signed into docker hub to see.
note i commented post merge on this pr that introduced this from future import itertools that import indirection was not needed.

```
ERROR: azure-cosmosdb-table 1.0.5 has requirement azure-storage-common~=1.1, but you'll have azure-storage-common 2.1.0 which is incompatible.
Installing collected packages: multidict, yarl, wrapt, vcrpy, vcrpy-unittest, backports.functools-lru-cache, azure-functions, azure-common, oauthlib, requests-oauthlib, isodate, msrest, pycparser, cffi, asn1crypto, cryptography, PyJWT, adal, msrestazure, azure-mgmt-authorization, azure-mgmt-apimanagement, azure-mgmt-applicationinsights, azure-mgmt-batch, azure-mgmt-cognitiveservices, azure-mgmt-cosmosdb, azure-mgmt-costmanagement, azure-mgmt-containerinstance, azure-mgmt-compute, azure-mgmt-cdn, azure-mgmt-containerregistry, azure-mgmt-containerservice, azure-mgmt-databricks, azure-nspkg, azure-mgmt-nspkg, azure-mgmt-datalake-nspkg, azure-mgmt-datalake-store, azure-mgmt-datafactory, azure-mgmt-dns, azure-mgmt-eventgrid, azure-mgmt-eventhub, azure-mgmt-iothub, azure-mgmt-keyvault, azure-mgmt-managementgroups, azure-mgmt-network, azure-mgmt-redis, azure-mgmt-resource, azure-mgmt-sql, azure-mgmt-storage, azure-mgmt-web, azure-mgmt-monitor, azure-mgmt-policyinsights, azure-mgmt-logic, azure-cosmos, azure-graphrbac, azure-keyvault, azure-storage-common, azure-storage-blob, azure-storage-queue, azure-storage-file, azure-cosmosdb-nspkg, azure-cosmosdb-table, applicationinsights, tzlocal, apscheduler, distlib, jsonpickle, bcrypt, pynacl, paramiko, azure-cli-nspkg, colorama, pygments, knack, antlr4-python3-runtime, humanfriendly, portalocker, azure-cli-telemetry, pyopenssl, wheel, azure-cli-core, netaddr, c7n-azure
Found existing installation: wheel 0.33.4
Uninstalling wheel-0.33.4:
Successfully uninstalled wheel-0.33.4
Successfully installed PyJWT-1.7.1 adal-1.2.2 antlr4-python3-runtime-4.7.2 applicationinsights-0.11.9 apscheduler-3.6.1 asn1crypto-0.24.0 azure-cli-core-2.0.71 azure-cli-nspkg-3.0.4 azure-cli-telemetry-1.0.3 azure-common-1.1.23 azure-cosmos-3.1.1 azure-cosmosdb-nspkg-2.0.2 azure-cosmosdb-table-1.0.5 azure-functions-1.0.0b5 azure-graphrbac-0.61.1 azure-keyvault-1.1.0 azure-mgmt-apimanagement-0.1.0 azure-mgmt-applicationinsights-0.2.0 azure-mgmt-authorization-0.60.0 azure-mgmt-batch-6.0.0 azure-mgmt-cdn-3.1.0 azure-mgmt-cognitiveservices-5.0.0 azure-mgmt-compute-6.0.0 azure-mgmt-containerinstance-1.5.0 azure-mgmt-containerregistry-2.8.0 azure-mgmt-containerservice-6.0.0 azure-mgmt-cosmosdb-0.7.0 azure-mgmt-costmanagement-0.1.0 azure-mgmt-databricks-0.1.0 azure-mgmt-datafactory-0.7.0 azure-mgmt-datalake-nspkg-3.0.1 azure-mgmt-datalake-store-0.5.0 azure-mgmt-dns-3.0.0 azure-mgmt-eventgrid-2.2.0 azure-mgmt-eventhub-3.0.0 azure-mgmt-iothub-0.8.2 azure-mgmt-keyvault-2.0.0 azure-mgmt-logic-3.0.0 azure-mgmt-managementgroups-0.2.0 azure-mgmt-monitor-0.7.0 azure-mgmt-network-4.0.0 azure-mgmt-nspkg-3.0.2 azure-mgmt-policyinsights-0.3.1 azure-mgmt-redis-6.0.0 azure-mgmt-resource-2.1.0 azure-mgmt-sql-0.12.0 azure-mgmt-storage-4.0.0 azure-mgmt-web-0.42.0 azure-nspkg-3.0.2 azure-storage-blob-2.1.0 azure-storage-common-2.1.0 azure-storage-file-2.1.0 azure-storage-queue-2.1.0 backports.functools-lru-cache-1.5 bcrypt-3.1.7 c7n-azure-0.5.5 cffi-1.12.3 colorama-0.4.1 cryptography-2.7 distlib-0.2.9.post0 humanfriendly-4.18 isodate-0.6.0 jsonpickle-1.2 knack-0.6.3 msrest-0.6.9 msrestazure-0.6.1 multidict-4.5.2 netaddr-0.7.19 oauthlib-3.1.0 paramiko-2.6.0 portalocker-1.5.1 pycparser-2.19 pygments-2.4.2 pynacl-1.3.0 pyopenssl-19.0.0 requests-oauthlib-1.2.0 tzlocal-2.0.0 vcrpy-2.0.1 vcrpy-unittest-0.1.7 wheel-0.30.0 wrapt-1.11.2 yarl-1.3.0
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.7/site-packages/c7n_azure/function_package.py", line 29, in <module>
from c7n_azure.session import Session
File "/usr/local/lib/python3.7/site-packages/c7n_azure/session.py", line 28, in <module>
from c7n_azure.utils import (ResourceIdParser, StringUtils, custodian_azure_send_override,
File "/usr/local/lib/python3.7/site-packages/c7n_azure/utils.py", line 32, in <module>
from future.moves import itertools
ModuleNotFoundError: No module named 'future'
Removing intermediate container 549f19bbb9ff
The command '/bin/sh -c apt-get --yes update && apt-get --yes install build-essential --no-install-recommends && pip3 install -r requirements.txt . && pip3 install -r tools/c7n_gcp/requirements.txt tools/c7n_gcp && pip3 install -r tools/c7n_azure/requirements.txt tools/c7n_azure && python -c "from c7n_azure.function_package import FunctionPackage; FunctionPackage('cache').build_cache( modules=['c7n', 'c7n-azure'], non_binary_packages=['pyyaml', 'pycparser', 'tabulate', 'pyrsistent'], excluded_packages=['azure-cli-core', 'distlib', 'future', 'futures'])" && apt-get --yes remove build-essential && apt-get purge --yes --auto-remove -o APT::AutoRemove::RecommendsImportant=false && rm -Rf /var/cache/apt/ && rm -Rf /var/lib/apt/lists/* && rm -Rf /src/ && rm -Rf /root/.cache/ && mkdir /output && chown custodian: /output' returned a non-zero code: 1
```

**Comment by logachev** [comment]
The root cause was in using `future` library.. It is an indirect dependency installed because of `aws_xray_sdk` from `requirements_dev.txt`. That's why it passed CI build, but failed Docker build

**Comment by kapilt** [comment]
Thanks for tracking this down.
