### ISSUE TITLE
azure - custodian report doesn't work with cosmosdb-collection

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4619]
```
(custodian) S:\custodian>custodian report -s=. cosmosdb-collections.yml
2019-08-16 14:10:29,494: custodian.azure.session:INFO Using environment variables for authentication parameters
2019-08-16 14:10:29,494: custodian.azure.session:INFO Creating session with Azure CLI Authentication
2019-08-16 14:10:29,511: custodian.azure.session:INFO Session using Subscription ID: aa98974b-5d2a-4d98-a78a-382f3715d07e
Traceback (most recent call last):
  File "S:\virtualenv\custodian\Scripts\custodian-script.py", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "s:\github\cloud-custodian\c7n\cli.py", line 373, in main
    command(config)
  File "s:\github\cloud-custodian\c7n\commands.py", line 137, in _load_policies
    return f(options, list(policies))
  File "s:\github\cloud-custodian\c7n\commands.py", line 297, in report
    policies, begin_date, options, sys.stdout, raw_output_fh=options.raw)
  File "s:\github\cloud-custodian\c7n\reports\csvout.py", line 75, in report
    include_policy=len(policy_names) > 1
  File "s:\github\cloud-custodian\c7n\reports\csvout.py", line 155, in __init__
    self._id_field = model.id
AttributeError: type object 'resource_type' has no attribute 'id'
```

**Comment by jomalsan** [comment]
I will work on this

**Comment by jomalsan** [comment]
Was able to reproduce the error

**Comment by jomalsan** [comment]
Was able to reproduce the error by running:
```
custodian run -s outputs cosmosdb.yaml
custodian report -s outputs cosmosdb.yaml
```

With cosmosdb.yaml looking like:
```yaml
policies:
  - name: cosmosdb-high-throughput
    resource: azure.cosmosdb-collection
    filters:
      - type: offer
        key: content.offerThroughput
        op: gt
        value: 100
```

**Comment by jomalsan** [comment]
Same error occurs when trying to report for Cosmos DB Databases and Key Vault Keys. They all share a common inheritance of `ChildTypeInfo` in `tools/c7n_azure/c7n_azure/query.py`.

No other classes directly inherit from `ChildTypeInfo`, only reference the field `parent_key` on it.
