### ISSUE TITLE
c7n_mailer's Slack Delivery expects JSON response from Slack webhook

### ISSUE THREAD

**Issue by slobodyanyuk** [cloud-custodian/cloud-custodian#4653]
c7n_mailer's Slack Delivery expects JSON response from Slack webhook API, while response is plaintext according to the documentation https://api.slack.com/incoming-webhooks#handling-errors.

`Traceback (most recent call last):
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 185, in process_sqs_message
    slack_delivery.slack_handler(sqs_message, slack_messages)
  File "/var/task/c7n_mailer/slack_delivery.py", line 123, in slack_handler
    self.send_slack_msg(key, payload)
  File "/var/task/c7n_mailer/slack_delivery.py", line 187, in send_slack_msg
    response_json = response.json()
  File "/var/task/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/task/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/var/task/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/var/task/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/var/task/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/var/task/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by slobodyanyuk** [comment]
https://github.com/cloud-custodian/cloud-custodian/pull/4654

**Comment by kapilt** [comment]
this is already addressed in the trunk version of mailer.

**Comment by jpooler-cht** [comment]
@kapilt  I'm also seeing this error, the c7n-mailer version is the latest one from pip, 0.5.3 (https://pypi.org/project/c7n-mailer/). Is there a scheduled release coming up?
