### ISSUE TITLE
Azure - Revisit time zone handling for mark-for-op action and marked-for-op filter

### ISSUE THREAD

**Issue by axis7818** [cloud-custodian/cloud-custodian#4671]
In some cases, the `marked-for-op` filter can fail with this stack trace:

```
Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 229, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/query.py", line 235, in resources
    return self.filter_resources(resources)
  File "/usr/local/lib/python3.7/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/filters.py", line 314, in process
    return super(TagActionFilter, self).process(resources, event)
  File "/usr/local/lib/python3.7/site-packages/c7n/filters/core.py", line 197, in process
    return list(filter(self, resources))
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/filters.py", line 343, in __call__
    action_date - timedelta(days=self.skew, hours=self.skew_hours))
TypeError: can't compare offset-naive and offset-aware datetimes
```

Here is an example policy file to replicate this (inspired by [this example](https://cloudcustodian.io/docs/azure/examples/resourcegroupsdelayedoperation-general.html), but with the `hours` field specified):

```yaml
policies:
  - name: rg-mark-empty-for-deletion
    description: |
      Find any empty resource groups and mark for deletion in 1 hour
    resource: azure.resourcegroup
    mode:
      type: container-periodic
      schedule: '0 * * * *'
    filters:
      - "tag:c7n_rg_empty": absent
      - type: empty-group
    actions:
      - type: mark-for-op
        tag: c7n_rg_empty
        op: delete
        hours: 1  # Specify the time in hours, this forces the tag to include the timezone info

  - name: rg-unmark-if-not-empty
    resource: azure.resourcegroup
    description: |
      Remove the deletion tag from any resource group which now contain resources
      so it doesn't get deleted by the following policy
    mode:
      type: container-periodic
      schedule: '0 * * * *'
    filters:
      - "tag:c7n_rg_empty": not-null
      - not:
        - type: empty-group
    actions:
      - type: untag
        tags: ['c7n_rg_empty']

  - name: rg-delete-empty
    resource: azure.resourcegroup
    description: |
      Delete any marked resource groups which are still empty if they have
      been empty for an hour.
    mode:
      type: container-periodic
      schedule: '0 * * * *'
    filters:
      - type: marked-for-op  # The timezone is omitted here
        tag: c7n_rg_empty
        op: delete
      - type: empty-group
    actions:
      - type: delete
```

Providing the `mark-for-op` time in hours will result in a tag with time zone info populated. When the `marked-for-op` filter is run, it will attempt to include a timezone that is provided in the filter's schema. In this case, none is provided and the error is thrown

**Comment by jomalsan** [comment]
Error is that one instance of TagActionFilter is created for filtering all of the resources. So when one resource has tzinfo, `self.current_date` gets set having time zone information. Then the next resource that does not have timezone information throws the error due to the timezone information mismatch
