### ISSUE TITLE
c7n-org notify action issue

### ISSUE THREAD

**Issue by Loxabe-IT** [cloud-custodian/cloud-custodian#4692]
Hi, I am getting an output from cloudwatch which I don't understand.
thing is that I am trying to push lambda in sub-accounts to check if tags are missing and send sqs from main account.

Here is the output from cloudwatch:

``[DEBUG]	2019-08-27T14:43:40.758Z	da543756-c889-4266-af8a-9e3a83f76272	metric:ResourceCount Count:1 policy:ec2-auto-tag-user restype:ec2 scope:policy"
[INFO]	2019-08-27T14:43:40.758Z	da543756-c889-4266-af8a-9e3a83f76272	Invoking actions [<c7n.actions.autotag.AutoTagUser object at 0x7faf0eabca90>, <c7n.actions.notify.Notify object at 0x7faf0eabc9b0>]
[INFO]	2019-08-27T14:43:40.758Z	da543756-c889-4266-af8a-9e3a83f76272	policy:ec2-auto-tag-user invoking action:autotaguser resources:1
[INFO]	2019-08-27T14:43:40.800Z	da543756-c889-4266-af8a-9e3a83f76272	policy:ec2-auto-tag-user invoking action:notify resources:1
[DEBUG]	2019-08-27T14:43:41.131Z	da543756-c889-4266-af8a-9e3a83f76272	metric:PolicyException Count:1 policy:ec2-auto-tag-user restype:ec2
[DEBUG]	2019-08-27T14:43:41.131Z	da543756-c889-4266-af8a-9e3a83f76272	metric:ApiCalls Count:1 policy:ec2-auto-tag-user restype:ec2
[ERROR]	2019-08-27T14:43:41.132Z	da543756-c889-4266-af8a-9e3a83f76272	Error while executing policy
Traceback (most recent call last):
File "/var/task/c7n/policy.py", line 482, in run
results = action.process(resources, event)
File "/var/task/c7n/actions/notify.py", line 188, in process
receipt = self.send_data_message(message)
File "/var/task/c7n/actions/notify.py", line 231, in send_data_message
return self.send_sqs(message)
File "/var/task/c7n/actions/notify.py", line 266, in send_sqs
queue = self.data['transport']['queue'].format(**message)
KeyError: 'queue'
[ERROR]	2019-08-27T14:43:41.132Z	da543756-c889-4266-af8a-9e3a83f76272	error during policy execution
Traceback (most recent call last):
File "/var/task/c7n/handler.py", line 168, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 925, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 482, in run
results = action.process(resources, event)
File "/var/task/c7n/actions/notify.py", line 188, in process
receipt = self.send_data_message(message)
File "/var/task/c7n/actions/notify.py", line 231, in send_data_message
return self.send_sqs(message)
File "/var/task/c7n/actions/notify.py", line 266, in send_sqs
queue = self.data['transport']['queue'].format(**message)
KeyError: 'queue'
[ERROR] KeyError: 'queue'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 925, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 482, in run
    results = action.process(resources, event)
  File "/var/task/c7n/actions/notify.py", line 188, in process
    receipt = self.send_data_message(message)
  File "/var/task/c7n/actions/notify.py", line 231, in send_data_message
    return self.send_sqs(message)
  File "/var/task/c7n/actions/notify.py", line 266, in send_sqs
    queue = self.data['transport']['queue'].format(**message)
END RequestId: da543756-c889-4266-af8a-9e3a83f76272``

I really appreciate your help.

**Comment by Loxabe-IT** [comment]
Thank you for the quick reply. The issue was at mail template, now it works as expected
