### ISSUE TITLE
ungraceful error suspected due to resource type Config does not support currently

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#4750]
The following policy 
```
policies:
  - name: post-ebs-snapshot-public
    resource: ebs-snapshot
    mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/CloudCustodian
      packages: [botocore, boto3, urllib3]
    filters:
      - type: cross-account
```
is causing the following error, which I suspect is due to AWS Config not supporting EBS-Snapshots as a resource-type, yet.  Would be nice to get a more graceful error in the meantime.
```
2019-09-08 00:51:14,884: custodian.policy:INFO Provisioning policy lambda post-ebs-snapshot-public
2019-09-08 00:51:26,813: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 494, in provision
    role=self.policy.options.assume_role)
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 322, in publish
    if e.add(func):
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 1556, in add
    return self.client.put_config_rule(ConfigRule=params)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter ConfigRule.Scope.ComplianceResourceTypes[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2019-09-08 00:51:26,815: custodian.commands:ERROR Error while executing policy post-ebs-snapshot-public, continuing
```

**Comment by kapilt** [comment]
this should be failing in validation
