### ISSUE TITLE
'AzureFunctionMode' is not defined

### ISSUE THREAD

**Issue by vtomardb** [cloud-custodian/cloud-custodian#4833]
Did a fresh installed of virtual env: 

```C02YK28HJGH5:virtualenv varun.tomar$ python3 -m venv custodian_new```

```C02YK28HJGH5:virtualenv varun.tomar$ source custodian_new/bin/activate```

```
(custodian_new) C02YK28HJGH5:virtualenv varun.tomar$ git clone https://github.com/cloud-custodian/cloud-custodian.git
Cloning into 'cloud-custodian'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 91247 (delta 14), reused 10 (delta 0), pack-reused 91203
Receiving objects: 100% (91247/91247), 123.45 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (73105/73105), done.
Checking out files: 100% (5890/5890), done.
(custodian_new) C02YK28HJGH5:virtualenv varun.tomar$ cd cloud-custodian
(custodian_new) C02YK28HJGH5:cloud-custodian varun.tomar$ pip install -e .
Obtaining file:///Users/varun.tomar/Documents/virtualenv/cloud-custodian
Collecting boto3>=1.9.94 (from c7n==0.8.44.2)
  Downloading 

You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
(custodian_new) C02YK28HJGH5:cloud-custodian varun.tomar$ c7n-mailer --config /Users/var/github/azure-cloud-custodian/_c7n-mailer/environments/mailer-dev.yml --update-lambda
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 9, in <module>
    load_entry_point('c7n-mailer==0.5.2', 'console_scripts', 'c7n-mailer')()
  File "/Library/Python/2.7/site-packages/c7n_mailer/cli.py", line 216, in main
    azure_deploy.provision(mailer_config)
  File "/Library/Python/2.7/site-packages/c7n_mailer/azure/deploy.py", line 79, in provision
    service_plan = AzureFunctionMode.extract_properties(function_properties,
NameError: global name 'AzureFunctionMode' is not defined
```

same error as reported in: ```https://github.com/cloud-custodian/cloud-custodian/issues/3158```

**Comment by kapilt** [comment]
is the c7n-mailer here from the virtualenv? ie `which c7n-mailer` returns a path to the virtualenv?

**Comment by kapilt** [comment]
i ask because your not installing c7n-mailer in the above commands

**Comment by vtomardb** [comment]
Issue with c7n-mailer installed as suggested by kapil
