### ISSUE TITLE
Azure: c7n-mailer: unable to send messages

### ISSUE THREAD

**Issue by vtomardb** [cloud-custodian/cloud-custodian#4847]
File 

```"
/virtualenv/custodian_new/lib/python3.6/site-packages/c7n_mailer/smtp_delivery.py", line 45, in send_message
    print("from:", message['From'])
TypeError: string indices must be integers
```

Using virtualenv.

This is what I noticed in `smtp_delivery.py`:

```  
def send_message(self, message, to_addrs):
 self._smtp_connection.sendmail(message['From'], to_addrs, message.as_string())
```

`message['From']` is not in the message. The output of the message is:

```
The following azure.vm resources

   {
  "id": "/subscriptions/8a64cfc7/resourceGroups/CENTRAL-RG/providers/Microsoft.Compute/virtualMachines/test",
  "name": "test",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus",
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_B1ls"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "18.04-LTS",
        "version": "latest"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "test_disk1_64fb50",
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "managedDisk": {
          "id": "/subscriptions/8a64cfc7/resourceGroups/CENTRAL-RG/providers/Microsoft.Compute/disks/test_disk1_64fb5"
        }
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "test",
      "adminUsername": "vtomar",
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "ssh": {
          "publicKeys": [
            {
              "path": "/home/vtomar/.ssh/authorized_keys",
              "keyData": "ssh-rsa A4Yb1haxviZwsd28HJGH5"
            }
          ]
        },
        "provisionVMAgent": true
      },
      "secrets": [],
      "allowExtensionOperations": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/8a64cfc7/resourceGroups/central-rg/providers/Microsoft.Network/networkInterfaces/test252"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true,
        "storageUri": "https://cent/"
      }
    },
    "provisioningState": "Succeeded",
    "vmId": "7bab15sdsee"
  },
  "resourceGroup": "CENTRAL-RG",
  "instanceView": {
    "hyperVGeneration": "V1",
    "disks": [
      {
        "name": "test_disk1",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Provisioning succeeded",
            "time": "2019-09-20T21:19:03.523044Z"
          }
        ]
      }
    ],
    "bootDiagnostics": {},
    "statuses": [
      {
        "code": "ProvisioningState/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "time": "2019-09-20T21:19:03.5387Z"
      },
      {
        "code": "PowerState/deallocated",
        "level": "Info",
        "displayStatus": "VM deallocated"
      }
    ],
    "c7n:MatchedFilters": [
      "statuses[].code"
    ]
  }
}

in account: 8a64cfc7

Matched policy:

actions:
- priority_header: '2'
  subject: Hello from C7N Mailer
  template: default
  to:
  - varun.tomar@xyz.com
  transport:
    queue: https://xxxxxxx
    type: asq
  type: notify
filters:
- key: statuses[].code
  op: not-in
  type: instance-view
  value: PowerState/running
  value_type: swap
name: stopped-vm
resource: azure.vm
```

**Comment by vtomardb** [comment]
If I install c7n-mailer using these steps it worked:

```
$ virtualenv c7n_mailer
$ source c7n_mailer/bin/activate
$ cd tools/c7n_mailer
$ pip install -r requirements.txt
$ python setup.py develop
```

**Comment by tomarv2** [comment]
If I follow the above steps, i get email and stack but getting errors:

```
2019-09-24 18:57:27,683 - custodian-mailer - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/varun.tomar/Desktop/cloud-custodian/tools/c7n_mailer/c7n_mailer/azure_mailer/azure_queue_processor.py", line 107, in _deliver_slack_message
    slack_delivery.slack_handler(queue_message, slack_messages)
  File "/Users/varun.tomar/Desktop/cloud-custodian/tools/c7n_mailer/c7n_mailer/slack_delivery.py", line 126, in slack_handler
    self.send_slack_msg(key, payload)
  File "/Users/varun.tomar/Desktop/cloud-custodian/tools/c7n_mailer/c7n_mailer/slack_delivery.py", line 203, in send_slack_msg
    response_json = response.json()
  File "//virtualenv/custodian_new/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "//virtualenv/custodian_new/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "//virtualenv/custodian_new/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "//virtualenv/custodian_new/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-09-24 18:57:28,258 - custodian-mailer - INFO - Sending message to SMTP server, smtp.gmail.com.
2019-09-24 18:57:29,034 - custodian-mailer - INFO - No messages left on the azure storage queue, exiting c7n_mailer.
```

and emails from policies are coming as blank..

**Comment by logachev** [comment]
Can you please share your jinja template?

I tried to run latest c7n & c7n_mailer with `default.html` template and it was working
![image](https://user-images.githubusercontent.com/1036695/65787044-591daf00-e158-11e9-87ed-9417beb35d28.png)

**Comment by vtomardb** [comment]
@logachev : 
 i am just using the default templates for slack and email, nothing customized as yet:

```
<!DOCTYPE html>
<html lang="en">

{# 
Sample Policy that can be used with this template:

Additional parameters can be passed in from the policy - i.e. action_desc, violation_desc

  - name: delete-unencrypted-ec2
    resource: ec2
    filters:
      - type: ebs
        key: Encrypted
        value: false
    actions:
      - terminate
      - type: notify
        template: default.html
        subject: "[custodian {{ account }}] Delete Unencrypted EC2 - {{ region }}"
        violation_desc: "The following EC2(s) are not encrypted:"
        action_desc: "The EC2(s) have been terminated"
        from: custodian@domain.com
        to:
          - owner@domain.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/12345678910/custodian-sqs-queue
#}


{# You can set any mandatory tags here, and they will be formatted/outputted in the message #}
{% set requiredTags = ['Application','Owner'] %}

{# The macros below format some resource attributes for better presentation #}
{% macro getTag(resource, tagKey) -%}
	{% if resource.get('Tags') %}
		{% for t in resource.get('Tags') %} 	
			{%  if t.get('Key') == tagKey %}
				{{ t.get('Value') }}    							
			{% endif %}
		{% endfor %}
	{% endif %}
{%- endmacro %}

{% macro extractList(resource, column) -%}
		{% for p in resource.get(column) %}
			{{ p }},
		{% endfor %}
{%- endmacro %}
	
{% macro columnHeading(columnNames, tableWidth) -%}
	<table>
	{% for columnName in columnNames %}
		<th>{{ columnName }}</th>
	{% endfor %}
{%- endmacro %}

{# The macro below creates the table:
   Formatting can be dependent on the column names that are passed in 
#}
{% macro columnData(resources, columnNames) -%}
	{% for resource in resources %}
		<tr>
		{% for columnName in columnNames %}
			{% if columnName in requiredTags %}
				<td>{{ getTag(resource,columnName) }}</td>
			{% elif columnName == 'tag.Name' %}
				<td>{{ getTag(resource,'Name') }}</td>
			{% elif columnName == 'InstanceCount' %}
				<td align="center">{{ resource['Instances'] | length }}</td>		
			{% elif columnName == 'VolumeConsumedReadWriteOps' %}
				<td>{{ resource['c7n.metrics']['AWS/EBS.VolumeConsumedReadWriteOps.Maximum'][0]['Maximum'] }}</td>
			{% elif columnName == 'PublicIp' %}
				<td>{{ resource['NetworkInterfaces'][0].get('Association')['PublicIp'] }}</td>										
			{% else %}
				<td>{{ resource[columnName] }}</td>
			{% endif %}
		{% endfor %}
		</tr>
	{% endfor %}
	</table>
{%- endmacro %}	

{# Main #}
{% macro createTable(columnNames, resources, tableWidth) %}
	{{ columnHeading(columnNames, tableWidth) }}				
	{{ columnData(resources, columnNames) }}
{%- endmacro %}

<head>
    <title>Custodian Notification - {{  account  }}</title>
</head>

<style>
	table {
		width: {{ tableWidth }};
		border-spacing: 0px;
		box-shadow: 5px 5px 5px grey;
	}
	table tr:first-child th:first-child {
		border-top-left-radius: 7px;
	}
	table tr:first-child th:last-child {
		border-top-right-radius: 7px;
	}
	table tr:last-child td:first-child {
		border-bottom-left-radius: 7px;
	}
	table tr:last-child td:last-child {
		border-bottom-right-radius: 7px;
	}
	td {
		border: 1px solid grey; 
		padding: 4px;	
	}
	th {
		background: linear-gradient(#0c2b5b,#a1bae2);
		color: white;
		border: 1px solid #a1bae2;
		text-align: center;
		padding: 5px;
	}
	tr:nth-child(even) {			
		background-color: #f2f2f2;			
	}
	tr:hover {
		background: #d7e3f7;
		color: black;
	}
</style>

<body>
    <ul>
    	<h2><font color="#505151"> {{  "%s - %s" | format(account,region)  }} </h2>
		<h3> {{  action['violation_desc']  }} </h3>
		
		{# Below, notifications for any resource-type can be formatted with specific columns #}	  				
		{% if policy['resource'] == "ami" %}
			{% set columnNames = ['Name','ImageId','CreationDate'] %}
			{{ createTable(columnNames, resources, '60') }}				
		  				
		{% elif policy['resource'] == "app-elb" %}
		  	{% set columnNames = ['LoadBalancerName','CreatedTime','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }}					  				
									
		{% elif policy['resource'] == "asg" %}
			{% if resources[0]['Invalid'] is defined %}
		  		{% set columnNames = ['AutoScalingGroupName','InstanceCount','Invalid'] %}
		  	{% else %}
		  		{% set columnNames = ['AutoScalingGroupName','InstanceCount','Application','Owner'] %}
		  	{% endif %}
			{{ createTable(columnNames, resources, '60') }}			  				
			    	
		{% elif policy['resource'] == "cache-cluster" %}
		  	{% set columnNames = ['CacheClusterId','CacheClusterCreateTime','CacheClusterStatus','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }}			  				  										  				

		{% elif policy['resource'] == "cache-snapshot" %}
			{% set columnNames = ['SnapshotName','CacheClusterId','SnapshotSource','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }}			  	

		{% elif policy['resource'] == "cfn" %}
			{% set columnNames = ['StackName'] %}
			{{ createTable(columnNames, resources, '50') }}			     	
			
		{% elif policy['resource'] == "cloudsearch" %}
			{% set columnNames = ['DomainName'] %}
			{{ createTable(columnNames, resources, '50') }}		    								    	
			
		{% elif policy['resource'] == "ebs" %}
			{% set columnNames = ['VolumeId','CreateTime','State','Application','Owner'] %}
			{{ createTable(columnNames, resources, '50') }}		 
			
		{% elif policy['resource'] == "ebs-snapshot" %}
			{% set columnNames = ['SnapshotId','StartTime','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }}			     		
			
		{% elif policy['resource'] == "ec2" %}
			{% if resources[0]['MatchedFilters'] == ['PublicIpAddress'] %}
				{% set columnNames = ['tag.Name','PublicIp','InstanceId'] %}
			{% else %}
				{% set columnNames = ['tag.Name','PrivateIpAddress','InstanceId','ImageId','Application','Owner'] %}
			{% endif %}
			{{ createTable(columnNames, resources, '80') }}					   
			
		{% elif policy['resource'] == "efs" %}
			{% set columnNames = ['CreationToken','CreationTime','FileSystemId','OwnerId'] %}
			{{ createTable(columnNames, resources, '50') }}		
			  				
		{% elif policy['resource'] == "elasticsearch" %}
			{% set columnNames = ['DomainName','Endpoint'] %}
			{{ createTable(columnNames, resources, '50') }}		
			  				
		{% elif policy['resource'] == "elb" %}
	    	{% set columnNames = ['LoadBalancerName','InstanceCount','AvailabilityZones','Application','Owner'] %}	    		
			{{ createTable(columnNames, resources, '80') }}			  

		{% elif policy['resource'] == "emr" %}
			{% set columnNames = ['Id','EmrState'] %}
			{{ createTable(columnNames, resources, '50') }}					

		{% elif policy['resource'] == "kinesis" %}
			{% set columnNames = ['StreamName'] %}
			{{ createTable(columnNames, resources, '50') }}						

		{% elif policy['resource'] == "launch-config" %}
		    {% set columnNames = ['LaunchConfigurationName'] %}
			{{ createTable(columnNames, resources, '30') }}		

		{% elif policy['resource'] == "log-group" %}
			{% set columnNames = ['logGroupName'] %}
			{{ createTable(columnNames, resources, '30') }}			  				  				  	
			
		{% elif policy['resource'] == "rds" %}
			{% if resources[0]['PubliclyAccessible'] == true or resources[0]['StorageEncrypted'] == false %}
				{% set columnNames = ['DBInstanceIdentifier','PubliclyAccessible','StorageEncrypted','DBSubnetGroup'] %}
			{% else %}
				{% set columnNames = ['DBInstanceIdentifier','Application','Owner'] %}
			{% endif %}				
			{{ createTable(columnNames, resources, '80') }}	
						
		{% elif policy['resource'] == "rds-snapshot" %}
			{% set columnNames = ['DBSnapshotIdentifier','SnapshotCreateTime','DBInstanceIdentifier','SnapshotType','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }}				

		{% elif policy['resource'] == "redshift" %}
			{% if resources[0]['PubliclyAccessible'] == true or resources[0]['Encrypted'] == false %}
				{% set columnNames = ['ClusterIdentifier','NodeCount','PubliclyAccessible','Encrypted'] %}
			{% else %}
				{% set columnNames = ['ClusterIdentifier','NodeCount','Application','Owner'] %}
			{% endif %}
			{{ createTable(columnNames, resources, '80') }}
				  				
		{% elif policy['resource'] == "redshift-snapshot" %}
			{% set columnNames = ['SnapshotIdentifier','DBName','Application','Owner'] %}
			{{ createTable(columnNames, resources, '80') }} 					  				
					
		{% elif policy['resource'] == "s3" %}
			{% if resources[0]['GlobalPermissions'] is defined %}
			 	{% set columnNames = ['Name','GlobalPermissions'] %}
			{% else %}
				{% set columnNames = ['Name','Application','Owner'] %}
			{% endif %}
			{{ createTable(columnNames, resources, '80') }} 										  								

		{% elif policy['resource'] == "security-group" %}
			{% set columnNames = ['GroupName','tag.Name','GroupId','VpcId'] %}
			{{ createTable(columnNames, resources, '80') }}
			
		{% elif policy['resource'] == "simpledb" %}
			{% set columnNames = ['DomainName'] %}
			{{ createTable(columnNames, resources, '60') }}	
			
		{# If no special formatting is defined for a resource type, all attributes will be formatted in the email #}
		{% else %}  							 
			<table style="width:100%; border:1px dashed black; border-collapse:collapse;"> 	
    			<tr>
    				{% for column in resources[0] %}
	    				<th>{{ column }}</th>
    				{% endfor %}
  				</tr>  			
			{% set columnlen = resources[0]|length|int %}
			{% for resource in resources %}
				<tr>
					{% for column in resource %}
						<td>{{ resource[column] }}</td>
					{% endfor %}	
				</tr>
			{% endfor %}  					
			</table>	  				  							  										  			 							  				
		{% endif %}
		
		<h3>{{  action['action_desc']  }}</h3>		

		<h4>
			For any other questions,  
				<a href="mailto:custodian@domain.com"> email us</a>
		</h4>
    </ul>
</body>
</html>
```

**Comment by vtomardb** [comment]
this is fixed by the changes made by @logachev
