### ISSUE TITLE
ci - test failure azure

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4879]
could be intermittent, but happened on trunk, so going to watch it for a bit

```
=================================== FAILURES ===================================
______________ SessionTest.test_get_function_target_subscription _______________
[gw1] linux2 -- Python 2.7.16 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/c7n_azure/tests/test_session.py", line 280, in test_get_function_target_subscription
    self.assertEqual(s.get_function_target_subscription_ids(), [])
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/session.py", line 212, in get_function_target_subscription_ids
    os.environ[constants.ENV_FUNCTION_MANAGEMENT_GROUP_NAME], self.get_credentials())
  File "/home/vsts/work/1/s/tools/c7n_azure/c7n_azure/utils.py", line 490, in get_subscriptions_list
    return [e.name for e in entities if e.type == '/subscriptions']
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/azure/mgmt/managementgroups/operations/entities_operations.py", line 149, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 200, in signed_session
    self.set_token() # Adal does the caching.
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 362, in set_token
    super(ServicePrincipalCredentials, self).set_token()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 187, in set_token
    if not self._context:
AttributeError: 'ServicePrincipalCredentials' object has no attribute '_context'
```

https://github.com/cloud-custodian/cloud-custodian/runs/241769836

**Comment by kapilt** [comment]
doesn't seem to have reoccurred in the three prs subsequently merged, tossing up as a heisenburg
