### ISSUE TITLE
ci - azure failures

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#4892]
ci appears to be failing for pull requests due to unrelated instability (compatibility breakage) in the azure sdks

```
==================================== ERRORS ====================================
____ ERROR collecting tools/c7n_azure/tests_azure/test_function_package.py _____
ImportError while importing test module '/home/vsts/work/1/s/tools/c7n_azure/tests_azure/test_function_package.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tools/c7n_azure/tests_azure/test_function_package.py:26: in <module>
    from azure.mgmt.web.models.user import User
E   ImportError: No module named user
=================================== FAILURES ===================================
____________ AppServicePlanTest.test_resize_plan_from_resource_tag _____________
[gw1] linux2 -- Python 2.7.16 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1322, in patched
    arg = patching.__enter__()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1378, in __enter__
    self.target = self.getter()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1548, in <lambda>
    getter = lambda: _importer(target)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1235, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1224, in _dot_lookup
    __import__(import_path)
ImportError: No module named operations
----------------------------- Captured stderr call -----------------------------
Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
------------------------------ Captured log call -------------------------------
INFO     custodian.azure.session:session.py:110 Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
__________________ AppServicePlanTest.test_resize_plan_linux ___________________
[gw1] linux2 -- Python 2.7.16 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1322, in patched
    arg = patching.__enter__()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1378, in __enter__
    self.target = self.getter()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1548, in <lambda>
    getter = lambda: _importer(target)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1235, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1224, in _dot_lookup
    __import__(import_path)
ImportError: No module named operations
----------------------------- Captured stderr call -----------------------------
Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
------------------------------ Captured log call -------------------------------
INFO     custodian.azure.session:session.py:110 Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
___________________ AppServicePlanTest.test_resize_plan_win ____________________
[gw1] linux2 -- Python 2.7.16 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1322, in patched
    arg = patching.__enter__()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1378, in __enter__
    self.target = self.getter()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1548, in <lambda>
    getter = lambda: _importer(target)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1235, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1224, in _dot_lookup
    __import__(import_path)
ImportError: No module named operations
----------------------------- Captured stderr call -----------------------------
Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
------------------------------ Captured log call -------------------------------
INFO     custodian.azure.session:session.py:110 Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
______________ AppServicePlanTest.test_resize_plan_win_only_count ______________
[gw1] linux2 -- Python 2.7.16 /home/vsts/work/1/s/.tox/py27/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1322, in patched
    arg = patching.__enter__()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1378, in __enter__
    self.target = self.getter()
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1548, in <lambda>
    getter = lambda: _importer(target)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1235, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1224, in _dot_lookup
    __import__(import_path)
ImportError: No module named operations
----------------------------- Captured stderr call -----------------------------
Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
------------------------------ Captured log call -------------------------------
INFO     custodian.azure.session:session.py:110 Authenticated [Access Token | ea42f556-5106-4743-99b0-c129bfa71a47]
```

**Comment by kapilt** [comment]
fixed by #4889
