### ISSUE TITLE
resource deletion continued despite tag fetch failure for ELBs upon network disruption

### ISSUE THREAD

**Issue by egeturgay** [cloud-custodian/cloud-custodian#4949]
We run cloudcustodian behind a squid proxy for outgoing connections. As a result of a disruption on the proxy caused connectivity to be disrupted during a cloud custodian run.

This in turn caused tags fetching to be failed, yet It continued with the deletion rule which caused the ELBs to be deleted.

I suspect even though, It sounds like an edge case, an unlucky connectivity disruption could end up deleting a lot of resources.

The rule in question deletes untagged ELBs
```
2019-10-09 15:57:33,098 - custodian.policy - INFO - policy:a05-delete-untagged-elb resource:elb region:eu-west-1 count:217 time:1.44
--
2019-10-09 15:58:40,968 - custodian.policy - INFO - policy:a05-delete-untagged-elb action:delete resources:217 execution_time:67.83
```

Here's the stacktrace for the issue:
```
/usr/local/bin/custodian run -s /output -r eu-west-1 /config/janitor.yml
argc=8 a0="/usr/local/bin/python" a1="/usr/local/bin/custodian" a2="run" a3="-s" a4="/output" a5="-r" a6="eu-west-1" a7="/config/janitor.yml"
15:57:12,451: custodian.output:ERROR Error while executing policy
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
   self._prepare_proxy(conn)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
   conn.connect()
 File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
   self._tunnel()
 File "/usr/local/lib/python3.7/site-packages/botocore/awsrequest.py", line 94, in _tunnel
   return super(AWSConnection, self)._tunnel()
 File "/usr/local/lib/python3.7/http/client.py", line 916, in _tunnel
   (version, code, message) = response._read_status()
 File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
   raise RemoteDisconnected("Remote end closed connection without"
Remote end closed connection without response
handling of the above exception, another exception occurred:
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 262, in send
   chunked=self._chunked(request.headers),
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
   method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
   raise six.reraise(type(error), error, _stacktrace)
 File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
   raise value.with_traceback(tb)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
   self._prepare_proxy(conn)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
   conn.connect()
 File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
   self._tunnel()
 File "/usr/local/lib/python3.7/site-packages/botocore/awsrequest.py", line 94, in _tunnel
   return super(AWSConnection, self)._tunnel()
 File "/usr/local/lib/python3.7/http/client.py", line 916, in _tunnel
   (version, code, message) = response._read_status()
 File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
   raise RemoteDisconnected("Remote end closed connection without"
('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))
handling of the above exception, another exception occurred:
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 229, in run
   resources = self.policy.resource_manager.resources()
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 453, in resources
   resources = self.source.resources(query)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 230, in resources
   return self.query.filter(self.manager, **query)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 90, in filter
   getattr(resource_manager, 'retry', None)) or []
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 69, in _invoke_client_enum
   data = results.build_full_result()
 File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 449, in build_full_result
   for response in self:
 File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
   response = self._make_request(current_kwargs)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 679, in _make_request
   return self.retry(self._method, **current_kwargs)
 File "/usr/local/lib/python3.7/site-packages/c7n/utils.py", line 383, in _retry
   return func(*args, **kw)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
   operation_model, request_dict, request_context)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
   return self._endpoint.make_request(operation_model, request_dict)
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
   return self._send_request(request_dict, operation_model)
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
   success_response, exception):
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
   caught_exception=caught_exception, request_dict=request_dict)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
   return self._emitter.emit(aliased_event_name, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
   return self._emit(event_name, kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
   response = handler(**kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
   if self._checker(attempts, response, caught_exception):
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
   caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
   return self._checker(attempt_number, response, caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
   caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
   attempt_number, caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
   raise caught_exception
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
   http_response = self._send(request)
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 244, in _send
   return self.http_session.send(request)
 File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 284, in send
   raise ProxyConnectionError(proxy_url=proxy_url, error=e)
Failed to connect to proxy URL: "http://redacted:3128"
15:57:12,456: custodian.commands:ERROR Error while executing policy a01-delete-untagged-asg, continuing
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
   self._prepare_proxy(conn)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
   conn.connect()
 File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
   self._tunnel()
 File "/usr/local/lib/python3.7/site-packages/botocore/awsrequest.py", line 94, in _tunnel
   return super(AWSConnection, self)._tunnel()
 File "/usr/local/lib/python3.7/http/client.py", line 916, in _tunnel
   (version, code, message) = response._read_status()
 File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
   raise RemoteDisconnected("Remote end closed connection without"
Remote end closed connection without response
handling of the above exception, another exception occurred:
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 262, in send
   chunked=self._chunked(request.headers),
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
   method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
   raise six.reraise(type(error), error, _stacktrace)
 File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
   raise value.with_traceback(tb)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
   self._prepare_proxy(conn)
 File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
   conn.connect()
 File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
   self._tunnel()
 File "/usr/local/lib/python3.7/site-packages/botocore/awsrequest.py", line 94, in _tunnel
   return super(AWSConnection, self)._tunnel()
 File "/usr/local/lib/python3.7/http/client.py", line 916, in _tunnel
   (version, code, message) = response._read_status()
 File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
   raise RemoteDisconnected("Remote end closed connection without"
('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))
handling of the above exception, another exception occurred:
(most recent call last):
 File "/usr/local/lib/python3.7/site-packages/c7n/commands.py", line 269, in run
   policy()
 File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 945, in __call__
   resources = mode.run()
 File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 229, in run
   resources = self.policy.resource_manager.resources()
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 453, in resources
   resources = self.source.resources(query)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 230, in resources
   return self.query.filter(self.manager, **query)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 90, in filter
   getattr(resource_manager, 'retry', None)) or []
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 69, in _invoke_client_enum
   data = results.build_full_result()
 File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 449, in build_full_result
   for response in self:
 File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
   response = self._make_request(current_kwargs)
 File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 679, in _make_request
   return self.retry(self._method, **current_kwargs)
 File "/usr/local/lib/python3.7/site-packages/c7n/utils.py", line 383, in _retry
   return func(*args, **kw)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
   operation_model, request_dict, request_context)
 File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
   return self._endpoint.make_request(operation_model, request_dict)

 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
   return self._send_request(request_dict, operation_model)
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
   success_response, exception):
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
   caught_exception=caught_exception, request_dict=request_dict)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
   return self._emitter.emit(aliased_event_name, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
   return self._emit(event_name, kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
   response = handler(**kwargs)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
   if self._checker(attempts, response, caught_exception):
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
   caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
   return self._checker(attempt_number, response, caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
   caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
   attempt_number, caught_exception)
 File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
   raise caught_exception
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
   http_response = self._send(request)
 File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 244, in _send
   return self.http_session.send(request)
 File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 284, in send
   raise ProxyConnectionError(proxy_url=proxy_url, error=e)
Failed to connect to proxy URL: "http://redacted:3128"
15:57:21,078: custodian.cache:WARNING Could not save cache /.cache/cloud-custodian.cache err: [Errno 2] No such file or directory: '/.cache/cloud-custodian.cache'
15:57:21,078: custodian.cache:INFO Generating Cache directory: /.cache.
15:57:21,135: custodian.policy:INFO policy:a02-tag-ebs-volumes resource:ebs region:eu-west-1 count:36 time:8.67
15:57:26,186: custodian.policy:INFO policy:a02-tag-ebs-volumes action:copyinstancetags resources:36 execution_time:5.05
15:57:28,435: custodian.policy:INFO policy:a03-delete-untagged-ebs-volumes resource:ebs region:eu-west-1 count:0 time:2.24
argc=7 a0="python" a1="/bin/report.py" a2="--slack" a3="https://redacted"
type=1309 audit(1570636649.137:111059): argc=7 a0="python" a1="/bin/report.py" a2="--slack" a3="redacted" a4="--name" a5="redacted_janitor" a6="/output"
15:57:31,648: custodian.policy:INFO policy:a04-terminate-untagged-ec2-instances resource:ec2 region:eu-west-1 count:0 time:3.21
15:57:33,098: custodian.policy:INFO policy:a05-delete-untagged-elb resource:elb region:eu-west-1 count:217 time:1.44
15:58:40,968: custodian.policy:INFO policy:a05-delete-untagged-elb action:delete resources:217 execution_time:67.83
15:58:42,651: custodian.policy:INFO policy:a06-delete-untagged-alb resource:app-elb region:eu-west-1 count:0 time:1.68
15:58:43,700: custodian.output:ERROR Error while executing policy```

**Comment by kapilt** [comment]
so each policy executes independently, I'm seeing several policies fail to due to lack of connectivity. the elb policy completes without error. generally its helpful to run with verbose for traceback conditions (identifies cache usage). Was squid here actually down or returning bad results/empty responses, in the case of the latter then there's really no telling whats going to happen because your feeding bad data to custodian. ie I'm not seeing any cache pollution or any catch outside of the top level policy handler. generally you'd want to ensure you have reliable connectivity to the api endpoints, if you want to run sans an igw, I'd suggest vpc endpoints.

**Comment by egeturgay** [comment]
Squid was actually down temporarily (as a result of a system reboot), It's not a caching proxy either so It wouldn't return empty results. The logs suggest that (at the bottom) that's it's generating the cache directory as It was absent so my assumption is that CC cache was not relevant. Would that be a correct assumption?
I think It was able to execute the deletion policy as the connection was back up but It had somehow empty tags.

I will try to reproduce the issue in a test environment but It's tricky.

Also, the above log is a subsequent run (logs below) of another failed attempt 4 minutes prior to the problematic deletion. So, It made me question whether It had any data (in regards to tags being empty) from the previous failed run.

We had a similar issue 6+ months ago where AWS returned empty tags for S3 which cloudcustodian removed data from many s3 buckets as a result, so even though, I agree that one should be running it with a reliable connectivity, It may be better to add a guardrail to prevent such deletions where Tags query is returned completely empty. Not sure whether that is achievable within its logic though?

```Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]: 2019-10-09 15:53:46,092: custodian.commands:ERROR Error while executing policy a05-delete-untagged-elb, continuing
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]: Traceback (most recent call last):
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:     self._prepare_proxy(conn)
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:     conn.connect()
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:     self._tunnel()
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:   File "/usr/local/lib/python3.7/site-packages/botocore/awsrequest.py", line 94, in _tunnel
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:     return super(AWSConnection, self)._tunnel()
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:   File "/usr/local/lib/python3.7/http/client.py", line 916, in _tunnel
Oct 09 15:53:46 ip-10-247-51-62 janitor[14493]:     (version, code, message) = response._read_status()```

**Comment by kapilt** [comment]
we have builtin safety guard rails in the form of max-resources which can be specified as either a resource count or percentage of the population, which if the filtered resource set exceeds will stop policy execution. https://cloudcustodian.io/docs/quickstart/advanced.html#limiting-how-many-resources-custodian-affects

**Comment by kapilt** [comment]
also fwiw, that continuing message is not about continuing the execution of the current policy, but about going on to the next policy.

**Comment by egeturgay** [comment]
thanks a lot for pointing the limits out. 
I have tried to re-produce it with no luck as It's probably a very rare condition. 

I will try to utilise the limits as well as mark-ops to see if I can reduce the impact If It ever happens again. thanks!
