### ISSUE TITLE
Azure:  getting error when using ACI method of deployment

### ISSUE THREAD

**Issue by vtomardb** [cloud-custodian/cloud-custodian#5013]
If I run the policy directly it works. for eg. if I use ACI and then inside the container I use:

```c7n -run -s /tmp/out -c <policy.yml>```  it works.

But if I follow the doc: https://cloudcustodian.io/docs/azure/configuration/acitutorial.html#azure-configuration-acitutorial, setting things as env. variables and running:

```
 ["/usr/local/bin/python3", "-m", "c7n_azure.container_host.host"]
```

I am getting below error:
```
Running Azure Cloud Custodian Self-Host
Output directory not specified.  Using directory: /tmp/tmpivj7dqk0
Authenticated [Principal | XXXXXXXXXXXXXXXXXXX]
Authenticated [Principal | XXXXXXXXXXXXXXXXXXX]
Authenticated [Principal | XXXXXXXXXXXXXXXXXXX]
Updating event grid subscriptions
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "Host.update_policies" to job store "default"
Added job "Host.poll_queue" to job store "default"
Scheduler started
Running job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 00:16:05 UTC)" (scheduled at 2019-10-31 00:16:05.375263+00:00)
Authenticated [Principal | XXXXXXXXXXXXXXXXXXX]
Client-Request-ID=a1363df4-fb73-11e9-aacd-0a580af46b14 Retry policy did not allow for a retry: Server-Timestamp=Thu, 31 Oct 2019 00:16:04 GMT, Server-Request-ID=ad035a8c-801e-0092-6f80-8fb1c9000000, HTTP status code=403, Exception=This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.RequestId:ad035a8c-801e-0092-6f80-8fb1c9000000Time:2019-10-31T00:16:05.6052887Z</Message></Error>.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 00:17:05 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 140, in update_policies
    raise e
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 135, in update_policies
    blobs = [b for b in client.list_blobs(container) if Host.has_yaml_ext(b.name)]
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1311, in list_blobs
    resp = self._list_blobs(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1437, in _list_blobs
    return self._perform_request(request, _converter, operation_context=_context)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:ad035a8c-801e-0092-6f80-8fb1c9000000
Time:2019-10-31T00:16:05.6052887Z</Message></Error>
```

My policy file:
```
vars:
  notify: &notify
    type: notify
    subject: "[Azure Policy] [Subscription: {{account}}] Public Storage accounts!"
    violation_desc: "Public Storage accounts"
    slack_template: slack_default
    template: default.html
    to:
      - vtom2019@gmail.com
    transport:
      type: asq
      queue: "https://xxxxxxxx"

policies:
  - name: storage-account-public-access
    description: |
        Find all storage accounts with public access
    resource: azure.storage
    mode:
      type: azure-event-grid
      # events: ['VmWrite', 'StorageWrite']
      events: [{
          resourceProvider: 'Microsoft.Storage/storageAccounts',
          event: 'write'
        }]
    filters:
    - type: value
      key: properties.networkAcls.ipRules
      value_type: size
      op: equal
      value: 0
    actions:
    - *notify

  - name: daily-storage-acccount-public-access
    description: |
        Find all storage accounts with public access
    resource: azure.storage
    filters:
    - type: value
      key: properties.networkAcls.ipRules
      value_type: size
      op: equal
      value: 0
    actions:
    - *notify
  
  - name: storage-container-public
    description: |
      Find all containers with public access enabled
    resource: azure.storage-container
    mode:
        type: azure-periodic
        schedule: '* * * * * *'
    filters:
      - type: value
        key: properties.publicAccess
        op: not-equal
        value: None   # Possible values: Blob, Container, None
    actions:
    - *notify
```

Gave owner permission to MSI:

```
 az role assignment create --assignee 99a7ffe0-abf9-4172-bda6-xxxxxx --role "Owner" --scope "/subscriptions/xxxxxxxxxx/resourceGroups/cloud-custodian/providers/Microsoft.Storage/storageAccounts/c7nstorage"
  569  create --assignee 99a7ffe0-abf9-4172-bda6-xxxxxx --role "Owner" --scope /subscriptions/xxxxxxxxxx
```

**Comment by aluong** [comment]
You also need to give the service principal two more roles `Storage Blob Data Contributor` and `Storage Queue Message Processor`. These are the needed data plane RBAC permissions for the service principal to fetch events from the Azure Queue.

More details can be found here
- https://cloudcustodian.io/docs/azure/configuration/containerhosting.html#configuration

If you happen to have Databricks in your subscription, you have to grant these permissions at the resource level.
- https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal#determine-resource-scope

**Comment by vtomardb** [comment]
<img width="967" alt="Screen Shot 2019-10-30 at 10 45 36 PM" src="https://user-images.githubusercontent.com/51141202/67922155-2441b500-fb67-11e9-9ec9-43c11f44c157.png">

i gave all the possible permissions, right now i am using my own subscription

**Comment by aluong** [comment]
In your policies, your modes should be `container-periodic` and `container-event`. Can you update those?

**Comment by vtomardb** [comment]
@aluong it worked: `container-periodic`..

**Comment by kapilt** [comment]
we should add validation that container hosting is only attempting to execute policies with supported mode and error out appropriately if not.

**Comment by vtomardb** [comment]
@aluong I think I said it bit early.. I noticed the error still exists:

```
Running Azure Cloud Custodian Self-Host
Output directory not specified.  Using directory: /tmp/tmpin6oq4__
Authenticated [Principal | XXXXXXXX]
Authenticated [Principal | XXXXXXXX]
Authenticated [Principal | XXXXXXXX]
Updating event grid subscriptions
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Added job "Host.update_policies" to job store "default"
Added job "Host.poll_queue" to job store "default"
Scheduler started
Running job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 17:22:45 UTC)" (scheduled at 2019-10-31 17:22:45.735349+00:00)
Authenticated [Principal | XXXXXXXX]
Client-Request-ID=0dd9667c-fc03-11e9-b989-0a580af44b05 Retry policy did not allow for a retry: Server-Timestamp=Thu, 31 Oct 2019 17:22:45 GMT, Server-Request-ID=c413b4cc-d01e-0106-2c0f-909752000000, HTTP status code=403, Exception=This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.RequestId:c413b4cc-d01e-0106-2c0f-909752000000Time:2019-10-31T17:22:45.9060112Z</Message></Error>.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 17:23:45 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 140, in update_policies
    raise e
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 135, in update_policies
    blobs = [b for b in client.list_blobs(container) if Host.has_yaml_ext(b.name)]
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1311, in list_blobs
    resp = self._list_blobs(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1437, in _list_blobs
    return self._perform_request(request, _converter, operation_context=_context)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:c413b4cc-d01e-0106-2c0f-909752000000
Time:2019-10-31T17:22:45.9060112Z</Message></Error>
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:00 UTC)" (scheduled at 2019-10-31 17:23:00.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:00 UTC)" executed successfully
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:15 UTC)" (scheduled at 2019-10-31 17:23:15.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:15 UTC)" executed successfully
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:30 UTC)" (scheduled at 2019-10-31 17:23:30.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:30 UTC)" executed successfully
Running job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 17:23:45 UTC)" (scheduled at 2019-10-31 17:23:45.735349+00:00)
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:45 UTC)" (scheduled at 2019-10-31 17:23:45.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:23:45 UTC)" executed successfully
Client-Request-ID=318a94f6-fc03-11e9-a0dd-0a580af44b05 Retry policy did not allow for a retry: Server-Timestamp=Thu, 31 Oct 2019 17:23:45 GMT, Server-Request-ID=3f755040-b01e-0134-230f-90cf82000000, HTTP status code=403, Exception=This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.RequestId:3f755040-b01e-0134-230f-90cf82000000Time:2019-10-31T17:23:45.7855947Z</Message></Error>.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2019-10-31 17:24:45 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 140, in update_policies
    raise e
  File "/usr/local/lib/python3.7/site-packages/c7n_azure/container_host/host.py", line 135, in update_policies
    blobs = [b for b in client.list_blobs(container) if Host.has_yaml_ext(b.name)]
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1311, in list_blobs
    resp = self._list_blobs(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/baseblobservice.py", line 1437, in _list_blobs
    return self._perform_request(request, _converter, operation_context=_context)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:3f755040-b01e-0134-230f-90cf82000000
Time:2019-10-31T17:23:45.7855947Z</Message></Error>
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:24:00 UTC)" (scheduled at 2019-10-31 17:24:00.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:24:00 UTC)" executed successfully
Running job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:24:15 UTC)" (scheduled at 2019-10-31 17:24:15.736558+00:00)
Job "Host.poll_queue (trigger: interval[0:00:15], next run at: 2019-10-31 17:24:15 UTC)" executed successfully

```

i tested with both these policies:
```
policies:
  - name: storage-account-public-access
    description: |
        Find all storage accounts with public access
    resource: azure.storage
    mode:
      type: container-event
      # events: ['VmWrite', 'StorageWrite']
      events: [{
          resourceProvider: 'Microsoft.Storage/storageAccounts',
          event: 'write'
        }]
    filters:
    - type: value
      key: properties.networkAcls.ipRules
      value_type: size
      op: equal
      value: 0
    actions:
    # - type: set-firewall-rules
    #   default-action: Deny
    #   ip-rules: []
    - *notify
  
  - name: storage-container-public
    description: |
      Find all containers with public access enabled
    resource: azure.storage-container
    mode:
        type: container-periodic
        schedule: '* * * * * *'
    filters:
      - type: value
        key: properties.publicAccess
        op: not-equal
        value: None   # Possible values: Blob, Container, None
    actions:
    - *notify
```

**Comment by wsf11** [comment]
It looks like `c7n-aci` only has permissions for the Storage Account hosting policies to execute. The policy you have written checks all storage accounts for public access. Try giving the SP the `Reader` role on the entire target subscription, not just a specific resource.

**Comment by vtomardb** [comment]
@wesyao it was issue with the template, doc was showing ARM template, i was using terraform and I may be missing something in my template.
