### ISSUE TITLE
c7n-guardian throwing error while enabling GuardDuty across accounts in organization

### ISSUE THREAD

**Issue by ranenr** [cloud-custodian/cloud-custodian#5038]
Hello, 

I am getting below error while enabling guardduty across all regions in all AWS organization accounts using c7n-guardian

2019-11-07 10:07:27,799: c7n-guardian:INFO Processing Region:ap-east-1
Traceback (most recent call last):
  File "/usr/local/bin/c7n-guardian", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/c7n_guardian/cli.py", line 202, in enable
    enable_region(master_info, accounts_config, executor, message, r)
  File "/usr/local/lib/python3.6/dist-packages/c7n_guardian/cli.py", line 212, in enable_region
    detector_id = get_or_create_detector_id(master_client)
  File "/usr/local/lib/python3.6/dist-packages/c7n_guardian/cli.py", line 339, in get_or_create_detector_id
    detectors = client.list_detectors().get('DetectorIds')
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListDetectors operation: The security token included in the request is invalid

It seems issue is being caused because of two new AWS regions "ap-east-1" and "me-south-1" which are not enabled by default and causing boto3 to fail while "ListDetectors" operations

**Comment by kapilt** [comment]
at the moment the workaround would be to supply the regions manually on the cli ie.` -r us-east-1 -r us-east-2` etc

**Comment by kapilt** [comment]
for c7n-org we ended up automatically checking via ec2 api which regions are enabled, but we ended up doing that with the master/executing account's role instead of per target account credentials, which leads to a possibility of differential. ideally we'd just reuse the c7n-org logic, and document the caveat that the executing account needs to have a superset of regions enabled vs sub accounts region enablement if they are differential.

**Comment by ranenr** [comment]
Thanks for you response..

I have excluded those two regions from cli.py as workaround if want to deploy on all regions.

def enable(config, master, tags, accounts, debug, message, region):
    """enable guard duty on a set of accounts"""
    accounts_config, master_info, executor = guardian_init(
        config, debug, master, accounts, tags)
    regions = expand_regions(region)
    for r in regions:
        if r=='ap-east-1' or r=='me-south-1':
            continue
        log.info("Processing Region:%s", r)
        enable_region(master_info, accounts_config, executor, message, r)
