### ISSUE TITLE
ci - windows builders are broken

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5046]
```
  Running setup.py develop for c7n-azure
    ERROR: Command errored out with exit status 1:
     command: 'D:\a\1\s\.tox\py37-windows\Scripts\python.EXE' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\a\\1\\s\\tools\\c7n_azure\\setup.py'"'"'; __file__='"'"'D:\\a\\1\\s\\tools\\c7n_azure\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\a\1\s\tools\c7n_azure\
    Complete output (16 lines):
    Fatal Python error: initsite: Failed to import the site module
    Traceback (most recent call last):
      File "D:\a\1\s\.tox\py37-windows\lib\site.py", line 769, in <module>
        main()
      File "D:\a\1\s\.tox\py37-windows\lib\site.py", line 746, in main
        paths_in_sys = addsitepackages(paths_in_sys)
      File "D:\a\1\s\.tox\py37-windows\lib\site.py", line 279, in addsitepackages
        addsitedir(sitedir, known_paths)
      File "D:\a\1\s\.tox\py37-windows\lib\site.py", line 202, in addsitedir
        addpackage(sitedir, name, known_paths)
      File "D:\a\1\s\.tox\py37-windows\lib\site.py", line 170, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
      File "D:\a\1\s\.tox\py37-windows\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
        for maybe in site.getsitepackages():
    AttributeError: module 'site' has no attribute 'getsitepackages'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\a\1\s\.tox\py37-windows\Scripts\python.EXE' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\a\\1\\s\\tools\\c7n_azure\\setup.py'"'"'; __file__='"'"'D:\\a\\1\\s\\tools\\c7n_azure\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

its a little bit unclear if this a regression in azure ci pipelines for windows, or specific to c7n_azure. there hasn't be a new release of tox in a while and they generally work to ensure compatibility.

I'm going to disable the windows ci builders for now to unblock ci

ping to @logachev  and @aluong  for awareness.

**Comment by kapilt** [comment]
I don't see any relevant changes on the azure pipeline window images generation, but given it takes a month or two for changes to appear reliably (per the last sqlite dep missing rollout), its a little unclear still https://github.com/microsoft/azure-pipelines-image-generation/tree/master/images/win/scripts

**Comment by logachev** [comment]
`pywin32` breaks virtual environment: https://github.com/mhammond/pywin32/issues/1439

**Comment by kapilt** [comment]
Thanks for tracking down. So we should be able to resolve with a temporary pin till this is resolved upstream.
