### ISSUE TITLE
"source: config" failing "KeyError: u'isMfaDeleteEnabled"

### ISSUE THREAD

**Issue by olsib** [cloud-custodian/cloud-custodian#5068]
There was recommendation to use "source: config" in policies that filter s3 so that it switches custodian from doing piecemeal assembly of an s3 resource to querying config for the bucket, which is a single api call, hence improved execution times.

policy.yaml
`
policies:
  - name: s3-default-encryption-disabled
    resource: s3
    source: config
    region: us-east-1
    description: S3 buckets that do not have default encryption enabled
    filters:
      - type: bucket-encryption
        state: False
`

Current Behavior
`custodian run --dryrun --region us-east-1 S3-check-bucket-encryption.yml -s reports
2019-11-13 15:38:15,867: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python2.7/site-packages/c7n/query.py", line 453, in resources
    resources = self.source.resources(query)
  File "/usr/local/lib/python2.7/site-packages/c7n/query.py", line 360, in resources
    self.load_resource(json.loads(r)) for r in page['Results']])
  File "/usr/local/lib/python2.7/site-packages/c7n/resources/s3.py", line 171, in load_resource
    method(resource, v)
  File "/usr/local/lib/python2.7/site-packages/c7n/resources/s3.py", line 353, in handle_BucketVersioningConfiguration
    if item_value['isMfaDeleteEnabled']:
KeyError: u'isMfaDeleteEnabled'
`

Desired Behaviour
Command should succed and return faster then without having "source: config" in the policy

`custodian version
0.8.45.3
`

**Comment by kapilt** [comment]
do you by chance know when config was enabled on these accounts? not sure if this is because config is changing format on us or an older recorded value, we have an explicit test on versioning which has a default boolean value for mfa delete.

**Comment by olsib** [comment]
should be a couple months on this account

**Comment by ajkerrigan** [comment]
This should be resolved by #7059 (FYI @cjhallman - I know you ran into this issue as well)
