### ISSUE TITLE
c7n-org suddenly throughing errors Memory Failed.

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5088]
Process ForkProcess-3:
Process ForkProcess-6:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 239, in _process_worker
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n_org/cli.py", line 538, in run_account
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/policy.py", line 882, in get_variables
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/utils.py", line 273, in local_session
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/credentials.py", line 50, in __call__
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/boto3/session.py", line 80, in __init__
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/boto3/session.py", line 120, in _setup_loader
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 680, in get_component
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 239, in _process_worker
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 903, in get_component
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 150, in <lambda>
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 234, in get_config_variable
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 227, in get_config_variable
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n_org/cli.py", line 538, in run_account
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/policy.py", line 882, in get_variables
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/utils.py", line 273, in local_session
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/credentials.py", line 50, in __call__
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 324, in provide
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 383, in provide
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/boto3/session.py", line 80, in __init__
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 325, in get_scoped_config
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 219, in _build_profile_map
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/boto3/session.py", line 120, in _setup_loader
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 352, in full_config
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configloader.py", line 106, in load_config
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 680, in get_component
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configloader.py", line 147, in raw_config_parse
  File "/usr/lib64/python3.7/configparser.py", line 610, in __init__
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 903, in get_component
  File "/usr/lib64/python3.7/configparser.py", line 1317, in __init__
MemoryError
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 150, in <lambda>
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 234, in get_config_variable

During handling of the above exception, another exception occurred:

  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 227, in get_config_variable
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 324, in provide
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configprovider.py", line 383, in provide
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 325, in get_scoped_config
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 205, in _sendback_result
  File "/usr/lib64/python3.7/multiprocessing/queues.py", line 358, in put
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 51, in dumps
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 39, in __init__
MemoryError
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 219, in _build_profile_map

During handling of the above exception, another exception occurred:

  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 352, in full_config
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configloader.py", line 106, in load_config
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/configloader.py", line 149, in raw_config_parse
  File "/usr/lib64/python3.7/configparser.py", line 696, in read
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
  File "/usr/lib64/python3.7/configparser.py", line 1014, in _read
MemoryError
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 242, in _process_worker
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 208, in _sendback_result

During handling of the above exception, another exception occurred:

  File "/usr/lib64/python3.7/multiprocessing/queues.py", line 358, in put
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 51, in dumps
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 39, in __init__
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 205, in _sendback_result
MemoryError
  File "/usr/lib64/python3.7/multiprocessing/queues.py", line 358, in put
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 51, in dumps
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 242, in _process_worker
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 208, in _sendback_result
  File "/usr/lib64/python3.7/multiprocessing/queues.py", line 358, in put
  File "/usr/lib64/python3.7/multiprocessing/reduction.py", line 51, in dumps
MemoryError
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n_org/cli.py", line 538, in run_account
    p.expand_variables(p.get_variables(account.get('vars', {})))
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/policy.py", line 882, in get_variables
    utils.local_session(self.session_factory)),
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/utils.py", line 244, in get_account_alias_from_sts
    response = session.client('iam').list_account_aliases()
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/session.py", line 839, in create_client
    client_config=config, api_version=api_version)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/client.py", line 79, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/client.py", line 117, in _load_service_model
    api_version=api_version)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/loaders.py", line 383, in load_service_model
    model = self.load_data(full_path)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/botocore/loaders.py", line 173, in load_file
    payload = fp.read().decode('utf-8')
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/custodian/bin/c7n-org", line 10, in <module>
    sys.exit(cli())
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n_org/cli.py", line 645, in run
    account_region_pcounts, account_region_success = f.result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib64/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
MemoryError

**custodian version 0.8.44.2**

accounts.yml file

accounts:
   - account_id: '1234456799897'
    name: testdev
    regions:
        us-east-1
        us-east-2
        us-west-1
        us-west-2
        eu-central-1
        role: arn:aws:iam::1234456799897:role/Role

  - account_id: '23456743533'
    name: testuat
    regions:
        us-east-1
        us-east-2
        us-west-1
        us-west-2
        eu-central-1
        role: arn:aws:iam::23456743533:role/Role

**Comment by kapilt** [comment]
seems like your running on underpowered hardware. wrt to memory size. you can adjust c7n-org memory usage via setting environment variable `C7N_ORG_PARALLEL` .. we default to 4 * logical cores, but for hosts/containers that are oddly sized or using cgroup restrictions that default may need adjustment. you might want to try playing with a few values like C7N_ORG_PARALLEL=3
