### ISSUE TITLE
azure - cli auth broken

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5115]
custodian azure provider is supposed to pickup cli auth by default if there are no explicitly provided auth options (per docs https://cloudcustodian.io/docs/azure/configuration/authentication.html#azure-cli) , but it seems to fail with an inscrutable auth failure error. 

```
$ az --version
azure-cli                         2.0.76

command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.76/libexec/bin/python'
Extensions directory '/Users/kapilt/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]


$ az account list
[
  {
    "cloudName": "AzureCloud",
    "id": "453fd504-7f29-....",
    "isDefault": true,
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    "tenantId": "7637bef8-0c4d-....",
    "user": {
      "name": "kapilt@example.com",
      "type": "user"
    }
  }
]

$ custodian run -c azure-periodic.yml  -s out -v
2019-11-24 11:30:56,498: custodian.commands:DEBUG Loaded file azure-periodic.yml. Contains 1 policies
2019-11-24 11:30:56,498: custodian.azure.session:ERROR Failed to authenticate.
Traceback (most recent call last):
  File "/Users/kapilt/projects/custodian/.tox/py37/lib/python3.7/site-packages/jwt/api_jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/session.py", line 146, in _initialize_session
    self._authenticate()
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/session.py", line 102, in _authenticate
    result = instance.authenticate()
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/session.py", line 384, in authenticate
    decoded = jwt.decode(credential.token['access_token'], verify=False)
  File "/Users/kapilt/projects/custodian/.tox/py37/lib/python3.7/site-packages/jwt/api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "/Users/kapilt/projects/custodian/.tox/py37/lib/python3.7/site-packages/jwt/api_jws.py", line 183, in _load
    raise DecodeError('Not enough segments')
jwt.exceptions.DecodeError: Not enough segments
```

**Comment by kapilt** [comment]
additionally the docs on creating a service principal are broken as they suggest passing a password on the cli, which thankfully is no longer supported
https://cloudcustodian.io/docs/azure/configuration/authentication.html#id1

```
$ az ad sp create-for-rbac --name c7n-devx --password thisisdumb                                                                                         
az: error: unrecognized arguments: --password thisisdumb
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {ad} ...

```

**Comment by kapilt** [comment]
actually i think this was my error, i had a fake token set from running unit tests.
