### ISSUE TITLE
account_id doesn't work in mailer.yml

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5226]
```
queue_url: https://sqs.us-west-2.amazonaws.com/{account_id}/cloud-custodian
role: arn:aws:iam::{account_id}:role/cloud-custodian-mailer
```

```
✗ c7n-mailer --config mailer.yml --update-lambda
2020-01-13 13:47:26,581 - custodian-mailer - INFO - Provisioning mailer lambda us-west-2
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/bin/c7n-mailer", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/c7n_mailer/cli.py", line 237, in main
    deploy.provision(mailer_config, functools.partial(session_factory, mailer_config))
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/c7n_mailer/deploy.py", line 99, in provision
    manager.publish(func)
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/c7n/mu.py", line 365, in publish
    func, role, s3_uri, qualifier=alias)
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/c7n/mu.py", line 518, in _create_or_update
    result = self.client.update_function_configuration(**new_config)
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/.local/share/virtualenvs/cloud-custodian-vLkLXQ1u/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateFunctionConfiguration operation: 1 validation error detected: Value 'arn:aws:iam::{account_id}:role/cloud-custodian-mailer' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
```

**Comment by kapilt** [comment]
are you deploying mailer per account? mostly mailer gets deployed centralized, which is why i'm not sure about the utility about adding such a feature.

**Comment by nitrocode** [comment]
I'm not deploying by account but the mailer, just like c7n, is already aware of the account ID and that ID is seen as sensitive information so why not provide it using the APIs instead of hard coding it into the configuration file?

**Comment by kapilt** [comment]
the mailer config file specifically has credentials for things (kms encrypted normally), ldap, smtp creds etc. we consider the account id sensitive only when exposed publicly, internal to organization i don't generally consider it sensitive. the mailer config file also has mappings of account ids to account contacts. ie. for the mailer file account ids are pretty common and central to its function, and i'm not clear on the value on trying to abstract that.
