### ISSUE TITLE
aws.iam-user resource access-key filter needs logic to stack multiple access-key filters

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5232]
With iam-user we are trying to identify and disable/delete only matching Access Keys which match all our filters however it is currently only using the last filter as it doesn't have logic to handle multiple filters stacked.  @kapilt  has started a PR for a fix

**Comment by jtroberts83** [comment]
I have tested the newly PR code and it fails.  While it works in dryrun mode,  when I take dryrun off the action to disable the keys errors out with the following error:

```
2020-01-16 04:09:29,005: custodian.policy:INFO policy:iam-old-access-keys-disable resource:iam-user region:us-east-1 count:1 time:0.37
2020-01-16 04:09:29,008: custodian.output:DEBUG metric:ResourceCount Count:1 policy:iam-old-access-keys-disable restype:iam-user scope:policy
2020-01-16 04:09:29,008: custodian.output:DEBUG metric:PolicyException Count:1 policy:iam-old-access-keys-disable restype:iam-user
2020-01-16 04:09:29,008: custodian.output:DEBUG metric:ApiCalls Count:7 policy:iam-old-access-keys-disable restype:iam-user
2020-01-16 04:09:29,008: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 320, in run
    results = a.process(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/resources/iam.py", line 1923, in process
    keys)
  File "/root/cc/lib/python3.6/site-packages/c7n/resources/iam.py", line 1945, in resolve_credential_keys
    if k['c7n:match-type'] == 'credential':
KeyError: 'c7n:match-type'
2020-01-16 04:09:29,009: custodian.commands:ERROR Error while executing policy iam-old-access-keys-disable, continuing
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/commands.py", line 283, in run
    policy()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 1032, in __call__
    resources = mode.run()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 320, in run
    results = a.process(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/resources/iam.py", line 1923, in process
    keys)
  File "/root/cc/lib/python3.6/site-packages/c7n/resources/iam.py", line 1945, in resolve_credential_keys
    if k['c7n:match-type'] == 'credential':
KeyError: 'c7n:match-type'
```
The test policy being run when the error is received is:
```
  filters:
      - type: access-key
        key: Status
        value: Active
        match-operator: and
      - type: access-key
        value_type: date
        key: CreateDate
        op: greater-than
        value: "2020/01/08"
        match-operator: and
      - type: access-key
        key: CreateDate
        value_type: age
        value: 6
        op: greater-than
        match-operator: and
  actions:
      - type: remove-keys
        disable: true
        matched: true
```

**Comment by jtroberts83** [comment]
@kapilt  **UPDATE**  I found one issue with the code that needs corrected.  https://github.com/cloud-custodian/cloud-custodian/blob/a06f2b46f6aa9a29f5ad36c23811a6f38d209e2a/c7n/resources/iam.py#L1548
needs to be changed from 'matched-type' to 'match-type' .  After I made this change the policy did run and seems to have worked.  It disabled only the matched key and left the other key alone. :)  So with the above little change I think we have a winner! 👍

**Comment by kapilt** [comment]
Thanks for testing the pr, I’ll fix that when backfilling tests next week. For future ref, it’s probably best for pr feedback to comment on the pr.
