### ISSUE TITLE
custodian --raw throwing error

### ISSUE THREAD

**Issue by tzd-sh** [cloud-custodian/cloud-custodian#5269]
I'm not sure which version it started happening with, but I find that in the most recent version of 'custodian' that I am using from c7n==0.8.45.4 package, the '--raw' parameter results in an error as follows:

Sample Policy File:
```
$ cat list-ec2-instances.yaml
policies:
  - name: list-ec2-instances
    resource: ec2
```

Run custodian:    
```
$ custodian run -s output list-ec2-instances.yaml
2020-01-23 22:57:40,295: custodian.policy:INFO policy:list-ec2-instances resource:ec2 region:us-east-1 count:0 time:0.57
```

Run custodian report with '--raw' parameter, throws error:
```
$ custodian report -s output --raw outfile.json list-ec2-instances.yaml
CustodianDate,InstanceId,tag:Name,InstanceType,LaunchTime,VpcId,PrivateIpAddress
Traceback (most recent call last):
  File "/home/ec2-user/custodian/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/cli.py", line 374, in main
    command(config)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/commands.py", line 141, in _load_policies
    return f(options, list(policies))
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/commands.py", line 311, in report
    policies, begin_date, options, sys.stdout, raw_output_fh=options.raw)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/reports/csvout.py", line 112, in report
    dumps(records, raw_output_fh, indent=2)
  File "/home/ec2-user/custodian/lib/python3.7/site-packages/c7n/utils.py", line 122, in dumps
    return json.dump(data, fh, cls=DateTimeEncoder, indent=indent)
  File "/usr/lib64/python3.7/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'

```

Run custodian report without '--raw' parameter, no error:
```
$ custodian report -s output list-ec2-instances.yaml
CustodianDate,InstanceId,tag:Name,InstanceType,LaunchTime,VpcId,PrivateIpAddress

$
```

**Comment by JohnHillegass** [comment]
Hey guys, I just submitted a PR that addresses this. @kapilt please let me know what you think. I added some details about my thought process to the PR notes.

**Comment by kapilt** [comment]
thanks @JohnHillegass, merged the pr with a small update.
