### ISSUE TITLE
{account_id} filter not working with value filter using value_from s3

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5273]
Getting an error with the following policy:
```
policies:

- name: iamaccesstest
  resource: iam-user
  filters:
          - type: value
            key: {account_id}
            op: not-in
            value_from:
                url: s3://mybucket/Exceptions.csv
                format: csv2dict
```
This throws the error:
```
error:'dict' object has no attribute 'startswith'
```
 tried quotes but throws another error:
```
c7n_org:ERROR Exception running policy:iamaccesstest account:my-account-name region:us-east-1 error:invalid token: Parse error at column 0, token "12345678900" (NUMBER), for expression:
"12345678900"
 ^
```

**Comment by kapilt** [comment]
please provide traceback from running with custodian (not c7n-org) with -v (--verbose option). also whats the format/structure of Exceptions.csv? its got a header row with literal account ids?

**Comment by jtroberts83** [comment]
traceback
```
traceback
```
(cc) root@ip-10-128-128-174:~# custodian run --assume arn:aws:iam::111111111111:role/AGT_Cloud_Custodian_Role -s . iamaccesskey.yaml -r us-east-1 --cache-period 0 -v --dryrun --debug
2020-01-27 17:14:57,457: custodian.cache:DEBUG Disabling cache
2020-01-27 17:14:57,457: custodian.commands:DEBUG Loaded file iamaccesskey.yaml. Contains 1 policies
2020-01-27 17:14:57,581: custodian.output:DEBUG Storing output with <LogFile file://./iamaccesstest/custodian-run.log>
2020-01-27 17:14:57,659: custodian.policy:DEBUG Running policy:iamaccesstest resource:iam-user region:us-east-1 c7n:0.8.45.4
2020-01-27 17:14:58,163: custodian.output:DEBUG metric:PolicyException Count:1 policy:iamaccesstest restype:iam-user
2020-01-27 17:14:58,163: custodian.output:DEBUG metric:ApiCalls Count:4 policy:iamaccesstest restype:iam-user
2020-01-27 17:14:58,163: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/root/cc/lib/python3.6/site-packages/c7n/query.py", line 460, in resources
    resources = self.filter_resources(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 501, in process
    return super(ValueFilter, self).process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 198, in process
    return list(filter(self, resources))
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 488, in __call__
    matched = self.match(i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 551, in match
    r = self.get_resource_value(self.k, i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 523, in get_resource_value
    self.expr[k] = jmespath.compile(k)
  File "/root/cc/lib/python3.6/site-packages/jmespath/__init__.py", line 8, in compile
    return parser.Parser().parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 111, in _parse
    parsed = self._expression(binding_power=0)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 124, in _expression
    left = nud_function(left_token)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 440, in _error_nud_token
    self._raise_parse_error_for_token(token, 'invalid token')
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 477, in _raise_parse_error_for_token
    actual_type, reason)
jmespath.exceptions.ParseError: invalid token: Parse error at column 0, token "111111111111" (NUMBER), for expression:
"111111111111"
 ^
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/cli.py", line 374, in main
    command(config)
  File "/root/cc/lib/python3.6/site-packages/c7n/commands.py", line 141, in _load_policies
    return f(options, list(policies))
  File "/root/cc/lib/python3.6/site-packages/c7n/commands.py", line 283, in run
    policy()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 1038, in __call__
    resources = PullMode(self).run()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/root/cc/lib/python3.6/site-packages/c7n/query.py", line 460, in resources
    resources = self.filter_resources(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 501, in process
    return super(ValueFilter, self).process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 198, in process
    return list(filter(self, resources))
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 488, in __call__
    matched = self.match(i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 551, in match
    r = self.get_resource_value(self.k, i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 523, in get_resource_value
    self.expr[k] = jmespath.compile(k)
  File "/root/cc/lib/python3.6/site-packages/jmespath/__init__.py", line 8, in compile
    return parser.Parser().parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 111, in _parse
    parsed = self._expression(binding_power=0)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 124, in _expression
    left = nud_function(left_token)
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 440, in _error_nud_token
    self._raise_parse_error_for_token(token, 'invalid token')
  File "/root/cc/lib/python3.6/site-packages/jmespath/parser.py", line 477, in _raise_parse_error_for_token
    actual_type, reason)
jmespath.exceptions.ParseError: invalid token: Parse error at column 0, token "111111111111" (NUMBER), for expression:
"111111111111"
 ^
> /root/cc/lib/python3.6/site-packages/jmespath/parser.py(477)_raise_parse_error_for_token()
-> actual_type, reason)
(Pdb)
```
```

**Comment by jtroberts83** [comment]
Changed the policy to use a json accounts file but still getting an error.

Here is the policy I ran:
```
policies:

- name: iamaccesstest
  resource: iam-user
  filters:
          - type: value
            key: "{account_id}"
            op: not-in
            value_from:
                url: s3://our-bucket/IAMAccessKeyExceptions.json
                format: json
                expr: "accounts[]"
```

and our accounts json looks like this:

```
accounts: [
"11111111111111",
"22222222222222",
"33333333333333"
]
```

and the error we receive is:
```
2020-01-27 19:57:56,838: custodian.cache:DEBUG Disabling cache
2020-01-27 19:57:56,838: custodian.commands:DEBUG Loaded file iamaccesskey.yaml. Contains 1 policies
2020-01-27 19:57:56,963: custodian.output:DEBUG Storing output with <LogFile file://./iamaccesstest/custodian-run.log>
2020-01-27 19:57:57,044: custodian.policy:DEBUG Running policy:iamaccesstest resource:iam-user region:us-east-1 c7n:0.8.45.4
2020-01-27 19:57:57,530: custodian.output:DEBUG metric:PolicyException Count:1 policy:iamaccesstest restype:iam-user
2020-01-27 19:57:57,530: custodian.output:DEBUG metric:ApiCalls Count:4 policy:iamaccesstest restype:iam-user
2020-01-27 19:57:57,530: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/root/cc/lib/python3.6/site-packages/c7n/query.py", line 460, in resources
    resources = self.filter_resources(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 501, in process
    return super(ValueFilter, self).process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 198, in process
    return list(filter(self, resources))
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 488, in __call__
    matched = self.match(i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 541, in match
    self.v = values.get_values()
  File "/root/cc/lib/python3.6/site-packages/c7n/resolver.py", line 155, in get_values
    data = json.loads(contents)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/cc/lib/python3.6/site-packages/c7n/cli.py", line 374, in main
    command(config)
  File "/root/cc/lib/python3.6/site-packages/c7n/commands.py", line 141, in _load_policies
    return f(options, list(policies))
  File "/root/cc/lib/python3.6/site-packages/c7n/commands.py", line 283, in run
    policy()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 1038, in __call__
    resources = PullMode(self).run()
  File "/root/cc/lib/python3.6/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/root/cc/lib/python3.6/site-packages/c7n/query.py", line 460, in resources
    resources = self.filter_resources(resources)
  File "/root/cc/lib/python3.6/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 501, in process
    return super(ValueFilter, self).process(resources, event)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 198, in process
    return list(filter(self, resources))
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 488, in __call__
    matched = self.match(i)
  File "/root/cc/lib/python3.6/site-packages/c7n/filters/core.py", line 541, in match
    self.v = values.get_values()
  File "/root/cc/lib/python3.6/site-packages/c7n/resolver.py", line 155, in get_values
    data = json.loads(contents)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> /usr/lib/python3.6/json/decoder.py(357)raw_decode()
-> raise JSONDecodeError("Expecting value", s, err.value) from None
(Pdb)
```

**Comment by kapilt** [comment]
so the first error is because key: is interpreted as a jmespath expression on the resource, which this is not.

the second error is because its not a valid json file.

not sure either of those matter, nutshell your looking for evaluating a static string, tbh this feels like its much more germane to using #4466 although perhaps a quick option is to enable constants in keys expressions.

**Comment by AdvithSubbu** [comment]
hi kapilt,
I have same exact requirement  as jtroberts83 and running into same issues. can you please let me know if there is a workaround ?

**Comment by ajkerrigan** [comment]
> hi kapilt, I have same exact requirement as jtroberts83 and running into same issues. can you please let me know if there is a workaround ?

You can handle this using [policy execution conditions](https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution) rather than filters. For example:

```yaml
conditions:
  - type: value
    key: account_id
    op: not-in
    value_from:
      url: s3://your-bucket/exclusions.json
      format: json
      expr: "accounts[]"
```

Given this content in `exclusions.json`:

```json
{"accounts": ["111111111111"]}
```
Your policy would avoid running in that account with a message like:
```
2022-03-10 15:42:42,973: custodian.policy:INFO Skipping policy:your-policy due to execution conditions
```

**Comment by AdvithSubbu** [comment]
Thanks for quick reply.

> > hi kapilt, I have same exact requirement as jtroberts83 and running into same issues. can you please let me know if there is a workaround ?
> 
> You can handle this using [policy execution conditions](https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution) rather than filters. For example:
> 
> ```yaml
> conditions:
>   - type: value
>     key: account_id
>     op: not-in
>     value_from:
>       url: s3://your-bucket/exclusions.json
>       format: json
>       expr: "accounts[]"
> ```
> 
> Given this content in `exclusions.json`:
> 
> ```json
> {"accounts": ["111111111111"]}
> ```
> 
> Your policy would avoid running in that account with a message like:
> 
> ```
> 2022-03-10 15:42:42,973: custodian.policy:INFO Skipping policy:your-policy due to execution conditions
> ```
Thank you for quick reply !!
 Is it correct ,that the policy below ,would run when account_id = 123456789? 

trying to delete resource when account_id = 123456789 and  test-if-migrated  present and its value is test-if-migrated=done

policies:
  - name: test-policy
    resource: aws.sns
    conditions:
      - type: value
        key: account_id
        op:  in
        value: ["123456789"]
    filters:      
        - or:
          - "tag:test-if-migrated": present
          - type: value
            key: "tag:test-if-migrated"
            op: eq
            value: "done"
    actions:
      - delete

**Comment by ajkerrigan** [comment]
Yes, it would only run for that single account ID. Concerning the tag checks... if you only want to match if `test-if-migrated` is `done` you don't need a separate `present` filter.

In that sample policy, the `or` block means the `done` check isn't doing anything - the filter will match any topic with a `test-if-migrated` key.

**Comment by AdvithSubbu** [comment]
Thank you !! one question , i have filters setup like the below in one of my policy

filters: **&filters**
  - not:
    - or:
      - "tag:state": "ca"
      - "tag:country": "usa"
  - or:
    - type: value
      key: "tag:test-if-migrated"
      op: eq
      value_from:
        url: s3://apps/apps-list.csv
    - type: value
      key: "tag:tag1"
      op: eq
      value_from:
        url: s3://apps/apps-lis2t.csv
    - type: value
      key: "tag:test1"
      op: eq
      value: "someval"
    - type: value
      key: "tag:test2"
      op: ne
      value: "someval2"

currently using the declared filters in other policies (in the same yaml file) (   ***filters** )

Question -  is it possible to add condition discussed above to only one of the tag ( only one tag needs condition attached to it)

**Comment by AdvithSubbu** [comment]
> Yes, it would only run for that single account ID. Concerning the tag checks... if you only want to match if `test-if-migrated` is `done` you don't need a separate `present` filter.
> 
> In that sample policy, the `or` block means the `done` check isn't doing anything - the filter will match any topic with a `test-if-migrated` key.

Hi @ajkerrigan,

Running into  Issue below when marking for op on elasticbeanstalk-environment.  Any suggestions ??

An error occurred (InvalidParameterValue) when calling the UpdateTagsForResource operation: Environment named XXXX is in an invalid state for this operation. Must be Ready.

**Comment by ajkerrigan** [comment]
> An error occurred (InvalidParameterValue) when calling the UpdateTagsForResource operation: Environment named XXXX is in an invalid state for this operation. Must be Ready.

Sounds like you can't tag an environment unless its `Status` is `Ready`. You may need a filter in your policy to skip environments otherwise.
