### ISSUE TITLE
c7n-org issue with initialize_kube

### ISSUE THREAD

**Issue by ismferd** [cloud-custodian/cloud-custodian#5281]
Launching c7n-org as docker with tag latest, I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/c7n_org/cli.py", line 624, in run
    config, use, debug, verbose, accounts, tags, policy, policy_tags=policy_tags)
  File "/usr/local/lib/python3.7/site-packages/c7n_org/cli.py", line 197, in init
    load_resources()
  File "/usr/local/lib/python3.7/site-packages/c7n/resources/__init__.py", line 31, in load_resources
    load_providers(set(pmap))
  File "/usr/local/lib/python3.7/site-packages/c7n/resources/__init__.py", line 70, in load_providers
    from c7n_kube.entry import initialize_kube
```

My policy:
```
policies:
  - name: lc-mark-as-unused
    resource: launch-config
    mode: 
      type: periodic
      schedule: "rate(15 days)"
      role: c7n_cloud_custodian_role
      tags:
        env: cor
        context: governance
        role: lc_garbage_collector
        app: cloudcustodian
    comments: |
      Mark any unused LC checking it every 15 days.
    filters:
      - unused
    actions:
      - type: notify
        violation_desc: This LC hasn't been used during the last 15 days
        action_desc: Please investigate if you can delete this LC.
        to:
          - https://hooks.slack.com/services/XXX
        transport:
          type: sqs
          queue: https://sqs.xxxx-xx-x.amazonaws.com/XXXX/cloud_custodian_sqs_mailer
          region: xx-xxxx-x
```

**Comment by kapilt** [comment]
thanks for the bug report, while we try to keep trunk stable/green, I would recommend using a named release tag on docker ie 0.8.46.1, there's a few larger changes that just landed on trunk which will need a few days to stabilize. we've discussed renaming the latest tag to point to the last stable release tag, but we haven't finished that change yet.

**Comment by kapilt** [comment]
docker images should be updated w/ fix within the hour
