### ISSUE TITLE
docker build issues with setuptools_scm

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5283]
````
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rf3t8j_o/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rf3t8j_o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-rf3t8j_o/pip-egg-info
cwd: /tmp/pip-req-build-rf3t8j_o/
Complete output (29 lines):
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extra_requires'
warnings.warn(msg)
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-req-build-rf3t8j_o/setup.py", line 46, in <module>
":python_version<'3.3'": ["backports.functools-lru-cache"]
File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.7/distutils/core.py", line 108, in setup
_setup_distribution = dist = klass(attrs)
File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
k: v for k, v in attrs.items()
File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
self.finalize_options()
File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
ep.load()(self)
File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
ep.load()(self, ep.name, value)
File "/tmp/pip-req-build-rf3t8j_o/.eggs/setuptools_scm-3.4.3-py3.7.egg/setuptools_scm/integration.py", line 17, in version_keyword
dist.metadata.version = _get_version(config)
File "/tmp/pip-req-build-rf3t8j_o/.eggs/setuptools_scm-3.4.3-py3.7.egg/setuptools_scm/__init__.py", line 147, in _get_version
parsed_version = _do_parse(config)
File "/tmp/pip-req-build-rf3t8j_o/.eggs/setuptools_scm-3.4.3-py3.7.egg/setuptools_scm/__init__.py", line 118, in _do_parse
"use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-rf3t8j_o'.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by kapilt** [comment]
we may have to just revert the pr, my local .git is ~245mb which is why we omit when building the docker image. alternatively we can perform a shallow checkout in the docker build but that restricts it to trunk only usage, where as the moment it derives source directly from the. final option would be to try to surgery in the exact metadata that setuptools_scm needs as a partial from the local checkout.

**Comment by kapilt** [comment]
originated in pr #5279

**Comment by kapilt** [comment]
it looks like setuptools_scm defines all kinds of mechanisms/hacks to work around stuff like this, the easiest one i can parse from it it, is putting a fallback_version into the config, still need to verify if thats viable.

**Comment by kapilt** [comment]
confirmed that seems to work, re 

```diff
+    use_scm_version={'write_to': 'c7n/version.py', 'fallback_version': '0.8.46.1'},
```
