### ISSUE TITLE
Missing id attribute in resource aws.glue-table

### ISSUE THREAD

**Issue by Evnsan** [cloud-custodian/cloud-custodian#5288]
## Problem
Using aws.glue-table with filter fires a `KeyError: None` error.

## Policy
```
policies:
  - name: aws-glue-table-costs-tags
    resource: aws.glue-table
    mode:
      type: periodic
      role: arn:aws:iam::6666666666:role/custodian-role-ABCDE00000
      schedule: "rate(1 day)"
    filters:
      - and:
        - type: value
          key: "State.Name"
          value: "running"
        - or:
          - "tag:Tag1": absent
          - "tag:Tag2": absent
    actions:
      - type: notify
        to:
          - noop@somewhere.com
        transport:
          type: sns
          region: us-esat-1
          template: slack_default
          topic: custodian-topic-000000000FGXKZ
          attributes:
            policy_name: aws-glue-table-costs-tags
```

## Execution output
```
>>custodian run -d -v policies/policy.yml -t aws.glue-table -s .
2020-01-28 13:45:35,592: custodian.commands:DEBUG Loaded file policies/policy.yml. Contains 24 policies
2020-01-28 13:45:35,601: custodian.aws:DEBUG using default region:us-east-1 from boto
2020-01-28 13:45:37,172: custodian.output:DEBUG Storing output with <LogFile file://./aws-glue-table-costs-tags/custodian-run.log>
2020-01-28 13:45:37,183: custodian.policy:DEBUG Running policy:aws-glue-table-costs-tags resource:aws.glue-table region:us-east-1 c7n:0.8.46.1
2020-01-28 13:45:38,544: custodian.resources.gluedatabase:DEBUG Filtered from 6 to 6 gluedatabase
2020-01-28 13:45:40,506: custodian.output:DEBUG metric:PolicyException Count:1 policy:aws-glue-table-costs-tags restype:aws.glue-table
2020-01-28 13:45:40,506: custodian.output:DEBUG metric:ApiCalls Count:8 policy:aws-glue-table-costs-tags restype:aws.glue-table
2020-01-28 13:45:40,506: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/query.py", line 467, in resources
    resources = self.filter_resources(resources)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 260, in process
    return self.process_set(resources, event)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 272, in process_set
    resource_map = {r[resource_type.id]: r for r in resources}
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 272, in <dictcomp>
    resource_map = {r[resource_type.id]: r for r in resources}
KeyError: None
2020-01-28 13:45:40,510: custodian.commands:ERROR Error while executing policy aws-glue-table-costs-tags, continuing
Traceback (most recent call last):
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/commands.py", line 283, in run
    policy()
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/policy.py", line 1045, in __call__
    resources = PullMode(self).run()
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/query.py", line 467, in resources
    resources = self.filter_resources(resources)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 260, in process
    return self.process_set(resources, event)
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 272, in process_set
    resource_map = {r[resource_type.id]: r for r in resources}
  File "/home/evnsan/cobli/cobli-custodian/venv/lib/python3.7/site-packages/c7n/filters/core.py", line 272, in <dictcomp>
    resource_map = {r[resource_type.id]: r for r in resources}
KeyError: None
```

## Root cause
[OrFilter](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/filters/core.py#L272) class use resource.id to map resources, but ResourceType [aws.glue-table](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/glue.py#L237) does not have one.
To validate this assumption, I added an id entry like this:
```
@resources.register('glue-table')
class GlueTable(query.ChildResourceManager):

    child_source = 'describe-table'

    class resource_type(TypeInfo):
        service = 'glue'
        parent_spec = ('glue-database', 'DatabaseName', None)
        enum_spec = ('get_tables', 'TableList', None)
        name = 'Name'
        id = 'Name'
        date = 'CreatedOn'
        arn_type = 'table'
```
The filter runs fine after that

**Comment by kapilt** [comment]
interesting, thanks for the bug report, I thought we had a meta test for this (check all resource metadata for id), but perhaps not.

**Comment by kapilt** [comment]
wrote a quick test, it looks like k8s resources are missing ids as well. only other one across providers was the glue-table.
