### ISSUE TITLE
azure - function app publishing error

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5426]
**Describe the bug**

re-rerunning a custodian policy with a deployed azure function error'd during update deployment (more specifically checking for a deployment error, error'd).

**Expected behavior**

The update should proceed idempotently and not re-create existing resources, nor error out with traceback.

**Background (please complete the following information):**
 - OS: OX 10.15
 - Python Version: 3.8.1
 - Custodian Version: 0.9.0/trunk
 - Cloud Provider: azure
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
   - name: custodian_functions_test_event_consumption
     resource: azure.resourcegroup
     mode:
         type: azure-event-grid
         events: ['ResourceGroupWrite']
     filters:
       - tag:custodian-function-test-event-consumption: absent
     actions:
       - type: tag
         tag: custodian-function-test-event-consumption
         value: passed
```
 - Traceback: [if applicable, please exclude sensitive/account information]

custodian run -c azure.yml -s out  --debug
2020-03-07 06:56:05,439: custodian.azure.session:INFO Authenticated [Principal | omit]
2020-03-07 06:56:07,899: custodian.azure.deployment_unit.DeploymentUnit:INFO Found Function Application "custodian-functions-test-event-consumption-e5ee1df1".
2020-03-07 06:56:08,180: custodian.azure.policy.AzureFunctionMode:INFO Creating storage queue
2020-03-07 06:56:08,946: custodian.azure.session:INFO Authenticated [Principal | omit]
2020-03-07 06:56:09,108: custodian.azure.policy.AzureFunctionMode:INFO Storage queue creation succeeded
2020-03-07 06:56:09,108: custodian.azure.policy.AzureFunctionMode:INFO Creating event grid subscription
2020-03-07 06:56:22,811: custodian.azure.policy.AzureFunctionMode:INFO Event grid subscription creation succeeded: subscription_id=omit
2020-03-07 06:56:22,811: custodian.azure.policy.AzureFunctionMode:INFO Building function package for custodian-functions-test-event-consumption-e5ee1df1
2020-03-07 06:56:23,707: custodian.azure.policy.AzureFunctionMode:INFO Function package built, size is 621KB
2020-03-07 06:56:23,707: custodian.azure.function_app_utils:INFO Publishing Function application
2020-03-07 06:56:24,188: custodian.azure.function_package.FunctionPackage:INFO Publishing Function package from /var/folders/m0/9m4c62yx3sd12290vsfcc14m0000gn/T/tmpjanj8d9p
2020-03-07 06:56:30,669: custodian.azure.function_package.FunctionPackage:INFO Function publish result: 202
2020-03-07 06:56:30,669: custodian.azure.function_package.FunctionPackage:INFO Waiting for the remote build to finish
2020-03-07 06:56:31,245: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:56:41,459: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:56:51,783: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:02,350: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:12,561: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:22,843: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:33,037: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:43,202: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending
2020-03-07 06:57:53,455: custodian.azure.function_package.FunctionPackage:INFO Deployment status: Pending                                                                                     
Traceback (most recent call last):  
  File "/Users/kapilt/projects/custodian/c7n/cli.py", line 374, in main
    command(config)                    
  File "/Users/kapilt/projects/custodian/c7n/commands.py", line 140, in _load_policies
    return f(options, list(policies))                                                                                                                                                         
  File "/Users/kapilt/projects/custodian/c7n/commands.py", line 285, in run
    policy()
  File "/Users/kapilt/projects/custodian/c7n/policy.py", line 1052, in __call__
    resources = mode.provision()
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/policy.py", line 393, in provision
    FunctionAppUtilities.publish_functions_package(self.function_params, package)
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/functionapp_utils.py", line 127, in publish_functions_package
    package.wait_for_remote_build(publish_creds, is_consumption)
  File "/Users/kapilt/projects/custodian/tools/c7n_azure/c7n_azure/function_package.py", line 221, in wait_for_remote_build
    status = requests.get(status_uri).json()['status']
  File "/Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> /Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/decoder.py(400)raw_decode()
-> return self.scan_once(s, idx=_w(s, idx).end())
(Pdb) u
> /Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/decoder.py(370)decode()
-> obj, end = self.raw_decode(s)
(Pdb) u
> /Users/kapilt/.pyenv/versions/3.8.0/envs/c7n-3.8/lib/python3.8/site-packages/simplejson/__init__.py(525)loads()                                                                             
-> return _default_decoder.decode(s)
(Pdb) p s
"Deployment 'temp-95728eac' not found."

**Comment by kapilt** [comment]
i haven't been able to reproduce since changing the policy, ie. repeated deployments work.

**Comment by logachev** [comment]
Yes, I saw this issue. It is fixed in my PR (looks like same issue for Consumption\Dedicated, so I'm using same approach as for Dedicated

**Comment by logachev** [comment]
Wait code was moved to a separate script and this issue was fixed (using same wait approach as dedicated functions)
