### ISSUE TITLE
c7n-org DistributionNotFound Inside its Own Container

### ISSUE THREAD

**Issue by jcderose** [cloud-custodian/cloud-custodian#5483]
**Describe the bug**
When I run the `report` command on the latest `c7n-org` container (`sha256:52032263852903f4766e9e96bb1a6a6c9b52324393c3a48197e2394ee6ccc3a5`), I receive the following error:

```
DistributionNotFound: The \'c7n-org\' distribution was not found and is required by the application\n'
```

**To Reproduce**
```
$ docker pull cloudcustodian/c7n-org:latest
```
- Write a simple `accounts.yml` file. (Only one account is required.)
- Write the policy.yml file example below.
- Run this block of code inside a Python3 shell:
```
            import docker
            client.containers.run('cloudcustodian/c7n-org', \
                f'report -v -c /home/custodian/accounts.yml -s /home/custodian/output --region=all -u /home/custodian/policy.yml -p check-buckets', \
                environment=["AWS_DEFAULT_REGION=us-west-2"], \
                volumes={custodian_path: {'bind': '/home/custodian', 'mode': 'rw'}} \
            )
```

**Expected behavior**
The `client.containers.run` command exits without any errors.

**Background (please complete the following information):**
 - OS: Ubuntu 18.04 (but the command is running in a container)
 - Python Version: 3.6.9
 - Custodian Version: latest after 0.8.46.1
 - Tool Version: n/a
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback:

The full traceback is:
```
Traceback (most recent call last):
  File "/etc/cloudcustodian/generate_cloud_custodian_report.py", line 65, in <module>
    main(args.client)
  File "/etc/cloudcustodian/generate_cloud_custodian_report.py", line 38, in main
    f.write(client.containers.run('cloudcustodian/c7n-org:latest',                 f'report -v -c /home/custodian/accounts.yml -s /home/custodian/output --region=all -u /home/custodian/policy.yml -p {policy_name}',                 environment=["AWS_DEFAULT_REGION=us-west-2"],                 volumes={custodian_path: {'bind': '/home/custodian', 'mode': 'rw'}}             ).decode("utf-8"))
  File "/usr/local/lib/python3.6/dist-packages/docker/models/containers.py", line 832, in run
    container, exit_status, command, image, out
docker.errors.ContainerError: Command 'report -v -c /home/custodian/accounts.yml -s /home/custodian/output --region=all -u /home/custodian/policy.yml -p aws.acm-certificate-untagged' in image 'cloudcustodian/c7n-org:latest' returned non-zero exit status 1: b'Traceback (most recent call last):\n  File "/usr/local/bin/c7n-org", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in <module>\n    @_call_aside\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside\n    f(*args, **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master\n    ws.require(__requires__)\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'c7n-org\' distribution was not found and is required by the application\n'
```

**Comment by kapilt** [comment]
And your parameters to the docker cli for run and report are?

**Comment by kapilt** [comment]
looks like we where previously installing the packages, but we're using requirements-dev now which installs as editable from src, but the dockerfile for c7n-org removes the src directory as part of image pruning. getting rid of the rm /src resolves
