### ISSUE TITLE
Missing Version Ref in Launch Template cause exception

### ISSUE THREAD

**Issue by scoleri** [cloud-custodian/cloud-custodian#5501]
If there is a missing version ref in a Launch Template custodian throws an exception.  Boto3 allows you to create Launch Templates without explicitly adding version.  

To reproduce:  run an asg scan on an account with an asg using a launch template without Version attribute.

```
Traceback (most recent call last):
  File "/home/cloudcustodian/custodian/bin/c7n-org", line 11, in <module>
    sys.exit(cli())
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n_org/cli.py", line 649, in run
    debug)] = (a, r)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/executor.py", line 63, in submit
    return MainThreadFuture(func(*args, **kw))
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n_org/cli.py", line 560, in run_account
    resources = p.run()
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/policy.py", line 1045, in __call__
    resources = PullMode(self).run()
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/policy.py", line 288, in run
    resources = self.policy.resource_manager.resources()
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/query.py", line 467, in resources
    resources = self.filter_resources(resources)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/manager.py", line 108, in filter_resources
    resources = f.process(resources, event)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/resources/asg.py", line 832, in process
    launch_info = LaunchInfo(self.manager).initialize(asgs)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/resources/asg.py", line 85, in initialize
    self.templates = self.get_launch_templates(asgs)
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/resources/asg.py", line 92, in get_launch_templates
    template_ids = list(tmpl_mgr.get_asg_templates(asgs))
  File "/home/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/resources/ec2.py", line 1956, in get_asg_templates
    t['Version']), []).append(a['AutoScalingGroupName'])
KeyError: 'Version'
```

**Comment by csabella** [comment]
I believe this was fixed with #5458.   The traceback contains the code before the change.

**Comment by JohnHillegass** [comment]
@scoleri, could you confirm if #5458 has resolved the issue for you?

**Comment by scoleri** [comment]
We are confirming right now - have to break some LT's with boto.

**Comment by scoleri** [comment]
It seems to still be broken:
`15:45 $ custodian version
0.8.46.1`

`2020-04-24 15:49:04,688: c7n_org:ERROR Exception running policy:asg-instances-attrib account:platform-test region:us-west-2 error:'Version'`

**Comment by JohnHillegass** [comment]
Ah ok seems like you are using the last release version. Could you checkout the trunk and try running that? No worries if not, the next release is targeted for Monday and will have the fix included.

**Comment by scoleri** [comment]
Not sure i did this right but...
`17:05 $ c7n-org run --dryrun -s ~/log/$(date +%Y%m%d) -c ~/Projects/cloudcustodianpolicys/AccountLists/AdHocALLAccounts.yaml -u ESTags.yaml -p asg-instances-attrib --cache-period 0  -a platform-test
2020-04-24 17:05:52,698: c7n_org:INFO Ran account:platform-test region:eu-west-1 policy:asg-instances-attrib matched:1 time:3.21
2020-04-24 17:05:55,056: c7n_org:ERROR Exception running policy:asg-instances-attrib account:platform-test region:us-west-2 error:Parameter validation failed:
Invalid type for parameter Versions[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2020-04-24 17:05:55,096: c7n_org:INFO Policy resource counts Counter({'asg-instances-attrib': 1})
(py36) ✘-1 ~/Projects/FINOPS/TaggedElasticSearch [master L|✔]
17:05 $ custodian version
0.9`

**Comment by JohnHillegass** [comment]
Ok thanks for confirming. I think I see the error here. If the ref is missing do you have any preferences as to what it falls back to?  I’m thinking of using $latest, currently it’s set to None which is throwing this error.
