### ISSUE TITLE
c7n-org AttributeError: \'Policy\' object has no attribute \'region\'

### ISSUE THREAD

**Issue by jcderose** [cloud-custodian/cloud-custodian#5556]
**Describe the bug**
When I run c7n-org with the `run` command in `--debug` mode, I get the following error: 
```
AttributeError: \'Policy\' object has no attribute \'region\'\n'
```

**To Reproduce**
```
$ docker pull cloudcustodian/c7n-org:latest
```
* Write a simple accounts.yml file. (Only one account is required.)
* Write the policy.yml file example below.
Run this block of code inside a Python3 shell:
```
            import docker
              client.containers.run(
                'cloudcustodian/c7n-org:latest',             
                'run -v -c /home/custodian/accounts.yml -s /home/custodian/output --region=all -u /home/custodian/policy.yml --debug',             
                environment=["AWS_DEFAULT_REGION=us-west-2"],             
                volumes={custodian_path: {'bind': '/home/custodian', 'mode': 'rw'}}         
             )
```
**Expected behavior**
The `client.containers.run` command exits successfully without any errors.

**Background (please complete the following information):**
 - OS: Ubuntu 18.04 (but the command is running in a container)
 - Python Version: 3.6.9
 - Custodian Version: latest after 0.8.46.1
 - Tool Version: n/a
 - Cloud Provider: aws
 - Policy: 
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback: 
```
Command 'run -v -c /home/custodian/accounts.yml -s /home/custodian/output --region=all -u /home/custodian/policy.yml --debug' in image 'cloudcustodian/c7n-org:latest' returned non-zero exit status 1: b'Traceback (most recent call last):\n  File "/usr/local/bin/c7n-org", line 11, in <module>\n    load_entry_point(\'c7n-org\', \'console_scripts\', \'c7n-org\')()\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main\n    rv = self.invoke(ctx)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke\n    return callback(*args, **kwargs)\n  File "/src/tools/c7n_org/c7n_org/cli.py", line 654, in run\n    debug)] = (a, r)\n  File "/usr/local/lib/python3.7/site-packages/c7n/executor.py", line 63, in submit\n    return MainThreadFuture(func(*args, **kw))\n  File "/src/tools/c7n_org/c7n_org/cli.py", line 558, in run_account\n    if p.region and p.region != region:\nAttributeError: \'Policy\' object has no attribute \'region\'\n'
```

**Comment by kapilt** [comment]
I'm not able to reproduce, noting you omitted your docker image hash, but with the latest image.

```
docker images | grep cloudcustodian/c7n-org
cloudcustodian/c7n-org                                    latest              09c4631c7628        9 hours ago         534MB
```

running your script, produces the expected output

```
$ cat ~/org-run/output/c7n/us-east-1/ec2/custodian-run.log 
2020-04-04 10:24:03,398 - custodian.policy - DEBUG - Running policy:ec2 resource:ec2 region:us-east-1 c7n:0.9
2020-04-04 10:24:03,710 - custodian.resources.ec2 - DEBUG - Filtered from 2 to 2 ec2
2020-04-04 10:24:03,711 - custodian.policy - INFO - policy:ec2 resource:ec2 region:us-east-1 count:2 time:0.31
2020-04-04 10:43:04,608 - custodian.policy - DEBUG - Running policy:ec2 resource:ec2 region:us-east-1 c7n:0.9
2020-04-04 10:43:04,906 - custodian.resources.ec2 - DEBUG - Filtered from 2 to 2 ec2
2020-04-04 10:43:04,907 - custodian.policy - INFO - policy:ec2 resource:ec2 region:us-east-1 count:2 time:0.30
2020-04-04 10:43:48,989 - custodian.policy - DEBUG - Running policy:ec2 resource:ec2 region:us-east-1 c7n:0.9
2020-04-04 10:43:48,996 - custodian.cache - DEBUG - Using cache file /home/custodian/.cache/c7n-org/644160558196-us-east-1.cache
2020-04-04 10:43:48,996 - custodian.resources.ec2 - DEBUG - Using cached c7n.resources.ec2.EC2: 2
2020-04-04 10:43:48,997 - custodian.resources.ec2 - DEBUG - Filtered from 2 to 2 ec2
2020-04-04 10:43:48,997 - custodian.policy - INFO - policy:ec2 resource:ec2 region:us-east-1 count:2 time:0.01
```

**Comment by kapilt** [comment]
please provide a sample policy and the output of running with --debug

**Comment by jcderose** [comment]
@kapilt here's the information you requested.

```
$ docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
cloudcustodian/c7n-org   latest              3c1e46696242        13 days ago         532MB
```

**Comment by jcderose** [comment]
I'm re-running with the newest `latest` version now, too.
```
$ docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
cloudcustodian/c7n-org   latest              4c783cff4e78        About an hour ago   531MB
cloudcustodian/c7n-org   <none>              3c1e46696242        13 days ago         532MB
```

**Comment by kapilt** [comment]
@jcderose are you able to reproduce with latest image?

**Comment by jcderose** [comment]
I am not, so it looks like the latest `latest` image works. Is there a better way to keep track of these multiple different images that are all tagged as `latest`?

**Comment by kapilt** [comment]
atm, latest refers to git trunk/master, you can docker pull to have it check for latest prior to run,  else you can substitute the image id (docker run 4c783cff4e78) or git tag (docker run cloudcustodian/c7n:0.8.46.1) which are immutable. we've had discussions in other GitHub issues about having latest image tag point to last release, but that's waiting on someone willing to contribute look at how to do that with docker hub automated builds.

**Comment by jcderose** [comment]
When the git trunk/master is updated and a new `latest` build is generated, does the build also get a new release version tag? Or do the version releases get tagged via a different workflow?

**Comment by kapilt** [comment]
atm lastest is a moving symbolic target, as noted you can use the image id for a given image, which is immutable. version tags correspond to official releases and are generated by repo tags/release process. the build process is the same for both.
