### ISSUE TITLE
aws: ecr: Cannot add lifecycle rule

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5597]
**Describe the bug**
Cannot add lifecycle rule to ecr

**To Reproduce**
1. Run policy
2. See error

**Expected behavior**
Lifecycle rule is added to ecr

**Background (please complete the following information):**
 - OS: OSX 10.15
 - Custodian Version: latest using custodian-cask
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: ecr-no-lifecycle
    description: |
      Add a default ecr lifecycle policy to any ecr without a lifecycle policy
    resource: ecr
    filters:
      - type: lifecycle-rule
        state: false
    actions:
      - type: set-lifecycle
        rules:
          - rulePriority: 1
            description: "Cleans up older untagged images"
            selection:
              tagStatus: untagged
              countType: imageCountMoreThan
              # c7n requirement
              countUnit: days
              countNumber: 5
            action:
              type: expire
```
 - Traceback:
```
2020-04-15 16:03:36,504: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 323, in run
    results = a.process(resources)
  File "/src/c7n/resources/ecr.py", line 319, in process
    client.put_lifecycle_policy(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the PutLifecyclePolicy operation: Invalid parameter at 'LifecyclePolicyText' failed to satisfy constraint: 'Lifecycle policy validation failure: instance failed to match exactly one schema (matched 0 out of 2)
```

**Additional context**
Related https://github.com/cloud-custodian/cloud-custodian/issues/5593

**Comment by kapilt** [comment]
with the fix for #5993 merged you can remove the extraneous`countUnit` parameter and this should work.. ie this is more a policy issue atm.

its interesting boto has some fine grained validation here, we might want to just switch to using that with a shape validate instead of the custom stuff we're doing.

**Comment by kapilt** [comment]
confirmed working if you fix the policy, closing

**Comment by rb-nr** [comment]
without `countUnit`

**Comment by nitrocode** [comment]
without `countUnit`

```
✗ custodian-cask run -c policies/ecr-no-lifecycle.yml -s out --region ap-northeast-1 --verbose --cache-period 0
Custodian Cask 20190904.1 (cloudcustodian/c7n:latest)
Skipped image pull - Last checked 18 minutes ago.

2020-04-15 16:20:19,962: custodian.commands:ERROR invalid policy file: /home/custodian/ecr-no-lifecycle.yml error: Failed to validate policy ecr-no-lifecycle
 Error on policy:ecr-no-lifecycle resource:ecr
'countUnit' is a required property

Failed validating 'required' in schema[12]['properties']['rules']['items']['properties']['selection']:
    {'addtionalProperties': False,
     'properties': {'countNumber': {'type': 'integer'},
                    'countType': {'enum': ['imageCountMoreThan',
                                           'sinceImagePushed']},
                    'countUnit': {'enum': ['hours', 'days']},
                    'tagPrefixList': {'items': {'type': 'string'},
                                      'type': 'array'},
                    'tagStatus': {'enum': ['tagged', 'untagged', 'any']}},
     'required': ['countType', 'countUnit'],
     'type': 'object'}

On instance['rules'][0]['selection']:
    {'countNumber': 5,
     'countType': 'imageCountMoreThan',
     'tagStatus': 'untagged'}
2020-04-15 16:20:19,962: custodian.commands:ERROR Found 1 errors.  Exiting.
```
