### ISSUE TITLE
azure - ci flakey test

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5621]
I've seen this pop on occasional (1 out of a hundred), filing a bug to track. looks like a bug in the upstream sdk.

from https://github.com/cloud-custodian/cloud-custodian/runs/602042788

```
2020-04-20T14:21:33.5698570Z =================================== FAILURES ===================================
2020-04-20T14:21:33.5702440Z ______________ SessionTest.test_get_function_target_subscription _______________
2020-04-20T14:21:33.5703650Z [gw3] darwin -- Python 3.7.6 /Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/bin/python
2020-04-20T14:21:33.5703840Z Traceback (most recent call last):
2020-04-20T14:21:33.5705830Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/tools/c7n_azure/tests_azure/test_session.py", line 278, in test_get_function_target_subscription
2020-04-20T14:21:33.5706240Z     self.assertEqual(s.get_function_target_subscription_ids(), [])
2020-04-20T14:21:33.5707290Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/tools/c7n_azure/c7n_azure/session.py", line 218, in get_function_target_subscription_ids
2020-04-20T14:21:33.5707600Z     os.environ[constants.ENV_FUNCTION_MANAGEMENT_GROUP_NAME], self.get_credentials())
2020-04-20T14:21:33.5708650Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/tools/c7n_azure/c7n_azure/utils.py", line 487, in get_subscriptions_list
2020-04-20T14:21:33.5709490Z     return [e.name for e in entities if e.type == '/subscriptions']
2020-04-20T14:21:33.5710280Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/tools/c7n_azure/c7n_azure/utils.py", line 487, in <listcomp>
2020-04-20T14:21:33.5710860Z     return [e.name for e in entities if e.type == '/subscriptions']
2020-04-20T14:21:33.5711520Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
2020-04-20T14:21:33.5711680Z     self.advance_page()
2020-04-20T14:21:33.5712410Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
2020-04-20T14:21:33.5712650Z     self._response = self._get_next(self.next_link)
2020-04-20T14:21:33.5713390Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/azure/mgmt/managementgroups/operations/entities_operations.py", line 149, in internal_paging
2020-04-20T14:21:33.5713600Z     response = self._client.send(request, stream=False, **operation_config)
2020-04-20T14:21:33.5714270Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/service_client.py", line 336, in send
2020-04-20T14:21:33.5714950Z     pipeline_response = self.config.pipeline.run(request, **kwargs)
2020-04-20T14:21:33.5715680Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
2020-04-20T14:21:33.5715930Z     return first_node.send(pipeline_request, **kwargs)  # type: ignore
2020-04-20T14:21:33.5716600Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
2020-04-20T14:21:33.5716790Z     response = self.next.send(request, **kwargs)
2020-04-20T14:21:33.5717430Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 65, in send
2020-04-20T14:21:33.5717620Z     self._creds.signed_session(session)
2020-04-20T14:21:33.5718290Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 200, in signed_session
2020-04-20T14:21:33.5718530Z     self.set_token() # Adal does the caching.
2020-04-20T14:21:33.5719530Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 362, in set_token
2020-04-20T14:21:33.5719780Z     super(ServicePrincipalCredentials, self).set_token()
2020-04-20T14:21:33.5720510Z   File "/Users/runner/runners/2.169.0/work/cloud-custodian/cloud-custodian/.tox/py37/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 187, in set_token
2020-04-20T14:21:33.5720700Z     if not self._context:
2020-04-20T14:21:33.5721220Z AttributeError: 'ServicePrincipalCredentials' object has no attribute '_context'
2020-04-20T14:21:33.5721770Z ----------------------------- Captured stderr call -----------------------------
2020-04-20T14:21:33.5722370Z Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
2020-04-20T14:21:33.5722920Z Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
2020-04-20T14:21:33.5723450Z Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
2020-04-20T14:21:33.5724000Z ------------------------------ Captured log call -------------------------------
2020-04-20T14:21:33.5724590Z INFO     custodian.azure.session:session.py:115 Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
2020-04-20T14:21:33.5725180Z INFO     custodian.azure.session:session.py:115 Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
2020-04-20T14:21:33.5725740Z INFO     custodian.azure.session:session.py:115 Authenticated [Principal | ea42f556-5106-4743-99b0-c129bfa71a47]
```

**Comment by kapilt** [comment]
going through this test its doing a good amount of monkey patching on globals (env-vars) which maybe causing issues with the other session credential modifying the azure tests are doing (coupled with thread usage). unfortunately the pytest --count / repeat plugin doesn't work with unit test based classes, so its hard to run in a loop till failure is triggered.

**Comment by kapilt** [comment]
@logachev @stefangordon if either of you have a chance to look at this some additional eyes would be appreciated.

**Comment by kapilt** [comment]
happened again in https://github.com/cloud-custodian/cloud-custodian/pull/5564/checks?check_run_id=625725566

**Comment by stefangordon** [comment]
Just glancing at it briefly, perhaps we just need to add one more patch on the top of the test there?

Seems via some path it intermittently ends up calling `set_token()` on the `ServicePrincipalCredentials` which requires `self._context` but `self._context` is only created in the `__init__` which we patch away at the start of the test.

If we can patch `set_token` or `_context` it should be ok?

**Comment by logachev** [comment]
I'll take a look tomorrow.

**Comment by kapilt** [comment]
seems to be happening more frequently then noted originally, re one from today https://github.com/cloud-custodian/cloud-custodian/pull/5408/checks?check_run_id=633298601

**Comment by JohnHillegass** [comment]
I just got one today too 
https://github.com/cloud-custodian/cloud-custodian/runs/634333341

**Comment by kapilt** [comment]
and again https://github.com/cloud-custodian/cloud-custodian/pull/5686/checks?check_run_id=634540477

I'm disabling this test, in my next pr

**Comment by h-dub** [comment]
I was able to reproduce this after about 20mins of running tox in a loop @ 32cores.

**Comment by h-dub** [comment]
was able to narrow it down to the 2 unused patches of ServicePrincipalCredentials.__init__  in test_azure_utils.py and test_handler.py

Without these 2 patches, all other patches of this method are happening in the same thread of execution and should be stable.
PR pending the CI stress running more than 2 hours without exploding in a ball of fire :)

**Comment by stefangordon** [comment]
@logachev In case he has any info, I think he wrote those

**Comment by kapilt** [comment]
seems to be resolved, closing.
