### ISSUE TITLE
github actions - cache failures

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#5664]
```
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/2c4ed222-ac5c-466d-b163-19853e6fd4a2/cache.tgz -C /home/runner/work/cloud-custodian/cloud-custodian/.tox/py37 .
[warning]Cache service responded with 500 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

**Comment by kapilt** [comment]
i reported upstream, and its resolved now.
https://github.com/actions/cache/issues/282
