### ISSUE TITLE
aws - glue-catalog filter 'or' comparison error

### ISSUE THREAD

**Issue by soncaocc** [cloud-custodian/cloud-custodian#5698]
**Describe the bug**
The glue-catalog filters seem to fail when an `-or` comparison is in use.

**To Reproduce**
Perform a dry run of a policy using `-or` on resource glue-catalog (see policy below).

**Expected behavior**
Glue: [get_data_catalog_encryption_settings](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_data_catalog_encryption_settings) returns the following:

```
{
    'DataCatalogEncryptionSettings': {
        'EncryptionAtRest': {
            'CatalogEncryptionMode': 'DISABLED'|'SSE-KMS',
            'SseAwsKmsKeyId': 'string'
        },
        'ConnectionPasswordEncryption': {
            'ReturnConnectionPasswordEncrypted': True|False,
            'AwsKmsKeyId': 'string'
        }
    }
}
```
I expect to be able to filter for either CatalogEncryptionMode:DISABLED or ReturnConnectionPasswordEncrypted:False. 

The policy is successful when I remove `-or` and filter for only one of the properties.

**Background (please complete the following information):**
 - OS: OSX 10.14
 - Python Version: 3.7.6
 - Custodian Version: 0.9.1
 - Tool Version: [N/A]
 - Cloud Provider: aws
 - Policy: 
```yaml
policies:
  - name: glue-catalog-encrypted
    resource: glue-catalog
    tags:
      - "whatever"
      - "whateverwhatever"
    description:
      Enable data at rest encryption for AWS Glue data catalog if the setting is disabled
    filters:
      - or:
        - type: value
          key: DataCatalogEncryptionSettings.EncryptionAtRest.CatalogEncryptionMode
          op: eq
          value: DISABLED
        - type: value
          key: DataCatalogEncryptionSettings.ConnectionPasswordEncryption.ReturnConnectionPasswordEncrypted
          op: eq
          value: false
```
 - Traceback: [if applicable, please exclude sensitive/account information]
```
2020-05-01 15:49:42,509: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\resources\glue.py", line 516, in resources
    return self.filter_resources(self._get_catalog_encryption_settings())
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\manager.py", line 109, in filter_resources
    resources = f.process(resources, event)
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 258, in process
    return self.process_set(resources, event)
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 270, in process_set
    resource_map = {r[rtype_id]: r for r in resources}
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 270, in <dictcomp>
    resource_map = {r[rtype_id]: r for r in resources}
KeyError: 'CatalogId'
2020-05-01 15:49:42,512: custodian.commands:ERROR Error while executing policy glue-catalog-encrypted, continuing
Traceback (most recent call last):
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\commands.py", line 281, in run
    policy()
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\policy.py", line 1056, in __call__
    resources = PullMode(self).run()
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\resources\glue.py", line 516, in resources
    return self.filter_resources(self._get_catalog_encryption_settings())
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\manager.py", line 109, in filter_resources
    resources = f.process(resources, event)
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 258, in process
    return self.process_set(resources, event)
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 270, in process_set
    resource_map = {r[rtype_id]: r for r in resources}
  File "c:\users\username\.virtualenvs\c7n-0.9.1-4h5kzyle\lib\site-packages\c7n\filters\core.py", line 270, in <dictcomp>
    resource_map = {r[rtype_id]: r for r in resources}
KeyError: 'CatalogId'
```

 - `custodian version --debug` output
```
Custodian:   0.9.1
Python:      3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Platform:   win32
Using venv:  True
Docker: False
Installed:

argcomplete==1.11.1
attrs==19.3.0
boto3==1.12.47
botocore==1.15.47
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.9.5
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==46.1.3
six==1.14.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```
**Additional context**

**Comment by PratMis** [comment]
Thanks for reporting this! Glue catalog is a resource that's different than other resources. As of now, there can be only one catalog resource per account(might change in future). Also, get_data_catalog_encryption_settings() doesn't expose any resource id which seems to be required for `or` boolean operation. 
Reading the boto docs, the default value of `CatalogId` is taken as AWS account ID (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_data_catalog_encryption_settings). I'm assuming it might be safe to append `CatalogId = account_id` to the resource if its absent which will fix usage of boolean operators. 
Lets wait for @kapilt to chime in!!
