### ISSUE TITLE
aws_xray_sdk.core.exceptions.exceptions.AlreadyEndedException: Already ended segment and subsegment cannot be modified.

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5740]
**Describe the bug**
aws_xray_sdk.core.exceptions.exceptions.AlreadyEndedException: Already ended segment and subsegment cannot be modified.

**To Reproduce**
See traceback below with command

**Expected behavior**
Lambda deployed without error

**Background (please complete the following information):**

```yaml
policies:
  - name: iam-user-hubfinding-remediate-disable
    description: SecurityHub finding filter for calls from malicious IPs with action of removing-keys
    resource: iam-user
    mode:
        type: hub-finding
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        member-role: arn:aws:iam::{account_id}:role/CloudCustodianMember
        memory: 128
        concurrency: 1
        tags:
          CostCenter: SecurityHubWorkshop
          CreatedBy: CloudCustodian
        pattern:
          detail:
            findings:
              Resources:
                "Type": ["AwsIamUser"]
              "Types": ["TTPs/UnauthorizedAccess:IAMUser-MaliciousIPCaller"]
    actions:
      - type: remove-keys
        disable: true

```
 - Traceback: [if applicable, please exclude sensitive/account information]
```
$ custodian run -s /tmp --trace xray iam-user-hubfinding-remediate-disable.yml
2020-05-09 16:20:44,245: aws_xray_sdk.core.patcher:INFO successfully patched module requests
2020-05-09 16:20:44,248: aws_xray_sdk.core.patcher:INFO successfully patched module botocore
2020-05-09 16:20:44,485: custodian.policy:INFO Provisioning policy lambda: iam-user-hubfinding-remediate-disable region: us-east-1
2020-05-09 16:20:45,376: custodian.commands:ERROR Error while executing policy iam-user-hubfinding-remediate-disable, continuing
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/c7n/commands.py", line 281, in run
    policy()
  File "/usr/local/lib/python3.8/site-packages/c7n/policy.py", line 1060, in __call__
    resources = mode.provision()
  File "/usr/local/lib/python3.8/site-packages/c7n/policy.py", line 514, in provision
    return manager.publish(
  File "/usr/local/lib/python3.8/site-packages/c7n/ctx.py", line 115, in __exit__
    self.tracer.__exit__()
  File "/usr/local/lib/python3.8/site-packages/c7n/resources/aws.py", line 448, in __exit__
    self.emitter.flush()
  File "/usr/local/lib/python3.8/site-packages/c7n/resources/aws.py", line 305, in flush
    self.client.put_trace_segments(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/ext/botocore/patch.py", line 37, in _xray_traced_botocore
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 612, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 591, in get_frozen_credentials
    self._refresh()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 486, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 643, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/lib/python3.8/site-packages/botocore/credentials.py", line 786, in _get_credentials
    return client.assume_role(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore
    return xray_recorder.record_subsegment(
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 428, in record_subsegment
    subsegment = self.begin_subsegment(name, namespace)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 302, in begin_subsegment
    self.context.put_subsegment(subsegment)
  File "/usr/local/lib/python3.8/site-packages/c7n/resources/aws.py", line 353, in put_subsegment
    super().put_subsegment(subsegment)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 70, in put_subsegment
    entity.add_subsegment(subsegment)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/models/segment.py", line 88, in add_subsegment
    super(Segment, self).add_subsegment(subsegment)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/models/entity.py", line 78, in add_subsegment
    self._check_ended()
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/models/entity.py", line 283, in _check_ended
    raise AlreadyEndedException("Already ended segment and subsegment cannot be modified.")
aws_xray_sdk.core.exceptions.exceptions.AlreadyEndedException: Already ended segment and subsegment cannot be modified.
```

```
$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.1
Python:      3.8.2 (default, Mar 11 2020, 00:29:50) 
             [Clang 11.0.0 (clang-1100.0.33.17)]
Platform:    posix.uname_result(sysname='Darwin', nodename='masked, release='19.4.0', version='Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.11.1
attrs==19.3.0
boto3==1.12.47
botocore==1.15.49
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.9.5
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==46.0.0
six==1.14.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```

**Additional context**

**Comment by kapilt** [comment]
what version aws-xray-sdk do you have? we do need the recent 2.5.0, previously we have various work arounds enabled xray

running your policy works out of the box

```
$ custodian run -c xray.yml -s out -v --trace xray 
2020-05-10 12:10:02,093: custodian.commands:DEBUG Loaded file xray.yml. Contains 1 policies
2020-05-10 12:10:02,104: custodian.aws:DEBUG using default region:us-east-1 from boto
2020-05-10 12:10:02,227: aws_xray_sdk.core.patcher:INFO successfully patched module botocore
2020-05-10 12:10:02,253: aws_xray_sdk.core.patcher:INFO successfully patched module requests
2020-05-10 12:10:02,303: custodian.output:DEBUG Storing output with <LogFile file://out/iam-user-hubfinding-remediate-disable/custodian-run.log>
2020-05-10 12:10:02,388: custodian.policy:INFO Provisioning policy lambda: iam-user-hubfinding-remediate-disable region: us-east-1
2020-05-10 12:10:02,505: custodian.serverless:DEBUG Created custodian serverless archive size: 0.45mb
2020-05-10 12:10:02,588: custodian.serverless:INFO Publishing custodian policy lambda function custodian-iam-user-hubfinding-remediate-disable
2020-05-10 12:10:03,142: custodian.serverless:DEBUG Updating function: custodian-iam-user-hubfinding-remediate-disable concurrency
2020-05-10 12:10:03,413: custodian.serverless:DEBUG Creating cwe rule for <CWEvent Type:hub-finding Events:>
2020-05-10 12:10:03,641: custodian.serverless:DEBUG Added lambda invoke cwe rule permission
2020-05-10 12:10:03,660: custodian.serverless:DEBUG Creating cwe rule target for <CWEvent Type:hub-finding Events:> on func:arn:aws:lambda:us-east-1:644160558196:function:custodian-iam-user-hubfinding-remediate-disable
2020-05-10 12:10:03,689: custodian.serverless:DEBUG Added event source: <CWEvent Type:hub-finding Events:> to function: arn:aws:lambda:us-east-1:644160558196:function:custodian-iam-user-hubfinding-remediate-disable
2020-05-10 12:10:03,692: custodian.output:DEBUG metric:ApiCalls Count:8 policy:iam-user-hubfinding-remediate-disable restype:iam-user
2020-05-10 12:10:03,777: custodian.aws:INFO View XRay Trace https://console.aws.amazon.com/xray/home?region=us-east-1#/traces/1-5eb8275a-944efda41a3544dab33f673f
```

**Comment by mikejgray** [comment]
I'm experiencing the same behavior, but only on the second execution. It worked fine until I tried to update my Lambdas.

FWIW the Lambda is still updating, and so is the trace. It's just the AddPermission API call that fails with a 409.
```
ResourceConflictException: An error occurred (ResourceConflictException) when calling the AddPermission operation: The statement id (custodian-ebs-mark-unattached-deletion) provided already exists. Please provide a new statement id, or remove the existing statement.
at _load_policies (commands.py:136)
at run (commands.py:282)
at __call__ (policy.py:1174)
at provision (policy.py:516)
at publish (mu.py:391)
at add (mu.py:1111)
at _api_call (client.py:316)
at _make_api_call (client.py:635)
```

```bash
**❯ custodian version --debug**
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.3
Python:      3.7.5 (default, Dec  5 2019, 09:27:32)
             [Clang 11.0.0 (clang-1100.0.33.12)]
Platform:    posix.uname_result(sysname='Darwin', nodename='hephaestus.local', release='19.5.0', version='Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed:

PyJWT==1.7.1
adal==1.2.4
antlr4-python3-runtime==4.8
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.11.1
attrs==19.3.0
azure-cli-core==2.0.81
azure-cli-nspkg==3.0.4
azure-cli-telemetry==1.0.4
azure-common==1.1.25
azure-cosmos==3.1.2
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.2.1
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.5.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.1.7
boto3==1.13.24
botocore==1.16.24
c7n==0.9.3
cachetools==4.1.0
certifi==2020.4.5.2
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
cryptography==2.9.2
distlib==0.3.0
docutils==0.15.2
google-api-core==1.19.1
google-api-python-client==1.9.1
google-auth==1.16.1
google-auth-httplib2==0.0.3
google-cloud-core==1.3.0
google-cloud-logging==1.15.0
google-cloud-monitoring==0.34.0
googleapis-common-protos==1.52.0
httplib2==0.18.1
humanfriendly==4.18
idna==2.9
importlib-metadata==1.6.1
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
knack==0.6.3
msrest==0.6.15
msrestazure==0.6.3
netaddr==0.7.19
oauthlib==3.1.0
paramiko==2.7.1
portalocker==1.7.0
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pygments==2.6.1
pyjwt==1.7.1
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
ratelimiter==1.2.0.post0
requests==2.23.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.0
s3transfer==0.3.3
setuptools==41.2.0
six==1.15.0
tabulate==0.8.7
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.25.9
wheel==0.30.0
zipp==3.1.0

**❯ pip freeze | grep xray**
aws-xray-sdk==2.6.0
```
