### ISSUE TITLE
InvalidOutputConfig using xray mode active

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5741]
**Describe the bug**
  File "/var/task/c7n/output.py", line 62, in select
    raise InvalidOutputConfig("Invalid %s: %s" % (
and rest of the stacktrace provided below is found is cloudwatch log for the policy provided below within about 10 mins of running step #2.  

Note to repeat results from #2 will need to first archive the guard duty finding, example provided in step 3 of https://github.com/aws-samples/aws-securityhub-automated-remediations-workshop/blob/master/docs/05-guardduty-iam-user.md

**To Reproduce**
1.  custodian run -s /tmp --profile developer --trace xray iam-user-hubfinding-remediate-disable.yml 
2.  aws guardduty create-sample-findings --detector-id `aws guardduty list-detectors --query DetectorIds --output text` --finding-types 'UnauthorizedAccess:IAMUser/MaliciousIPCaller'

**Background (please complete the following information):**

```yaml
policies:
  - name: iam-user-hubfinding-remediate-disable
    description: SecurityHub finding filter for calls from malicious IPs with action of removing-keys
    resource: iam-user
    mode:
        type: hub-finding
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        member-role: arn:aws:iam::{account_id}:role/CloudCustodianMember
        memory: 128
        tags:
          CostCenter: SecurityHubWorkshop
          CreatedBy: CloudCustodian
        pattern:
          detail:
            findings:
              Resources:
                "Type": ["AwsIamAccessKey"]
              "Types": ["TTPs/UnauthorizedAccess:IAMUser-MaliciousIPCaller"]
              Severity:
                Label: ["MEDIUM", "HIGH", "CRITICAL"]
        tracing_config:
          Mode: Active
    actions:
      - type: remove-keys
        disable: true

```
 - Traceback: 
```
[ERROR] InvalidOutputConfig: Invalid c7n.output.tracer: xray
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 170, in dispatch_event
    policies = PolicyCollection.from_data(policy_data, policy_config)
  File "/var/task/c7n/policy.py", line 87, in from_data
    policies = [Policy(p, options, session_factory=sf)
  File "/var/task/c7n/policy.py", line 87, in <listcomp>
    policies = [Policy(p, options, session_factory=sf)
  File "/var/task/c7n/policy.py", line 881, in __init__
    self.ctx = ExecutionContext(self.session_factory, self, self.options)
  File "/var/task/c7n/ctx.py", line 54, in __init__
    self.tracer = tracer_outputs.select(self.options.tracer, self)
  File "/var/task/c7n/output.py", line 62, in select
    raise InvalidOutputConfig("Invalid %s: %s" % (
END RequestId: 5efdded4-68cf-4cc6-9ffe-68e26df07bd5
REPORT RequestId: 5efdded4-68cf-4cc6-9ffe-68e26df07bd5	Duration: 18.58 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 77 MB	
XRAY TraceId: 1-5eb72914-bc66a19256b6971e84000e5a	SegmentId: 38a96e257cefea21	Sampled: true	
```

```
Custodian:   0.9.1
Python:      3.8.2 (default, Mar 11 2020, 00:29:50) 
             [Clang 11.0.0 (clang-1100.0.33.17)]
Platform:    posix.uname_result(sysname='Darwin', nodename='masked', release='19.4.0', version='Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.11.1
attrs==19.3.0
boto3==1.12.47
botocore==1.15.49
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.9.5
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==46.0.0
six==1.14.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```
**Additional context**

**Comment by kapilt** [comment]
xray sdk is not included by default in custodian lambda policies, it requires a packages declaration under mode

```
mode:
   packages: [aws_xray_sdk]
```

**Comment by FireballDWF** [comment]
I see the changes it the linked draft PR and makes sense and will make this much easier to use.  Thank you!
