### ISSUE TITLE
EBS  modify_ebs_default_kms_key_id exiting with errors

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5758]
**Describe the bug**
When try to modify ebs default kms key Id policy is exiting with keyError; account_id

**To Reproduce**
policies:
  - name: set-default-ebs-encryption
    resource: aws.account
    description: |
       Enable ebs encryption by default.
    filters:
      - type: default-ebs-encryption
        key: "alias/aws/ebs"
        state: true
    actions:
      - type: set-ebs-encryption
        state: true
        key: alias/Standard-Key

**Expected behavior**
If the ebs default encryption is using default KMS Key, need to modify the Kms key with a different key

**Background (please complete the following information):**
 - OS: amazon linux2
 - Python Version:  python 3.8.1
 - Custodian Version:  0.8.46.1 & 0.9.1
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: set-default-ebs-encryption
    resource: aws.account
    description: |
       Enable ebs encryption by default.
    filters:
      - type: default-ebs-encryption
        key: "alias/aws/ebs"
        state: true
    actions:
      - type: set-ebs-encryption
        state: true
        key: alias/Standard-Key
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

```
Traceback (most recent call last):
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/commands.py", l ine 281, in run
policy()
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/policy.py", lin e 1065, in call
resources = mode.run()
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/policy.py", lin e 291, in run
resources = self.policy.resource_manager.resources()
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/resources/accou nt.py", line 89, in resources
return self.filter_resources([get_account(self.session_factory, self.config) ])
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/manager.py", li ne 109, in filter_resources
resources = f.process(resources, event)
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/resources/accou nt.py", line 1407, in process
if not vf.process([{'KmsKeyId': key}]):
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/filters/kms.py" , line 55, in process
return [r for r in resources if self.process_resource(r, related)]
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/filters/kms.py" , line 55, in <listcomp>
return [r for r in resources if self.process_resource(r, related)]
File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/filters/related .py", line 90, in process_resource
resource[model.id],
KeyError: 'account_id'
```
**Additional context**
Tested in both Custodian version 0.8.46 & 0.9.1 with same error.

**Comment by kapilt** [comment]
so we a handful of resources that are special, account being the most commonly used of them, and needing special handling in its kms-key filter / related filter.

**Comment by SonamChhetri** [comment]
Any update in this issue ?

**Comment by alfredgamulo** [comment]
As of version `0.9.11`, this appears to be resolved. The policy described correctly sets the default encryption key to the specified customer managed key.

**Comment by alfredgamulo** [comment]
Since I last tested this under the version `0.9.11` and that version was just released, I am closing this issue. Please let me know if you have any concerns.
