### ISSUE TITLE
Filtering elastic IP addresses that do not have AllocationId causing stack trace

### ISSUE THREAD

**Issue by rafe-delphix** [cloud-custodian/cloud-custodian#5812]
**Describe the bug**

There are some elastic IP addresses that do not have allocation IDs. This may be because they are EC2 classic instances and/or elastic IP addresses. The presence of these elastic IP addresses will cause an unhandled KeyError to occur during query.

**To Reproduce**

Run cloud custodian against an AWS account or region that has an elastic IP address that does not have an allocation ID.

**Expected behavior**

It is expected that elastic IP addresses that do not have allocation IDs can be included in part of a c7n policy. The presence of these elastic IP addresses should not cause an unhandled KeyError.

**Background (please complete the following information):**
 - OS: Lambda
 - Python Version: 3.8
 - Custodian Version: 0.9.2
 - Tool Version: N/A
 - Cloud Provider: AWS
 - Policy:
```yaml
#
# Copyright (c) 2019, 2020 by Delphix. All rights reserved.
#
#
# This policy releases Elastic IPs that match the following criteria:
#
# - Not all mandatory tags are present (Owner / Project / Expiration / CostCenter)
# - Not in use (not attached)

policies:
  - name: delete-noncompliant-elastic-ips
    comment: Release Elastic IPs not related to dcenter and not used
    resource: network-addr
    mode:
      type: periodic
      schedule: "cron(57 * * * ? *)"
      role: arn:aws:iam::{account_id}:role/CloudCustodian
    filters:
      # Only elastic-ips with missing mandatory tags are included
      - or:
        - "tag:dlpx:Owner": absent
        - "tag:dlpx:Project": absent
        - "tag:dlpx:Expiration": absent
        - "tag:dlpx:CostCenter": absent
    actions:
#     - type: release
        # Only release unattached elastic IPs (https://cloudcustodian.io/docs/aws/resources/network-addr.html#release)
#       force: False
     - type: notify
       template: delphix.html
       template_format: 'html'
       priority_header: '5'
       violation_desc: "The following Elastic IPs didn't have the mandatory tags"
       action_desc: "they were released"
       subject: "DRY-RUN Policy Report: Release Elastic IPs with missing tags on {{ account }} ({{ account_id }}) - {{ region }}"
       to:
         - <excluded>
         - <excluded>
       transport:
         type: sqs
         queue: "{mailer_queue}"
```
 - Traceback:

```
[ERROR] KeyError: 'AllocationId'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 176, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1126, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 532, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 484, in resources
    resources = self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 121, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/core.py", line 289, in process
    return self.process_set(resources, event)
  File "/var/task/c7n/filters/core.py", line 306, in process_set
    resource_map = {r[rtype_id]: r for r in resources}
  File "/var/task/c7n/filters/core.py", line 306, in <dictcomp>
    resource_map = {r[rtype_id]: r for r in resources}

```
 - `custodian version --debug` output
$ custodian version --debug
```
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.2
Python:      3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
             [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='rkaplan-mbpro.lan', release='18.7.0', version='Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.11.1
attrs==19.3.0
boto3==1.13.14
botocore==1.16.14
docutils==0.15.2
importlib-metadata==1.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==46.4.0
six==1.14.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```
**Additional context**

**Comment by kapilt** [comment]
vpc is over 10 years old, many services and instance types are not available without. ie. your referencing a problem with an environment over a decade old thats strictly legacy and stuck in the past, which represents a less than 1% usage case.  we're not assuming the support burden on it trying to support that as a project. I suggest you upgrade your environment.

**Comment by kapilt** [comment]
also if you feel the need to add copyright policies in a public GitHub issue without a corresponding license, please don't bother, thats rude on so many levels.

**Comment by rafe-delphix** [comment]
The addition of the copyright issue was an oversight on my part. It was not intentional. Apologies.
