### ISSUE TITLE
" TypeError: subscribe() takes 2 positional arguments but 3 were given " when running multi account c7n-ord command

### ISSUE THREAD

**Issue by farookhus** [cloud-custodian/cloud-custodian#5863]
**Describe the bug**
Error out as " TypeError: subscribe() takes 2 positional arguments but 3 were given " after running the command "  c7n-org run -c accounts.yml -s output -u temp.yml "

**To Reproduce**
Error out as " TypeError: subscribe() takes 2 positional arguments but 3 were given " after running the command "  c7n-org run -c accounts.yml -s output -u temp.yml "

**Expected behavior**
(custodian) servername[/home/username/custodian_install/policies]$ c7n-org run -c accounts.yml -s output -u policy.yml
Traceback (most recent call last):
  File "/home/username/custodian_install/custodian/bin/c7n-org", line 8, in <module>
    sys.exit(cli())
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_org/cli.py", line 624, in run
    config, use, debug, verbose, accounts, tags, policy, policy_tags=policy_tags)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_org/cli.py", line 196, in init
    load_available()
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/resources/__init__.py", line 64, in load_available
    load_providers((provider,))
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/resources/__init__.py", line 85, in load_providers
    from c7n_azure.entry import initialize_azure
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/entry.py", line 23, in <module>
    import c7n_azure.policy
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/policy.py", line 28, in <module>
    from c7n_azure.resources.arm import ArmResourceManager
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/resources/arm.py", line 24, in <module>
    from c7n_azure.query import QueryResourceManager, QueryMeta, ChildResourceManager, TypeInfo, \
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/query.py", line 396, in <module>
    resources.subscribe(resources.EVENT_FINAL, QueryResourceManager.register_actions_and_filters)
TypeError: subscribe() takes 2 positional arguments but 3 were given

**Background (please complete the following information):**
 - OS: x86_64 x86_64 x86_64 GNU/Linux
 - Python Version: Python 3.6.8
 - Custodian Version: 0.9.3
 - Tool Version: [if applicable]
 - Cloud Provider: AWS
 - Policy: my-policy
policies: 
policies:
  - name: my-policy
    resource: ec2
    filters:
       - "tag:custodian_xxxxx": absent

 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

Custodian:   0.9.3
Python:      3.6.8 (default, Apr  2 2020, 13:34:55)
             [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Platform:    posix.uname_result(sysname='Linux', nodename='xxxxx', release='3.10.0-1127.8.2.el7.x86_64', version='#1 SMP Tue May 12 16:57:42 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed:

Traceback (most recent call last):
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/cli.py", line 362, in main
    command(config)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/commands.py", line 549, in version_cmd
    found = load_available(resources=False)
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/resources/__init__.py", line 64, in load_available
    load_providers((provider,))
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n/resources/__init__.py", line 85, in load_providers
    from c7n_azure.entry import initialize_azure
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/entry.py", line 23, in <module>
    import c7n_azure.policy
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/policy.py", line 28, in <module>
    from c7n_azure.resources.arm import ArmResourceManager
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/resources/arm.py", line 24, in <module>
    from c7n_azure.query import QueryResourceManager, QueryMeta, ChildResourceManager, TypeInfo, \
  File "/home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/query.py", line 396, in <module>
    resources.subscribe(resources.EVENT_FINAL, QueryResourceManager.register_actions_and_filters)
TypeError: subscribe() takes 2 positional arguments but 3 were given
> /home/username/custodian_install/custodian/lib64/python3.6/site-packages/c7n_azure/query.py(396)<module>()
-> resources.subscribe(resources.EVENT_FINAL, QueryResourceManager.register_actions_and_filters)

**Comment by kapilt** [comment]
you have a mismatched install, with a new version of c7n package, but an older c7n_azure package. updating your install should resolve, pip install -U c7n_azure

**Comment by farookhus** [comment]
I ran " pip install -U c7n_azure " as well as " pip uninstall c7n_azure " , none of them helped. I'm getting the same error. I'm not using the Azure for now, but got plans to use in future.

**Comment by farookhus** [comment]
@kapilt I was able to resolve this after uninstall of "pip uninstall c7n_gcp" too. Thanks for your quick intervention on this.
