### ISSUE TITLE
New format ecs arn required

### ISSUE THREAD

**Issue by joeystevens00** [cloud-custodian/cloud-custodian#5881]
**Describe the bug**
During execution of a policy for ECS Service cloudtrail event the IDs found aren't being counted as resources because of an error:

```
[INFO]	2020-06-22T20:25:10.399Z	3f61472f-2af7-423f-82f0-95c63071a841	Found resource ids:['arn:aws:ecs:us-east-1:123456789012:service/cloudcustodian']

[ERROR] PolicyExecutionError: New format ecs arn required
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 176, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1135, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 444, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 639, in resolve_resources
    return super().resolve_resources(event)
  File "/var/task/c7n/policy.py", line 426, in resolve_resources
    resources = self.policy.resource_manager.get_resources(resource_ids)
  File "/var/task/c7n/resources/ecs.py", line 177, in get_resources
    return super(Service, self).get_resources(ids, cache, augment=False)
  File "/var/task/c7n/query.py", line 543, in get_resources
    resources = self.source.get_resources(ids)
  File "/var/task/c7n/resources/ecs.py", line 105, in get_resources
    raise PolicyExecutionError("New format ecs arn required")

```

**Expected behavior**
Looks like that error comes from [here](https://github.com/cloud-custodian/cloud-custodian/blob/92d4340fd3641ebcce905a3c3070cd93cab9addb/c7n/resources/ecs.py#L94) and the docstring includes a link to a dead page in the documentation https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-resource-ids.html. I'm not sure how it expects the ID to be passed, so either a more helpful error or no error.

**Background (please complete the following information):**
 - OS: Docker cloudcustodian/c7n:0.9.3.0
 - Python Version: python 3.8
 - Custodian Version: 0.9.3.0
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
- name: notify-ecs-service-update
  resource: aws.ecs-service
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/custodian
    events:
      - event: UpdateService
        ids: "responseElements.service.serviceArn"
        source: ecs.amazonaws.com
  actions:
    - type: notify
      template: default
      priority_header: '3'
      subject: "ECS Service Update [custodian {{ account }} - {{ region }}]"
      slack_template: slack_info
      message: "ECS Service Update"
      to:
        - slack://#channel
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/{account_id}/cloud-custodian-mailer
```

**Comment by nitrocode** [comment]
I'm writing a similar policy. If you're not planning on tagging the task/service/cluster, why should using the new arn format matter ?
