### ISSUE TITLE
Lambda CloudTrail policy errors out on checking tags

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5886]
**Describe the bug**
When running a policy to check for lambda access keys in the functions environmental variables, it errors out trying to get the functions tag keys it appears based on the traceback

**To Reproduce**
Running a lambda policy which triggers on the CloudTrail event UpdateFunctionConfiguration20150331v2 which then checks tag values is erroring out. 

**Expected behavior**
Expecting it to verify a tag value when someone updates their lambda function and then check the environmental variables

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15] Ubuntu v20
 - Python Version: [e.g. python 3.8.1] 3.8.1
 - Custodian Version: [e.g. 0.8.46.1] 0.9.1.0
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure] aws
 - Policy: 
```
- name: lambda-ak-in-env-variables-mark
  description: |
      Finds new lambda functions which have a AWS access key in their 
      environmental variables and marks them for deletion and
      notifies the owner
  resource: lambda
  mode:
      type: cloudtrail
      events:
        - source: lambda.amazonaws.com
          event: UpdateFunctionConfiguration20150331v2
          ids: "requestParameters.functionName"
      packages:
        - botocore
        - boto3
        - urllib3
        - certifi
  filters:
      - "tag:CreationDate": present
      - type: value
        value_type: date
        key: "tag:CreationDate"
        op: greater-than
        value: "2020/06/11"
      - or:
          - type: value
            key: Environment.Variables.[*][0][0]
            op: regex
            value: "^AKIA[0-9A-Z]{16}$"

```
 - Traceback: 
```
[ERROR]	2020-06-23T16:16:30.672Z	a81a00ba-b205-4601-b35f-e6fc58cc3bc9	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 176, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1030, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 448, in run
    resources = self.policy.resource_manager.filter_resources(
  File "/var/task/c7n/manager.py", line 109, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/core.py", line 499, in process
    return super(ValueFilter, self).process(resources, event)
  File "/var/task/c7n/filters/core.py", line 197, in process
    return list(filter(self, resources))
  File "/var/task/c7n/filters/core.py", line 486, in __call__
    matched = self.match(i)
  File "/var/task/c7n/filters/core.py", line 549, in match
    r = self.get_resource_value(self.k, i)
  File "/var/task/c7n/filters/core.py", line 507, in get_resource_value
    if t.get('Key') == tk:
AttributeError: 'str' object has no attribute 'get'
```
 - `custodian version --debug` output

**Additional context**

**Comment by jtroberts83** [comment]
Sorry this has been fixed in new version, closing out
