### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by KVInventoR** [cloud-custodian/cloud-custodian#5901]
**Describe the bug**
During run policy with mark-for-op 
```
    actions:
      - type: mark-for-op
        tag: maid_status
        msg: "Doesn't meet tagging policy {op}@{action_date}"
        op: stop
        hours: 1
```
I got:
```
2020-06-27 12:47:58,150: custodian.policy:INFO policy:ec2_tags_validate_mode_cloudtrail resource:ec2 region:us-west-2 count:19 time:9.92
2020-06-27 12:47:58,166: custodian.policy:INFO policy:ec2_tags_compliance_unmark resource:ec2 region:us-west-2 count:8 time:0.01
2020-06-27 12:47:58,181: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/resources/ec2.py", line 150, in resources
    return super(EC2, self).resources(query=query)
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/query.py", line 507, in resources
    resources = self.filter_resources(resources)
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/manager.py", line 121, in filter_resources
    resources = f.process(resources, event)
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/filters/core.py", line 217, in process
    return list(filter(self, resources))
  File "/Users/inventor/.pyenv/versions/3.8.1/envs/aws-3-8-1/lib/python3.8/site-packages/c7n/tags.py", line 339, in __call__
    return self.current_date >= (
TypeError: can't compare offset-naive and offset-aware datetimes
```
**To Reproduce**
policy with:
```
    actions:
      - type: mark-for-op
        tag: maid_status
        msg: "Doesn't meet tagging policy:  {op}@{action_date}"
        op: stop
        hours: 1
```

and next policy:
```
    actions:
      - stop
      - type: mark-for-op
        op: terminate
        days: 7
```

CC - c7n   0.9.3

During debug I found next:
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/tags.py
Line 339:
```
        return self.current_date >= (
            action_date - timedelta(days=skew, hours=skew_hours))
```
action_date  = 2020-06-24 00:00:00
self.current_date = 2020-06-28 09:45:49.116526+00:00

self.current_date used TZ, but variable action_date doesn't support TZ, 
I didn't find how self.current_date filed out by current timestamp, looks like action_date also should include by default support tz.

**Comment by kapilt** [comment]
what's the full policy?

**Comment by kapilt** [comment]
closing no response.
