### ISSUE TITLE
Cannot filter Azure object storage by UsedCapacity metric

### ISSUE THREAD

**Issue by diegolima** [cloud-custodian/cloud-custodian#5967]
**Describe the bug**
When filtering `azure.storage` resources by the `UsedCapacity` metric the following API error is received:
```
azure.mgmt.monitor.v2018_01_01.models._models_py3.ErrorResponseException: Commonly allowed time grains: 01:00:00 between metrics: UsedCapacity, can not support requsted time grain: 1.00:00:00
```

**To Reproduce**
Create a policy with the following contents:
```
- name: az-objectstorage
    resource: azure.storage
    filters:
      - type: metric
        metric: UsedCapacity
        aggregation: average
        op: gte
        threshold: 0
```

**Expected behavior**
Resources should be returned based on the metric filter

**Background (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: 3.8.2
 - Custodian Version: 0.9.2
 - Cloud Provider: azure
 - Policy: see above
 - Traceback:
```
Traceback (most recent call last):
  File "/src/tools/c7n_azure/c7n_azure/filters.py", line 192, in get_metric_data
    metrics_data = self.client.metrics.list(
  File "/usr/local/lib/python3.8/site-packages/azure/mgmt/monitor/v2018_01_01/operations/_metrics_operations.py", line 141, in list
    raise models.ErrorResponseException(self._deserialize, response)
azure.mgmt.monitor.v2018_01_01.models._models_py3.ErrorResponseException: Commonly allowed time grains: 01:00:00 between metrics: UsedCapacity, can not support requsted time grain: 1.00:00:00, TraceId: {1fdd9285-8034-400d-9294-b152c74a302d}
```

**Comment by diegolima** [comment]
I believe the API call is wrong there, using `1.00:00:00` instead of `01:00:00` for the timeGrain property

**Comment by diegolima** [comment]
I've found a solution after reading the schema: adding a `interval` to this request, as it seems that the default `PT1D` is not valid for this metric. The working policy is the following:

```
- name: az-objectstorage-inventory
    description: |
      List object storages and retrieve their space usage
    resource: azure.storage
    filters:
      - type: metric
        metric: UsedCapacity
        aggregation: average
        op: gte
        threshold: 0
        interval: PT1H
        timeframe: 1
```
