### ISSUE TITLE
Error when deploying Azure Function: ValueError: 'Embedded' is not a valid ManagedServiceIdentityType

### ISSUE THREAD

**Issue by tonyferrell** [cloud-custodian/cloud-custodian#5987]
**Describe the bug**
I am attempting to deploy an Azure Function policy following the information found [here](https://cloudcustodian.io/docs/azure/configuration/functionshosting.html#event-grid-functions). I am trying to deploy with a service principal configured  using the environment variables `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, `AZURE_SUBSCRIPTION_ID`, `AZURE_TENANT_ID`, but during deployment I receive an error:

```
msrest.exceptions.SerializationError: 'Embedded' is not valid value for enum <enum 'ManagedServiceIdentityType'>
```

**To Reproduce**
  * Check out master
  * Create policy file `my-policy.yml` with content:
```yaml
policies:
    - name: tag-key-vault-creator
      resource: azure.keyvault
      mode:
        type: azure-event-grid
        events:
          - resourceProvider: Microsoft.KeyVault/vaults
            event: write
      filters:
        - "tag:CreatorEmail": null
      actions:
        - type: auto-tag-user
          tag: CreatorEmail
```
  * run  `custodian run my-policy.yml -s out`

**Expected behavior**
Cloud Custodian Azure function is deployed.

**Background (please complete the following information):**
 - OS: OSX 10.15.5
 - Python Version: python 3.8.5
 - Custodian Version: `0.9.4` - built from master at commit `e1647a4375a5060005d79ff6a754a8ac4961da9c`
 - Cloud Provider: Azure
 - Policy: I tried with a bunch of different 
```yaml
policies:
    - name: tag-key-vault-creator
      resource: azure.keyvault
      mode:
        type: azure-event-grid
        events:
          - resourceProvider: Microsoft.KeyVault/vaults
            event: write
      filters:
        - "tag:CreatorEmail": null
      actions:
        - type: auto-tag-user
          tag: CreatorEmail
 ```
 - Traceback:
```
2020-07-27 07:24:18,458: custodian.azure.policy.AzureFunctionMode:ERROR policy:tag-key-vault-creator function policies should use UserAssigned Identities see https://cloudcustodian.io/docs/azure/configuration/functionshosting.html#authentication-options
2020-07-27 07:24:18,771: custodian.azure.session:INFO Authenticated [Principal | 673ba59b-d196-4d0d-a64a-54d5de409824]
2020-07-27 07:24:18,772: custodian.azure.policy.AzureFunctionMode:ERROR policy:tag-key-vault-creator function policies should use UserAssigned Identities see https://cloudcustodian.io/docs/azure/configuration/functionshosting.html#authentication-options
2020-07-27 07:24:19,258: custodian.azure.deployment_unit.DeploymentUnit:INFO Function Application "tag-key-vault-creator-a13f8df5" not found.
2020-07-27 07:24:19,470: custodian.azure.deployment_unit.DeploymentUnit:INFO Found Application Service Plan "cloud-custodian".
2020-07-27 07:24:19,872: custodian.azure.deployment_unit.DeploymentUnit:INFO Found Application Insights "cloud-custodian".
2020-07-27 07:24:20,216: custodian.azure.deployment_unit.DeploymentUnit:INFO Found Storage Account "custodiana13f8df5".
2020-07-27 07:24:20,425: custodian.azure.deployment_unit.DeploymentUnit:INFO Creating Function Application "tag-key-vault-creator-a13f8df5"
2020-07-27 07:24:20,427: custodian.commands:ERROR Error while executing policy tag-key-vault-creator, continuing
ValueError: 'Embedded' is not a valid ManagedServiceIdentityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 984, in serialize_enum
    enum_obj(result)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 600, in __new__
    raise exc
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'Embedded' is not a valid ManagedServiceIdentityType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anf/code/cloud-custodian/c7n/commands.py", line 282, in run
    policy()
  File "/Users/anf/code/cloud-custodian/c7n/policy.py", line 1183, in __call__
    resources = mode.provision()
  File "/Users/anf/code/cloud-custodian/tools/c7n_azure/c7n_azure/policy.py", line 448, in provision
    super(AzureEventGridMode, self).provision()
  File "/Users/anf/code/cloud-custodian/tools/c7n_azure/c7n_azure/policy.py", line 277, in provision
    self.function_app = FunctionAppUtilities.deploy_function_app(self.function_params)
  File "/Users/anf/code/cloud-custodian/tools/c7n_azure/c7n_azure/functionapp_utils.py", line 96, in deploy_function_app
    return function_app_unit.provision(function_app_params)
  File "/Users/anf/code/cloud-custodian/tools/c7n_azure/c7n_azure/provisioning/deployment_unit.py", line 30, in provision
    result = self._provision(params)
  File "/Users/anf/code/cloud-custodian/tools/c7n_azure/c7n_azure/provisioning/function_app.py", line 93, in _provision
    return self.client.web_apps.create_or_update(params['resource_group_name'],
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/azure/mgmt/web/v2019_08_01/operations/_web_apps_operations.py", line 333, in create_or_update
    raw_result = self._create_or_update_initial(
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/azure/mgmt/web/v2019_08_01/operations/_web_apps_operations.py", line 280, in _create_or_update_initial
    body_content = self._serialize.body(site_envelope, 'Site')
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 626, in body
    return self._serialize(data, data_type, **kwargs)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 483, in _serialize
    return self.serialize_data(
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 780, in serialize_data
    return self._serialize(data, **kwargs)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 780, in serialize_data
    return self._serialize(data, **kwargs)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 523, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 768, in serialize_data
    return Serializer.serialize_enum(data, enum_obj=enum_type)
  File "/Users/anf/code/cloud-custodian/lib/python3.8/site-packages/msrest/serialization.py", line 991, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'Embedded' is not valid value for enum <enum 'ManagedServiceIdentityType'>
2020-07-27 07:24:20,441: custodian.commands:ERROR The following policies had errors while executing
 - tag-key-vault-creator
```
 - `custodian version --debug` output
```
Custodian:   0.9.4
Python:      3.8.5 (default, Jul 21 2020, 10:48:26) 
             [Clang 11.0.3 (clang-1103.0.32.62)]
Platform:    posix.uname_result(sysname='Darwin', nodename='DLPVM2-MnOS-X86.corp.microsoft.com', release='19.5.0', version='Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.4
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.12.0
attrs==19.3.0
azure-cli-core==2.9.1
azure-cli-nspkg==3.0.4
azure-cli-telemetry==1.0.4
azure-common==1.1.25
azure-core==1.7.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.3.0
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.0.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.6.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.1.7
boto3==1.14.27
botocore==1.17.27
c7n==0.9.4
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
cryptography==3.0
distlib==0.3.1
docutils==0.15.2
humanfriendly==8.2
idna==2.10
importlib-metadata==1.7.0
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
knack==0.7.1
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.17
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.1
pkginfo==1.5.0.1
portalocker==1.7.1
pycparser==2.20
pygments==2.6.1
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
setuptools==47.1.0
six==1.15.0
tabulate==0.8.7
tzlocal==2.1
urllib3==1.25.10
zipp==3.1.0
```

**Additional context**
When I run `custodian validate` I get an error message, but it says the configuration is valid:
```
2020-07-27 07:48:51,231: custodian.azure.policy.AzureFunctionMode:ERROR policy:tag-key-vault-creator function policies should use UserAssigned Identities see https://cloudcustodian.io/docs/azure/configuration/functionshosting.html#authentication-options
2020-07-27 07:48:51,232: custodian.commands:INFO Configuration valid: my-policy.yml
```

Not sure if this intended to be a blocking error (which would sort of match with the actual error I'm experiencing)

**Comment by kapilt** [comment]
this was a regression in 0.9.4 there's a pr up to fix, using user assigned identity or managed system identity would also resolve in addition to downgrade to 0.9.3. The upcoming 0.9.5 release will have a fix.
