### ISSUE TITLE
Azure: c7n-mailer deployment issue.

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#6012]
Using `pip install c7n-mailer`

```
root@8b79684d85a3:/# c7n-mailer
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 5, in <module>
    from c7n_mailer.cli import main
  File "/usr/local/lib/python3.8/dist-packages/c7n_mailer/cli.py", line 9, in <module>
    from c7n_mailer import deploy, utils
  File "/usr/local/lib/python3.8/dist-packages/c7n_mailer/deploy.py", line 19, in <module>
    from c7n.mu import (
ModuleNotFoundError: No module named 'c7n'
```

Using docker image for `docker pull cloudcustodian/mailer`:

with python 3.6 and 3.8:

```
Traceback (most recent call last):
  File "/usr/local/bin/c7n-mailer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/c7n_mailer/cli.py", line 233, in main
    azure_deploy.provision(mailer_config)
  File "/usr/local/lib/python3.6/site-packages/c7n_mailer/azure_mailer/deploy.py", line 129, in provision
    function_app_name=function_app_name)
TypeError: __init__() got an unexpected keyword argument 'function_app_resource_group_name'
```

Older version from pip and docker seems to work. After doing an install:

```
c7n_1  | 2020-08-05 01:21:43,817 - custodian.azure.session - INFO - Authenticated [Principal | 12345]
c7n_1  | 2020-08-05 01:21:44,370 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Function Application "c7n-mailer-mailer-12345" not found.
c7n_1  | 2020-08-05 01:21:46,171 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Application Service Plan "c7n-mailer" not found.
c7n_1  | 2020-08-05 01:21:46,171 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Creating Application Service Plan "c7n-mailer"
c7n_1  | 2020-08-05 01:21:46,342 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Found Resource Group "cloud-custodian".
c7n_1  | 2020-08-05 01:21:55,289 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Application Service Plan "c7n-mailer" successfully created
c7n_1  | 2020-08-05 01:21:55,514 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Found Application Insights "c7n-mailer".
c7n_1  | 2020-08-05 01:21:56,189 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Found Storage Account "custodian12345".
c7n_1  | 2020-08-05 01:21:56,412 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Creating Function Application "c7n-mailer-mailer-12345"
c7n_1  | 2020-08-05 01:22:28,013 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Function Application "c7n-mailer-mailer-12345" successfully created
c7n_1  | 2020-08-05 01:22:28,013 - c7n_mailer.azure.deploy - INFO - Building function package for c7n-mailer-mailer-12345
c7n_1  | 2020-08-05 01:22:28,186 - c7n_mailer.azure.deploy - INFO - Function package built, size is 0MB
c7n_1  | 2020-08-05 01:22:28,186 - custodian.azure.function_app_utils - INFO - Publishing Function application
c7n_1  | 2020-08-05 01:22:30,016 - custodian.azure.function_package.FunctionPackage - INFO - Publishing Function package from /tmp/tmpj9auz92f
c7n_1  | 2020-08-05 01:22:31,597 - custodian.azure.function_package.FunctionPackage - INFO - Function publish result: 202
c7n_1  | 2020-08-05 01:22:31,598 - custodian.azure.function_app_utils - INFO - Finished publishing Function application
```

I am not able to see the function in Azure portal. Any pointers, please.

<img width="838" alt="Screen Shot 2020-08-04 at 6 30 14 PM" src="https://user-images.githubusercontent.com/11890959/89361673-b5a70000-d680-11ea-9415-49179b2cb783.png">

**Comment by tomarv2** [comment]
looks like an issue here, based on my understanding, it takes 4 args:

```
    class FunctionAppInfrastructureParameters:
        def __init__(self, app_insights, service_plan, storage_account,
                     function_app):
            self.app_insights = app_insights
            self.service_plan = service_plan
            self.storage_account = storage_account
            self.function_app = function_app
```

5 are getting passed:
```
    params = FunctionAppUtilities.FunctionAppInfrastructureParameters(
        app_insights=app_insights,
        service_plan=service_plan,
        storage_account=storage_account,
        function_app_resource_group_name=service_plan['resource_group_name'],
        function_app_name=function_app_name)
```

**Comment by tomarv2** [comment]
@logachev 

this is my docker-compose for mailer:

```
version: "3.4"
services:
  c7n:
    env_file:
      - .env
    image: "cloudcustodian/mailer:0.9.1.0" 
    entrypoint: 
    - /bin/bash
    - -c
    - |
      /usr/local/bin/c7n-mailer --config /tmp/mailer.yml --update-lambda
    volumes:
        - "mailer.yml:/tmp/mailer.yml"
        - "templates:/tmp/templates"
```

When I am trying to run it:
```
c7n_1  | 2020-08-05 05:14:29,226 - custodian.azure.session - INFO - Authenticated [Principal | 12345]
c7n_1  | 2020-08-05 05:14:29,813 - custodian.azure.deployment_unit.DeploymentUnit - INFO - Found Function Application "c7n-mailer-mailer-f12345".
c7n_1  | 2020-08-05 05:14:29,988 - c7n_mailer.azure.deploy - INFO - Building function package for c7n-mailer-mailer-12345
c7n_1  | 2020-08-05 05:14:30,168 - c7n_mailer.azure.deploy - INFO - Function package built, size is 0MB
c7n_1  | 2020-08-05 05:14:30,168 - custodian.azure.function_app_utils - INFO - Publishing Function application
c7n_1  | 2020-08-05 05:14:31,239 - custodian.azure.function_package.FunctionPackage - INFO - Publishing Function package from /tmp/tmp5f27m1fe
c7n_1  | 2020-08-05 05:14:33,939 - custodian.azure.function_package.FunctionPackage - INFO - Function publish result: 202
c7n_1  | 2020-08-05 05:14:33,940 - custodian.azure.function_app_utils - INFO - Finished publishing Function application
```

It shows package size is 0MB, any pointers?

**Comment by kapilt** [comment]
thanks for the detailed bug report, this is a regression in 0.9.4 from changes to azure functions to support the more secure MSI/CSI authn/authz to provide api access to functions. the mailer needs an update to redress, using the previous c7n/c7n azure/mailer releases from 0.9.3 for the moment would be the recommend.

**Comment by tomarv2** [comment]
docker run \
-e AZURE_CLIENT_ID="123" \
-e AZURE_CLIENT_SECRET="123" \
-e AZURE_SUBSCRIPTION_ID="123" \
-e AZURE_TENANT_ID="123" \
-v c7n-mailer/environments:/tmp/environments
-it cloudcustodian/mailer:0.9.3.0 -c /tmp/environments/mailer.yml --update-lambda

App service is getting deployed no issues, it created Storage account if it does not exists, Insight.. etc..
but the function is coming as blank.

Looking at the `App Service` -> `Settings` -> `Configuration`.  I don't see `WEBSITE_RUN_FROM_PACKAGE` variable.

<img width="684" alt="Screen-Shot-2020-08-11-at-2 29 32-PM" src="https://user-images.githubusercontent.com/11890959/90065089-9c194000-dca0-11ea-9ef9-d6760d728a6a.png">


Tried in two different subscriptions.

**Comment by mikefomichev** [comment]
Faced the same issue with c7n-mailer deployment to Azure.
Caught the zipped mailer project during the deployment, unzipped it, and tried to deploy the mailer using Visual Studio Code. The deployment process failed with the error:
`ERROR: Could not find a version that satisfies the requirement pkg_resources==0.0.0 (from -r requirements.txt (line 27)) (from versions: none)`
Then I commented out the line # 36 of c7n_maile/c7n_mailer/deploy.py (    # 'pkg_resources',) and was able to successfully deploy the mailer in Azure.

**Comment by kapilt** [comment]
fix merged

**Comment by stefangordon** [comment]
Discussion on Gitter that there are still lingering issues here.  I'm reopening this issue to investigate.

![image](https://user-images.githubusercontent.com/4087345/106157160-442fa200-6137-11eb-9d72-79d3f5b143f1.png)
