### ISSUE TITLE
Convert custodian policy documents into cloudformation templates for modes config-rule, config-poll-rule.

### ISSUE THREAD

**Issue by tomjones2a** [cloud-custodian/cloud-custodian#6051]
**Is your feature request related to a problem? Please describe.**
When using cloud-custodian/tools/ops/policylambda.py to convert custodian policy documents into cloudformation templates, there is missing functionality for the modes config-rule and config-poll-rule. 

**Describe the solution you'd like**
We would like cloud-custodian/tools/ops/policylambda.py to add support for modes config-rule and config-poll-rule to generate SAM/Cloudformation for Config Rules.  We need to convert custodian policies containing AWS Config Rules into cloudformation so that underlying resources can be linted and managed.

**Describe alternatives you've considered**
The main alternative would be to run direct custodian commands in a CodeBuild step instead, however this doesn't allow us to lint the resources before they are created, allow us to manage the resources, detect drift, etc. (features of cloudformation)

**Additional context**
When runnning cloud-custodian/tools/ops/policylambda.py on a custodian policy document that contains modes config-rule or config-poll-rule, the following error occurs:

Traceback (most recent call last):
  File "cloud-custodian/tools/ops/policylambda.py", line 150, in <module>
    main()
  File "cloud-custodian/tools/ops/policylambda.py", line 133, in main
    sam_func = render(p)
  File "cloud-custodian/tools/ops/policylambda.py", line 67, in render
    events = [e for e in policy_lambda.get_events(None)
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 908, in get_events
    ConfigRule(self.policy.data['mode'], session_factory))
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 1599, in __init__
    self.session = session_factory()
TypeError: 'NoneType' object is not callable

**Comment by kapilt** [comment]
contributions welcome, while I added that script as an example, our main focus is on the integrated provisioning to offer a consistent experience across providers, we already do delta provisioning wrt to changes. wrt to linting thats generally easy to achieve using custodian itself to police its own assets, and the managed aspect is what tools/ops/mugc.py is for.. unless you perhaps you had different meaning to the word.

**Comment by CYarros10** [comment]
@kapilt the existing tools are great for managing custodian separately, but for users/companies that already have infrastructure pipelines in place that build, validate, deploy, approve, and report on resources... it would be nice to utilize CC's policy language while sticking to existing deployment methods.
