### ISSUE TITLE
Add support for kinesisanalyticsv2

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#6052]
**Is your feature request related to a problem? Please describe.**
When trying to scan a Flink 1.8 kinesis data analytics app created in the console I was getting this error

```
botocore.errorfactory.UnsupportedOperationException: An error occurred (UnsupportedOperationException) when calling the DescribeApplication operation: test2 was created/updated by kinesisanalyticsv2 SDK. Please use kinesisanalyticsv2 SDK to make changes to test2.
```

It seems that these apps are getting created with the v2 SDK so need the added support to scan them

**Describe the solution you'd like**
Add a resource type for `kinesis-analytics-v2` to allow scanning and action on these resources

**Comment by kapilt** [comment]
do you have an example policy, and `custodian version --debug` output

**Comment by JohnHillegass** [comment]
## Debug Output
Custodian:   0.9.4
Python:      3.8.5 (default, Jul 21 2020, 10:48:26)
             [Clang 11.0.3 (clang-1103.0.32.62)]
Platform:    posix.uname_result(sysname='Darwin', nodename='Johns-MBP.hsd1.va.comcast.net', release='19.6.0', version='Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.27
botocore==1.17.27
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==47.1.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.1.0

## Example policy
policies:
    - name: dk
      resource: kinesis-analytics

**Comment by JohnHillegass** [comment]
> do you have an example policy, and `custodian version --debug` output

Hey @kapilt yep, just added! I am a bit confused as to why the console would decide to use v2 over v1 as the resource type.

**Comment by kapilt** [comment]
what's the full traceback?

**Comment by JohnHillegass** [comment]
> what's the full traceback?
```bash
(c7n-VLeefSBS-py3.8) phippy@Zees-MBP [20:28:14] [~/projects/policies]
-> % custodian run -s kinesis/ kinesis.yml
2020-08-20 20:28:42,810: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/phippy/projects/cloud-custodian/c7n/policy.py", line 281, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 493, in resources
    resources = self.augment(resources)
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 549, in augment
    return self.source.augment(resources)
  File "/Users/phippy/projects/cloud-custodian/c7n/resources/kinesis.py", line 238, in augment
    return universal_augment(self.manager, super().augment(resources))
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 261, in augment
    results = list(w.map(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 701, in _scalar_augment
    response = op(*args, **kw)
  File "/Users/phippy/projects/cloud-custodian/c7n/utils.py", line 363, in _retry
    return func(*args, **kw)
  File "/Users/phippy/Library/Caches/pypoetry/virtualenvs/c7n-VLeefSBS-py3.8/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/phippy/Library/Caches/pypoetry/virtualenvs/c7n-VLeefSBS-py3.8/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperationException: An error occurred (UnsupportedOperationException) when calling the DescribeApplication operation: test1 was created/updated by kinesisanalyticsv2 SDK. Please use kinesisanalyticsv2 SDK to make changes to test1.
2020-08-20 20:28:42,821: custodian.commands:ERROR Error while executing policy dk, continuing
Traceback (most recent call last):
  File "/Users/phippy/projects/cloud-custodian/c7n/commands.py", line 272, in run
    policy()
  File "/Users/phippy/projects/cloud-custodian/c7n/policy.py", line 1175, in __call__
    resources = mode.run()
  File "/Users/phippy/projects/cloud-custodian/c7n/policy.py", line 281, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 493, in resources
    resources = self.augment(resources)
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 549, in augment
    return self.source.augment(resources)
  File "/Users/phippy/projects/cloud-custodian/c7n/resources/kinesis.py", line 238, in augment
    return universal_augment(self.manager, super().augment(resources))
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 261, in augment
    results = list(w.map(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/phippy/projects/cloud-custodian/c7n/query.py", line 701, in _scalar_augment
    response = op(*args, **kw)
  File "/Users/phippy/projects/cloud-custodian/c7n/utils.py", line 363, in _retry
    return func(*args, **kw)
  File "/Users/phippy/Library/Caches/pypoetry/virtualenvs/c7n-VLeefSBS-py3.8/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/phippy/Library/Caches/pypoetry/virtualenvs/c7n-VLeefSBS-py3.8/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperationException: An error occurred (UnsupportedOperationException) when calling the DescribeApplication operation: test1 was created/updated by kinesisanalyticsv2 SDK. Please use kinesisanalyticsv2 SDK to make changes to test1.
```

**Comment by kylejohnson514** [comment]
Hi, I looked into this a little bit, mostly regarding the possible mapping of v1 and v2 resources.

Using `kinesisanalytics` boto client to call `list_applications` will retrieve all Kinesis Analytics resources, with no way to distinguish between version 1 and version 2.
Using `kinesisanalyticsv2` boto client to call `list_applications` will retrieve all of the same resources, but will also include the runtime, which we could use to manually filter out between v1 and v2 kinesis analytics resources. Boto docs here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesisanalyticsv2.html#KinesisAnalyticsV2.Client.list_applications

So, when we want to do anything with kinesis analytics, we'd need to first make a boto client using `kinesisanalyticsv2`, call `list_applications`, then assign new clients to the resource objects running older runtime envs (i.e. SQL 1.0, Flink 1.6) to use `kinesisanalytics` boto clients vs. newer runtime envs (i.e. Flink 1.8) to use `kinesisanalyticsv2` boto clients, and then the API calls will use the correct version.

It's a lot of manual mapping and exceptions that gets complex and messy pretty quickly. I was playing around with it a bit [here](https://github.com/cloud-custodian/cloud-custodian/compare/master...kylejohnson514:kinesis-analytics-v2) , though I'm currently still running into some errors.

All-in-all, I think an AWS request for the enumeration api to retrieve version-specific resources based on the API used (kinesisanalytics vs. kinesisanalyticsv2) would be the most straightforward approach.

**Comment by JohnHillegass** [comment]
Closed by https://github.com/cloud-custodian/cloud-custodian/pull/6689
