### ISSUE TITLE
Azure - Storage Account Policies Fail to Deploy

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#6060]
**Describe the bug**
I can't seem to deploy storage account policies

**To Reproduce**
Run any of the last 4 tagged releases for the docker container, deploy the policy below.

**Expected behavior**
errors dont occur when I try to deploy this, it worked before.

**Background (please complete the following information):**
 - OS: Darwin 10.15.6 and whatever is in the c7n container image
 - Python Version: 3.8.1 and 
 - Custodian Version: [e.g. 0.9.1.0 - 0.9.4.0]
 - Tool Version: [if applicable]
 - Cloud Provider: azure
 - Policy: 
```yaml
vars:
  schedules:
    mode: &azure-12h
      type: azure-periodic
      schedule: 0 0 */12 * * *
      # execution-options:
      #     output_dir: azure://xxxxxxx.blob.core.windows.net/custodian-run-logs/{policy_name}

policies:
  - name: add-storage-firewall
    mode: *azure-12h
    description: Find storage accounts without open ip list and restrict them.
    resource: azure.storage
    filters:
    - type: value
      key: properties.networkAcls.ipRules
      value_type: size
      op: eq
      value: 0
```
 - Traceback:
```yaml
2020-08-21 17:46:33,280: custodian.commands:ERROR Error while executing policy add-storage-firewall, continuing
Traceback (most recent call last):
  File "/src/c7n/commands.py", line 281, in run
    policy()
  File "/src/c7n/policy.py", line 1060, in __call__
    resources = mode.provision()
  File "/src/tools/c7n_azure/c7n_azure/policy.py", line 329, in provision
    FunctionAppUtilities.publish_functions_package(self.function_params, package)
  File "/src/tools/c7n_azure/c7n_azure/functionapp_utils.py", line 124, in publish_functions_package
    package.publish(publish_creds)
  File "/src/tools/c7n_azure/c7n_azure/function_package.py", line 196, in publish
    r.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://$add-storage-firewall-alongstringhere@add-storage-firewall-xxxxxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&synctriggers=true
```

**Additional context**

**Comment by h-dub** [comment]
Thank you for the report. I am not able to reproduce this on the master branch.
This error message is related to deployment of the function app that is triggering the repeated policy execution.
409 can mean that the attempted deployment is conflicting with a deployment that is already in progress. I have seen delays several mins for the portal to sync up and show all the pending deployments.
Deleting the function app that was created, waiting for 10mins, and running again might resolve the problem if it is still occurring.

**Comment by kapilt** [comment]
its possible if this was an upgrading a previously deployed function that the platform might not upgrade in place and the function needs to be re-created on a current release (0.9+).

**Comment by stefangordon** [comment]
409 on zip deploy can likely only be resolved by waiting or deleting the function (if it is doing this after ~10 minutes have passed).   This is Azure saying the function is either still deploying or Kudu is in a cool-off period after a deployment failure.

Let me know if you have still had ongoing issues this last month.
