### ISSUE TITLE
Unable to Read Gov Subscription

### ISSUE THREAD

**Issue by SuperTonic09** [cloud-custodian/cloud-custodian#6072]
**Describe the bug**
Getting an error when attempting to read government subscription.

**To Reproduce**
```
az cloud set --name AzureUSGovernment
az account set —subscription <SubID>
custodian run --dryrun -s . test.yml 
2020-08-25 20:44:01,202: custodian.azure.session:INFO Authenticated [Azure CLI | <SubID>]
2020-08-25 20:44:01,281: custodian.azure.query:ERROR Failed to query resource.
Type: azure.vm.
Error: Azure Error: SubscriptionNotFound
Message: The subscription '<SubID>' could not be found.
2020-08-25 20:44:01,282: custodian.output:ERROR Error while executing policy
[…]
```

**Expected behavior**
2020-08-25 16:59:01,596: custodian.azure.session:INFO Authenticated [Azure CLI | <SubID>]
2020-08-25 16:59:03,275: custodian.policy:INFO policy:test-policy resource:azure.vm region: count:2 time:1.68

**Background (please complete the following information):**
 - OS: Linux (ubuntu 18.04)
 - Python Version: 3.6.9
 - Custodian Version: 0.9.4
 - Tool Version: "azure-cli": "2.10.1"
 - Cloud Provider: Azure
 - Policy:
```yaml
policies:
  - name: test-policy 
    resource: azure.vm
    filters:
     - type: network-interface
       key: 'properties.ipConfigurations[].properties.publicIPAddress.id'
       value: not-null

```
 - Traceback: [if applicable, please exclude sensitive/account information]
```
Traceback (most recent call last):
  File "/home/custodian/cloud-custodian/c7n/policy.py", line 281, in run
    resources = self.policy.resource_manager.resources()
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 275, in resources
    resources = self.augment(self.source.get_resources(query))
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 80, in get_resources
    return self.query.filter(self.manager)
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 47, in filter
    return [r.serialize(True) for r in result]
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 47, in <listcomp>
    return [r.serialize(True) for r in result]
  File "/home/custodian/custodian/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/custodian/custodian/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/custodian/custodian/lib/python3.6/site-packages/azure/mgmt/compute/v2019_07_01/operations/_virtual_machines_operations.py", line 982, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound
Message: The subscription '<SubID>' could not be found.
2020-08-25 20:44:01,283: custodian.commands:ERROR Error while executing policy test-policy, continuing
Traceback (most recent call last):
  File "/home/custodian/cloud-custodian/c7n/commands.py", line 272, in run
    policy()
  File "/home/custodian/cloud-custodian/c7n/policy.py", line 1169, in __call__
    resources = PullMode(self).run()
  File "/home/custodian/cloud-custodian/c7n/policy.py", line 281, in run
    resources = self.policy.resource_manager.resources()
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 275, in resources
    resources = self.augment(self.source.get_resources(query))
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 80, in get_resources
    return self.query.filter(self.manager)
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 47, in filter
    return [r.serialize(True) for r in result]
  File "/home/custodian/cloud-custodian/tools/c7n_azure/c7n_azure/query.py", line 47, in <listcomp>
    return [r.serialize(True) for r in result]
  File "/home/custodian/custodian/lib/python3.6/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/custodian/custodian/lib/python3.6/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/custodian/custodian/lib/python3.6/site-packages/azure/mgmt/compute/v2019_07_01/operations/_virtual_machines_operations.py", line 982, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: SubscriptionNotFound
Message: The subscription '<SubID>' could not be found.
2020-08-25 20:44:01,284: custodian.commands:ERROR The following policies had errors while executing
 - test-policy
```
 - `custodian version --debug` output
```
Custodian:   0.9.4
Python:      3.6.9 (default, Jul 17 2020, 12:50:27) 
             [GCC 8.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='gsa-cc-vm01', release='5.3.0-1035-azure', version='#36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.4
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.12.0
attrs==19.3.0
azure-cli-core==2.10.1
azure-cli-nspkg==3.0.4
azure-cli-telemetry==1.0.4
azure-common==1.1.25
azure-core==1.8.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.3.0
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.0.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.6.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.1.7
boto3==1.14.40
botocore==1.17.40
c7n==0.9.4
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==7.1.2
colorama==0.4.3
cryptography==3.0
distlib==0.3.1
docutils==0.15.2
humanfriendly==8.2
idna==2.10
importlib-metadata==1.7.0
importlib-resources==3.0.0
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
knack==0.7.2
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.18
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.1
pkginfo==1.5.0.1
portalocker==1.7.1
pycparser==2.20
pygments==2.6.1
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
setuptools==39.0.1
six==1.15.0
tabulate==0.8.7
tzlocal==2.1
urllib3==1.25.10
zipp==3.1.0
```
**Additional context**
Issue is still observable even after specifying the `--region=AzureUSGovernment` flag.

**Comment by kapilt** [comment]
merged
