### ISSUE TITLE
[Azure] Ability to get 0 when there is no metric data

### ISSUE THREAD

**Issue by mboret** [cloud-custodian/cloud-custodian#6085]
**Is your feature request related to a problem? Please describe.**
Currently, it's not "really" possible to detect some unused resources like a Load Balancer when there is no metric data over the selected time range.

From the Custodian documentation:
```yaml
policies:
  - name: notify-inactive-loadbalancer
    resource: azure.loadbalancer
    filters:
      - type: metric
        metric: PacketCount
        op: le
        aggregation: total
        threshold: 1000
        timeframe: 72
```
This policy doesn't list Load Balancers without request(no data) over the past 72h. The parameter "no-data" changes nothing(include or exclude, same behaviour). 
Furthermore, with metrics which support "maximum" or "minimum" as aggregation type, metrics without data raise an error.

Example with this policy which raises an error if there is a stopped Virtual Machine(... yes I can filter VMs to exclude stopped ones but it's not a correct solution IMO as for some resource it's not possible to perform this kind of filter.)
```yaml
policies:
  - name: vm-high-cpu
    resource: azure.vm
    filters:
      - type: metric
        metric: Percentage CPU
        aggregation: maximum
        op: gt
        threshold: 95
        timeframe: 72
```
```
2020-08-31 15:21:43,837: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.8/site-packages/c7n/policy.py", line 281, in run
    resources = self.policy.resource_manager.resources()
  File "/home/matt/.local/lib/python3.8/site-packages/c7n_azure/query.py", line 279, in resources
    resources = self.filter_resources(resources)
  File "/home/matt/.local/lib/python3.8/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/home/matt/.local/lib/python3.8/site-packages/c7n_azure/filters.py", line 174, in process
    processed = list(w.map(self.process_resource, resources))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/matt/.local/lib/python3.8/site-packages/c7n_azure/filters.py", line 241, in process_resource
    return resource if self.passes_op_filter(resource) else None
  File "/home/matt/.local/lib/python3.8/site-packages/c7n_azure/filters.py", line 237, in passes_op_filter
    aggregate_value = self.func(m_data)
  File "/home/matt/.local/lib/python3.8/site-packages/c7n_azure/utils.py", line 223, in min
    return float(min(clean_numbers))
ValueError: min() arg is an empty sequence
```

**Describe the solution you'd like**
Ability to get 0 as value when there is no data point over the selected time range. Not sure if we can set it as a default behaviour or through a parameter.

**Comment by kapilt** [comment]
hmmm.. there's a no_data_action, 'exclude', 'include' style, but perhaps your right perhaps we need an additional option here to zero the data. in aws there's no metrics ingested against stopped resources so this hasn't been a problem there. we'll need to dig deeper on azure handles this.
