### ISSUE TITLE
Security group policy throwing error - The specified rule does not exist in this security group.

### ISSUE THREAD

**Issue by Bheesma** [cloud-custodian/cloud-custodian#6099]
**Describe the bug**

The following policy:

```
  - name: sg-egress-remove-http-port
    resource: aws.security-group
    filters:
      - type: egress
        Ports: [80]
    actions:
      - type: remove-permissions
        egress: matched
```

throws this error:

```
2020-09-03 07:00:26,896: custodian.commands:ERROR Error while executing policy sg-egress-remove-http-port, continuing
Traceback (most recent call last):
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/commands.py", line 272, in run
    policy()
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/policy.py", line 1175, in __call__
    resources = mode.run()
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/policy.py", line 313, in run
    results = a.process(resources)
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/c7n/resources/vpc.py", line 1367, in process
    method(GroupId=r['GroupId'], IpPermissions=groups)
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/pkc/aws/cloudcustodian/custodian/lib/python3.6/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidPermission.NotFound) when calling the RevokeSecurityGroupEgress operation: The specified rule does not exist in this security group.
```

**To Reproduce**

- Add port 80 to one of the security groups
- Run cloud custodian with the above mentioned policy
- The error is thrown
- Sometimes the matching rule gets removed. However, upon running cloud custodian again, it tries to delete the rule. In dry run, the resources section lists the security group that are not even matching.

**Expected behavior**
The security group deletion should be idempotent. If no security groups are matching, it should not try to perform the actions.

**Background (please complete the following information):**
 - OS: OSX 10.15.6
 - Python Version: python 3.6.5
 - Custodian Version: 0.9.4
 - Tool Version: 
 - Cloud Provider: AWS
 - Policy: included above
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output
```

Custodian:   0.9.4
Python:      3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
             [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='Prakashs-MacBook-Pro.local', release='19.6.0', version='Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.31
botocore==1.17.31
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==50.0.1
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.1.0
```

**Comment by kapilt** [comment]
hmm.. in this case I think your saying there is a security group matching.. can you provide the output of describe security group and/or include the full output of the policy log before the traceback? the idempotent reference is if there is something else modifying the sg prior to the removal from the policy.
