### ISSUE TITLE
AWS:  iam-role policy not deleting roles

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#6109]
```
policies:
  - name: remove-role
    resource: iam-role
    filters:
      - "tag:NoDelete": absent
    actions:
      - type: delete
        force: true
```

 custodian version
```
0.9.4
```

Error:

```
2020-09-08 10:48:33,898: custodian.actions:WARNING Role:arn:aws:iam::role cannot be deleted, set force to detach policy and delete
2020-09-08 10:48:34,042: custodian.output:ERROR Error while executing policy
and delete
2020-09-08 10:48:34,042: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
 File "site-packages/c7n/policy.py", line 313, in run
   results = a.process(resources)
 File "site-packages/c7n/resources/iam.py", line 1095, in process
   raise error
 File "site-packages/c7n/resources/iam.py", line 1084, in process
   client.delete_role(RoleName=r['RoleName'])
 File "site-packages/botocore/client.py", line 316, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "site-packages/botocore/client.py", line 635, in _make_api_call
   raise error_class(parsed_response, operation_name)
botocore.errorfactory.DeleteConflictException: An error occurred (DeleteConflict) when calling the DeleteRole operation: Cannot delete entity, must delete policies first.
2020-09-08 10:48:34,044: custodian.commands:ERROR Error while executing policy remove-role, continuing
Traceback (most recent call last):
 File "site-packages/c7n/commands.py", line 272, in run
   policy()
 File "site-packages/c7n/policy.py", line 1175, in __call__
   resources = mode.run()
 File "site-packages/c7n/policy.py", line 313, in run
   results = a.process(resources)
 File "site-packages/c7n/resources/iam.py", line 1095, in process
   raise error
 File "site-packages/c7n/resources/iam.py", line 1084, in process
   client.delete_role(RoleName=r['RoleName'])
 File "site-packages/botocore/client.py", line 316, in _api_call
   return self._make_api_call(operation_name, kwargs)
 File "site-packages/botocore/client.py", line 635, in _make_api_call
   raise error_class(parsed_response, operation_name)
botocore.errorfactory.DeleteConflictException: An error occurred (DeleteConflict) when calling the DeleteRole operation: Cannot delete entity, must delete policies first.
2020-09-08 10:48:34,044: custodian.commands:ERROR The following policies had errors while executing
- remove-role
```

**Comment by kapilt** [comment]
so force will detach named policies, but it looks like you have an inline policy in this case.

**Comment by tomarv2** [comment]
yes, these roles have inline policies.
