### ISSUE TITLE
tools/ops/policylambda.py does not convert config rules

### ISSUE THREAD

**Issue by CYarros10** [cloud-custodian/cloud-custodian#6111]
**Describe the bug**
When using the current version of policylambda.py to convert a config-rule policy to SAM template, the script fails because self.session / session_factory() is empty

**To Reproduce**

1. export AWS_PROFILE=<profile> 
2. create a policy with mode: config-rule
3. run command: 

`python3 cloud-custodian/tools/ops/policylambda.py -o output_sam -c <policy.yaml>;`

4. view error:

```
Traceback (most recent call last):
  File "cloud-custodian/tools/ops/policylambda.py", line 186, in <module>
    main()
  File "cloud-custodian/tools/ops/policylambda.py", line 176, in main
    policy_lambda = dispatch_render(p, sam)
  File "cloud-custodian/tools/ops/policylambda.py", line 137, in dispatch_render
    properties = render_func(p, policy_lambda, sam)
  File "cloud-custodian/tools/ops/policylambda.py", line 93, in render_config_rule
    config_rule = policy_lambda.get_events(None).pop()
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 898, in get_events
    ConfigRule(self.policy.data['mode'], session_factory))
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 1589, in __init__
    self.session = session_factory()
TypeError: 'NoneType' object is not callable
```

**Expected behavior**

The policylambda.py file should result in a SAM package containing the config-rule infrastructure

**Background (please complete the following information):**
 - OS: 10.14
 - Python Version: 3.8.1
 - Custodian Version: 0.9.4
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  #1. S3 Bucket Encryption
  - name: config-s3-bucket-encryption
    resource: aws.s3
    description: >
      Compliance: Bucket Encryption.
    mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/Cloud_Custodian_S3_Lambda_Role
      packages: [boto3, botocore, urllib3]
      tags:
        RSMs: "123"
        CostCenter: abc
        __Exception-LambdaEncryption: "0123456789"
    filters:
      - and:
        - type: bucket-encryption
          state: false
        - "tag:__Exception-S3Encryption": absent
```
 - Traceback: 

```
Traceback (most recent call last):
  File "cloud-custodian/tools/ops/policylambda.py", line 186, in <module>
    main()
  File "cloud-custodian/tools/ops/policylambda.py", line 176, in main
    policy_lambda = dispatch_render(p, sam)
  File "cloud-custodian/tools/ops/policylambda.py", line 137, in dispatch_render
    properties = render_func(p, policy_lambda, sam)
  File "cloud-custodian/tools/ops/policylambda.py", line 93, in render_config_rule
    config_rule = policy_lambda.get_events(None).pop()
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 898, in get_events
    ConfigRule(self.policy.data['mode'], session_factory))
  File "/usr/local/lib/python3.7/site-packages/c7n/mu.py", line 1589, in __init__
    self.session = session_factory()
TypeError: 'NoneType' object is not callable
```

**Additional context**

This block of code fails:

```
def render_config_rule(p, policy_lambda, sam):
    properties = render_function_properties(p, policy_lambda)
    policy_lambda.arn = {'Ref': resource_name(p.name)}
    config_rule = policy_lambda.get_events(None).pop()
    rule_properties = config_rule.get_rule_params(policy_lambda)
```

This block of code succeeds:

```

def get_lambda_arn(function_name):
    sts = boto3.client("sts")
    account_id = sts.get_caller_identity()["Arn"].split(":")[4]
    region = boto3.session.Session().region_name
    arn = "arn:aws:lambda:" + str(region) \
          + ":" + account_id + ":function:" \
          + function_name
    return arn

def render_config_rule(p):
    policy_lambda = mu.PolicyLambda(p)
    policy_lambda.arn = get_lambda_arn(policy_lambda.name)
    config_rule = policy_lambda.get_events(Session)

    properties = config_rule[0].get_rule_params(policy_lambda)
```

**Comment by kapilt** [comment]
i ran your policy with trunk version of policylambda.py with no issues, and no env vars set. i suspect your issue is related to the fact your trying to use an old version of custodian, you'll need a current version of custodian to use the trunk policylambda script. there are unit tests now for policylambda.py verifying behavior.

```
cloud-custodian on  upstream [$?] is 📦 v0.9.6 via 🐍 v3.8.5 (c7n-3.8) 
❯ python tools/ops/policylambda.py  -c foo.yml -o x

cloud-custodian on  upstream [$?] is 📦 v0.9.6 via 🐍 v3.8.5 (c7n-3.8) 
❯ env | grep AWS
```
