### ISSUE TITLE
Glue policies are not working as expected

### ISSUE THREAD

**Issue by nhemchandra** [cloud-custodian/cloud-custodian#6231]
I have below custodian policy. I'm not able to view results from the custodian config rule.

Corresponding custodian Lambdas giving the following errors.
*************************************************************************************************
[ERROR]	2020-10-20T15:47:27.122Z	e67de231-c90c-47f6-8591-7a7e5fb41a65	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 166, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1134, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 773, in run
    for r in self.policy.resource_manager.get_resource_manager(
  File "/var/task/c7n/manager.py", line 95, in get_resource_manager
    if not data and self.source_type == 'config' and getattr(
AttributeError: 'GlueDataCatalog' object has no attribute 'source_type'

[ERROR] AttributeError: 'GlueDataCatalog' object has no attribute 'source_type'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 166, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1134, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 773, in run
    for r in self.policy.resource_manager.get_resource_manager(
  File "/var/task/c7n/manager.py", line 95, in get_resource_manager
    if not data and self.source_type == 'config' and getattr(
*************************************************************************************************

$ custodian version
0.9.7
$ custodian validate rules/Glue.yaml
2020-10-20 11:54:52,963: custodian.commands:INFO Configuration valid: rules/Glue.yaml
$ custodian run --dryrun -s /tmp/ rules/Glue.yaml --profile assumerole
2020-10-20 11:55:03,175: custodian.policy:INFO policy:PCE-MEDIUM-glue-catalog-security-config resource:glue-catalog region:us-east-1 count:1 time:1.62
2020-10-20 11:55:03,842: custodian.policy:INFO policy:PCE-MEDIUM-glue-data-catalog-encryption resource:glue-catalog region:us-east-1 count:1 time:0.66

Glue.yaml
*************************************************************************************************
# Glue rules collection

policies:
  #Ensure that glue data catalog settings 
  - name: glue-catalog-security-config
    resource: glue-catalog
    description: |
      Data catalog return non-compliance items not enabled with Encrypt connection passwords settings
    mode:
      type: config-poll-rule
      role: xxxxxx
      schedule: TwentyFour_Hours
    filters:
      - type: value
        key: DataCatalogEncryptionSettings.ConnectionPasswordEncryption.ReturnConnectionPasswordEncrypted
        value: false
        op: eq 

  #Ensure that glue data catalog encryption is enabled 
  - name: glue-data-catalog-encryption
    resource: glue-catalog
    description: |
      Data catalog return non-compliance items not enabled with Catalog Encryption mode
    mode:
      type: config-poll-rule
      role: xxxxx
      schedule: TwentyFour_Hours
    filters:
      - type: value
        key: DataCatalogEncryptionSettings.EncryptionAtRest.CatalogEncryptionMode
        value: DISABLED
        op: eq
*************************************************************************************************

  Im able to see data with the run as per below in resource.json file.
*************************************************************************************************
[
  {
    "DataCatalogEncryptionSettings": {
      "EncryptionAtRest": {
        "CatalogEncryptionMode": "DISABLED"
      },
      "ConnectionPasswordEncryption": {
        "ReturnConnectionPasswordEncrypted": false
      }
    },
    "CatalogId": "xxxxxxxx",
    "c7n:MatchedFilters": [
      "DataCatalogEncryptionSettings.ConnectionPasswordEncryption.ReturnConnectionPasswordEncrypted"
    ]
  }
]      
 *************************************************************************************************

**Comment by PratMis** [comment]
AWS config doesn't support Glue at the moment

**Comment by PratMis** [comment]
@nhemchandra Also, is there any specific reason you're using `type: config-poll-rule`?

**Comment by nhemchandra** [comment]
For Non config rules managed by custodian, we'll use "type: config-poll-rule"
I can see data and definitely custodian support it.

**Comment by nhemchandra** [comment]
Any update on this one.

**Comment by PratMis** [comment]
Hello, what do you mean by "non config rules managed by custodian?" Are you using the config UI for any downstream job? If not, you can just use the periodic mode in custodian. See policy below:
```
policies:
  - name: glue-data-catalog-encryption
    resource: glue-catalog
    description: |
     Data catalog return non-compliance items not enabled with Catalog Encryption mode
    mode:
      role: arn:aws:iam::{account_id}:role/CloudCustodianRole
      type: periodic
      schedule: "rate(20 minutes)"
    filters:
      - type: value
        key: DataCatalogEncryptionSettings.EncryptionAtRest.CatalogEncryptionMode
        value: DISABLED
        op: eq
```

**Comment by nhemchandra** [comment]
I'll try and get back to you.

**Comment by PratMis** [comment]
Cool, also fyi this will not show up in AWS Config Rules and you might want to add sometime to notification/remediation action.

**Comment by nhemchandra** [comment]
How we want to show it as a rule in AWS config.
Is that not possible?
