### ISSUE TITLE
Invalid tag errors while tagging/deleting EC2/RDS snapshots

### ISSUE THREAD

**Issue by edwardmoon** [cloud-custodian/cloud-custodian#6242]
Getting intermittent errors about invalid resources running custodian scripts to tag/delete EC2/EBS/RDS snapshots over 30 days old. Errors occur regarding resources that do not exist.

**To Reproduce**
Run custodian script that tag RDS snapshots over 30 days old or run script that deletes tagged EC2/EBS/RDS snapshot. Running with --cache-period 0 reduces, but does not eliminate errors experienced.

**Expected behavior**
Custodian scripts should run reliably each time, not intermittently complain about invalid resources which cannot be found in the AWS console.

**Background (please complete the following information):**
 - OS: Linux and Mac OS X 10.15.7
 - Python Version: python 3.8.2 and 3.8.5
 - Custodian Version: 0.9.7 and 0.9.4
 - Tool Version: n/a
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: ebs-delete-old-ebs-snapshots
    resource: ebs-snapshot
    filters:
      - type: age
        days: 30
        op: ge
    actions:
      - delete
      - type: post-finding
        severity_normalized: 0
        types:
          - "Software and Configuration Checks/AWS Security Best Practices"
policies:
  - name: ebs-mark-unattached-deletion
    resource: ebs
    comments: |
      Mark any unattached EBS volumes for deletion in 30 days.
      Volumes set to not delete on instance termination do have
      valid use cases as data drives, but 99% of the time they
      appear to be just garbage creation.
    filters:
      - Attachments: []
      - "tag:maid_status": absent
    actions:
      - type: mark-for-op
        op: delete
        days: 1

  - name: ebs-unmark-attached-deletion
    resource: ebs
    comments: |
      Unmark any attached EBS volumes that were scheduled for deletion
      if they are currently attached
    filters:
      - type: value
        key: "Attachments[0].Device"
        value: not-null
      - "tag:maid_status": not-null
    actions:
      - unmark

  - name: ebs-delete-marked
    resource: ebs
    comments: |
      Delete any attached EBS volumes that were scheduled for deletion
    filters:
      - type: marked-for-op
        op: delete
    actions:
      - delete
      - type: post-finding
        severity_normalized: 0
        types:
          - "Software and Configuration Checks/AWS Security Best Practices"
policies: 
   - name: check-buckets
      resource: aws.s3
xpolicies:
  - name: rds-delete-old-rds-snapshots
    resource: rds-snapshot
    filters:
      - type: age
        days: 30
        op: ge
      - type: value
        key: snapshotType
        value: manual
        op: in
    actions:
      - delete
      - type: post-finding
        severity_normalized: 0
        types:
          - "Software and Configuration Checks/AWS Security Best Practices"```
 - Traceback: [if applicable, please exclude sensitive/account information]
2020-10-22 21:54:59,678: custodian.actions:ERROR Exception with tags: [{'Key': 'c7n:FindingId:ebs-delete-marked', 'Value': 'us-west-2/077047573990/7b1384033bce122f6f06b8266dba6309/401d451c2a463ec9b6a247716da10ba7:2020-10-22T21:54:59.305807+00:00'}]  An error occurred (InvalidVolume.NotFound) when calling the CreateTags operation: The volume 'vol-077e93b8fd5da3534' does not exist.
2020-10-22 21:54:59,679: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/c7n/policy.py", line 313, in run
    results = a.process(resources)
  File "/usr/lib/python3.8/site-packages/c7n/resources/securityhub.py", line 423, in process
    tag_action({
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 414, in process
    _common_tag_processer(
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 123, in _common_tag_processer
    raise error
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 420, in process_resource_set
    self.manager.retry(
  File "/usr/lib/python3.8/site-packages/c7n/utils.py", line 363, in _retry
    return func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidVolume.NotFound) when calling the CreateTags operation: The volume 'vol-077e93b8fd5da3534' does not exist.
2020-10-22 21:54:59,681: custodian.commands:ERROR Error while executing policy ebs-delete-marked, continuing
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/c7n/commands.py", line 272, in run
    policy()
  File "/usr/lib/python3.8/site-packages/c7n/policy.py", line 1175, in __call__
    resources = mode.run()
  File "/usr/lib/python3.8/site-packages/c7n/policy.py", line 313, in run
    results = a.process(resources)
  File "/usr/lib/python3.8/site-packages/c7n/resources/securityhub.py", line 423, in process
    tag_action({
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 414, in process
    _common_tag_processer(
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 123, in _common_tag_processer
    raise error
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/c7n/tags.py", line 420, in process_resource_set
    self.manager.retry(
  File "/usr/lib/python3.8/site-packages/c7n/utils.py", line 363, in _retry
    return func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidVolume.NotFound) when calling the CreateTags operation: The volume 'vol-077e93b8fd5da3534' does not exist.
2020-10-22 21:54:59,682: custodian.commands:ERROR The following policies had errors while executing
 - ebs-delete-marked
 - `custodian version --debug` output
Custodian:   0.9.7
Python:      3.8.2 (default, Jul 18 2020, 19:35:03)
             [GCC 9.2.0]
Platform:    posix.uname_result(sysname='Linux', nodename='ee4b48a1008f', release='4.19.76-linuxkit', version='#1 SMP Tue May 26 11:42:35 UTC 2020', machine='x86_64')
Using venv:  False
Docker: True
Installed:

argcomplete==1.12.1
attrs==20.2.0
boto3==1.16.3
botocore==1.19.3
importlib-metadata==1.7.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==41.2.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.11
zipp==3.3.1
**Additional context**
Mac OS X cloud custodian info:
Custodian:   0.9.4
Python:      3.8.5 (default, Jul 21 2020, 10:48:26)
             [Clang 11.0.3 (clang-1103.0.32.62)]
Platform:    posix.uname_result(sysname='Darwin', nodename='USBUR1VWB170865', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.29
botocore==1.17.29
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==49.2.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.1.0

Stack trace from Mac OS X:
020-10-20 11:47:38,488: custodian.policy:INFO policy:rds-delete-old-rds-snapshots action:rdssnapshotdelete resources:1 execution_time:0.41
2020-10-20 11:47:39,213: custodian.actions:ERROR Exception with tags: {'c7n:FindingId:rds-delete-old-rds-snapshots': 'us-west-2/656419642964/85f0c1ece704c771604d04897382d900/b432f86496aadd4fa8e8caa87d95aed6:2020-10-20T18:47:38.499622+00:00'}  Resource Tag Errors {'arn:aws:rds:us-west-2:656419642964:snapshot:companybusdev1-final-snapshot-19-sept-2020': 'InvalidParameterValue'}
2020-10-20 11:47:39,216: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/policy.py", line 323, in run
    results = a.process(resources)
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/resources/securityhub.py", line 433, in process
    tag_action({
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 851, in process
    _common_tag_processer(
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 133, in _common_tag_processer
    raise error
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 857, in process_resource_set
    return universal_retry(
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1133, in universal_retry
    raise Exception("Resource Tag Errors %s" % (errors))
Exception: Resource Tag Errors {'arn:aws:rds:us-west-2:656419642964:snapshot:companybusdev1-final-snapshot-19-sept-2020': 'InvalidParameterValue'}
2020-10-20 11:47:39,231: custodian.commands:ERROR Error while executing policy rds-delete-old-rds-snapshots, continuing
Traceback (most recent call last):
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/commands.py", line 282, in run
    policy()
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/policy.py", line 1176, in __call__
    resources = mode.run()
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/policy.py", line 323, in run
    results = a.process(resources)
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/resources/securityhub.py", line 433, in process
    tag_action({
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 851, in process
    _common_tag_processer(
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 133, in _common_tag_processer
    raise error
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 857, in process_resource_set
    return universal_retry(
  File "/Users/xemoon/repos/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1133, in universal_retry
    raise Exception("Resource Tag Errors %s" % (errors))
Exception: Resource Tag Errors {'arn:aws:rds:us-west-2:656419642964:snapshot:companybusdev1-final-snapshot-19-sept-2020': 'InvalidParameterValue'}
2020-10-20 11:47:39,233: custodian.commands:ERROR The following policies had errors while executing
 - rds-delete-old-rds-snapshots

**Comment by jtroberts83** [comment]
@edwardmoon If your policy ebs-delete-old-ebs-snapshots runs before the other policies then it could be causing issues.  Put the policies that perform a **delete** action at the very end of your policy file or make sure they run after the other policies which tag etc.  If the first policy is deleting some resources and then the policy right after is querying and taking some action on some of the same resources then it might cause an issue but like you said with the cache-period 0 being set it shouldn't be using cache anyways...Still might be a timing issue of some sort.  Maybe give that a try?

**Comment by jtroberts83** [comment]
Another thing you could try is adding additional filters to the other policies to exclude ones over 30 days old which you are deleting on the top policy, that way it won't include those same snapshots in the queries to follow and could help you avoid the error.  Let me know if either works and we can troubleshoot some more

**Comment by edwardmoon** [comment]
I'll try reordering the custodian scripts and see if that helps. However, I
should note that when I tested locally (on Mac OS X detailed in the
report), I was able to duplicate the issue only running one of the scripts.

**Comment by kapilt** [comment]
you would need to do delete after post finding, post-finding tries to tag the resource for state when posting so that it can update the same finding later, but in this case your deleting it before its being posted.

**Comment by kapilt** [comment]
ie invert your actions and it works fine.
