### ISSUE TITLE
AWS: error running ASG propagate policy

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#6251]
Custodian Version:  0.8.46.1

Cloud Provider: AWS
 
Policy
```
policies:
- name: auto-owner-asg
  resource: asg
  mode:
     type: cloudtrail
     role: "arn:aws:iam::{account_id}:role/Custodian"
     events:
       - source: autoscaling.amazonaws.com
         event: CreateAutoScalingGroup
         ids: requestParameters.autoScalingGroupName
  filters:
    - not:
      - type: value
        key: "tag:Owner"
        op: regex
        value: "(.*?@test.*?)"
        value_type: normalize
  actions:
    - type: auto-tag-user
      tag: Owner
    - type: tag
      key: propagate-tags
      value: "True"

- name: asg-propagate-tags-owner
  resource: asg
  mode:
    type: periodic
    schedule: "rate(5 minutes)"
    role: "arn:aws:iam::{account_id}:role/Custodian"
  region: us-east-2
  filters:
     - "tag:propagate-tags": present
     - type: value
       key: "tag:Owner"
       op: regex
       value: "(.*?@test.*?)"
       value_type: normalize
  actions:
     - type: remove-tag
       key: propagate-tags
     - type: propagate-tags
       tags:
         - "Owner"
```

Error:
```
[ERROR]    2020-10-27T18:30:32.480Z    ec614241-19ef-4d44-b3a0-400229378905    error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 166, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1138, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 526, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 317, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/asg.py", line 1212, in process
    instance_count = sum(list(w.map(self.process_asg, asgs)))
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/resources/asg.py", line 1230, in process_asg
    if not self.manager.config.dryrun and instances:
UnboundLocalError: local variable 'instances' referenced before assignment
[ERROR] 2020-10-27T18:30:32.480Z ec614241-19ef-4d44-b3a0-400229378905 error during policy execution Traceback (most recent call last): File "/var/task/c7n/handler.py", line 166, in dispatch_event p.push(event, context) File "/var/task/c7n/policy.py", line 1138, in push return mode.run(event, lambda_ctx) File "/var/task/c7n/policy.py", line 526, in run return PullMode.run(self) File "/var/task/c7n/policy.py", line 317, in run results = a.process(resources) File "/var/task/c7n/resources/asg.py", line 1212, in process instance_count = sum(list(w.map(self.process_asg, asgs))) File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator yield fs.pop().result() File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 439, in result return self.__get_result() File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result raise self._exception File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/var/task/c7n/resources/asg.py", line 1230, in process_asg if not self.manager.config.dryrun and instances: UnboundLocalError: local variable 'instances' referenced before assignment
```

**Comment by jtroberts83** [comment]
@tomarv2 Which policy is that error occurring on or does it happen for both policies?

**Comment by tomarv2** [comment]
2nd one, 1st one works fine..

**Comment by jtroberts83** [comment]
@tomarv2  I tested the propagate-tags action at the most basic level with no filters and both periodic and pull mode and both error out so that is definitely broken.  Thanks for filling the issue on this as I imagine that would be broken for lots of users

**Comment by jtroberts83** [comment]
@kapilt I confirmed the propagate-tags action for aws.asg resource is broken in version 0.9.7 as well

**Comment by kapilt** [comment]
while looking at the fix, i also realized there's an issue in the policy, actions work on the output from describe, but they don't generally attempt to patch the resource with outcomes, so the notion of tagging the resource, and the propagating a tag set by another action in the same policy tag won't work because the resource the action is operating on doesn't have the tag. we could just recognize that asg tags are special and and some specific handling for this.

**Comment by tomarv2** [comment]
as you said, I am trying to tag based on outcomes. I was thinking, it should be something like this:

```
  actions:
    - type: auto-tag-user
      tag: Owner
     propagate: True <--- this flag should be added
```

This is what I am trying to do, as seen in the screenshot I would like to check that box(Tag New Instances), so everytime a new instance gets created it gets the tag:

<img width="1331" alt="Screen Shot 2020-10-27 at 10 19 35 AM" src="https://user-images.githubusercontent.com/11890959/97589301-95a28680-19ba-11eb-8244-4efc631bff25.png">
