### ISSUE TITLE
ci - docker image fails due to trivy rate limit download on github

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#6328]
**Describe the bug**

github rate limiting github ;-)

(12 durations < 0.005s hidden.  Use -vv to show these durations.)
========================= 5 passed, 1 skipped in 8.47s =========================
2020-12-03T19:18:43.687Z	INFO	Need to update DB
2020-12-03T19:18:43.687Z	INFO	Downloading DB...
2020-12-03T19:18:43.744Z	FATAL	failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: GET https://api.github.com/repos/aquasecurity/trivy-db/releases: 403 API rate limit exceeded for 40.76.194.212. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 40m04s]
Traceback (most recent call last):
  File "tools/dev/dockerpkg.py", line 535, in <module>
    cli()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/dev/dockerpkg.py", line 310, in build
    scan_image(":".join(image_refs[0]))
  File "tools/dev/dockerpkg.py", line 451, in scan_image
    subprocess.check_call(cmd, stderr=subprocess.STDOUT)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/runner/work/cloud-custodian/cloud-custodian/bin/trivy', 'cloudcustodian/c7n:dev']' returned non-zero exit status 1.
Error: Process completed with exit code 1.

**Comment by kapilt** [comment]
its not clear what we could be doing additionally, trivy itself is doing the download, and GitHub auth is already in the env
