### ISSUE TITLE
SNS remove-statement action does not remove org-ids

### ISSUE THREAD

**Issue by khapp** [cloud-custodian/cloud-custodian#6522]
**Describe the bug**
SNS remove-statement action does not remove org-ids

**To Reproduce**
Create SNS topic with cross-account org access in policy:

Example Policy: 

{
    "Version": "2008-10-17",
    "Id": "__default_policy_ID",
    "Statement": [
        {
            "Sid": "allow-publish-from-organization-accounts",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "sns:Publish"
            ],
            "Resource": "snsTopicArn",
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgID": "o-blahblah"
                }
            }
        }
    ]
}

**Expected behavior**
o-blahblah should be removed.

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: Python 3.8.5
 - Custodian Version: 9.5
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: 

- name: agt-sns-remediate-public-real-time
  resource: sns
  mode:
      type: cloudtrail
      events:
         - source: sns.amazonaws.com
           event: CreateTopic
           ids: 'responseElements.topicArn'
      packages:
        - botocore
        - boto3
        - urllib3
        - certifi
  filters:
    - type: cross-account
  actions:
    - type: remove-statements
      statement_ids: matched
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**

Cloudwatch Logs Error:

2021-03-11T08:35:12.297-06:00

Copy
[ERROR]	2021-03-11T14:35:12.297Z	e46dfcf9-0c60-4a3f-9213-7ef2cc0905bb	Error processing sns:arn:aws:sns:us-east-1:1234567890:kristen-top-level-org-test
Traceback (most recent call last):
  File "/var/task/c7n/resources/sns.py", line 295, in process
    results += filter(None, [self.process_resource(client, r)])
  File "/var/task/c7n/resources/sns.py", line 313, in process_resource
    client.set_topic_attributes(
  File "/var/task/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: Policy Error: null
[ERROR] 2021-03-11T14:35:12.297Z e46dfcf9-0c60-4a3f-9213-7ef2cc0905bb Error processing sns:arn:aws:sns:us-east-1:1234567890:kristen-top-level-org-test Traceback (most recent call last): File "/var/task/c7n/resources/sns.py", line 295, in process results += filter(None, [self.process_resource(client, r)]) File "/var/task/c7n/resources/sns.py", line 313, in process_resource client.set_topic_attributes( File "/var/task/botocore/client.py", line 316, in _api_call return self._make_api_call(operation_name, kwargs) File "/var/task/botocore/client.py", line 635, in _make_api_call raise error_class(parsed_response, operation_name) botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: Policy Error: null

**Comment by mnss8991** [comment]
Hi I want to fix this issue. I am very interested to contribute. I have some experience of ansible which is a yaml scripting language. Could you assign this task for me. Please let me know if there is some procedure for assigning as I am new for this open source contribution.

**Comment by thisisshi** [comment]
@mnss8991 Feel free to get started by taking look at developer docs here: https://cloudcustodian.io/docs/contribute.html
