### ISSUE TITLE
Custodian throws KeyError when trying to retrieve Glue Workflow resources

### ISSUE THREAD

**Issue by kylejohnson514** [cloud-custodian/cloud-custodian#6556]
**Describe the bug**
While trying to use a filter for `glue-workflow`, Custodian throws `KeyError: 'list_workflows'`. This error occurs as Custodian is attempting to query for the `glue-workflow` resources, before any filter is applied to them.

**To Reproduce**
Run a simple policy to pull `glue-workflow` objects, i.e.)

```
policies:
  - name: pull-glue-workflow-resources
    resource: glue-workflow
```

**Expected behavior**
Custodian should be able to successfully pull `glue-workflow` resources

**Additional context**
The definition of the GlueWorkflow resource looks like this:
```
@resources.register('glue-workflow')
class GlueWorkflow(QueryResourceManager):

    class resource_type(TypeInfo):
        service = 'glue'
        enum_spec = ('list_workflows', 'Workflows', None)
        detail_spec = ('get_workflow', 'Name', None, 'Workflow')
        id = name = 'Name'
        arn_type = 'workflow'
        universal_taggable = object()
        cfn_type = 'AWS::Glue::Workflow'
```

I think something is wrong with how `enum_spec` and `detail_spec` are being used to pull the resources.

Here are the logs from when I try to run a sample policy:

```
Traceback (most recent call last):
  File "/Users/kyle/public-cloud-custodian/cloud-custodian/c7n/policy.py", line 284, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/kyle/public-cloud-custodian/cloud-custodian/c7n/query.py", line 511, in resources
    resources = self.source.resources(query)
  File "/Users/kyle/public-cloud-custodian/cloud-custodian/c7n/query.py", line 222, in resources
    return self.query.filter(self.manager, **query)
  File "/Users/kyle/public-cloud-custodian/cloud-custodian/c7n/query.py", line 77, in filter
    getattr(resource_manager, 'retry', None)) or []
  File "/Users/kyle/public-cloud-custodian/cloud-custodian/c7n/query.py", line 51, in _invoke_client_enum
    if client.can_paginate(enum_op):
  File "/Users/kyle/anaconda3/envs/c7n/lib/python3.7/site-packages/botocore/client.py", line 796, in can_paginate
    actual_operation_name = self._PY_TO_OP_NAME[operation_name]
KeyError: 'list_workflows'
```

**Comment by PratMis** [comment]
It works for me. What version of boto/botocore are you using?
```
 ~/development/policies  custodian run -c glue.yml -s output --profile skunkworks --region us-east-1 --cache-period=0                                 ✔  5s    cloud-custodian   09:54:27 AM
2021-03-19 09:54:30,037: custodian.policy:INFO policy:filter-glue-workflows resource:glue-workflow region:us-east-1 count:0 time:0.43
 ~/development/policies  cat glue.yml                                                                                                                      ✔    cloud-custodian   09:54:30 AM
policies:
  - name: filter-glue-workflows
    resource: glue-workflow
```
