### ISSUE TITLE
c7n-org: "all" regions in govCloud is broken

### ISSUE THREAD

**Issue by archoversight** [cloud-custodian/cloud-custodian#6585]
**Describe the bug**

https://github.com/cloud-custodian/cloud-custodian/blob/85e82a775d5c1485271155bdf46205c465d9f954/tools/c7n_org/c7n_org/cli.py#L197-L205

Sets the default region to `us-east-1` when attempting to describe all regions. However this does not work when executing inside AWS govCloud, so currently selecting all regions is a manual process.

**To Reproduce**

```
accounts:
        - account_id: 'govCloud-id'
          name: govCloud
          regions:
                  - all
          role: arn:aws-us-gov:iam::govCloud-id:role/global/cloud-custodian
          tags:
                  - type:prod
```

```
c7n-org run -c aws-accounts.yml -s testing -u policies/ebs-garbage-collection.yml -vvv
```

Leads to the following traceback:

```
Traceback (most recent call last):
  File "/home/cloud-custodian/.venv/bin/c7n-org", line 8, in <module>
    sys.exit(cli())
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/c7n_org/cli.py", line 665, in run
    for r in resolve_regions(region or a.get('regions', ()), a):
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/c7n_org/cli.py", line 201, in resolve_regions
    return [region['RegionName'] for region in client.describe_regions()['Regions']]
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cloud-custodian/.venv/lib64/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeRegions operation: AWS was not able to validate the provided access credentials
```

**Expected behavior**

I expect c7n-org to execute against all available regions.

**Background (please complete the following information):**
 - OS: RHEL 8.0
 - Python Version: 3.8.0
 - Custodian Version: 
    - c7n==0.9.11
    - c7n-org==0.6.10
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
- name: ebs-mark-unattached-deletion
  resource: ebs
  comments: |
    Mark any unattached EBS volumes for deletion in 30 days.
    Volumes set to not delete on instance termination do have
    valid use cases as data drives, but 99% of the time they
    appear to be just garbage creation.
  filters:
    - Attachments: []
    - "tag:maid_status": absent
  actions:
    - type: mark-for-op
      op: delete
      days: 30

- name: ebs-unmark-attached-deletion
  resource: ebs
  comments: |
    Unmark any attached EBS volumes that were scheduled for deletion
    if they are currently attached
  filters:
    - type: value
      key: "Attachments[0].Device"
      value: not-null
    - "tag:maid_status": not-null
  actions:
    - unmark

- name: ebs-delete-marked
  resource: ebs
  comments: |
    Delete any attached EBS volumes that were scheduled for deletion
  filters:
    - type: marked-for-op
      op: delete
  actions:
    - delete
```
 - Traceback: see above

```
Custodian:   0.9.11
Python:      3.8.0 (default, Mar  9 2020, 18:02:46)
             [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-10-108-32-223', release='4.18.0-193.29.1.el8_2.x86_64', version='#1 SMP Thu Oct 22 10:09:53 EDT 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.2
attrs==20.3.0
boto3==1.17.33
botocore==1.20.33
importlib-metadata==3.7.3
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.3.6
setuptools==41.6.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
urllib3==1.26.4
zipp==3.4.1
```

**Additional context**

I am running inside the aws govcloud partition.

**Comment by kapilt** [comment]
there aren't many regions in gov cloud, they don't have to be set in the accounts file, they can be passed in via the cli. -r region-1,region-2

**Comment by kapilt** [comment]
we should probably defer to environment variables AWS_DEFAULT_REGION, AWS_REGION with fallback to us-east-1 in this context. but the work around is also trivial re pass region on cli.

**Comment by archoversight** [comment]
Yes, the work-around is fairly trivial, and I have done so since I am splatting out the config file using Jinja2 inside ansible.

**Comment by SamarthUpadhya** [comment]
@archoversight  Did this issue get fixed? I was unable to custodian with  
run -r all ( Error: region must me specified)
( or -r region-1, region-2)  : wrong format
 (-r region-1 -r region-r): sucessful run but will only pick the first region

**Comment by archoversight** [comment]
@SamarthUpadhya I have `all` in my `accounts.yml` that is passed to the c7n-org command, which internally attempts to figure out what regions it should run against.

I don't think `all` is a valid target for a region when using `custodian run` directly.
