### ISSUE TITLE
Lambda function invoked but the support ticket to increase service limit did not get created

### ISSUE THREAD

**Issue by SamarthUpadhya** [cloud-custodian/cloud-custodian#6657]
1)The command executed successfully and have invoked a lambda function. It even tells that the policy been executed. I see the lambda function in the region but the support ticket is not created 

 ```
custodian run  -s out --profile xxxx --region=xxxxxx lambda.yml --verbose 
2021-04-27 17:16:02,833: custodian.commands:DEBUG Loaded file lambda.yml. Contains 1 policies
2021-04-27 17:16:03,093: custodian.output:DEBUG Storing output with <LogFile file://out/account-service-limits/custodian-run.log>
2021-04-27 17:16:03,103: custodian.policy:INFO Provisioning policy lambda: account-service-limits region: us-east-2
2021-04-27 17:16:03,236: custodian.serverless:DEBUG Created custodian serverless archive size: 0.45mb
2021-04-27 17:16:03,460: custodian.serverless:INFO Publishing custodian policy lambda function custodian-account-service-limits
2021-04-27 17:16:06,022: custodian.serverless:DEBUG Creating cwe rule for <CWEvent Type:periodic Events:>
2021-04-27 17:16:06,478: custodian.serverless:DEBUG Added lambda invoke cwe rule permission
2021-04-27 17:16:06,530: custodian.serverless:DEBUG Creating cwe rule target for <CWEvent Type:periodic Events:> on func:arn:aws:lambda:xxxxxxx:function:custodian-account-service-limits
2021-04-27 17:16:06,584: custodian.serverless:DEBUG Added event source: <CWEvent Type:periodic Events:> to function: arn:aws:lambda:us-xxxxxxx:function:custodian-account-service-limits
2021-04-27 17:16:06,588: custodian.output:DEBUG metric:ApiCalls Count:7 policy:account-service-limits restype:account
```
If i run the custodian command without invoking lambda function, it is creating a support ticket for me. I cannot bypass OTP to execute custodian command so i have to run it via lambda which will run periodically. 

Here is the policy that i used 
`policies:
  - name: account-service-limits
    resource: account
    mode:
     type: periodic
     role: arn:aws:iam::xxxxxxxxxx:role/xxxxxxxx
     schedule: rate(2 days)
    filters:
      - type: service-limit
        threshold: 20
    actions:
      - type: request-limit-increase
        notify: [xxxxxx@xxxxxxx.com]
        percent-increase: 30
        message: "Please raise the below account limit"`

2) Running custodian cmd with -r all flag does not work

**Comment by kapilt** [comment]
do you have the lambda execution logs? this is showing the logs from the cli provisioning the lambda.

**Comment by SamarthUpadhya** [comment]
@kapilt I was able to fix the issue. I was missing permission for my role. Here is the log for the failed event:

`[ERROR] ClientError: An error occurred (AccessDenied) when calling the ListAccountAliases operation: User: arn:aws:sts::xxxxxxxxxx:assumed-role/xxxxxx/custodian-account-service-limits is not authorized to perform: iam:ListAccountAliases on resource: *
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1143, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 526, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/resources/account.py", line 75, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/var/task/c7n/resources/account.py", line 38, in get_account
    aliases = client.list_account_aliases().get(
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)`

After assigning the policy to my role , the lambda function was invoked and it submitted a support ticket

**Comment by SamarthUpadhya** [comment]
@kapilt -r all or using multiple region ( -r region-1, region-2) or ( -r region-1 -r region-2) in cli is not working 
` custodian run  --cache-period 0 --dryrun -s out --profile prod -r us-west-1 -r us-east-1 lambda.yml --debug -v
2021-04-28 11:43:06,242: custodian.cache:DEBUG Disabling cache
2021-04-28 11:43:06,242: custodian.commands:DEBUG Loaded file lambda.yml. Contains 1 policies
2021-04-28 11:43:06,607: custodian.output:DEBUG Storing output with <LogFile file://out/us-west-1/account-service-limits/custodian-run.log>
2021-04-28 11:43:06,619: custodian.policy:DEBUG Running policy:account-service-limits resource:account region:us-west-1 c7n:0.9.11
2021-04-28 11:43:10,254: custodian.resources.account:DEBUG Filtered from 1 to 1 account
2021-04-28 11:43:10,254: custodian.policy:INFO policy:account-service-limits resource:account region:us-west-1 count:1 time:3.63
2021-04-28 11:43:10,257: custodian.policy:DEBUG dryrun: skipping actions
2021-04-28 11:43:10,258: custodian.output:DEBUG metric:ResourceCount Count:1 policy:account-service-limits restype:account scope:policy
2021-04-28 11:43:10,259: custodian.output:DEBUG metric:ApiCalls Count:51 policy:account-service-limits restype:account`
If i use -r all
`botocore.exceptions.NoRegionError: You must specify a region.`
