### ISSUE TITLE
AWS - EC2 config query policies malfunctioning

### ISSUE THREAD

**Issue by mattheidelbaugh** [cloud-custodian/cloud-custodian#6664]
**Describe the bug**
Config query policies for EC2 do not validate as valid configuration or return an error on execution.  

**To Reproduce**
custodian run on the first policy with no query parameter (test-config-query-ec2)
custodian validate on either of the latter two polices with query parameter (test-config-query-ec2-clause or test-config-query-ec2-expr)

**Expected behavior**
All three policies should return all ec2 instances in account

**Background (please complete the following information):**
 - OS: OSX 10.15.7
 - Python Version:  3.9.2
 - Custodian Version: 0.9.12
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy:
```yaml
policies: 
  - name: test-config-query-ec2
    resource: aws.ec2
    source: config

  - name: test-config-query-ec2-clause
    resource: aws.ec2
    source: config
    query: 
      - clause: resourceType = 'AWS::EC2::Instance'

  - name: test-config-query-ec2-expr
    resource: aws.ec2
    source: config
    query: 
      - expr: "select resourceId, configuration, supplementaryConfiguration where resourceType = 'AWS::EC2::Instance'"
```
 - Traceback for custodian run on test-config-query-ec2: 
   2021-04-30 13:16:24,284: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/resources/ec2.py", line 140, in resources
    return super(EC2, self).resources(query=query)
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/query.py", line 514, in resources
    resources = self.source.resources(query)
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/query.py", line 411, in resources
    for page in pager.paginate(Expression=query['expr']):
KeyError: 'expr'
2021-04-30 13:16:24,289: custodian.commands:ERROR Error while executing policy test-config-query-ec2, continuing
Traceback (most recent call last):
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/commands.py", line 272, in run
    policy()
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/policy.py", line 1178, in __call__
    resources = PullMode(self).run()
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/resources/ec2.py", line 140, in resources
    return super(EC2, self).resources(query=query)
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/query.py", line 514, in resources
    resources = self.source.resources(query)
  File "/Users/EAH523/policy-foundry/custodian/custodian-0.9.12/cloud-custodian_0.9.12/c7n/query.py", line 411, in resources
    for page in pager.paginate(Expression=query['expr']):
KeyError: 'expr'
2021-04-30 13:16:24,290: custodian.commands:ERROR The following policies had errors while executing

 - Output from custodian validate on test-config-query-ec2-clause: 
   2021-04-30 13:37:21,474: custodian.commands:ERROR Configuration invalid: test-config-query.yml
2021-04-30 13:37:21,474: custodian.commands:ERROR Policy: test-config-query is invalid: EC2 Query Filter invalid filter name {'clause': "resourceType = 'AWS::EC2::Instance'"}

 - Output from custodian validate on test-config-query-ec2-expr: 
2021-04-30 13:38:58,590: custodian.commands:ERROR Configuration invalid: test-config-query.yml
2021-04-30 13:38:58,590: custodian.commands:ERROR Policy: test-config-query is invalid: EC2 Query Filter invalid filter name {'expr': "select resourceId, configuration where resourceType = 'AWS::EC2::Instance'"}
   
 - `custodian version --debug` output
Custodian:   0.9.12
Python:      3.9.2 (default, Feb 24 2021, 13:30:36)
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='38f9d3a74321', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

PyJWT==1.7.1
PyYAML==5.4.1
adal==1.2.7
appdirs==1.4.4
applicationinsights==0.11.10
apscheduler==3.7.0
argcomplete==1.12.3
attrs==20.3.0
azure-common==1.1.27
azure-core==1.13.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.0
azure-graphrbac==0.61.1
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.1
azure-keyvault-secrets==4.2.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.2.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.0.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.4.2
azure-storage-queue==12.1.6
boto3==1.17.57
botocore==1.20.57
c7n==0.9.12
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.7
decorator==5.0.7
distlib==0.3.1
dogpile.cache==1.1.2
google-api-core==1.26.3
google-api-python-client==1.12.8
google-auth==1.29.0
google-auth-httplib2==0.1.0
google-cloud-core==1.6.0
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.37.1
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
httplib2==0.19.1
idna==2.10
importlib-metadata==4.0.1
iso8601==0.1.14
isodate==0.6.0
jmespath==0.10.0
jsonpatch==1.32
jsonpointer==2.1
jsonschema==3.2.0
keystoneauth1==4.3.1
kubernetes==10.0.1
msal==1.11.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
munch==2.5.0
netaddr==0.7.20
netifaces==0.10.9
oauthlib==3.1.0
openstacksdk==0.52.0
os-service-types==1.7.0
packaging==20.9
pbr==5.5.1
portalocker==1.7.1
protobuf==3.15.8
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.4.2
setuptools==49.2.1
six==1.15.0
stevedore==3.3.0
tabulate==0.8.9
typing-extensions==3.7.4.3
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.26.4
websocket-client==0.58.0
zipp==3.4.1

**Additional context**
I have tested identical versions of all three of these policies on other resource types (ex. dynamodb), and they all validate and run properly and return all instances of the given resource type in the account.  These issues also are occur when tested on 0.9.11.

**Comment by PratMis** [comment]
Looks like this section of the code(https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/ec2.py#L131-L156) is overriding the query expression irrespective of source(describe/config). Afaics, we may not need it anymore. Thoughts @kapilt ?

**Comment by kapilt** [comment]
we should make the extant ec2 query parser describe source only, query is specific to source. the ec2 one pre-dates our support of aws config.
