### ISSUE TITLE
Custodian crashes when using az cli auth and Azure-Identity 1.6.0

### ISSUE THREAD

**Issue by redNixon** [cloud-custodian/cloud-custodian#6684]
c7n_azure/session.AzureCredential: is throwing a ValueError exception when you try to use azure cli based authenication when azure-identity==1.6.0 is installed.  
  
azure-identity 1.6.0 included a mention of the change in the release notes but did not mark it as a breaking change:  https://github.com/Azure/azure-sdk-for-python/pull/18509 

> AzureCliCredential raises CredentialUnavailableError when the CLI times out, and kills timed out subprocesses

A new return pattern was introduced 
``` diff
@@ -120,25 +119,25 @@ def _run_command(command):
         if platform.python_version() >= "3.3":
             kwargs["timeout"] = 10
 
-        output = subprocess.check_output(args, **kwargs)
-        return output, None
+        return subprocess.check_output(args, **kwargs)
```

**To Reproduce**

1. Login with the azure cli
2. Do not have any other auth mechanism or env vars set
3. .Run `custodian run  --dryrun -s out  anyAzurePolicy.yml

The simplest fix would require a version bump of the minimum supported     
'azure-identity>=1.5.0,<2.0.0'
``` 
Traceback (most recent call last):
  File "/git/cloud-custodian/tools/c7n_azure/c7n_azure/session.py", line 177, in _initialize_session
    self.credentials = AzureCredential(
  File "/git/cloud-custodian/tools/c7n_azure/c7n_azure/session.py", line 93, in __init__
    account_info, error = _run_command('az account show --output json')
ValueError: too many values to unpack (expected 2)

**Comment by stefangordon** [comment]
Thank you for reporting.  I have confirmed the issue with the Azure Identity update released May 13th and I'm investigating.

@logachev

**Comment by stefangordon** [comment]
@redNixon I believe `azure-identity` is pinned to 1.5.0 - Did you manually upgrade it in your custodian env? 

We'll want to fix it regardless, but want to make sure I'm judging the priority correctly.

**Comment by redNixon** [comment]
Installing a new custodian environment can cause this to get pulled in depending on which route in the docs you go.

If you install custodian and c7n_azure using the [normal method](https://cloudcustodian.io/docs/quickstart/index.html#install-cc) using the pypi packages then azure-identity 1.5.0 will be installed.  However if you followed the [Azure specific](https://cloudcustodian.io/docs/azure/gettingstarted.html#install-cloud-custodian-and-azure-plugin) 'Getting Started' docs it suggests installing custodian in more a "dev env" like way.

```shell
$ python3 -m venv custodian
$ source custodian/bin/activate
$ git clone https://github.com/cloud-custodian/cloud-custodian.git
$ cd cloud-custodian
$ pip install -e .
$ pip install -e tools/c7n_azure
```

Following this section's install guide will result 1.6.0 being installed since it will look at tools/c7n_azure/setup.py(  '>=1.5.0,<2.0.0' ) for the the dependency list instead of requirements.txt file.

**Comment by stefangordon** [comment]
Thank you @redNixon
