### ISSUE TITLE
resource:iam-user filter:policy is broken.

### ISSUE THREAD

**Issue by aiell0** [cloud-custodian/cloud-custodian#670]
I am using the following policy:

```
policies:
  - name: name
    description: |
      some description
    resource: iam-user
    filters:
      - type: policy
```

Upon running that policy I receive the following error:

```
Traceback (most recent call last):
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/commands.py", line 114, in run
    policy()
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/policy.py", line 463, in __call__
    return mode.run()
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/policy.py", line 167, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/query.py", line 152, in resources
    return self.filter_resources(resources)
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/manager.py", line 63, in filter_resources
    resources = f.process(resources, event)
  File "/Users/laiello58/Development/git/cloud-custodian-aol-plugin/env/lib/python2.7/site-packages/c7n/resources/iam.py", line 457, in process
    if self.match(p):
AttributeError: 'UserAttachedPolicy' object has no attribute 'match'
```

If there is supposed to be more user input to make this work, it is not documented (in the code or otherwise).

**Comment by kapilt** [comment]
yeah.. i'm currently re-reviewing the iam filters that were contributed to validate some of the work done there, eta post reinvent.

**Comment by kapilt** [comment]
@joshuaroot look familiar

**Comment by joshuaroot** [comment]
I do see that, but I am not familiar with AttributeErrors being thrown. I'll check this out. Sorry for the lack of response, I must have missed this one.

**Comment by kapilt** [comment]
fix merged a while back, closing.
