### ISSUE TITLE
Error when auto-tagging AWS Backup Plans

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6761]
**Describe the bug**
I was attempting to auto-tag the creator of Backup Plans and ran into several errors

**To Reproduce**
```
- name: backup-plan-auto-tag-user
  resource: aws.backup-plan
  description: |
     Tags the user who created the backup plan
  mode:
     type: cloudtrail
     events:
        - source: backup.amazonaws.com
          event: CreateBackupPlan
          ids: "responseElements.backupPlanId"
  filters:
    - "tag:CreatorName": absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
```

**Expected behavior**
I would expect the backup plan to be tagged with the creator name

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15] AmazonLinux2 AMI latest
 - Python Version: [e.g. python 3.8.1] 3.8
 - Custodian Version: [e.g. 0.8.46.1] 0.9.11
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure] AWS
 - Policy: [please exclude any account/sensitive information]
```
- name: aws-backup-plan-auto-tag-user
  resource: aws.backup-plan
  description: |
     Tags the user who created the backup plan
  mode:
     type: cloudtrail
     events:
        - source: backup.amazonaws.com
          event: CreateBackupPlan
          ids: "responseElements.backupPlanId"
  filters:
    - "tag:CreatorName": absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 ```
 Copy
[ERROR]	2021-06-21T22:31:35.221Z	5835208c-f498-4f3a-8963-fba4517be4f4	Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 482, in run_resource_set
    results = action.process(resources, event)
  File "/var/task/c7n/actions/autotag.py", line 140, in process
    self.set_resource_tags(new_tags, untagged_resources)
  File "/var/task/c7n/actions/autotag.py", line 146, in set_resource_tags
    tag_action({'key': key, 'value': value}, self.manager).process(resources)
  File "/var/task/c7n/tags.py", line 838, in process
    _common_tag_processer(
  File "/var/task/c7n/tags.py", line 120, in _common_tag_processer
    raise error
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/tags.py", line 843, in process_resource_set
    arns = self.manager.get_arns(resource_set)
  File "/var/task/c7n/query.py", line 604, in get_arns
    arns.append(r[arn_key])
KeyError: 'BackupPlanArn'
[ERROR] 2021-06-21T22:31:35.221Z 5835208c-f498-4f3a-8963-fba4517be4f4 Error while executing policy Traceback (most recent call last): File "/var/task/c7n/policy.py", line 482, in run_resource_set results = action.process(resources, event) File "/var/task/c7n/actions/autotag.py", line 140, in process self.set_resource_tags(new_tags, untagged_resources) File "/var/task/c7n/actions/autotag.py", line 146, in set_resource_tags tag_action({'key': key, 'value': value}, self.manager).process(resources) File "/var/task/c7n/tags.py", line 838, in process _common_tag_processer( File "/var/task/c7n/tags.py", line 120, in _common_tag_processer raise error File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/var/task/c7n/tags.py", line 843, in process_resource_set arns = self.manager.get_arns(resource_set) File "/var/task/c7n/query.py", line 604, in get_arns arns.append(r[arn_key]) KeyError: 'BackupPlanArn'
2021-06-21T16:31:35.223-06:00
Copy
[ERROR]	2021-06-21T22:31:35.223Z	5835208c-f498-4f3a-8963-fba4517be4f4	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1143, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 454, in run
    return self.run_resource_set(event, resources)
  File "/var/task/c7n/policy.py", line 482, in run_resource_set
    results = action.process(resources, event)
  File "/var/task/c7n/actions/autotag.py", line 140, in process
    self.set_resource_tags(new_tags, untagged_resources)
  File "/var/task/c7n/actions/autotag.py", line 146, in set_resource_tags
    tag_action({'key': key, 'value': value}, self.manager).process(resources)
  File "/var/task/c7n/tags.py", line 838, in process
    _common_tag_processer(
  File "/var/task/c7n/tags.py", line 120, in _common_tag_processer
    raise error
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/tags.py", line 843, in process_resource_set
    arns = self.manager.get_arns(resource_set)
  File "/var/task/c7n/query.py", line 604, in get_arns
    arns.append(r[arn_key])
KeyError: 'BackupPlanArn'
[ERROR] 2021-06-21T22:31:35.223Z 5835208c-f498-4f3a-8963-fba4517be4f4 error during policy execution Traceback (most recent call last): File "/var/task/c7n/handler.py", line 165, in dispatch_event p.push(event, context) File "/var/task/c7n/policy.py", line 1143, in push return mode.run(event, lambda_ctx) File "/var/task/c7n/policy.py", line 454, in run return self.run_resource_set(event, resources) File "/var/task/c7n/policy.py", line 482, in run_resource_set results = action.process(resources, event) File "/var/task/c7n/actions/autotag.py", line 140, in process self.set_resource_tags(new_tags, untagged_resources) File "/var/task/c7n/actions/autotag.py", line 146, in set_resource_tags tag_action({'key': key, 'value': value}, self.manager).process(resources) File "/var/task/c7n/tags.py", line 838, in process _common_tag_processer( File "/var/task/c7n/tags.py", line 120, in _common_tag_processer raise error File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/var/task/c7n/tags.py", line 843, in process_resource_set arns = self.manager.get_arns(resource_set) File "/var/task/c7n/query.py", line 604, in get_arns arns.append(r[arn_key]) KeyError: 'BackupPlanArn'
2021-06-21T16:31:35.240-06:00
Copy
[ERROR] KeyError: 'BackupPlanArn'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1143, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 454, in run
    return self.run_resource_set(event, resources)
  File "/var/task/c7n/policy.py", line 482, in run_resource_set
    results = action.process(resources, event)
  File "/var/task/c7n/actions/autotag.py", line 140, in process
    self.set_resource_tags(new_tags, untagged_resources)
  File "/var/task/c7n/actions/autotag.py", line 146, in set_resource_tags
    tag_action({'key': key, 'value': value}, self.manager).process(resources)
  File "/var/task/c7n/tags.py", line 838, in process
    _common_tag_processer(
  File "/var/task/c7n/tags.py", line 120, in _common_tag_processer
    raise error
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/c7n/tags.py", line 843, in process_resource_set
    arns = self.manager.get_arns(resource_set)
  File "/var/task/c7n/query.py", line 604, in get_arns
    arns.append(r[arn_key])
    ```
 
 
 - `custodian version --debug` output
```
Custodian:   0.9.11
Python:      3.7.9 (default, Apr 30 2021, 20:11:56) 
             [GCC 7.3.1 20180712 (Red Hat 7.3.1-12)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-172-31-13-227.ec2.internal', release='4.14.232-176.381.amzn2.x86_64', version='#1 SMP Wed May 19 00:31:54 UTC 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.6
applicationinsights==0.11.9
apscheduler==3.7.0
argcomplete==1.12.2
attrs==20.3.0
azure-common==1.1.26
azure-core==1.12.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.6.0
azure-graphrbac==0.61.1
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.1
azure-keyvault-secrets==4.2.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.0.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.1.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.0.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.0.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.0.0
azure-mgmt-subscription==1.0.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.4.1
azure-storage-queue==12.1.5
boto3==1.17.33
botocore==1.20.33
c7n==0.9.11
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.6
distlib==0.3.1
google-api-core==1.26.1
google-api-python-client==1.12.8
google-auth==1.28.0
google-auth-httplib2==0.1.0
google-cloud-core==1.6.0
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.36.2
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
grpcio==1.36.1
httplib2==0.19.0
idna==2.10
importlib-metadata==3.7.3
importlib-resources==5.1.2
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
msal==1.10.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
packaging==20.9
portalocker==1.7.1
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyjwt==1.7.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.3.6
setuptools==47.1.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.26.4
zipp==3.4.1
```
**Additional context**

**Comment by khapp** [comment]
Is there any updates to this?  I ran into the exact same issue.
