### ISSUE TITLE
[aws.rds-snapshot.action.region-copy] Fails when 'copy_tags' is enabled and tags with the 'aws:' reserved prefix exist

### ISSUE THREAD

**Issue by jmdudley** [cloud-custodian/cloud-custodian#6782]
**Describe the bug**
`aws.rds-snapshot.action.region-copy` throws` botocore.exceptions.ClientError`, `InvalidParameterValue` when the `copy_tags` property is set to `true` as all tags from the original rds-snapshot resource, including the tags starting with `'aws:'`, are attempted to be copied.

**To Reproduce**
1. Copy/paste the policy from below
2. Run: custodian run -s . [policy-from-below].yml
3. See the error: `botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CopyDBSnapshot operation: Tag keys cannot start with the reserved prefix "aws:".`

**Expected behavior**
All tags should be copied from the original rds-snapshot resource to the newly created copy with the exception of any tags with keys beginning with the `'aws:'` reserved prefix.

**Background (please complete the following information):**
 - OS: Windows 10.0.18363 Build 18363
 - Python Version: Python 3.8.5
 - Custodian Version: 0.9.12
 - Cloud Provider: aws
 - Policy:
```yaml
---
vars:
  dr-tag-filter: &dtf
    - type: value
      key: tag:snapshot_dr_region
      op: eq
  origin-region-filter: &orf
    - type: value
      key: AvailabilityZone
      op: contains
  no-encryption-filter: &nef
    - type: value
      key: Encrypted
      op: eq
      value: false

policies:
  - name: rds-snapshot-dr-copy-us-east-1
    resource: aws.rds-snapshot
    filters:
      - and:
          - Status: available
          - <<: *dtf
            value: us-east-1
          - <<: *orf
            value: us-west-2
          - <<: *nef
          - tag:dr_snapshot_copied: absent
          - tag:snapshot_origin_region: absent
    actions:
      - type: region-copy
        target_region: us-east-1
        copy_tags: true ## currently 'true' errors as it tries to copy "aws:" tags
        tags:
          snapshot_origin_region: us-west-2
      - type: tag
        tags:
          dr_snapshot_copied: "{now:%Y-%m-%dT%H:%M:%S%z}"
```
 - Traceback:
 ```text
2021-07-01 15:51:44,028: custodian.cache:DEBUG Disabling cache
2021-07-01 15:51:44,029: custodian.commands:DEBUG Loaded file rds-snapshot-dr-copy-region.yml. Contains 2 policies
2021-07-01 15:51:44,040: custodian.aws:DEBUG using default region:us-west-2 from boto
2021-07-01 15:51:44,664: custodian.output:DEBUG Storing output with <LogFile file://.\rds-snapshot-dr-copy-us-east-1\custodian-run.log>
2021-07-01 15:51:44,676: custodian.policy:DEBUG Running policy:rds-snapshot-dr-copy-us-east-1 resource:aws.rds-snapshot region:us-west-2 c7n:0.9.12
2021-07-01 15:51:47,287: custodian.resources.rdssnapshot:DEBUG Filtered from 10 to 1 rdssnapshot
2021-07-01 15:51:47,288: custodian.policy:INFO policy:rds-snapshot-dr-copy-us-east-1 resource:aws.rds-snapshot region:us-west-2 count:1 time:2.61
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:ResourceCount Count:1 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot scope:policy
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:PolicyException Count:1 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:ApiCalls Count:3 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot
2021-07-01 15:51:50,589: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\policy.py", line 317, in run
    results = a.process(resources)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1348, in process
    self.process_resource_set(resource_set)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1397, in process_resource_set
    self.process_resource(target_client, target_key, rtags, r)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1371, in process_resource
    result = retry(target.copy_db_snapshot, **p)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\utils.py", line 444, in _retry
    return func(*args, **kw)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CopyDBSnapshot operation: Tag keys cannot start with the reserved prefix "aws:".
```
 - `custodian version --debug` output:
 ```text
2021-07-01 15:51:44,028: custodian.cache:DEBUG Disabling cache
2021-07-01 15:51:44,029: custodian.commands:DEBUG Loaded file rds-snapshot-dr-copy-region.yml. Contains 2 policies
2021-07-01 15:51:44,040: custodian.aws:DEBUG using default region:us-west-2 from boto
2021-07-01 15:51:44,664: custodian.output:DEBUG Storing output with <LogFile file://.\rds-snapshot-dr-copy-us-east-1\custodian-run.log>
2021-07-01 15:51:44,676: custodian.policy:DEBUG Running policy:rds-snapshot-dr-copy-us-east-1 resource:aws.rds-snapshot region:us-west-2 c7n:0.9.12
2021-07-01 15:51:47,287: custodian.resources.rdssnapshot:DEBUG Filtered from 10 to 1 rdssnapshot
2021-07-01 15:51:47,288: custodian.policy:INFO policy:rds-snapshot-dr-copy-us-east-1 resource:aws.rds-snapshot region:us-west-2 count:1 time:2.61
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:ResourceCount Count:1 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot scope:policy
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:PolicyException Count:1 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot
2021-07-01 15:51:50,588: custodian.output:DEBUG metric:ApiCalls Count:3 policy:rds-snapshot-dr-copy-us-east-1 restype:aws.rds-snapshot
2021-07-01 15:51:50,589: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\policy.py", line 317, in run
    results = a.process(resources)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1348, in process
    self.process_resource_set(resource_set)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1397, in process_resource_set
    self.process_resource(target_client, target_key, rtags, r)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\resources\rds.py", line 1371, in process_resource
    result = retry(target.copy_db_snapshot, **p)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\c7n\utils.py", line 444, in _retry
    return func(*args, **kw)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\username\AppData\Roaming\Python\Python38\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CopyDBSnapshot operation: Tag keys cannot start with the reserved prefix "aws:".
```

**Additional context**
Actual copying of the snapshot to region works fine as long as the `copy_tags:` property is set to `false`

**Comment by jmdudley** [comment]
It seems that this may only be an issue for snapshots created manually via the AWS console since they inherit **all** tags (including `aws:` tags) while automated snapshots only inherit tags without the `aws:` prefix.
