### ISSUE TITLE
DescribeInstances fails on a region with hundreds of thousands of instances

### ISSUE THREAD

**Issue by sean-zou** [cloud-custodian/cloud-custodian#6851]
**Describe the bug**
Getting this error on a region with hundreds of thousands of instances:
```
[ERROR] ClientError: An error occurred (InternalError) when calling the DescribeInstances operation (reached max retries: 4): An internal error has occurred
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1145, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 526, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 285, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/resources/ec2.py", line 140, in resources
    return super(EC2, self).resources(query=query)
  File "/var/task/c7n/query.py", line 518, in resources
    resources = self.source.resources(query)
  File "/var/task/c7n/query.py", line 223, in resources
    return self.query.filter(self.manager, **query)
  File "/var/task/c7n/query.py", line 75, in filter
    return self._invoke_client_enum(
  File "/var/task/c7n/query.py", line 56, in _invoke_client_enum
    data = results.build_full_result()
  File "/var/task/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/var/task/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/var/task/c7n/query.py", line 748, in _make_request
    return self.retry(self._method, **current_kwargs)
  File "/var/task/c7n/utils.py", line 444, in _retry
    return func(*args, **kw)
  File "/var/task/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
```
**To Reproduce**
Just run the policy

**Expected behavior**
No errors.

**Background (please complete the following information):**
 - OS: AWS Lambda
 - Python Version: Python 3.8
 - Custodian Version:0.9.13
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: ec2-inventory
    resource: aws.ec2
```

**Additional context**

**Comment by kapilt** [comment]
you should try configuring retry modes via environment variable or config file for the sdk 
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html

alternatively switch out to a different data source (config)

you seem to be running a  custom front end to apoll based policy in lambda, which is also not recommendable for any scale.

unfortunately we don't support custom front ends, as custodian is not a library.
