### ISSUE TITLE
AWS: --region all in conjunction with --assume invokes EC2:DescribeRegions using profile session client

### ISSUE THREAD

**Issue by robbie-demuth** [cloud-custodian/cloud-custodian#6884]
### Describe the bug

When running `custodian run --assume <SOME_ROLE_ARN> --region all` when `<SOME_ROLE_ARN>` has access to invoke EC2:DescribeRegions but the credentials picked up by the standard credentials chain do not, Cloud Custodian fails with the following error:

```
2021-09-07 14:16:11,947: custodian.commands:DEBUG Loaded file cloud-custodian/custodian.yml. Contains 1 policies
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 5, in <module>
    main()
  File "/src/c7n/cli.py", line 360, in main
    command(config)
  File "/src/c7n/commands.py", line 98, in _load_policies
    policies += provider.initialize_policies(
  File "/src/c7n/resources/aws.py", line 595, in initialize_policies
    get_profile_session(options).client('ec2').describe_regions(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation.
```

### What did you expect to happen?

It appears that Cloud Custodian invokes EC2:DescribeRegions using the profile session client:

https://github.com/cloud-custodian/cloud-custodian/blob/0.9.13.0/c7n/resources/aws.py#L592-L598

I would have expected Cloud Custodian to do so _after_ assuming the role defined by `<SOME_ROLE_ARN>`

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.13
Python:      3.8.10 (default, Jun  2 2021, 10:49:15) 
             [GCC 9.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='2b3470e2d4a2', release='5.10.47-linuxkit', version='#1 SMP Sat Jul 3 21:51:47 UTC 2021', machine='x86_64')
Using venv:  True
Docker: True
Installed: 

PyJWT==1.7.1
PyYAML==5.4.1
adal==1.2.7
appdirs==1.4.4
applicationinsights==0.11.10
apscheduler==3.7.0
argcomplete==1.12.3
attrs==21.2.0
azure-common==1.1.27
azure-core==1.15.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.2
azure-graphrbac==0.61.1
azure-identity==1.6.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.5.0
azure-storage-queue==12.1.6
boto3==1.17.102
botocore==1.20.102
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.7
decorator==5.0.9
distlib==0.3.2
dogpile.cache==1.1.3
google-api-core==1.30.0
google-api-python-client==1.12.8
google-auth==1.32.0
google-auth-httplib2==0.1.0
google-cloud-core==1.7.1
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.40.0
google-crc32c==1.1.2
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
httplib2==0.19.1
idna==2.10
importlib-metadata==4.6.0
iso8601==0.1.14
isodate==0.6.0
jmespath==0.10.0
jsonpatch==1.32
jsonpointer==2.1
jsonschema==3.2.0
keystoneauth1==4.3.1
kubernetes==10.0.1
msal==1.12.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
munch==2.5.0
netaddr==0.7.20
netifaces==0.11.0
oauthlib==3.1.1
openstacksdk==0.52.0
os-service-types==1.7.0
packaging==20.9
pbr==5.6.0
portalocker==1.7.1
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.4.2
setuptools==44.0.0
six==1.16.0
stevedore==3.3.0
tabulate==0.8.9
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.26.6
websocket-client==1.1.0
zipp==3.4.1
```

### Policy

```shell
policies:
  - name: garbage-collect-snapshots
    resource: ebs-snapshot
    max-resources-percent: 20
    query:
      - Name: tag:appian:system
        Values: [SiteWorkerGroupOperator]
    filters:
      - type: value
        key: tag:appian:deletion-protected
        op: ne
        value: "true"
      - type: value
        key: tag:appian:expires-at
        value_type: age
        op: gt
        value: 0
    actions:
      - delete
```

### Relevant log/traceback output

```shell
2021-09-07 14:16:11,947: custodian.commands:DEBUG Loaded file cloud-custodian/custodian.yml. Contains 1 policies
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 5, in <module>
    main()
  File "/src/c7n/cli.py", line 360, in main
    command(config)
  File "/src/c7n/commands.py", line 98, in _load_policies
    policies += provider.initialize_policies(
  File "/src/c7n/resources/aws.py", line 595, in initialize_policies
    get_profile_session(options).client('ec2').describe_regions(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation.
```

**Comment by kapilt** [comment]
Thanks for the bug report, agreed this should ideally be done post assumption as pre and post may have differential region enablement
