### ISSUE TITLE
auto-tag-user error NoneType when ec2 role has underscore in name

### ISSUE THREAD

**Issue by pjshort22** [cloud-custodian/cloud-custodian#6900]
### Describe the bug

After upgrade from Cloud Custodian v0.9.5.0 to 0.9.13.0 we are getting errors on auto-tag-user.

After investigation it is found to be an error with autotag.py after a recent update.

When auto-tag-user is processing an event with instance role and instance role has _ in the name it errors out with NoneType

Example policy
- name: ec2-unmark-running-autotag-start
  resource: ec2
  mode:
     type: cloudtrail
     events:
        - source: ec2.amazonaws.com
          event: StartInstances
          ids: "responseElements.instancesSet.items[].instanceId"
  actions:
    - type: unmark
      tags: ["c7n"]
    - type: auto-tag-user
      tag: ServerStartedBy

Example event with EC2 instance starting Server:

    "region": "us-east-1",
    "resources": [],
    "detail": {
        "eventVersion": "1.08",
        "userIdentity": {
            "type": "AssumedRole",
            "principalId": "AROAXXXXXXXXXXXXXXXXX:i-0XXXXXXXXXXXXXX",
            "arn": "arn:aws:sts::012345678901:assumed-role/XXX_Role/i-XXXXXXXXXXXXXXXXX"

Error message
[ERROR]	2021-09-21T15:46:28.924Z	93be044e-4dee-47f2-bc03-56cc6b531725	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1164, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 459, in run
    return self.run_resource_set(event, resources)
  File "/var/task/c7n/policy.py", line 487, in run_resource_set
    results = action.process(resources, event)
  File "/var/task/c7n/actions/autotag.py", line 131, in process
    if user_info['user']:
TypeError: 'NoneType' object is not subscriptable

This was workign fine in 0.9.05 but broken in 0.9.13.0

if the role XXX_Role is without _ ie XXXRole  it works fine.

### What did you expect to happen?

No errors when using role with underscore ie XXX_Role

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian v0.9.13.0 using c7n-org docker image 

https://hub.docker.com/r/cloudcustodian/c7n-org
```

### Policy

```shell
Example policy
- name: ec2-unmark-running-autotag-start
  resource: ec2
  mode:
     type: cloudtrail
     events:
        - source: ec2.amazonaws.com
          event: StartInstances
          ids: "responseElements.instancesSet.items[].instanceId"
  actions:
    - type: unmark
      tags: ["c7n"]
    - type: auto-tag-user
      tag: ServerStartedBy
```

### Relevant log/traceback output

```shell
[ERROR] TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1164, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 459, in run
    return self.run_resource_set(event, resources)
  File "/var/task/c7n/policy.py", line 487, in run_resource_set
    results = action.process(resources, event)
  File "/var/task/c7n/actions/autotag.py", line 131, in process
    if user_info['user']:
[ERROR] TypeError: 'NoneType' object is not subscriptable Traceback (most recent call last):   File "/var/task/custodian_policy.py", line 4, in run     return handler.dispatch_event(event, context)   File "/var/task/c7n/handler.py", line 165, in dispatch_event     p.push(event, context)   File "/var/task/c7n/policy.py", line 1164, in push     return mode.run(event, lambda_ctx)   File "/var/task/c7n/policy.py", line 459, in run     return self.run_resource_set(event, resources)   File "/var/task/c7n/policy.py", line 487, in run_resource_set     results = action.process(resources, event)   File "/var/task/c7n/actions/autotag.py", line 131, in process     if user_info['user']:
```

**Comment by ajkerrigan** [comment]
Thanks for reporting this @pjshort22 - it's a good question. This issue isn't related to the underscore though, it's the fact that the creator is an instance profile (I see the same error message on my end with or without an underscore in the role name). That case is one of a couple that are [specifically ignored](https://github.com/cloud-custodian/cloud-custodian/blob/78e28d6e7d65d0cdf1e9f1949ec4bf0b7b2df7f8/c7n/actions/autotag.py#L97-L102) in the `auto-tag-user` action.

What would you want to see as the tag value in this case... the role name? The instance ID? Both? :thinking:

**Comment by pjshort22** [comment]
@ajkerrigan thanks for the comments and yes see issue as well. It would be great if took the Instance Id or the role, and not just error. I say which ever is easiest. :-)
