### ISSUE TITLE
set-firewall-rules doesn't work on azure.sqlserver

### ISSUE THREAD

**Issue by danil2308** [cloud-custodian/cloud-custodian#6910]
### Describe the bug

down below I place my rule.yaml file content

```
policies:
- name: find-sqlserver-without-firewall-rules
  resource: azure.sqlserver
  filters:
    - type: value
      key: tag:andertest
      value: present
      value_regex: (yes)
    - type: value
      key: name
      value: present
      value_regex: (anderson*)

  actions:
    - type: set-firewall-rules
      bypass-rules:
          - AzureServices
      append: True
      ip-rules:
          - 11.12.13.0/16
```

If I only execute the filter part it would return the sql server I'm looking for, yet if I execute all together (filter and action) I'll receive the next error

```
2021-09-27 15:12:03,604: custodian.azure.sql-server:ERROR set-firewall-rules failed for 'andersonsqltest'.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/actions/base.py", line 69, in _process_resources
    result = self._process_resource(r)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/resources/sqlserver.py", line 363, in _process_resource
    self.client.firewall_rules.create_or_update(
TypeError: create_or_update() takes 5 positional arguments but 6 were given
2021-09-27 15:12:03,605: custodian.policy:INFO policy:find-sqlserver-without-firewall-rules action:sqlsetfirewallaction resources:1 execution_time:0.32
```
down below I leave my custodian version --debug command output.
```
 custodian version --debug                                 

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.13
Python:      3.8.10 (default, Jun  2 2021, 10:49:15)
             [GCC 9.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='1HKQ1F3', release='5.10.16.3-microsoft-standard-WSL2', version='#1 SMP Fri Apr 2 22:23:49 UTC 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed:

PyJWT==1.7.1
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.7.0
argcomplete==1.12.3
attrs==21.2.0
azure-common==1.1.27
azure-core==1.15.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.2
azure-graphrbac==0.61.1
azure-identity==1.6.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.5.0
azure-storage-queue==12.1.6
boto3==1.17.102
botocore==1.20.102
c7n==0.9.13
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.7
distlib==0.3.2
idna==2.10
importlib-metadata==4.6.0
importlib-resources==5.2.0
importlib_metadata==4.6.0
isodate==0.6.0
jmespath==0.10.0
jsonschema==3.2.0
msal==1.12.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.1
portalocker==1.7.1
pycparser==2.20
pyjwt==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.4.2
setuptools==44.0.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
tzlocal==2.1
urllib3==1.26.6
zipp==3.4.1
```
May I receive some help with this? Thanks

### What did you expect to happen?

I expected my old sql firewall rules to be removed and then having one new entry for "11.12.13.0/16"

### Cloud Provider

Microsoft Azure

### Policy

```shell
policies:
- name: find-sqlserver-without-firewall-rules
  resource: azure.sqlserver
  filters:
    - type: value
      key: tag:andertest
      value: present
      value_regex: (yes)
    - type: value
      key: name
      value: present
      value_regex: (anderson*)

  actions:
    - type: set-firewall-rules
      bypass-rules:
          - AzureServices
      append: True
      ip-rules:
          - 11.12.13.0/16
```

### Relevant log/traceback output
custodian run rules.yaml --verbose -m azure --output-dir=./results

```shell
2021-09-27 15:41:32,494: custodian.azure.session:INFO Authenticated [Azure CLI | a7ffc9c0-e376-4bb4-8f03-b13f138296d0]
2021-09-27 15:41:32,494: custodian.cache:DEBUG Using in-memory cache
2021-09-27 15:41:32,495: custodian.output:DEBUG Storing output with <LogFile file://./results/find-sqlserver-without-firewall-rules/custodian-run.log>
2021-09-27 15:41:32,495: custodian.policy:DEBUG Running policy:find-sqlserver-without-firewall-rules resource:azure.sqlserver region:AzureCloud c7n:0.9.13
2021-09-27 15:41:33,631: custodian.azure.utils.ServiceClient.send:DEBUG 200
2021-09-27 15:41:33,631: custodian.azure.utils.ServiceClient.send:DEBUG x-ms-ratelimit-remaining-subscription-reads:11999
2021-09-27 15:41:33,634: custodian.resources.sqlserver:DEBUG Filtered from 8 to 1 sqlserver
2021-09-27 15:41:33,635: custodian.policy:INFO policy:find-sqlserver-without-firewall-rules resource:azure.sqlserver region:AzureCloud count:1 time:1.14
2021-09-27 15:41:33,635: custodian.azure.utils.AppInsightsHelper:WARNING Bad format: 'azure://'
2021-09-27 15:41:33,635: custodian.azure.utils.AppInsightsHelper:WARNING Bad format: 'azure://'
2021-09-27 15:41:33,635: custodian.commands:ERROR Error while executing policy find-sqlserver-without-firewall-rules, continuing
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/utils.py", line 462, in get_instrumentation_key
    uuid.UUID(data)
  File "/usr/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/policy.py", line 304, in run
    self.policy.ctx.metrics.put_metric(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/output.py", line 263, in put_metric
    point = self._format_metric(key, value, unit, dimensions)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/output.py", line 120, in _format_metric
    self._initialize()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/output.py", line 115, in _initialize
    self.instrumentation_key = AppInsightsHelper.get_instrumentation_key(self.config['url'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/utils.py", line 467, in get_instrumentation_key
    return AppInsightsHelper._get_instrumentation_key(values[0], values[1])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/utils.py", line 462, in get_instrumentation_key
    uuid.UUID(data)
  File "/usr/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/policy.py", line 1205, in __call__
    resources = mode.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/policy.py", line 334, in run
    return resources
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/ctx.py", line 93, in __exit__
    self.metrics.put_metric('PolicyException', 1, "Count")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n/output.py", line 263, in put_metric
    point = self._format_metric(key, value, unit, dimensions)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/output.py", line 120, in _format_metric
    self._initialize()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/output.py", line 115, in _initialize
    self.instrumentation_key = AppInsightsHelper.get_instrumentation_key(self.config['url'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/c7n_azure/utils.py", line 467, in get_instrumentation_key
    return AppInsightsHelper._get_instrumentation_key(values[0], values[1])
IndexError: list index out of range
2021-09-27 15:41:33,639: custodian.commands:ERROR The following policies had errors while executing
 - find-sqlserver-without-firewall-rules
```

**Comment by kapilt** [comment]
whats the command line your using to run? @cloud-custodian/azure

**Comment by stefangordon** [comment]
Something a bit suspicious here - looks like the legacy start/end string definition we were using does not match the docs on the current library.

https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_azure/c7n_azure/resources/sqlserver.py#L363

https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.operations.firewallrulesoperations?view=azure-python#create-or-update-resource-group-name--server-name--firewall-rule-name--parameters----kwargs-

There are many unit tests but they all patch `azure.mgmt.sql.operations._firewall_rules_operations.FirewallRulesOperations.create_or_update`.

There are probably no live tests on the action because the legacy SQL firewall was very difficult to work with.  It appears the firewall and SDK have now been modernized and this bug was probably introduced during #6544.
