### ISSUE TITLE
aws.account filter default-ebs-encryption throws error when key does not exist

### ISSUE THREAD

**Issue by wiredin** [cloud-custodian/cloud-custodian#6914]
### Describe the bug

When using aws.account.filters.default-ebs-encryption and checking for which KMS key is being used for default encryption, if the KMS key and/or alias specified does not exist in the region in the account then CloudCustodian throws an error Key Error: 'account_id'

### What did you expect to happen?

CloudCustodian handles the fact that the key doesn't exist by returning a value of false for the filter check instead of an error.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.13
Python:      3.9.4 (default, Apr  5 2021, 01:49:30) 
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='REDACTED', release='19.6.0', version='Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.102
botocore==1.20.102
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.4.2
setuptools==54.2.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.6
zipp==3.4.1
```

### Policy

```shell
filters:
      - type: default-ebs-encryption
        key: "alias/aws/ebs"
        state: true
```

### Relevant log/traceback output

```shell
2021-09-29 22:21:52,216: c7n_org:ERROR Exception running policy:fed-sec-account-set-default-ebs-encryption-onetime account:pact-gov-testing-dev region:us-east-2 error:'account_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n_org/cli.py", line 563, in run_account
    resources = p.run()
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 1175, in __call__
    resources = PullMode(self).run()
  File "/usr/local/lib/python3.9/site-packages/c7n/policy.py", line 284, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.9/site-packages/c7n/resources/account.py", line 75, in resources
    return self.filter_resources([get_account(self.session_factory, self.config)])
  File "/usr/local/lib/python3.9/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.9/site-packages/c7n/filters/core.py", line 300, in process
    return self.process_set(resources, event)
  File "/usr/local/lib/python3.9/site-packages/c7n/filters/core.py", line 316, in process_set
    r[rtype_id] for r in f.process(resources, event)])
  File "/usr/local/lib/python3.9/site-packages/c7n/resources/account.py", line 1408, in process
    if not vf.process([{'KmsKeyId': key}]):
  File "/usr/local/lib/python3.9/site-packages/c7n/filters/kms.py", line 54, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "/usr/local/lib/python3.9/site-packages/c7n/filters/kms.py", line 54, in <listcomp>
    return [r for r in resources if self.process_resource(r, related)]
  File "/usr/local/lib/python3.9/site-packages/c7n/filters/related.py", line 79, in process_resource
    resource[model.id],
KeyError: 'account_id'
```

### Extra information or context

Seems related to this issue reported previously but closed. 
https://github.com/cloud-custodian/cloud-custodian/issues/5758

**Comment by wiredin** [comment]
In my case, alias/aws/ebs does not exist in the region I'm checking so C7N throws an error.
