### ISSUE TITLE
check-permissions filter not working on aws.iam-group resource

### ISSUE THREAD

**Issue by Cenisar-Villanueva** [cloud-custodian/cloud-custodian#7009]
### Describe the bug

When I tried to used the check-permissions filter on aws.iam-group resource I got an AttributeError

### What did you expect to happen?

I expect it will return the User group name that has the permission specified in the filter.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.13
Python:      3.8.5 (default, Jan 27 2021, 15:41:15) 
             [GCC 9.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='CODEV-LAPTOP-0123', release='5.4.72-microsoft-standard-WSL2', version='#1 SMP Wed Oct 28 23:40:43 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.20.10
botocore==1.23.10
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.5.0
setuptools==44.0.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.6
zipp==3.4.1
```

### Policy

```shell
policies:
  - name: iam-group-check-policy
    resource: aws.iam-group
    filters:
      - type: check-permissions
        match: allowed
        actions:
          - "cloudwatch:*"
```

### Relevant log/traceback output

```shell
custodian run -s output/ policies/test.yml --cache-period 0
2021-11-23 17:02:08,021: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/query.py", line 527, in resources
    resources = self.filter_resources(resources)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/resources/iam.py", line 685, in process
    evaluations = self.get_evaluations(client, arn, r, actions)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/resources/iam.py", line 759, in get_evaluations
    if self.boundaries:
AttributeError: 'CheckPermissions' object has no attribute 'boundaries'
2021-11-23 17:02:08,037: custodian.commands:ERROR Error while executing policy iam-group-check-policy, continuing
Traceback (most recent call last):
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/policy.py", line 1205, in __call__
    resources = mode.run()
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/query.py", line 527, in resources
    resources = self.filter_resources(resources)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/resources/iam.py", line 685, in process
    evaluations = self.get_evaluations(client, arn, r, actions)
  File "/home/cenisar/Virtual_Environments/Cloud_Custoidan_venv/custodian/lib/python3.8/site-packages/c7n/resources/iam.py", line 759, in get_evaluations
    if self.boundaries:
AttributeError: 'CheckPermissions' object has no attribute 'boundaries'
2021-11-23 17:02:08,040: custodian.commands:ERROR The following policies had errors while executing
 - iam-group-check-policy
```

### Extra information or context

This is the IAM policy attached to the group with Cloudwatch Full Access.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "autoscaling:Describe*",
                "cloudwatch:*",
                "logs:*",
                "sns:*",
                "iam:GetPolicy",
                "iam:GetPolicyVersion",
                "iam:GetRole"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "arn:aws:iam::*:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents*",
            "Condition": {
                "StringLike": {
                    "iam:AWSServiceName": "events.amazonaws.com"
                }
            }
        }
    ]
}

**Comment by ajkerrigan** [comment]
Thanks for reporting this @Cenisar-Villanueva - it's a good catch! Looks like we were building a collection of permission boundaries for IAM entity types that support them, but then checking that collection later for _all_ entity types.

While testing this I found that we had an option to opt-out of checking boundaries and it wasn't working. That led to #7012, which should fix the issue you're seeing and also allow check-permissions filters with `boundaries: False` to avoid considering boundaries.

**Comment by Cenisar-Villanueva** [comment]
Thanks for checking @ajkerrigan 
Let me know once fixed is deployed so I can test on my side.

**Comment by ajkerrigan** [comment]
> Thanks for checking @ajkerrigan Let me know once fixed is deployed so I can test on my side.

The fix is merged - you can install and test from master today, or wait for the next release.
