### ISSUE TITLE
ResourceConflictException when calling the UpdateFunctionConfiguration operation

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#7010]
### Ask your question

_**Note:** This is a placeholder issue detailing errors that will occur beginning December 6th, 2021 when using a Cloud Custodian version lower than 0.9.14 to update existing Cloud Custodian Lambda functions. This is due to an [AWS change](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) , which Cloud Custodian accommodates in version 0.9.14+ thanks to #6969._

When attempting to _update_ an existing Cloud Custodian policy deployed as a Lambda function, I see the following error:

```
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-2:123456789012:function:custodian-my-test-policy
```

**Fix:** Updating Cloud Custodian to [0.9.14](https://github.com/cloud-custodian/cloud-custodian/releases/tag/0.9.14.0) handles Lambda state changes appropriately and avoids this issue.

### Policy

```shell
policies:
  - name: my-test-policy
    resource: asg
    mode:
      type: cloudtrail
      events:
        - source: autoscaling.amazonaws.com
          event: CreateAutoScalingGroup
          ids: requestParameters.autoScalingGroupName
      role: custodian
```

### Relevant log/traceback output

```shell
2021-11-23 14:37:41,250: custodian.commands:DEBUG Loaded file /home/aj/code/sandbox-policies/my-test-policy.yml. Contains 1 policies
2021-11-23 14:37:41,278: custodian.aws:DEBUG using default region:us-east-2 from boto
2021-11-23 14:37:41,572: custodian.output:DEBUG Storing output with <LogFile file:///home/aj/c7n-out/my-test-policy/custodian-run.log>
2021-11-23 14:37:41,603: custodian.policy:INFO Provisioning policy lambda: my-test-policy region: us-east-2
2021-11-23 14:37:41,797: custodian.serverless:DEBUG Created custodian serverless archive size: 0.47mb
2021-11-23 14:37:41,970: custodian.serverless:DEBUG Updating function custodian-my-test-policy code
2021-11-23 14:37:42,873: custodian.serverless:DEBUG Updating function: custodian-my-test-policy config MemorySize
2021-11-23 14:37:42,968: custodian.output:DEBUG metric:PolicyException Count:1 policy:my-test-policy restype:asg
2021-11-23 14:37:42,968: custodian.output:DEBUG metric:ApiCalls Count:3 policy:my-test-policy restype:asg
2021-11-23 14:37:42,968: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/aj/code/cloud-custodian/c7n/policy.py", line 513, in provision
    return manager.publish(
  File "/home/aj/code/cloud-custodian/c7n/mu.py", line 385, in publish
    result, changed = self._create_or_update(
  File "/home/aj/code/cloud-custodian/c7n/mu.py", line 490, in _create_or_update
    result = self.client.update_function_configuration(**new_config)
  File "/home/aj/.pyenv/versions/c7n-dev/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/aj/.pyenv/versions/c7n-dev/lib/python3.9/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-2:123456789012:function:custodian-my-test-policy
2021-11-23 14:37:42,971: custodian.commands:ERROR Error while executing policy my-test-policy, continuing
Traceback (most recent call last):
  File "/home/aj/code/cloud-custodian/c7n/commands.py", line 301, in run
    policy()
  File "/home/aj/code/cloud-custodian/c7n/policy.py", line 1203, in __call__
    resources = mode.provision()
  File "/home/aj/code/cloud-custodian/c7n/policy.py", line 513, in provision
    return manager.publish(
  File "/home/aj/code/cloud-custodian/c7n/mu.py", line 385, in publish
    result, changed = self._create_or_update(
  File "/home/aj/code/cloud-custodian/c7n/mu.py", line 490, in _create_or_update
    result = self.client.update_function_configuration(**new_config)
  File "/home/aj/.pyenv/versions/c7n-dev/lib/python3.9/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/aj/.pyenv/versions/c7n-dev/lib/python3.9/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-2:123456789012:function:custodian-my-test-policy
```

**Comment by ajkerrigan** [comment]
Going to close this since "upgrade to 0.9.14+" is the resolution.
