### ISSUE TITLE
SNS remove-statements action on single statement policy

### ISSUE THREAD

**Issue by mattheidelbaugh** [cloud-custodian/cloud-custodian#7011]
### Describe the bug

When I run a policy with the remove-statements action on an sns topic whose policy only has a singular statement, the SetAttributes API call that custodian makes fails with an AttributeError on the policy.  

### What did you expect to happen?

I expected it to remove that singular statement resulting in an empty/nonexistent policy for that topic.  

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.14
Python:      3.8.10 (default, Nov  9 2021, 15:22:20) 
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='38f9d3a53571', release='19.6.0', version='Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.20.2
botocore==1.23.2
cffi==1.15.0
cryptography==35.0.0
importlib-metadata==4.8.2
jmespath==0.10.0
jsonschema==3.2.0
pycparser==2.21
pyrsistent==0.18.0
python-dateutil==2.8.2
pyyaml==5.4.1
s3transfer==0.5.0
setuptools==56.0.0
six==1.16.0
tabulate==0.8.9
urllib3==1.26.7
zipp==3.6.0
```

### Policy

```shell
policies:
- name: sns-public-access-correct
  resource: aws.sns
  mode:
    type: cloudtrail
    events:
    - event: CreateTopic
      ids: requestParameters.topicArn
      source: sns.amazonaws.com
    - event: SetTopicAttributes
      ids: requestParameters.topicArn
      source: sns.amazonaws.com
  filters:
  - type: cross-account
    whitelist_from:
      expr: accounts.*.account
      url: accounts-aws.json
  actions:
  - type: remove-statements
    statement_ids: matched
```

### Relevant log/traceback output

```shell
[ERROR]	2021-11-23T18:39:22.038Z	3e33a498-420c-4f35-b3c0-851e3646a158	Error processing sns:arn:aws:sns:us-east-1:111222333444:test-noncompliant
Traceback (most recent call last):
  File "/var/task/c7n/resources/sns.py", line 286, in process
    results += filter(None, [self.process_resource(client, r)])
  File "/var/task/c7n/resources/sns.py", line 304, in process_resource
    client.set_topic_attributes(
  File "/opt/python/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: Policy Error: null
[ERROR] 2021-11-23T18:39:22.038Z 3e33a498-420c-4f35-b3c0-851e3646a158 Error processing sns:arn:aws:sns:us-east-1:851925785310:ipat-o16pa5-external-account-noncompliant Traceback (most recent call last): File "/var/task/c7n/resources/sns.py", line 286, in process results += filter(None, [self.process_resource(client, r)]) File "/var/task/c7n/resources/sns.py", line 304, in process_resource client.set_topic_attributes( File "/opt/python/botocore/client.py", line 388, in _api_call return self._make_api_call(operation_name, kwargs) File "/opt/python/botocore/client.py", line 708, in _make_api_call raise error_class(parsed_response, operation_name) botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the SetTopicAttributes operation: Invalid parameter: Policy Error: null
```

**Comment by ajkerrigan** [comment]
Hi @mattheidelbaugh, thanks for providing the full context along with this issue. The AWS API won't let you set an empty access policy for an SNS topic. One way to get around that is providing your own replacement policy statement. We can do that from the Custodian side as part of the `modify-policy` action. It looks like the [docs](https://cloudcustodian.io/docs/aws/resources/aws-common-actions.html#aws-common-actions-modify-policy) for that action use an SQS example policy, but an SNS example might look like:

```
policies:
  - name: sns-replace-cross-account
    resource: sns
    filters:
      - type: cross-account
    actions:
      - type: modify-policy
        add-statements:
          - Sid: CrossAccountReplacement
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sns:GetTopicAttributes
            Resource: "*"
            Condition:
              StringEquals:
                "AWS:SourceOwner": "{account_id}"
        remove-statements: matched
```

In this example, we replace the offending cross-account statement(s) with a policy that is a more limited version of the default policy AWS uses for new topics.

As far as "is this a bug?" I don't think we can do this sort of replacement automatically because it's a judgement call. But it seems reasonable to provide a clearer message for the "empty policy" case and offer suggestions.

**Comment by mattheidelbaugh** [comment]
@ajkerrigan Thanks very much for the response! This is extremely helpful.
