### ISSUE TITLE
Strange runtime behavior when running c7n-org against multiple azure subscriptions

### ISSUE THREAD

**Issue by psilohanf** [cloud-custodian/cloud-custodian#7041]
### Describe the bug

When I run c7n-org against our 70 subscriptions I get lots of warnings and errors after some time into the action:
```
2021-12-29 17:43:45,495: c7n_org:WARNING Error running policy in <subscription-name1> @ global exception: 1
2021-12-29 17:43:45,552: c7n_org:WARNING Error running policy in <subscription-name2> @ global exception: 1
...
```
After a few of these warnings the output changes to a lot of:
`AzureCliCredential.get_token failed: Failed to invoke the Azure CLI`
and then back to the warnings.

Looking into the run-log of the issuing subscription I see:
```
2021-12-29 17:43:44,929 - custodian.azure.session - ERROR - Failed to authenticate.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/c7n_azure/session.py", line 175, in _initialize_session
    self.credentials = AzureCredential(
  File "/usr/local/lib/python3.9/site-packages/c7n_azure/session.py", line 94, in __init__
    account_json = json.loads(account_info)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

  But when I try the same thing with a smaller subset of subscriptions including the ones issuing the warnings then everything runs okay.

### What did you expect to happen?

I expected this to run without errors like on a smaller subset (tried about eight).

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.14
Python:      3.9.9 (main, Nov 21 2021, 03:23:42)
             [Clang 13.0.0 (clang-1300.0.29.3)]
Platform:    posix.uname_result(sysname='Darwin', nodename='<nodename>', release='20.6.0', version='Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed:

PyJWT==1.7.1
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.8.1
argcomplete==1.12.3
attrs==21.2.0
azure-common==1.1.27
azure-core==1.20.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.2
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.3.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.9.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.6.0
azure-storage-queue==12.1.6
backports.zoneinfo==0.2.1
boto3==1.19.12
botocore==1.22.12
c7n==0.9.14
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.4
cryptography==35.0.0
distlib==0.3.3
docutils==0.17.1
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.4.0
isodate==0.6.0
jmespath==0.10.0
jsonschema==3.2.0
msal==1.16.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.1
portalocker==1.7.1
pycparser==2.21
pyjwt==1.7.1
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
pyyaml==5.4.1
requests==2.26.0
requests-oauthlib==1.3.0
s3transfer==0.5.0
setuptools==59.0.1
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.2
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.7
zipp==3.6.0
```

### Policy

```shell
policies:
    - name: check-mandatory-readers
      description: |
        "A definite set of reader roles must be assigned"
      resource: azure.subscription
      filters:
        - or:
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                # these must be checked for
                - type: value
                  key: "principalName"
                  value: "wertshnrteu"
                  op: eq
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                - type: value
                  key: "principalName"
                  value: "etz3zteh"
                  op: eq
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                - type: value
                  key: "principalName"
                  value: "wersfgsdfger"
                  op: eq
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                - type: value
                  key: "principalName"
                  value: "eztwtrwrt"
                  op: eq
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                - type: value
                  key: "principalName"
                  value: "asfgafasf"
                  op: eq
          - type: missing
            policy:
              resource: azure.roleassignment
              filters:
                - type: role
                  key: properties.roleName
                  op: eq
                  value: Reader
                - type: value
                  key: "principalName"
                  value: "asdf"
                  op: eq
      # here comes the action...
```

### Relevant log/traceback output

```shell
see above
```

**Comment by kapilt** [comment]
hmmm.. I wonder if there is some sort of credential file refresh happening in the background.. thoughts @logachev ?
