### ISSUE TITLE
KeyError: 'isMfaDeleteEnabled' error when running s3 config policy

### ISSUE THREAD

**Issue by cjhallman** [cloud-custodian/cloud-custodian#7042]
### Describe the bug

Received key error: 

> KeyError: 'isMfaDeleteEnabled'

 when running simple custodian policy with `source: config` for` resource: aws.s3`.

### What did you expect to happen?

I expected the policy to pull back all s3 buckets in the account

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.14
Python:      3.9.5 (default, May  4 2021, 03:33:11) 
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='3c22fb4babd9', release='19.6.0', version='Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.20.21
botocore==1.23.21
cffi==1.15.0
cryptography==36.0.0
importlib-metadata==4.8.2
jmespath==0.10.0
jsonschema==3.2.0
pycparser==2.21
pyrsistent==0.18.0
python-dateutil==2.8.2
pyyaml==5.4.1
s3transfer==0.5.0
setuptools==60.2.0
six==1.16.0
tabulate==0.8.9
typing-extensions==4.0.1
urllib3==1.26.7
zipp==3.6.0
```

### Policy

```shell
policies:
  - name: config
    resource: {{resource_name}}
    source: config
```

### Relevant log/traceback output

```shell
2021-12-29 15:55:18,918: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 522, in resources
    resources = self.source.resources(query)
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 416, in resources
    results.extend([
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 417, in <listcomp>
    self.load_resource(json.loads(r)) for r in page['Results']])
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/resources/s3.py", line 122, in load_resource
    method(resource, v)
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/resources/s3.py", line 306, in handle_BucketVersioningConfiguration
    if item_value['isMfaDeleteEnabled']:
KeyError: 'isMfaDeleteEnabled'
2021-12-29 15:55:18,920: custodian.commands:ERROR Error while executing policy config, continuing
Traceback (most recent call last):
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/policy.py", line 1204, in __call__
    resources = PullMode(self).run()
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 522, in resources
    resources = self.source.resources(query)
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 416, in resources
    results.extend([
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/query.py", line 417, in <listcomp>
    self.load_resource(json.loads(r)) for r in page['Results']])
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/resources/s3.py", line 122, in load_resource
    method(resource, v)
  File "/Users/DLX707/Desktop/repos/enterprise-policies/.venv/lib/python3.9/site-packages/c7n/resources/s3.py", line 306, in handle_BucketVersioningConfiguration
    if item_value['isMfaDeleteEnabled']:
KeyError: 'isMfaDeleteEnabled'
```

**Comment by cjhallman** [comment]
This is actually the same issue as https://github.com/cloud-custodian/cloud-custodian/issues/5068

**Comment by ajkerrigan** [comment]
Thanks for the report and for proactively hunting down the duplicate @cjhallman ! I'll close this and take a look at the original issue.
