### ISSUE TITLE
Azure c7n-mailer not deploying properly

### ISSUE THREAD

**Issue by mikejgray** [cloud-custodian/cloud-custodian#7044]
### Describe the bug

When I tried to deploy the Azure c7n-mailer as a Function App using a SystemAssigned identity, it failed with errors in two locations.

1. azure-identity was not part of the dependencies, causing execution to fail when using the SystemAssigned identity
2. A Session class is initialized using the wrong kwarg:
```python
Error starting mailer MailerAzureQueueProcessor(). 
 Error: __init__() got an unexpected keyword argument 'resource' 
Traceback (most recent call last):
  File "/home/site/wwwroot/c7n_mailer/azure_mailer/handle.py", line 14, in start_c7n_mailer
    session = Session(authorization_file=auth_file, resource=STORAGE_AUTH_ENDPOINT)
TypeError: __init__() got an unexpected keyword argument 'resource'
```
Changing `resource` to `resource_endpoint_type` allows for successful execution.

@ajkerrigan suggested I submit a PR for these fixes and I'll add some tests to avoid future regressions as well.

### What did you expect to happen?

I expected the deployed function to execute correctly and pull messages from the queue, but it didn't.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.14
Python:      3.9.1 (default, Mar 10 2021, 13:44:38) 
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='poseidon.local', release='20.6.0', version='Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

PyJWT==1.7.1
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.8.1
argcomplete==1.12.3
attrs==21.2.0
azure-common==1.1.27
azure-core==1.20.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.2
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.3.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.9.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.6.0
azure-storage-queue==12.1.6
backports.zoneinfo==0.2.1
boto3==1.19.12
botocore==1.22.12
c7n==0.9.14
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.4
cryptography==35.0.0
distlib==0.3.3
docutils==0.17.1
google-api-core==2.2.2
google-api-python-client==2.29.0
google-auth==2.3.3
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.0
google-cloud-audit-log==0.2.0
google-cloud-core==2.1.0
google-cloud-logging==2.7.0
google-cloud-monitoring==2.6.0
google-cloud-storage==1.42.3
google-crc32c==1.3.0
google-resumable-media==2.1.0
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
grpcio==1.41.1
grpcio-status==1.41.1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.4.0
isodate==0.6.0
jmespath==0.10.0
jsonschema==3.2.0
msal==1.16.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.1
packaging==21.2
portalocker==1.7.1
proto-plus==1.19.7
protobuf==3.19.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyjwt==1.7.1
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.26.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.5.0
setuptools==49.2.1
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.2
tzdata==2021.5
tzlocal==4.1
uritemplate==4.1.1
urllib3==1.26.7
zipp==3.6.0
```

### Policy

```shell
N/A
```

### Relevant log/traceback output

```shell
Error starting mailer MailerAzureQueueProcessor(). 
 Error: __init__() got an unexpected keyword argument 'resource' 
Traceback (most recent call last):
  File "/home/site/wwwroot/c7n_mailer/azure_mailer/handle.py", line 14, in start_c7n_mailer
    session = Session(authorization_file=auth_file, resource=STORAGE_AUTH_ENDPOINT)
TypeError: __init__() got an unexpected keyword argument 'resource'
```

**Comment by ajkerrigan** [comment]
In case it ends up being useful later, I'll just add this [link](https://gitter.im/cloud-custodian/cloud-custodian?at=61ce2be4d143b14f83f2e9f1) to the Gitter thread where you raised and worked through this issue. Thanks again @mikejgray for logging this :+1: !
