### ISSUE TITLE
AWS ssm-data-sync resource has id mapped incorrectly to 'DataSync' when it should be 'SyncName'

### ISSUE THREAD

**Issue by mcripps9** [cloud-custodian/cloud-custodian#7169]
### Describe the bug

The ssm-data-sync resource has the id mapped as 'DataSync' instead of 'SyncName' causing 'custodian report' to fail with a KeyError.  In c7n/resources/ssm.c around like 789:
```
@resources.register('ssm-data-sync')
class SSMDataSync(QueryResourceManager):
    """Resource for AWS DataSync
    https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-inventory-datasync.html
    """
    class resource_type(TypeInfo):

        enum_spec = ('list_resource_data_sync', 'ResourceDataSyncItems', None)
        service = 'ssm'
        arn_type = 'datasync'
        id = 'DataSync'
```
should be:
```
        id = 'SyncName'
```
Typical output of aws ssm list-resource-data-sync is:
```
        {
            "SyncName": "InspectorResourceDataSync-do-not-delete",
            "S3Destination": {
                "BucketName": "inspector-inventory-prod-us-east-1-abc123456789",
                "SyncFormat": "JsonSerDe",
                "Region": "us-east-1",
                "AWSKMSKeyARN": "arn:aws:kms:us-east-1:01234567890:alias/SnpKmsKey"
            },
            "LastSyncTime": "2022-03-16T13:08:12.263000-04:00",
            "LastSuccessfulSyncTime": "2022-03-16T13:08:12.263000-04:00",
            "SyncLastModifiedTime": "2021-12-03T10:38:12.234000-05:00",
            "LastStatus": "Successful",
            "SyncCreatedTime": "2021-12-03T10:38:12.234000-05:00",
            "LastSyncStatusMessage": "The sync was successfully completed"
        },
```

### What did you expect to happen?

aws.ssm-data-sync policies should execute and report correctly.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.15
Python:      3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05) 
             [Clang 13.0.0 (clang-1300.0.29.3)]
Platform:    posix.uname_result(sysname='Darwin', nodename='REDACTED.local', release='20.6.0', version='Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==21.4.0
boto3==1.21.20
botocore==1.24.20
docutils==0.17.1
importlib-metadata==4.11.2
importlib-resources==5.4.0
jmespath==0.10.0
jsonschema==4.4.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.5.2
six==1.16.0
tabulate==0.8.9
typing-extensions==4.1.1
urllib3==1.26.8
zipp==3.7.0
```

### Policy

```shell
- name: aws-ssm-data-sync
  resource: aws.ssm-data-sync
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/Users/REDACTED/custodian/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/cli.py", line 363, in main
    command(config)
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/commands.py", line 127, in _load_policies
    return f(options, list(policies))
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/commands.py", line 331, in report
    do_report(
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/reports/csvout.py", line 99, in report
    rows = formatter.to_csv(records, unique=not options.all_findings)
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/reports/csvout.py", line 215, in to_csv
    uniq = self.uniq_by_id(records)
  File "/Users/REDACTED/custodian/lib/python3.9/site-packages/c7n/reports/csvout.py", line 197, in uniq_by_id
    rec_id = rec[self._id_field]
KeyError: 'DataSync'
```

### Extra information or context

Yes, I actually found a use for this resource!

**Comment by ajkerrigan** [comment]
Thanks for raising this @mcripps9 - the fix will be live in the next release (which should be 0.9.17.0).
