### ISSUE TITLE
[GCP] sourcerepo resource type fails to scan

### ISSUE THREAD

**Issue by SaMnCo** [cloud-custodian/cloud-custodian#7247]
### Describe the bug

Running a policy like 

```
- name: gcp-sourcerepo
  resource: gcp.sourcerepo
```

will result in an error 

```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sourcerepo.googleapis.com/v1/projects/project-name-/repos?alt=json returned "Permission denied on resource project project-name-.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/project-name-/apiui/credential'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'CONSUMER_INVALID', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/project-name-', 'service': 'sourcerepo.googleapis.com'}}]">
```
Effectively looking at the `source.py`, 

```
        scope_key = 'name'
        scope_template = "projects/{}-"
        name = id = 'name'
```
It seems there is a typo in the `scope_template`

### What did you expect to happen?

Policy should return the list of sourcerepo 

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.15
Python:      3.9.4 (default, Apr 19 2021, 13:14:41) 
             [GCC 9.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='stacklet', release='5.13.0-40-generic', version='#45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==21.4.0
boto3==1.22.6
botocore==1.25.6
c7n==0.9.15
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.9
docutils==0.17.1
google-api-core==2.7.3
google-api-python-client==2.47.0
google-auth==2.6.6
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.1
google-cloud-audit-log==0.2.0
google-cloud-core==2.3.0
google-cloud-logging==2.7.1
google-cloud-monitoring==2.9.1
google-cloud-storage==1.44.0
google-crc32c==1.3.0
google-resumable-media==2.3.2
googleapis-common-protos==1.56.0
grpc-google-iam-v1==0.12.4
grpcio==1.46.0
httplib2==0.20.4
idna==3.3
importlib-metadata==4.11.3
importlib-resources==5.7.1
jmespath==0.10.0
jsonschema==4.4.0
packaging==16.8
proto-plus==1.20.3
protobuf==3.20.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.6
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.3
pyyaml==6.0
ratelimiter==1.2.0.post0
requests==2.26.0
retrying==1.3.3
rsa==4.8
s3transfer==0.5.2
six==1.16.0
tabulate==0.8.9
typing-extensions==4.2.0
uritemplate==4.1.1
urllib3==1.26.9
zipp==3.8.0
```

### Policy

```shell
- name: gcp-sourcerepo
  resource: gcp.sourcerepo
```

### Relevant log/traceback output

```shell
2022-05-10 11:45:46,388: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 192, in resources
    resources = self._fetch_resources(q)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 212, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 75, in get_resources
    return self.query.filter(self.manager, **query)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 49, in filter
    return self._invoke_client_enum(
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 55, in _invoke_client_enum
    for page in client.execute_paged_query(enum_op, params):
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/client.py", line 422, in execute_paged_query
    response = self._execute(request)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/client.py", line 489, in _execute
    return request.execute(http=self.http,
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sourcerepo.googleapis.com/v1/projects/project-name-/repos?alt=json returned "Permission denied on resource project project-name-.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/project-name-/apiui/credential'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'CONSUMER_INVALID', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/project-name-', 'service': 'sourcerepo.googleapis.com'}}]">
2022-05-10 11:45:46,389: custodian.commands:ERROR Error while executing policy gcp-sourcerepo, continuing
Traceback (most recent call last):
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n/policy.py", line 1210, in __call__
    resources = mode.run()
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n/policy.py", line 290, in run
    resources = self.policy.resource_manager.resources()
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 192, in resources
    resources = self._fetch_resources(q)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 212, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 75, in get_resources
    return self.query.filter(self.manager, **query)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 49, in filter
    return self._invoke_client_enum(
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/query.py", line 55, in _invoke_client_enum
    for page in client.execute_paged_query(enum_op, params):
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/client.py", line 422, in execute_paged_query
    response = self._execute(request)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/c7n_gcp/client.py", line 489, in _execute
    return request.execute(http=self.http,
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/scozannet/.pyenv/versions/3.9.4/envs/experiments/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://sourcerepo.googleapis.com/v1/projects/project-name-/repos?alt=json returned "Permission denied on resource project project-name-.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/project-name-/apiui/credential'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'CONSUMER_INVALID', 'domain': 'googleapis.com', 'metadata': {'consumer': 'projects/project-name-', 'service': 'sourcerepo.googleapis.com'}}]">
```

**Comment by ajkerrigan** [comment]
Nailed it @SaMnCo, thanks for the detailed report :+1: . Looking to sort this out in #7267 .
