### ISSUE TITLE
c7n-mailer: Custodian Mailer Error

### ISSUE THREAD

**Issue by shakusbakus** [cloud-custodian/cloud-custodian#7502]
### Describe the bug

When i try and use a freshly deployed mailer it fails to start, so it cant process the messages in SQS

### What did you expect to happen?

Messages processed and email notifications sent 

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.16
Python:      3.9.9 (main, Nov 21 2021, 03:22:47)
             [Clang 12.0.0 (clang-1200.0.32.29)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MCP27LML7L', release='21.3.0', version='Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed:

argcomplete==2.0.0
attrs==21.4.0
boto3==1.21.42
botocore==1.24.42
docutils==0.17.1
importlib-metadata==4.11.3
jmespath==1.0.0
jsonschema==4.4.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.5.2
six==1.16.0
tabulate==0.8.9
urllib3==1.26.9
zipp==3.8.0
```

### Policy

```shell
ami-age policy

{
  "execution-options": {},
  "policies": [{
    "name": "ami-age",
    "resource": "ami",
    "mode": {
      "role": "arn:aws:iam::123456789012:role/CloudCustodianRole",
      "type": "periodic",
      "memory": 192,
      "schedule": "rate(1 hour)",
      "tags": {
        "custodian-info": "mode=periodic:version=0.9.16"
      }
    },
    "filters": [{
        "type": "image-age",
        "op": "greater-than",
        "days": 1
      },
      {
        "tag:maid_status": "absent"
      },
      {
        "type": "unused"
      }
    ],
    "actions": [{
        "type": "mark-for-op",
        "op": "deregister",
        "days": 1
      },
      {
        "type": "notify",
        "template": "default",
        "priority_header": "2",
        "subject": "AMIs - Over Sixty Days Old Policy - ami-patrol - [custodian {{ account_id }} - {{ region }}]",
        "to": [
          "adam.roberts@rackspace.com"
        ],
        "transport": {
          "type": "sqs",
          "queue": "https://sqs.eu-west-1.amazonaws.com/123456789012/c7n-mailer"
        }
      }
    ]
  }]
}
mailer policy

{
  "queue_url": "https://sqs.eu-west-1.amazonaws.com/123456789012/c7n-mailer",
  "role": "arn:aws:iam:: 123456789012:role/CloudCustodianRole",
  "from_address": "rhys.izzard@rackspace.com",
  "region": "eu-west-1",
  "lambda_tags": {
    "owner": "ops"
  },
  "ses_region": "eu-west-1",
  "memory": 1024,
  "runtime": "python3.7",
  "timeout": 300,
  "subnets": null,
  "security_groups": null,
  "contact_tags": [],
  "ldap_uri": null,
  "ldap_bind_dn": null,
  "ldap_bind_user": null,
  "ldap_bind_password": null,
  "endpoint_url": null,
  "datadog_api_key": null,
  "slack_token": null,
  "slack_webhook": null,
  "templates_folders": ["msg-templates/"]
}
```

### Relevant log/traceback output

```shell
Mailer Policy output 


START RequestId: 9b2c832c-6775-4d8e-b371-340d66b7d1d3 Version: $LATEST
[WARNING] 2022-06-21T09:18:53.579Z 9b2c832c-6775-4d8e-b371-340d66b7d1d3 Unknown sqs_message or sns format {
"Type" : "Notification",
"MessageId" : "ec2a
[ERROR] 2022-06-21T09:18:53.580Z 9b2c832c-6775-4d8e-b371-340d66b7d1d3 Error starting mailer MailerSqsQueueProcessor().
Error: Error -3 while decompressing data: incorrect header check
Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 33, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 118, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 137, in process_sqs_message
sqs_message = json.loads(zlib.decompress(base64.b64decode(body)))
zlib.error: Error -3 while decompressing data: incorrect header check
END RequestId: 9b2c832c-6775-4d8e-b371-340d66b7d1d3
REPORT RequestId: 9b2c832c-6775-4d8e-b371-340d66b7d1d3 Duration: 575.43 ms Billed Duration: 576 ms Memory Size: 1024 MB Max Memory Used: 116 MB
```

### Extra information or context

Messages hit SQS but the mailer cant process them.

**Comment by ajkerrigan** [comment]
Hmm is it possible you have something else sending to that queue? Possibly manual test messages generated outside custodian? It may be worth trying some local tests using `c7n-mailer-replay` to see if it can parse and format messages from the queue. For example this will fetch and save a message from your mailer queue locally:

```
aws sqs receive-message \
  --queue-url https://sqs.eu-west-1.amazonaws.com/123456789012/c7n-mailer \
  --query 'Messages[0].Body' \
  --output text | tee mailer-replay.gz
```

And if you have a developer installation of c7n installed at `~/cloud-custodian`, you would be able to run something like:

```
c7n-mailer-replay -t ~/cloud-custodian/msg-templates -c <path to your mailer config>.yml -T mailer-replay.gz
```

To see if that produces a rendered mailer notification body for the given SQS message.
