### ISSUE TITLE
Unhandled exception when deleting protected instances

### ISSUE THREAD

**Issue by fivetran-kirillkobylyanskiy** [cloud-custodian/cloud-custodian#7555]
### Describe the bug

If the rds/ec2 instance is protected from deletion, it could not be deleted and I see exception traceback.
Due to this error, **other instances cannot be modified with the same policy**.

### What did you expect to happen?

I expect to see just warning message or something like this. And certainly I want other instances to be modified.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n:0.9.13.0
```

### Policy

```shell
- name: terminate_instances
    resource: aws.ec2
    filters:
      - type: value
        key: tag:expires_on
        value: 28
        op: gt
        value_type: age
    actions:
    - type: terminate
```

### Relevant log/traceback output

```shell
2022-07-06 05:23:49,214: custodian.policy:INFO policy:terminate_instances resource:aws.ec2 region:us-west-1 count:21 time:0.03
2022-07-06 05:23:50,168: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 322, in run
    results = a.process(resources)
  File "/src/c7n/resources/ec2.py", line 1544, in process
    self.manager.retry(
  File "/src/c7n/utils.py", line 446, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (OperationNotPermitted) when calling the TerminateInstances operation: The instance 'instance-id' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.
```
```


### Extra information or context

_No response_

**Comment by jtroberts83** [comment]
@fivetran-kirillkobylyanskiy You will need to specify the `force: true` attribute to get past the termination protection. If you view the schema via running the command: custodian schema ec2.actions.terminate

Schema
------

properties:
  force:
    type: boolean
  type:
    enum:
    - terminate
required:
- type

**Comment by Paladin-Dranser** [comment]
Hi @fivetran-kirillkobylyanskiy,

you can try to use [termination-protected](https://cloudcustodian.io/docs/aws/resources/ec2.html#termination-protected) filter for ec2 as a workaround, for example:

```yaml
policies:
  - name: termination-protection-NOT-enabled
    resource: ec2
    filters:
      - not:
        - type: termination-protected
```
