### ISSUE TITLE
ci - doc builds not using cache and thus taking excess time

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#7620]
### Describe the bug

doc builds should be utilizing a cache to avoid having to recompile docs from scratch vs an incremental build.

### What did you expect to happen?

https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true

```
Run (poetry run custodian version && echo "::set-output name=venv::success") || (rm -rf .venv && echo "::set-output name=venv::recreate")
[8](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:9)
Creating virtualenv c7n-5MWOw5K9-py3.8 in /home/runner/.cache/pypoetry/virtualenvs
[9](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:10)
Traceback (most recent call last):
[10](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:11)
  File "<string>", line 1, in <module>
[11](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:12)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
[12](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:13)
    return _bootstrap._gcd_import(name[level:], package, level)
[13](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:14)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[14](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:15)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[15](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:16)
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[16](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:17)
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[17](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:18)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
[18](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:19)
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[19](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:20)
  File "/home/runner/work/cloud-custodian/cloud-custodian/c7n/cli.py", line 7, in <module>
[20](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:21)
    import argcomplete
[21](https://github.com/cloud-custodian/cloud-custodian/runs/7727283875?check_suite_focus=true#step:8:22)
ModuleNotFoundError: No module named 'argcomplete'
```

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
fix merged in #7621
