### ISSUE TITLE
s3-public-block-enable-all

### ISSUE THREAD

**Issue by nick4646** [cloud-custodian/cloud-custodian#7678]
### Describe the bug

When I run "s3-public-block-enable-all" policy, I am running into local SSL certificate issue. Unable to figure out the problem. I tried running different policies and they are all working fine except for this one. 

### What did you expect to happen?

I want to block public access on aws s3 buckets.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.18
Python:      3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Platform:    posix.uname_result(sysname='Darwin', nodename='WFS-C02H83WTQ05N', release='21.3.0', version='Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101', machine='arm64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.1.0
boto3==1.24.44
botocore==1.27.44
docutils==0.17.1
importlib-metadata==4.12.0
jmespath==1.0.1
jsonschema==4.9.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
urllib3==1.26.11
zipp==3.8.1
```

### Policy

```shell
policies:
  - name: s3-public-block-enable-all
    resource: s3
    filters:
      - type: check-public-block
    actions:
      - type: set-public-block
```

### Relevant log/traceback output

```shell
raceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 523, in resources
    resources = self.source.resources(query)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 223, in resources
    return self.query.filter(self.manager, **query)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 75, in filter
    return self._invoke_client_enum(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 59, in _invoke_client_enum
    data = op(**params)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 898, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/httpsession.py", line 475, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://s3.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
2022-08-22 16:38:35,748: custodian.commands:ERROR Error while executing policy s3-public-block-enable-all, continuing
Traceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 1280, in __call__
    resources = PullMode(self).run()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 523, in resources
    resources = self.source.resources(query)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 223, in resources
    return self.query.filter(self.manager, **query)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 75, in filter
    return self._invoke_client_enum(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 59, in _invoke_client_enum
    data = op(**params)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 898, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/Users/BAlavindla/wfs-solution-cloud-custodian/custodian/lib/python3.10/site-packages/botocore/httpsession.py", line 475, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://s3.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
2022-08-22 16:38:35,749: custodian.commands:ERROR The following policies had errors while executing
 - s3-public-block-enable-all
```

### Extra information or context

kindly please help.

**Comment by thisisshi** [comment]
are you running the policy on a corporate network or vpn? you may need to set your HTTP_PROXY/HTTPS_PROXY env vars

**Comment by nick4646** [comment]
Thanks Sonny. 

This is running as expected when I export the ca certs.
