### ISSUE TITLE
Incorrect parsing of Data LifeCycle Manager policy tags

### ISSUE THREAD

**Issue by kjsch** [cloud-custodian/cloud-custodian#7699]
### Describe the bug

When running a dlm policy that uses tags in the filter, get the error: AttributeError: 'str' object has no attribute 'get'

### What did you expect to happen?

Expected c7n to filter the resources based on given tag values.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.18
Python:      3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Platform:   win32
Using venv:  True
Docker: False
Installed:

argcomplete==2.0.0
attrs==22.1.0
boto3==1.24.44
botocore==1.27.44
docutils==0.17.1
importlib-metadata==4.12.0
importlib-resources==5.7.1
jmespath==1.0.1
jsonschema==4.9.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.2.0
urllib3==1.26.11
zipp==3.8.0
```

### Policy

```shell
policies:

  - name: no-error
    resource: aws.dlm-policy
    description: "This policy does not hit the error"
    filters:
      - type: value
        key: StatusMessage
        op: not-equal
        value: "ENABLED"

  - name: error
    resource: aws.dlm-policy
    description: "This policy errors due to tag bug in filter"
    filters:
      - type: value
        key: StatusMessage
        op: not-equal
        value: "ENABLED"
      - not:
        - "tag:some-tag": "some-value"

  - name: error2
    resource: aws.dlm-policy
    description: "This policy also errors due to tag bug in filter"
    filters:
      - type: value
        key: "tag:some-tag"
        value: absent
```

### Relevant log/traceback output

```shell
2022-08-29 09:05:07,591: custodian.policy:INFO policy:no-error resource:aws.dlm-policy region:us-east-2 count:1 time:0.00
2022-08-29 09:05:07,628: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "C:\Users\user\custodian\lib\site-packages\c7n\query.py", line 532, in resources
    resources = self.filter_resources(resources)
  File "C:\Users\user\custodian\lib\site-packages\c7n\manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 378, in process
    return self.process_set(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 397, in process_set
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 553, in process
    return super(ValueFilter, self).process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 190, in process
    return list(filter(self, resources))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 540, in __call__
    matched = self.match(i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 576, in match
    r = self.get_resource_value(self.k, i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 556, in get_resource_value
    return super(ValueFilter, self).get_resource_value(k, i, self.data.get('value_regex'))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 236, in get_resource_value
    if t.get('Key') == tk:
AttributeError: 'str' object has no attribute 'get'
2022-08-29 09:05:07,649: custodian.commands:ERROR Error while executing policy error, continuing
Traceback (most recent call last):
  File "C:\Users\user\custodian\lib\site-packages\c7n\commands.py", line 301, in run
    policy()
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 1286, in __call__
    resources = mode.run()
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "C:\Users\user\custodian\lib\site-packages\c7n\query.py", line 532, in resources
    resources = self.filter_resources(resources)
  File "C:\Users\user\custodian\lib\site-packages\c7n\manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 378, in process
    return self.process_set(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 397, in process_set
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 553, in process
    return super(ValueFilter, self).process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 190, in process
    return list(filter(self, resources))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 540, in __call__
    matched = self.match(i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 576, in match
    r = self.get_resource_value(self.k, i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 556, in get_resource_value
    return super(ValueFilter, self).get_resource_value(k, i, self.data.get('value_regex'))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 236, in get_resource_value
    if t.get('Key') == tk:
AttributeError: 'str' object has no attribute 'get'
2022-08-29 09:05:07,675: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "C:\Users\user\custodian\lib\site-packages\c7n\query.py", line 532, in resources
    resources = self.filter_resources(resources)
  File "C:\Users\user\custodian\lib\site-packages\c7n\manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 553, in process
    return super(ValueFilter, self).process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 190, in process
    return list(filter(self, resources))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 540, in __call__
    matched = self.match(i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 576, in match
    r = self.get_resource_value(self.k, i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 556, in get_resource_value
    return super(ValueFilter, self).get_resource_value(k, i, self.data.get('value_regex'))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 236, in get_resource_value
    if t.get('Key') == tk:
AttributeError: 'str' object has no attribute 'get'
2022-08-29 09:05:07,690: custodian.commands:ERROR Error while executing policy error2, continuing
Traceback (most recent call last):
  File "C:\Users\user\custodian\lib\site-packages\c7n\commands.py", line 301, in run
    policy()
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 1286, in __call__
    resources = mode.run()
  File "C:\Users\user\custodian\lib\site-packages\c7n\policy.py", line 293, in run
    resources = self.policy.resource_manager.resources()
  File "C:\Users\user\custodian\lib\site-packages\c7n\query.py", line 532, in resources
    resources = self.filter_resources(resources)
  File "C:\Users\user\custodian\lib\site-packages\c7n\manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 553, in process
    return super(ValueFilter, self).process(resources, event)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 190, in process
    return list(filter(self, resources))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 540, in __call__
    matched = self.match(i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 576, in match
    r = self.get_resource_value(self.k, i)
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 556, in get_resource_value
    return super(ValueFilter, self).get_resource_value(k, i, self.data.get('value_regex'))
  File "C:\Users\user\custodian\lib\site-packages\c7n\filters\core.py", line 236, in get_resource_value
    if t.get('Key') == tk:
AttributeError: 'str' object has no attribute 'get'
2022-08-29 09:05:07,694: custodian.commands:ERROR The following policies had errors while executing
 - error
 - error2
```

### Extra information or context

It appears that the c7n filter code expects the returned tag info to be an array of objects with 'Key' and 'Value' keys, but the DLM API returns a 'Tags' object with each tag being a key/value.

```
$ aws dlm get-lifecycle-policies
{
    "Policies": [
        {
            "PolicyId": "policy-003ec5a7028453d10",
            "Description": "testing",
            "State": "DISABLED",
            "Tags": {
                "k1": "v1",
                "k2": "v2"
            },
            "PolicyType": "EBS_SNAPSHOT_MANAGEMENT"
        }
    ]
}
```

**Comment by thisisshi** [comment]
Thanks for the bug report, I'll take a look at this
