### ISSUE TITLE
test case `test_value_from_sqlkv` failed

### ISSUE THREAD

**Issue by kentnsw** [cloud-custodian/cloud-custodian#7728]
Spent quite some time on it but I don't know what I miss. The cache got closed after `get`.

https://github.com/cloud-custodian/cloud-custodian/blob/a38464e809db68f76983ce9779d8712c4b19a525/tests/test_resolver.py#L114

```
❯ pytest tests/test_resolver.py -k test_value_from_sqlkv
Test session starts (platform: darwin, Python 3.9.13, pytest 7.1.2, pytest-sugar 0.9.5)
rootdir: /Users/ouj/repos/ncttools/nct-cloud-custodian/lib/cloud-custodian, configfile: tox.ini
plugins: cov-2.12.1, xdist-2.5.0, forked-1.4.0, sugar-0.9.5, terraform-0.6.1
collecting ...

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_value_from_sqlkv ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Traceback (most recent call last):
  File "/Users/ouj/repos/ncttools/nct-cloud-custodian/lib/cloud-custodian/tests/test_resolver.py", line 114, in test_value_from_sqlkv
    assert values.get_values() == {"magic"}
  File "/Users/ouj/repos/ncttools/nct-cloud-custodian/lib/cloud-custodian/c7n/resolver.py", line 171, in get_values
    self.cache.save(("value-from", key), contents)
  File "/Users/ouj/repos/ncttools/nct-cloud-custodian/lib/cloud-custodian/c7n/cache.py", line 162, in save
    with self.conn as cursor:
AttributeError: __enter__
------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------
cache::__enter__
cache::get::key ('value-from', ['moon', 'json', '[].bean'])
cache::__exit__
cache::close
cache::save::key ('value-from', ['moon', 'json', '[].bean'])

 tests/test_resolver.py ⨯                                                                                                                                          100% ██████████
================================================================================ warnings summary ================================================================================
../../../../../Library/Caches/pypoetry/virtualenvs/c7n-gekGVErX-py3.9/lib/python3.9/site-packages/botocore/httpsession.py:41
  /Users/ouj/Library/Caches/pypoetry/virtualenvs/c7n-gekGVErX-py3.9/lib/python3.9/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================ short test summary info =============================================================================
FAILED tests/test_resolver.py::test_value_from_sqlkv - AttributeError: __enter__

Results (0.09s):
       1 failed
         - tests/test_resolver.py:106 test_value_from_sqlkv
      17 deselected
```

**Comment by ajkerrigan** [comment]
Appreciate you testing out the tweaked cache implementation, it's good to have more folks using it ahead of release!

As for this error, I can't replicate it though it does look similar to one of the cache issues I hit recently. Is your local environment using a commit that includes #7711?

**Comment by kentnsw** [comment]
@ajkerrigan thank you for your hints, I found the root cause. It was because the resolver.py hasn't been merged correctly in my fork. The code following `with self.cache:` should be kept inside.
