### ISSUE TITLE
Azure: Error installing new version of custodian

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#7783]
If using `cloudcustodian/c7n:0.9.10.0` or below. I am able to install cloud custodian and it works but as soon as I upgrade to `cloudcustodian/c7n:0.9.11.0` or anything after `10` its failing with the below message:

```
Updating event grid subscriptions
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2022-09-21 02:45:51 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 286, in create_container
    return self._client.container.create( # type: ignore
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 134, in create
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'No Content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py", line 514, in create_container
    container.create_container(
  File "/usr/local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 294, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/usr/local/lib/python3.8/site-packages/azure/core/exceptions.py", line 218, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_container_client.py", line 286, in create_container
    return self._client.container.create( # type: ignore
  File "/usr/local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 134, in create
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'No Content'
ErrorCode:None
```

Running in Azure ACI</div>

As AJ pointed out, may be related to this: https://github.com/Azure/azure-cli/issues/19530

**Comment by kapilt** [comment]
per the referenced issue we might need to just update our sdk. specifically blob client, that's pretty strange though, if their changing core blob store behavior.

**Comment by tomarv2** [comment]
@kapilt wanted to follow up on this and see if there is a plan to release with the upgraded sdk soon?
