### ISSUE TITLE
Tagging failing for ARM resource of SQL database

### ISSUE THREAD

**Issue by psilohanf** [cloud-custodian/cloud-custodian#7794]
### Describe the bug

I am running a simple tagging action policy against all ARM resources in a subscription. It works for most of the resources except a few. One of them is the SQL database resource. Despite being "taggable" (also via the web console) it throws an error when custodian tries to do that.

### What did you expect to happen?

Resources of type SQL database shall be tagged like other ARM resources in the same subscription.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.18
Python:      3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Platform:    posix.uname_result(sysname='Darwin', nodename='ckrueger-MBP', release='21.6.0', version='Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed:

PyJWT==2.4.0
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.9.1
argcomplete==2.0.0
attrs==22.1.0
azure-common==1.1.28
azure-core==1.24.2
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.11.2
azure-graphrbac==0.61.1
azure-identity==1.10.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.4.0
azure-keyvault-keys==4.5.1
azure-keyvault-secrets==4.4.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.3.1
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.1
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.13.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.9.0
azure-storage-queue==12.4.0
boto3==1.24.44
botocore==1.27.44
c7n==0.9.18
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
click==8.1.3
cryptography==37.0.4
distlib==0.3.5
docutils==0.17.1
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
isodate==0.6.1
jmespath==1.0.1
jsonschema==4.9.0
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.2.0
pkgutil-resolve-name==1.3.10
portalocker==2.5.1
pycparser==2.21
pyjwt==2.4.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
pyyaml==6.0
requests==2.28.1
requests-oauthlib==1.3.1
s3transfer==0.6.0
setuptools==63.4.3
six==1.16.0
tabulate==0.8.10
typing-extensions==4.3.0
tzdata==2022.2
tzlocal==4.2
urllib3==1.26.11
zipp==3.8.1
```

### Policy

```shell
policies:
    - name: tag-all-resources
      description: |
        Adds the mandatory tags to all resources in this subscription
      resource: azure.armresource
      actions:
       - type: tag
         tag: team
         value: team-name
       - type: tag
         tag: contactemail
         value: user@example.com
       - type: tag
         tag: costtag
         value: fancytag
```

### Relevant log/traceback output

```shell
2022-09-26 14:30:21,318: custodian.azure.tagging.Tag:ERROR tag failed for 'path-to-SQL-db-resource'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/c7n_azure/actions/base.py", line 69, in _process_resources
    result = self._process_resource(r)
  File "/usr/local/lib/python3.10/site-packages/c7n_azure/actions/tagging.py", line 72, in _process_resource
    return TagHelper.add_tags(self, resource, new_tags)
  File "/usr/local/lib/python3.10/site-packages/c7n_azure/tags.py", line 80, in add_tags
    TagHelper.update_resource_tags(tag_action, resource, tags)
  File "/usr/local/lib/python3.10/site-packages/c7n_azure/tags.py", line 32, in update_resource_tags
    raise NotImplementedError('Cannot tag resource with type {0}'
NotImplementedError: Cannot tag resource with type Microsoft.Sql/servers/databases
```

**Comment by kxs-mdoyon** [comment]
Getting same bug here.
