### ISSUE TITLE
c7n-salactus gives syntax error 

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7829]
### Describe the bug

I have installed the redis-server, get it running, installed supervisor and run the `supervisord.conf` file as well. But when I run `c7n-salactus --help`, I got a syntax error. 

### What did you expect to happen?

Well,  I expect it to give me a help menu. 

### Cloud Provider

Amazon Web Services (AWS)

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/home/ubuntu/custodian/bin/c7n-salactus", line 11, in <module>
    load_entry_point('c7n-salactus==0.3.0', 'console_scripts', 'c7n-salactus')()
  File "/home/ubuntu/custodian/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/custodian/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ubuntu/custodian/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ubuntu/custodian/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/custodian/lib/python3.8/site-packages/c7n_salactus/cli.py", line 251
    def reset(async=None):
              ^
SyntaxError: invalid syntax
```

**Comment by ajkerrigan** [comment]
Thanks for the report @haiauth :+1: . I'm seeing the same issue installing `0.3.0` from PyPI. Looks like that's dying because in current versions of Python, `async` is a keyword. However, it looks like #2608 fixed this issue in salactus back in 2018. Salactus isn't part of the typical release bundle, but this suggests we need to get a new release published. Given the time since last release, I wouldn't be surprised if we find other issues in the process.

**Comment by haiauth** [comment]
@ajkerrigan Thank you for your response. Do you have a timeline when the new release/fix will be released?
