### ISSUE TITLE
AWS Glue Connections/Catalog Keys Not Being Validated

### ISSUE THREAD

**Issue by vparv** [cloud-custodian/cloud-custodian#7895]
### Describe the bug

When setting encryption for a glue connection or glue catalog, the KMS key ARN is not validated before being applied to the resource. This can lead to invalid KMS key ARNs being applied to resources. On the other hand, the same invalid key ARN would not be able to be applied using the AWS console, as there is validation being done before applying.

### What did you expect to happen?

I expected for Cloud Custodian to not apply the invalid key and return an error. Instead, it will allow the key to be applied and no error is shown.

### Cloud Provider

Amazon Web Services (AWS)

**Comment by vparv** [comment]
The tests in test_glue.py are faulty as they apply an alias to the key ARN field within the console. Custodian allows them to apply it, but if you try to save it within the console, it will give you an error. 

Please see the image below when I ran test_glue_datacat_put_encryption and applied alias/skunk/glue/encrypted as SseAwsKmsKeyId using the set-encryption action.

![Screen Shot 2022-10-20 at 11 43 18 AM](https://user-images.githubusercontent.com/44989522/196996292-b5963e20-14ba-4d58-af1f-cbfee805e8f1.jpg)

The same is true when applying a AWS KMS Key Id for Glue Connection password encryption. Allowed to apply invalid keys using Custodian but not on the console.

**Comment by PratMis** [comment]
Hi @vparv, yes this seems to be a problem from AWS side. Technically, we shouldn't have to get into the business of validating kms key arns. For all the services, AWS does it for us. I tried to create an ebs-snapshot with an invalid key and I got this
```
>>> response = client.start_snapshot(VolumeSize=10, Encrypted=True, KmsKeyArn='arn:aws:kms:us-east-1:644160558196:key/082cd05f-96d1-49f6-a5ac-32093d2cfe58')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yxd411/development/cloud-custodian/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/yxd411/development/cloud-custodian/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the StartSnapshot operation: Invalid parameters for a dependent service: com.amazonaws.services.kms.model.NotFoundException: Key 'arn:aws:kms:us-east-1:644160558196:key/082cd05f-96d1-49f6-a5ac-32093d2cfe58' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: 77a58a3f-728e-4d25-8ad3-6475fcc5f782; Proxy: null)
```
For glue, AWS forgot to cover that for us. We also ran into this issue where people could apply a random key alias to encrypt their glue catalog. We raised this issue and looks like they fixed their console. But the apis are still not fixed. Does that make sense? I think the solution here would be to only pass a valid key for now. I don't think custodian ever validates or checks for the existence of a kms key.

**Comment by PratMis** [comment]
I think when we developed this feature for catalog, we assumed that AWS wouldn't let you pass in an invalid key.

**Comment by PratMis** [comment]
Apparently, AWS seems to have fixed this. They still do not validate the key but they don't let you create a database or data store if the key is not valid
