### ISSUE TITLE
Error when S3 bucket does not have tags

### ISSUE THREAD

**Issue by dre2004** [cloud-custodian/cloud-custodian#7899]
### Describe the bug

I have a policy that checks that all my S3 buckets have encryption turned on and if they don't it will tag them. When a bucket has no tags the interpolate_values method from the Tags class errors.

### What did you expect to happen?

That an S3 bucket not having any tags is handled correctly.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n:0.9.16
```

### Policy

```shell
name: s3-bucket-encryption-off
notify_only: True
resource: s3
filters:
  - type: bucket-encryption
    state: False
actions:
  - type: tag
    tags:
      CloudCustodianS3EncryptionOff: True
  - type: notify
    slack_template: slack_notify
    slack_msg_color: danger
    to:
      - https://hooks.slack.com/services/XXXXXXXXXXXXXXXX
    transport:
      type: sqs
      queue: '%%MAILER_QUEUE_URL%%'
mode:
  schedule: rate(1 hour)
  type: periodic
```

### Relevant log/traceback output

```shell
[ERROR]	2022-10-18T10:54:30.175Z	59a6212e-d114-443a-836a-3b6150074f0f	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1201, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 536, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 322, in run
    results = a.process(resources)
  File "/var/task/c7n/tags.py", line 410, in process
    self.interpolate_values(tags)
  File "/var/task/c7n/tags.py", line 433, in interpolate_values
    t['Value'] = t['Value'].format(**params)
```

### Extra information or context

I am using the `custodian c7n:0.9.16` container. I've had a quick look at the code and I am guessing that whatever the interpolate_values method is being sent is a boolean rather than a list of tags.

https://github.com/cloud-custodian/cloud-custodian/blob/6f0617f384e954947149bfafc3ab9db9bd6cb822/c7n/tags.py#L427-L433

I have found the corresponding event in CloudTrail, here is a snippet of the request.

```
    "eventTime": "2022-10-18T11:15:57Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "GetBucketTagging",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "XXX.XXX.XXX.XXX",
    "userAgent": "[CloudCustodian(s3-bucket-encryption-off)/0.9.16 Python/3.9.13 Linux/4.14.255-276-224.499.amzn2.x86_64 exec-env/AWS_Lambda_python3.9 Botocore/1.23.32]",
    "errorCode": "NoSuchTagSet",
    "errorMessage": "The TagSet does not exist",
    "requestParameters": {
        "tagging": "",
        "bucketName": "some-bucket-name",
        "Host": "some-bucket-name.s3.us-west-2.amazonaws.com"
    },
```

According to the API, GetBucketTagging has a special error `NoSuchTagSet` that is returned if a bucket does not have a tag set associated with it.

- [API GetBucketTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketTagging.htm)

**Comment by sanjeev98kumar** [comment]
Will this be a good first issue to start with? I am looking for my first PR
