### ISSUE TITLE
Cache error on some long running policies

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#7936]
### Describe the bug

Ran into this when trying to delete/deregister ecs task definitions. Apparently, because the number of resources were too high

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.19
Python:      3.9.15 (main, Oct 11 2022, 22:27:25)
             [Clang 14.0.0 (clang-1400.0.29.102)]
Using venv:  True
```

### Policy

```shell
- name: ecstaskdfntn-delete
  resource: aws.ecs-task-definition
  filters:
  - tag:xyz: absent
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/c7n/policy.py", line 302, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.7/dist-packages/c7n/query.py", line 536, in resources
    self._cache.save(cache_key, resources)
  File "/usr/local/lib/python3.7/dist-packages/c7n/cache.py", line 162, in save
    (sqlite3.Binary(encode(key)), sqlite3.Binary(encode(data)), timestamp))
OverflowError: BLOB longer than INT_MAX bytes
```

**Comment by sanjeev98kumar** [comment]
Will this be a good first issue to start with? I am looking for my first PR. Thanks

**Comment by castrojo** [comment]
@sanjeev98kumar Here's some "help wanted" issues that might be worth browsing, ping me if you'd like more help! https://github.com/cloud-custodian/cloud-custodian/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
