### ISSUE TITLE
AttributeError: 'GlueDataCatalog' object has no attribute 'get_arns'

### ISSUE THREAD

**Issue by jare19** [cloud-custodian/cloud-custodian#7944]
### Describe the bug

Receiving the following error when running the policy via periodic lambda execution once it tries to send to security hub.
AttributeError: 'GlueDataCatalog' object has no attribute 'get_arns'

### What did you expect to happen?

Policy execution to work and finding to be posted in security hub.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n:0.9.14
```

### Policy

```shell
- name: glue-catalog-password-encryption
  resource: aws.glue-catalog
  comments: ...
  conditions:
  - type: value
    key: region
    op: eq
    value: us-east-1
  filters:
  - type: value
    key: DataCatalogEncryptionSettings.ConnectionPasswordEncryption.ReturnConnectionPasswordEncrypted
    value: false
  actions:
  - type: post-finding
    severity_label: CRITICAL
    recommendation: ...
    compliance_status: FAILED
    types:
    - Software and Configuration Checks
    recommendation_url: ...
  mode:
    execution-options:
      output_dir: s3://{output_bucket}/logs/{account_id}/{region}
      assume_role: arn:aws:iam::{account_id}:role/...
    role: arn:aws:iam::{account_id}:role/...
    schedule: rate(1 hour)
    dead_letter_config:
      TargetArn: arn:aws:sqs:...
    tags: ...
    type: periodic
```

### Relevant log/traceback output

```shell
2022-10-26 13:58:32,447 - custodian.policy - DEBUG - Running policy:glue-catalog-password-encryption resource:aws.glue-catalog region:us-east-1 c7n:0.9.14
2022-10-26 13:58:33,028 - custodian.resources.gluedatacatalog - DEBUG - Filtered from 1 to 1 gluedatacatalog
2022-10-26 13:58:33,028 - custodian.policy - INFO - policy:glue-catalog-password-encryption resource:aws.glue-catalog region:us-east-1 count:1 time:0.58
2022-10-26 13:58:33,032 - custodian.output - DEBUG - metric:ResourceCount Count:1 policy:glue-catalog-password-encryption restype:aws.glue-catalog scope:policy
2022-10-26 13:58:33,032 - custodian.output - DEBUG - metric:PolicyException Count:1 policy:glue-catalog-password-encryption restype:aws.glue-catalog
2022-10-26 13:58:33,044 - custodian.output - DEBUG - metric:ApiCalls Count:2 policy:glue-catalog-password-encryption restype:aws.glue-catalog
2022-10-26 13:58:33,044 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 322, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/securityhub.py", line 415, in process
    finding = self.get_finding(
  File "/var/task/c7n/resources/securityhub.py", line 538, in get_finding
    finding_resources.append(self.format_resource(r))
  File "/var/task/c7n/resources/securityhub.py", line 594, in format_resource
    'Id': self.manager.get_arns([r])[0],
AttributeError: 'GlueDataCatalog' object has no attribute 'get_arns'
```

### Extra information or context

This also errors when the following is used for a filter:
```
    filters:
      - type: glue-security-config
        ReturnConnectionPasswordEncrypted: false
```

I am, although, able to work around this with the `aws.account` resource rather than the `aws.glue-catalog` resource.

**Comment by SaMnCo** [comment]
Also impacting 0.9.26 afaics
