### ISSUE TITLE
resources/awslambda.py using KMSKeyArn instead of KmsKeyArn

### ISSUE THREAD

**Issue by ensono-michaelhogg** [cloud-custodian/cloud-custodian#7960]
### Describe the bug

When evaluating Lambda Description Tags, passing KMSKeyArn causes botocore validate.py to fail:
"KMSKeyArn", must be one of: Code, CodeSha256, DeadLetterConfig, Environment, FunctionName, Handler, KmsKeyArn, LastModified, Layers, MasterArn, MemorySize, RevisionId, Role, Runtime, Timeout, TracingConfig, VpcConfig, Version

### What did you expect to happen?

No exception

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.19
Python:      3.7.10 (default, Jun  3 2021, 00:02:01)
             [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
Platform:    posix.uname_result(sysname='Linux', nodename='redacted', release='4.14.294-220.533.amzn2.x86_64', version='#1 SMP Thu Sep 29 01:01:23 UTC 2022', machine='x86_64')
Using venv:  True
Docker: False
Installed:

PyYAML==6.0
Pygments==2.13.0
SecretStorage==3.3.3
argcomplete==2.0.0
attrs==22.1.0
aws-xray-sdk==2.10.0
bleach==5.0.1
boto3==1.24.87
botocore==1.27.87
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.5
coverage==6.5.0
cryptography==38.0.1
docutils==0.17.1
execnet==1.9.0
flake8==3.9.2
freezegun==1.2.2
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.9.0
iniconfig==1.1.1
jaraco-classes==3.2.3
jaraco.classes==3.2.3
jeepney==0.8.0
jmespath==1.0.1
jsonpatch==1.32
jsonpointer==2.3
jsonschema==4.16.0
keyring==23.9.3
mccabe==0.6.1
mock==4.0.3
more-itertools==8.14.0
multidict==6.0.2
packaging==21.3
pkginfo==1.8.3
pkgutil-resolve-name==1.3.10
placebo==0.9.0
pluggy==1.0.0
portalocker==2.5.1
psutil==5.9.2
py==1.11.0
pycodestyle==2.7.0
pycparser==2.21
pyflakes==2.3.1
pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==7.1.3
pytest-cov==3.0.0
pytest-forked==1.4.0
pytest-recording==0.12.1
pytest-sugar==0.9.5
pytest-terraform==0.6.4
pytest-xdist==2.5.0
python-dateutil==2.8.2
pyyaml==6.0
readme-renderer==37.2
requests==2.28.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
s3transfer==0.6.0
secretstorage==3.3.3
six==1.16.0
tabulate==0.8.10
termcolor==2.0.1
tomli==2.0.1
tqdm==4.64.1
twine==3.8.0
typing-extensions==4.3.0
urllib3==1.26.12
vcrpy==4.2.1
webencodings==0.5.1
wrapt==1.14.1
yarl==1.8.1
zipp==3.8.1
```

### Policy

```shell
policies:
  - name: Tagging-ResourceLevelTags-Description-Lambda
    description: |
      Redacted
    resource: lambda
    filters:
      - "tag:Description": absent
    actions:
     - type: post-finding
       description: |
          Redacted
       severity_label: MEDIUM
       types:
         - "Software and Configuration Checks/Industry and Regulatory Standards/Redacted"
       recommendation: "Redacted"
       recommendation_url: "Redacted"
       confidence: 100
       compliance_status: FAILED
       record_state: ACTIVE
```

### Relevant log/traceback output

```shell
2022-10-25 03:56:16,214: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/policy.py", line 337, in run
    results = a.process(resources)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/resources/securityhub.py", line 445, in process
    client.batch_import_findings, Findings=findings
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/utils.py", line 446, in _retry
    return func(*args, **kw)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 902, in _make_api_call
    api_params, operation_model, context=request_context
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 963, in _convert_to_request_dict
    api_params, operation_model
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in Findings[0].Resources[0].Details.AwsLambdaFunction: "KMSKeyArn", must be one of: Code, CodeSha256, DeadLetterConfig, Environment, FunctionName, Handler, KmsKeyArn, LastModified, Layers, MasterArn, MemorySize, RevisionId, Role, Runtime, Timeout, TracingConfig, VpcConfig, Version
2022-10-25 03:56:16,216: custodian.commands:ERROR Error while executing policy EEC-Tagging-ResourceLevelTags-Description-Lambda, continuing
Traceback (most recent call last):
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/commands.py", line 302, in run
    policy()
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/policy.py", line 1300, in __call__
    resources = mode.run()
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/policy.py", line 337, in run
    results = a.process(resources)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/resources/securityhub.py", line 445, in process
    client.batch_import_findings, Findings=findings
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/c7n/utils.py", line 446, in _retry
    return func(*args, **kw)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 902, in _make_api_call
    api_params, operation_model, context=request_context
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/client.py", line 963, in _convert_to_request_dict
    api_params, operation_model
  File "/usr/local/bin/venv/custodian/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in Findings[0].Resources[0].Details.AwsLambdaFunction: "KMSKeyArn", must be one of: Code, CodeSha256, DeadLetterConfig, Environment, FunctionName, Handler, KmsKeyArn, LastModified, Layers, MasterArn, MemorySize, RevisionId, Role, Runtime, Timeout, TracingConfig, VpcConfig, Version
```

### Extra information or context

To fix this I changed KMSKeyArn to KmsKeyArn inside "resources/awslambda.py" at lines [255] and [329]

**Comment by sanjeev98kumar** [comment]
Hi @ensono-michaelhogg will this be a good first issue to start with? I am looking for my first PR

**Comment by ensono-michaelhogg** [comment]
@sanjeev98kumar thanks, I have created a PR
https://github.com/cloud-custodian/cloud-custodian/pull/7962

**Comment by jare19** [comment]
Here is more information, I apologize about not piggybacking off of this in the first place but the error is tied to the security hub upload and only if there are encrypted environment variables. 
Related PR with more info - #7977
