### ISSUE TITLE
aws - cloudhsm-cluster policies failing in event mode 

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#7991]
### Describe the bug

When running a cloudhsm cluster policy in event mode, there's a traceback that pops up. I suspect it's happening due to an api change on the AWS side. 

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
policies:
- name: cldhsmclstr-subnet-test-event
  resource: aws.cloudhsm-cluster
  mode:
    type: cloudtrail
    events:
    - event: CreateCluster
      ids: responseElements.cluster.clusterId
      source: cloudhsm.amazonaws.com
  filters:
  - type: subnet
    key: tag:abc
    op: ne
    value: 'xyz'
```

### Relevant log/traceback output

```shell
[ERROR] ParamValidationError: Parameter validation failed:
Invalid type for parameter Filters, value: cluster-qsxzbw5t4aw, type: <class 'str'>, valid types: <class 'dict'>
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1288, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 487, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 691, in resolve_resources
    return super().resolve_resources(event)
  File "/var/task/c7n/policy.py", line 469, in resolve_resources
    resources = self.policy.resource_manager.get_resources(resource_ids)
  File "/var/task/c7n/query.py", line 576, in get_resources
    resources = self.source.get_resources(ids)
  File "/var/task/c7n/query.py", line 227, in get_resources
    return self.query.get(self.manager, ids)
  File "/var/task/c7n/query.py", line 100, in get
    resources = self.filter(resource_manager, **params)
  File "/var/task/c7n/query.py", line 79, in filter
    return self._invoke_client_enum(
  File "/var/task/c7n/query.py", line 57, in _invoke_client_enum
    data = results.build_full_result()
  File "/var/runtime/botocore/paginate.py", line 451, in build_full_result
    for response in self:
  File "/var/runtime/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/var/task/c7n/query.py", line 761, in _make_request
    return self.retry(self._method, **current_kwargs)
  File "/var/task/c7n/utils.py", line 448, in _retry
    return func(*args, **kw)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/runtime/botocore/client.py", line 739, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/runtime/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
```

**Comment by PratMis** [comment]
Fix coming out shortly
