### ISSUE TITLE
[aws:sns] ResourceNotFound Terminates Policy Evaluation Early

### ISSUE THREAD

**Issue by tmack8001** [cloud-custodian/cloud-custodian#8009]
### Describe the bug

When I ran an audit on SNS usage (our AWS account has thousands of SNS Topics and they come and go fairly frequently based on ever changing resources and compute within the account) the policy fails randomly after 2 exceptions of `ResourceNotFound` from the `sns:ListTagsForResource` boto operation.

### What did you expect to happen?

I expected that the policy would successfully execute and only WARN when resources weren't able to be retrieved after getting the initial list of resources to operate/describe further.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.19
Python:      3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
Platform:    posix.uname_result(sysname='Darwin', nodename='C02XV0UQJGH7', release='22.1.0', version='Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed:

argcomplete==2.0.0
attrs==21.4.0
boto3==1.24.88
botocore==1.27.88
docutils==0.17.1
importlib-metadata==4.13.0
jmespath==1.0.1
jsonschema==4.16.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
urllib3==1.26.12
zipp==3.8.1
```

### Policy

```shell
- name: sns-policy
  resource: aws.sns
  comment: |
    This policy will fetch all sns topics.
```

### Relevant log/traceback output

```shell
custodian run --dryrun --region us-west-1  -s ./us-west-1 custodian.yml --verbose
2022-11-17 18:04:30,101: custodian.commands:DEBUG Loaded file custodian.yml. Contains 1 policies
2022-11-17 18:04:30,478: custodian.output:DEBUG Storing output with <LogFile file://./us-west-1/sns-policy/custodian-run.log>
2022-11-17 18:04:30,484: custodian.policy:DEBUG Running policy:sns-policy resource:aws.sns region:us-west-1 c7n:0.9.19
2022-11-17 18:04:30,486: custodian.cache:DEBUG expiring stale cache entries
2022-11-17 18:14:11,014: custodian.output:DEBUG metric:PolicyException Count:1 policy:sns-policy restype:aws.sns
2022-11-17 18:14:11,015: custodian.output:DEBUG metric:ApiCalls Count:12535 policy:sns-policy restype:aws.sns
2022-11-17 18:14:11,015: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 534, in resources
    resources = self.augment(resources)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 590, in augment
    return self.source.augment(resources)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/resources/sns.py", line 31, in augment
    return list(w.map(_augment, resources))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/resources/sns.py", line 24, in _augment
    tags = self.manager.retry(client.list_tags_for_resource,
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/utils.py", line 446, in _retry
    return func(*args, **kw)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFound) when calling the ListTagsForResource operation: Resource does not exist
2022-11-17 18:14:11,029: custodian.commands:ERROR Error while executing policy sns-policy, continuing
Traceback (most recent call last):
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/commands.py", line 302, in run
    policy()
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 1323, in __call__
    resources = PullMode(self).run()
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 534, in resources
    resources = self.augment(resources)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/query.py", line 590, in augment
    return self.source.augment(resources)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/resources/sns.py", line 31, in augment
    return list(w.map(_augment, resources))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/c7n/resources/sns.py", line 24, in _augment
    tags = self.manager.retry(client.list_tags_for_resource,
  File "./custodian/lib/python3.10/site-packages/c7n/utils.py", line 446, in _retry
    return func(*args, **kw)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "./cloud-custodian/custodian/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFound) when calling the ListTagsForResource operation: Resource does not exist
2022-11-17 18:14:11,047: custodian.commands:ERROR The following policies had errors while executing
 - sns-policy
```

### Extra information or context

Obviously the policy definition as provided doesn't actually filter or do anything with the results. Simply I wanted to get an inventory of all SNS:Topics to start with. Applying filters afterwards can easily be added and perform work, but to start with I can't get a full inventory as I'm assuming either permissions to a specific Topic is DENYed and/or the Topic is deleted after retrieved from the initial sns:ListTopics API.

There are a total of 12,535 API Calls happening I understand, there are a massive amount of SNS Topics within this account, the policy command execution should be tolerant of a single error (I think?) and instead should WARN/ERROR vs a terminal error of the policy execution. For instance inventorying my aws:s3 footprint is still successful (not full inventory, but the command execution at least doesn't fail) when permissions to a specific entity are not allowed.

```
2022-11-07 11:36:45,275 - custodian.filters - ERROR - Message: An error occurred (AccessDenied) when calling the GetBucketEncryption operation: Access Denied Bucket: 123abc
```

**Comment by thisisshi** [comment]
kind of seems like a race condition or stale cache, regardless, the way that we fetch tags has changed but sns hasn't, tl;dr is no more per resource fetching of tags, now tags can be fetched via a single api call which will greatly decrease the 12.5k api calls you see as well as fix this issues

pr: #8075
