### ISSUE TITLE
c7n_gcp fails with "Nonetype" object is not iterable when running policy against project with no clusters

### ISSUE THREAD

**Issue by chase-replicated** [cloud-custodian/cloud-custodian#8055]
### Describe the bug

We use c7n-org to check multiple gcp projects for gke clusters that lack labels required by organization-wide security policies. When these are run against a project that doesn't have any kubernetes clusters, the policy run fails with the error `"Nonetype" object is not iterable`. I'm getting the same error running locally and running on a remote github actions runner. 

### What did you expect to happen?

I expected that the policy should recognize that there are no resources and simply move on to the next policy rather than generating a stack trace.

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
custodian version --debug                                                                                

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.19
Python:      3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
Platform:    posix.uname_result(sysname='Darwin', nodename='Chases-MacBook-Pro.local', release='21.6.0', version='Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.1.0
boto3==1.24.88
botocore==1.27.88
c7n==0.9.20
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
docutils==0.17.1
google-api-core==2.10.1
google-api-python-client==2.64.0
google-auth==2.12.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.5
google-cloud-audit-log==0.2.4
google-cloud-core==2.3.2
google-cloud-logging==3.2.4
google-cloud-monitoring==2.11.2
google-cloud-storage==1.44.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.56.4
grpc-google-iam-v1==0.12.4
grpcio==1.49.1
grpcio-status==1.49.1
httplib2==0.20.4
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.9.0
jmespath==1.0.1
jsonschema==4.16.0
pkgutil-resolve-name==1.3.10
proto-plus==1.22.1
protobuf==4.21.7
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
ratelimiter==1.2.0.post0
requests==2.28.1
retrying==1.3.3
rsa==4.9
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.3.0
uritemplate==4.1.1
urllib3==1.26.12
zipp==3.8.1
```

### Policy

```shell
policy it's getting hung up on:

  - name: 'deleting-expired-cluster'
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: resourceLabels."expires-on"
        value_type: age
        op: gt
        value: 0
    actions:
      - delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub
```

Full policy being used in command:
```
policies:
  - name: 'labels-are-corrected-removing-marks-from-instance'
    resource: gcp.instance
    filters:
      - labels."owner": present
      - labels."expires-on": present
      - type: value
        key: labels."expires-on"
        op: regex
        value: '^(\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])$|never)$'
      - type: value
        key: labels."owner"
        op: regex
        value: '^\w*$'
      - or:
          - labels."compliance-stop-after": present
          - labels."compliance-delete-after": present
    actions:
      - type: set-labels
        remove: [compliance-stop-after, compliance-delete-after]
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'terminating-expired-instance'
    resource: gcp.instance
    filters:
      - type: value
        key: labels."expires-on"
        value_type: age
        op: gt
        value: 0
    actions:
      - delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'marking-instance-invalid-labels-found'
    resource: gcp.instance
    filters:
      - and:
          - labels."compliance-stop-after": absent
          - labels."compliance-delete-after": absent
      - or:
          - type: value
            key: labels."expires-on"
            op: regex
            value: '^(?!(\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])$)|^never$).*'
          - type: value
            key: labels."owner"
            op: regex
            value: '^.*\W+.*$'
          - labels."owner": absent
          - labels."expires-on": absent
    actions:
      - type: mark-for-op
        label: compliance-stop-after
        op: stop
        days: 2
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'stopping-and-marking-for-deletion-instance-previously-marked-for-stopping'
    resource: gcp.instance
    filters:
      - type: marked-for-op
        label: compliance-stop-after
        op: stop
      - or:
          - type: value
            key: labels."expires-on"
            op: regex
            value: '^(?!(\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])$)|^never$).*'
          - type: value
            key: labels."owner"
            op: regex
            value: '^.*\W+.*$'
          - labels."owner": absent
          - labels."expires-on": absent
      - labels."compliance-delete-after": absent
    actions:
      - stop
      - type: set-labels
        remove: [compliance-stop-after]
      - type: mark-for-op
        label: compliance-delete-after
        op: delete
        days: 2
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'terminating-previously-stopped-instance'
    resource: gcp.instance
    filters:
      - type: marked-for-op
        label: compliance-delete-after
        op: delete
      - or:
          - type: value
            key: labels."expires-on"
            op: regex
            value: '^(?!(\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])$)|^never$).*'
          - type: value
            key: labels."owner"
            op: regex
            value: '^.*\W+.*$'
          - labels."owner": absent
          - labels."expires-on": absent
    actions:
      - delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'deleting-cluster-labels-invalid'
    resource: gcp.gke-cluster
    filters:
      - or:
          - resourceLabels."owner": absent
          - resourceLabels."expires-on": absent
          - type: value
            key: resourceLabels."expires-on"
            op: regex
            value: '^(?!(\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])$)|^never$).*'
          - type: value
            key: resourceLabels."owner"
            op: regex
            value: '^.*\W+.*$'
    actions:
      - type: delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'deleting-expired-cluster'
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: resourceLabels."expires-on"
        value_type: age
        op: gt
        value: 0
    actions:
      - delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'unmarking-reattached-disk'
    resource: gcp.disk
    filters:
      - labels."compliance-delete-after": present
      - users: present
    actions:
      - type: set-labels
        remove: [compliance-delete-after]
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'marking-detached-disk'
    resource: gcp.disk
    filters:
      - labels."compliance-delete-after": absent
      - lastDetachTimestamp: present
      - users: absent
    actions:
      - type: mark-for-op
        label: compliance-delete-after
        op: delete
        days: 2
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub

  - name: 'deleting-marked-detached-disk'
    resource: gcp.disk
    filters:
      - type: marked-for-op
        label: compliance-delete-after
        op: delete
    actions:
      - delete
      - type: notify
        format: json
        transport:
          type: pubsub
          topic: projects/{account_id}/topics/custodian-pubsub
```
```


### Relevant log/traceback output

```shell
Here's the full stacktrace from running it locally: 


c7n-org run -c configs/gcp.yml -s out/gcp -u policies/gcp-cloud-cleanup.yml --debug
2022-12-05 10:32:22,135: c7n_org:ERROR Exception running policy:deleting-cluster-labels-invalid account:kots-field-labs region:global error:'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/c7n_org/cli.py", line 617, in run_account
    resources = p.run()
  File "/usr/local/lib/python3.10/site-packages/c7n/policy.py", line 1329, in __call__
    resources = mode.run()
  File "/usr/local/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/query.py", line 204, in resources
    resources = self._fetch_resources(q)
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/query.py", line 226, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/resources/gke.py", line 44, in augment
    for r in resources:
TypeError: 'NoneType' object is not iterable
> /usr/local/lib/python3.10/site-packages/c7n_gcp/resources/gke.py(44)augment()
-> for r in resources:
(Pdb) exit
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/c7n_org/cli.py", line 697, in run
    futures[w.submit(
  File "/usr/local/lib/python3.10/site-packages/c7n/executor.py", line 28, in submit
    return MainThreadFuture(func(*args, **kw))
  File "/usr/local/lib/python3.10/site-packages/c7n_org/cli.py", line 617, in run_account
    resources = p.run()
  File "/usr/local/lib/python3.10/site-packages/c7n/policy.py", line 1329, in __call__
    resources = mode.run()
  File "/usr/local/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/query.py", line 204, in resources
    resources = self._fetch_resources(q)
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/query.py", line 226, in _fetch_resources
    return self.augment(self.source.get_resources(query)) or []
  File "/usr/local/lib/python3.10/site-packages/c7n_gcp/resources/gke.py", line 44, in augment
    for r in resources:
TypeError: 'NoneType' object is not iterable
```
```


### Extra information or context

_No response_

**Comment by chase-replicated** [comment]
Changing /usr/local/lib/python3.10/site-packages/c7n_gcp/resources/gke.py from
```
 43     def augment(self, resources):
 44         for r in resources:
 45             if r.get('resourceLabels'):
 46                 r['labels'] = r['resourceLabels']
 47         return resources
```
to
```
 43     def augment(self, resources):
 44         if resources is None:
 45             return resources
 46         for r in resources:
 47             if r.get('resourceLabels'):
 48                 r['labels'] = r['resourceLabels']
 49         return resources
```
resolves this error, although I'm not sure whether this is the best solution.

**Comment by thisisshi** [comment]
@chase-replicated is gke enabled in the account? or are there just no resources?

**Comment by chase-replicated** [comment]
> @chase-replicated is gke enabled in the account? or are there just no resources?

GKE is enabled, there are just no resources currently. We use it for testing, so there may or may not be resources in there at any given time, especially given that we use Cloud Custodian to clean up unused resources.

That being said, I would hope that it would still give a more graceful output than an Exception stack trace even if GKE wasn't enabled at all, as if we have new projects we'd like to point the set of policies at the project whether or not the service has been enabled yet. I don't see a downside to letting it perform that way.
