### ISSUE TITLE
aws.elb filters create invalid ARN and fail with boto errors

### ISSUE THREAD

**Issue by speshak** [cloud-custodian/cloud-custodian#8173]
### Describe the bug

When using any filters on an `aws.elb` resource, c7n creates an ELB ARN that lacks the account ID, and is rejected as invalid.

### What did you expect to happen?

That the generated ARN would be valid and subsequent API calls would succeed.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.21
Python:      3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MINN-315049-C02GC4HVML87', release='22.2.0', version='Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==2.0.0
attrs==22.1.0
boto3==1.26.30
botocore==1.29.30
c7n==0.9.21
cachetools==5.2.0
certifi==2022.12.7
charset-normalizer==2.0.12
docutils==0.17.1
google-api-core==2.10.2
google-api-python-client==2.70.0
google-auth==2.15.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.6
google-cloud-audit-log==0.2.4
google-cloud-core==2.3.2
google-cloud-logging==3.3.1
google-cloud-monitoring==2.11.3
google-cloud-storage==1.44.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
grpc-google-iam-v1==0.12.4
grpcio==1.49.1
grpcio-status==1.49.1
httplib2==0.21.0
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.10.1
jmespath==1.0.1
jsonschema==4.17.3
pkgutil-resolve-name==1.3.10
proto-plus==1.22.1
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
pyrate-limiter==2.8.4
pyrsistent==0.19.2
python-dateutil==2.8.2
pyyaml==6.0
requests==2.27.1
retrying==1.3.4
rsa==4.9
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.13
zipp==3.11.0
```

### Policy

```shell
policies:
  - name: ciphers
    resource: aws.elb
    filters:
      - type: ssl-policy
        matching: "^Protocol-"
        whitelist:
          - "Protocol-TLSv1.1"
          - "Protocol-TLSv1.2"
```

### Relevant log/traceback output

```shell
ERROR    custodian.output:output.py:336 Error while executing policy
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/venv/lib/python3.10/site-packages/c7n/query.py", line 534, in resources
    resources = self.augment(resources)
  File "/venv/lib/python3.10/site-packages/c7n/query.py", line 590, in augment
    return self.source.augment(resources)
  File "/venv/lib/python3.10/site-packages/c7n/resources/elb.py", line 38, in augment
    return tags.universal_augment(self.manager, resources)
  File "/venv/lib/python3.10/site-packages/c7n/tags.py", line 91, in universal_augment
    resource_tag_results = client.get_resources(
  File "/venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the GetResources operation: arn:aws:elasticloadbalancing:us-east-1::loadbalancer/elb-cipher-success is not a valid AmazonResourceName (ARN)
```

**Comment by speshak** [comment]
I determined the issue I was encountering was caused by the limited testing environment I was using. I was able to fix things by explicitly setting an account ID in the session.
