### ISSUE TITLE
Azure: Error upgrading to 0.9.22.0

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#8185]
### Describe the bug

Upgrading to the latest version of the custodian in Azure is giving below error:

### What did you expect to happen?

No errors during upgrade.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
cloudcustodian/c7n:0.9.22.0
```

### Relevant log/traceback output

```shell
Running Azure Cloud Custodian Self-Host
Authenticated [MSI | ]
Updating event grid subscriptions
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-01-20 05:16:46 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 531, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 321, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-01-20 05:17:46 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 531, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 321, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-01-20 05:18:46 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 531, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 321, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 185, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
```
```


### Extra information or context

_No response_

**Comment by thisisshi** [comment]
could you post the policy that failed?

**Comment by tomarv2** [comment]
Test policy:

```
vars:
  notify: &notify
    type: notify
    subject: "[Azure Policy] [Subscription: {{account_id}}] test mailer1"
    template: db_email.html

policies:
  - name: auto-owner-key-vault
    resource: azure.keyvault
    description: |
      Tag all new key-vault with the 'Owner Email' tag.
    actions:
      - <<: *notify
        subject: "[Azure Policy] [Subscription: {{account_id}}] test mailer2"
        to:
          - abc@abc.com
        transport:
          type: asq
          queue: "https://123456789012.queue.core.windows.net/c7n-aci-notifications"
```

**Comment by kapilt** [comment]
hmm.. this looks like a container mode policy but not clear that's reflected in the policy itself? can you confirm the policy is accurate. the error looks like something that came from an sdk upgrade and its interaction with the policy storage uri, since we can't construct the blob store client.

**Comment by tomarv2** [comment]
The policies are running but just errors in container logs (screenshot below). 

Reverting to the old version of the custodian logs are clean.

Policies are the same between version upgrades.

<img width="1402" alt="Screen Shot 2023-01-23 at 9 17 20 AM" src="https://user-images.githubusercontent.com/11890959/214105791-09071486-c3d8-42ee-878c-aba12b84f752.png">

**Comment by tomarv2** [comment]
Tried to upgrade today again to `0.9.22` not working reverting to ``0.9.10` works:

<img width="1410" alt="Screen Shot 2023-02-18 at 7 25 08 AM" src="https://user-images.githubusercontent.com/11890959/219874358-de3d1298-eb4c-450f-8162-774f9540ae98.png">

**Comment by tomarv2** [comment]
Tried upgrading to 9.26, getting below error, reverting to 0.9.10 works::

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 557, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 320, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-04-27 02:39:16 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 557, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 320, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-04-27 02:40:16 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 557, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 320, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2023-04-27 02:41:16 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 119, in update_policies
    self.policy_blob_client = Storage.get_blob_client_by_uri(self.policy_storage_uri,
  File "/src/tools/c7n_azure/c7n_azure/storage_utils.py", line 111, in get_blob_client_by_uri
    blob_service.create_container(storage.container_name)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_blob_service_client.py", line 557, in create_container
    container.create_container(
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_container_client.py", line 320, in create_container
    process_storage_error(error)
  File "/usr/local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: No Content
ErrorCode:None
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
```
