### ISSUE TITLE
GCP: error running c7n-mailer

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#8257]
### Describe the bug

When running mailer in GCP, getting error:

```
c7n-mailer -c configs/config.yml -t templates --run --debug
```

### What did you expect to happen?

NA

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
c7n_mailer varun.tomar$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.22
Python:      3.8.10 (default, Jun  9 2021, 08:13:01) 
             [Clang 11.0.0 (clang-1100.0.33.8)]
Platform:    posix.uname_result(sysname='Darwin', nodename='C02', release='21.6.0', version='Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.2.0
boto3==1.26.51
botocore==1.29.51
cachetools==5.2.1
certifi==2022.12.7
charset-normalizer==3.0.1
docutils==0.17.1
google-api-core==2.11.0
google-api-python-client==2.73.0
google-auth==2.16.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.6
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.2
google-cloud-logging==3.4.0
google-cloud-monitoring==2.14.0
google-cloud-storage==1.44.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.58.0
grpc-google-iam-v1==0.12.6
grpcio==1.49.1
httplib2==0.21.0
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.10.2
jmespath==1.0.1
jsonschema==4.17.3
pkgutil-resolve-name==1.3.10
proto-plus==1.22.2
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
pyrate-limiter==2.8.5
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
requests==2.28.2
retrying==1.3.4
rsa==4.9
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.14
zipp==3.11.0
```
```


### Policy

```shell
policies:
  - name: enable-subnet-flowlogs
    resource: gcp.subnet
    mode:
      type: gcp-audit
      methods:
        - v1.compute.subnetworks.insert
        - beta.compute.subnetworks.insert
    filters:
      - enableFlowLogs: empty
      - not:
        - type: value
          key: "network"
          op: regex
          value: "(.*?/networks/demo-managed-.*?)" 
          value_type: normalize
    actions:
      - type: notify
        to:
          - test@test.com
        transport:
          type: pubsub
          topic: projects/delme/topics/c7n-notifications

```
```


### Relevant log/traceback output

```shell
{
insertId: "63e5c27400"
labels: {2}
logName: "projects/delme/logs/cloudfunctions.googleapis.com%2Fcloud-functions"
receiveTimestamp: "2023-02-10T04:05:08.565476477Z"
resource: {2}
severity: "INFO"
textPayload: "2023-02-10 04:05:05,822 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/bin/c7n-mailer", line 8, in <module>
    sys.exit(main())
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/cli.py", line 274, in main
    processor.run()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/gcp_mailer/gcp_queue_processor.py", line 46, in run
    self.process_message(message, discard_date)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/gcp_mailer/gcp_queue_processor.py", line 58, in process_message
    self.handle_targets(pubsub_message, publish_date, email_delivery=True, sns_delivery=False)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/target.py", line 17, in handle_targets
    to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(message)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/email_delivery.py", line 208, in get_to_addrs_email_messages_map
    list(to_addrs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/utils_email.py", line 111, in get_mimetext_message
    'template', 'default', config['templates_folders'])
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/c7n_mailer/utils.py", line 94, in get_rendered_jinja
    datetime.utcnow().timetuple())
TypeError: an integer is required (got type NoneType)"
timestamp: "2023-02-10T04:05:08.422192Z"
trace: "projects/delme/traces/b93f50c0e7ef6e15c1695df89e724975"
}
```
```


### Extra information or context

_No response_

**Comment by tomarv2** [comment]
@ajkerrigan I am not able to figure out what is missing. Any pointers?

**Comment by tomarv2** [comment]
Locally running locally on mac. Ran it in a loop and it fails as well:

```
(3.8) C026R:c7n_mailer varun.tomar$ for i in {1..10}; do c7n-mailer -c config.yml -t templates --run --debug; done

2023-02-10 07:49:20,849 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:23,647 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:25,026 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
Traceback (most recent call last):
  File ".pyenv/versions/3.8/bin/c7n-mailer", line 6, in <module>
    sys.exit(main())
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 274, in main
    processor.run()
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/gcp_mailer/gcp_queue_processor.py", line 46, in run
    self.process_message(message, discard_date)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/gcp_mailer/gcp_queue_processor.py", line 58, in process_message
    self.handle_targets(pubsub_message, publish_date, email_delivery=True, sns_delivery=False)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/target.py", line 17, in handle_targets
    to_addrs_to_email_messages_map = email_delivery.get_to_addrs_email_messages_map(message)
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 203, in get_to_addrs_email_messages_map
    to_addrs_to_mimetext_map[to_addrs] = get_mimetext_message(
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/utils_email.py", line 109, in get_mimetext_message
    body = get_rendered_jinja(
  File "/cloud-custodian/tools/c7n_mailer/c7n_mailer/utils.py", line 90, in get_rendered_jinja
    execution_start = datetime.utcfromtimestamp(
TypeError: an integer is required (got type NoneType)
2023-02-10 07:49:28,196 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:30,697 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:32,288 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:34,706 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:36,210 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:38,719 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:40,178 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:43,223 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:44,780 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:46,231 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:47,960 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:50,777 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:52,262 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:54,752 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.
2023-02-10 07:49:56,284 - custodian-mailer - INFO - Downloading messages from the GCP PubSub Subscription.
2023-02-10 07:49:58,759 - custodian-mailer - INFO - No messages left in the gcp topic subscription, now exiting c7n_mailer.

**Comment by tomarv2** [comment]
Some more debugging, in `c7n_mailer/gcp_mailer` ->`gcp_queue_processor.py`. The message that is getting decoded in `process_message`:

```
pubsub_message = self.unpack_to_dict(encoded_gcp_pubsub_message["message"]["data"])
```

The `execution_start` is decoded_message is `None`, causing it to fail.

```
'execution_id': None, 'execution_start': None, 'version': '0.9.22', 'action': {'type': 'notify', 'subject': '[GCP Policy] [Account: {{account_id}} ] 
```

**Comment by kapilt** [comment]
fix merged, thanks
