### ISSUE TITLE
GCP: Error detected in vpc-creation policy

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#8264]
### Describe the bug

Running the VPC custodian policy throws the below error.

```
"Exception on /_ah/push-handlers/pubsub/projects/delme/topics/custodian-auto-audit-vpc-creation [POST]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 28, in run
    result = run(event, context)
  File "/workspace/c7n_gcp/handler.py", line 44, in run
    p.push(event, context)
  File "/workspace/c7n/policy.py", line 1291, in push
    return mode.run(event, lambda_ctx)
  File "/workspace/c7n_gcp/policy.py", line 158, in run
    resources = self.resolve_resources(event)
  File "/workspace/c7n_gcp/policy.py", line 139, in resolve_resources
    resource = self.policy.resource_manager.get_resource(resource_info['labels'])
  File "/workspace/c7n_gcp/query.py", line 183, in get_resource
    return self.resource_type.get(self.get_client(), resource_info)
  File "/workspace/c7n_gcp/resources/network.py", line 33, in get
    resource_info["resourceName"]).groups()
AttributeError: 'NoneType' object has no attribute 'groups'"
```

### What did you expect to happen?

NA

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.22
Python:      3.8.10 (default, Jun  9 2021, 08:13:01) 
             [Clang 11.0.0 (clang-1100.0.33.8)]
Platform:    posix.uname_result(sysname='Darwin', nodename='C02CD0SHMD6R', release='21.6.0', version='Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.2.0
boto3==1.26.51
botocore==1.29.51
cachetools==5.2.1
certifi==2022.12.7
charset-normalizer==3.0.1
docutils==0.17.1
google-api-core==2.11.0
google-api-python-client==2.73.0
google-auth==2.16.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.6
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.2
google-cloud-logging==3.4.0
google-cloud-monitoring==2.14.0
google-cloud-storage==1.44.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.58.0
grpc-google-iam-v1==0.12.6
grpcio==1.49.1
httplib2==0.21.0
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.10.2
jmespath==1.0.1
jsonschema==4.17.3
pkgutil-resolve-name==1.3.10
proto-plus==1.22.2
protobuf==4.21.12
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
pyrate-limiter==2.8.5
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
requests==2.28.2
retrying==1.3.4
rsa==4.9
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.14
zipp==3.11.0
```
```


### Policy

```shell
vars:
  notify: &notify
    type: notify
    to:
      - email@address.com
    format: txt
    transport:
      type: pubsub
      topic: projects/delme/topics/c7n-notifications

policies:
  - name: vpc-creation
    description: |
      Send notification when a new VPC is created with auto subnet creation.
    resource: gcp.vpc
    mode:
      type: gcp-audit
      methods:
        - beta.compute.networks.insert
    filters:
      - "autoCreateSubnetworks": true
    actions:
      - <<: *notify
```
```


### Relevant log/traceback output

```shell
NA
```

### Extra information or context

NA

**Comment by tomarv2** [comment]
Also this policy:

```
policies:
  - name: label-storage-event
    description: |
      Tags all newly created storages
    resource: gcp.bucket
    # mode:
    #   type: gcp-audit
    #   methods:
    #     - storage.buckets.create
    filters:
      - "labels.owner": absent
    actions:
      - <<: *notify
```

Error:

```
resource: {2}
severity: "ERROR"
textPayload: "Exception on /_ah/push-handlers/pubsub/projects/delme/topics/c7n-auto-label [POST]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 246, in run
    event = extract_input(input_json)  # extract the required inputs
  File "/workspace/main.py", line 26, in extract_input
    if "resource" in input_event.keys() and "labels" in input_event["resource"].keys():
AttributeError: 'NoneType' object has no attribute 'keys'"
timestamp: "2023-02-11T06:27:50.022788Z"
trace: "projects/delme/traces/ee8f66c69b174c15222190bd7825bb50"
```
