### ISSUE TITLE
GCP: Error sending policy output to storage bucket

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#8266]
### Describe the bug

Unable to send logs to Google cloud storage:

Running below command:
```
poetry run custodian run -r us-west2 --cache-period=0 enable-subnet-flowlogs.yml -s gs://test-c7n-logs
```

```
2023-02-12 16:27:43,851: custodian.commands:ERROR Error while executing policy subnet-flowlogs-enable, continuing
Traceback (most recent call last):
  File "cloud-custodian/c7n/commands.py", line 302, in run
    policy()
  File "cloud-custodian/c7n/policy.py", line 1332, in __call__
    resources = mode.run()
  File "cloud-custodian/c7n/policy.py", line 319, in run
    with self.policy.ctx as ctx:
  File "cloud-custodian/c7n/ctx.py", line 74, in __enter__
    self.initialize()
  File "cloud-custodian/c7n/ctx.py", line 48, in initialize
    self.output = blob_outputs.select(self.options.output_dir, self)
  File "cloud-custodian/c7n/output.py", line 57, in select
    raise InvalidOutputConfig("Invalid %s: %s" % (
c7n.exceptions.InvalidOutputConfig: Invalid c7n.output.blob: gs://test-c7n-logs
```

### What did you expect to happen?

In `c7n/output.py`:

```
    def select(self, selector, ctx):
        if not selector:
            return self['default'](ctx, {'url': selector})
        if '://' not in selector and selector in self:
            selector = "{}://".format(selector)
        elif self.default_protocol and '://' not in selector:
            selector = "{}://{}".format(
                self.default_protocol, selector)

        for k in self.keys():
            if selector.startswith(k):
                return self[k](ctx, parse_url_config(selector))
        raise InvalidOutputConfig("Invalid %s: %s" % (
            self.plugin_type,
            selector))
```

for `k in self.keys()` its only returning: `null, default, file, s3`. In this case I am expecting it to returns `gs` which I am guessing is causing the issue.

```
--Selector--
null ---> gs://test-c7n-logs
--Selector--
default ---> gs://test-c7n-logs
--Selector--
file ---> gs://test-c7n-logs
--Selector--
s3 ---> gs://test-c7n-logs
```

### Cloud Provider

Google Cloud (GCP)

**Comment by tomarv2** [comment]
Looks like the value coming in https://github.com/cloud-custodian/cloud-custodian/blob/620d17df550df718f2f3dc6c044be13604025511/c7n/output.py#L483 

```
    def get_output_vars(self):
        data = {
            'account_id': self.ctx.options.account_id,
            'region': self.ctx.options.region,
            'policy_name': self.ctx.policy.name,
            'now': datetime.datetime.utcnow(),
            'uuid': str(uuid.uuid4()),
        }
```

{'account_id': None, 'region': '', 'policy_name': 'subnet-flowlogs-enable', 'now': datetime.datetime(2023, 2, 13, 3, 16, 44, 398792), 'uuid': '52752f3a-d55e-4fa7-9bef-a1d4b984ac50'}
