### ISSUE TITLE
Custodian fails completely when it tries to delete the last master instance in primary Aurora cluster when there is a secondary cluster

### ISSUE THREAD

**Issue by paladin-dranser** [cloud-custodian/cloud-custodian#8291]
### Describe the bug

There is a global Aurora database (primary + secondary clusters). Custodian policy tries to delete primary cluster with `delete-instances` options (so that it deletes instances first).

As there is a secondary cluster, the last master instance can't be deleted and we get the following error:
```console
botocore.errorfactory.InvalidDBClusterStateFault: An error occurred (InvalidDBClusterStateFault) when calling the DeleteDBInstance operation: Cannot delete the last instance of the master cluster. Delete the replica cluster before deleting the last master cluster instance.
```
After this, custodian fails completely so that:
- custodian doesn't try to delete other cluster if there are lots of them
- other actions (after 'detele' action) is not ran 

### What did you expect to happen?

I expected that custodian handles this type of errors gracefully and continue deleting other RDS clusters and completing other actions.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.19.0
```

### Policy

```shell
- name: rds-delete-unused-clusters
    resource: rds-cluster
    filters:
      - DeletionProtection: false
    actions:
      - type: delete
        skip-snapshot: false
        delete-instances: true
      - type: notify
        ...
```

### Relevant log/traceback output

```shell
2023-02-16 08:04:05,420 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/rdscluster.py", line 169, in process
    client.delete_db_instance(
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidDBClusterStateFault: An error occurred (InvalidDBClusterStateFault) when calling the DeleteDBInstance operation: Cannot delete the last instance of the master cluster. Delete the replica cluster before deleting the last master cluster instance.
```

### Extra information or context

I guess we need to handle errors for 'delete' action of RDS cluster during deleting RDS instances (for loop): https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/resources/rdscluster.py#L172

**Comment by kapilt** [comment]
I think rds cross region clusters was introduced after the delete action was added, it looks like we would need to orchestrate some apis across regions for this, I think it would probably be a separate opt in config option.

**Comment by paladin-dranser** [comment]
I guess, there is some way to filter this kind of RDS clusters. However, the bug is not about that custodian doesn't work with global Aurora clusters, but is about error-handling for 'delete-database' operation.

For example, a policy finds 12 clusters, tries to delete DBs of the first clusters ,fails without error handling. As a result custodian fails too and doesn't try to delete next 11 clusters. The same behaviour if there are multiple actions (e.g., delete, notify) -> the first action raises an exception, the second action is not started.

**Comment by DawnElixir** [comment]
+1 for this error handling issue. In general, there are error raised from AWS API for one resource and c7n doesn't do action for rest of the resources.
