### ISSUE TITLE
Use of {now} produces exception: AttributeError: 'datetime.datetime' object has no attribute 'format'

### ISSUE THREAD

**Issue by kjsch** [cloud-custodian/cloud-custodian#8318]
### Describe the bug

When running a policy with an action to tag a resource using a value of {now} custodian produces the error:

AttributeError: 'datetime.datetime' object has no attribute 'format'

### What did you expect to happen?

Expect custodian to add a tag to the resource with a value of the current date.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.23
Python:      3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Platform:   win32
Using venv:  True
Docker: False
Installed:

argcomplete==2.0.0
attrs==22.2.0
boto3==1.26.72
botocore==1.29.72
docutils==0.17.1
importlib-metadata==4.13.0
importlib-resources==5.10.2
jmespath==1.0.1
jsonschema==4.17.3
pkgutil-resolve-name==1.3.10
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.5.0
urllib3==1.26.14
zipp==3.13.0
```

### Policy

```shell
policies:
  - name: tag-unattached-volumes
    resource: aws.ebs
    filters:
      - Attachments: []
    actions:
      - type: tag
        key: unattached
        value: "{now}"
```

### Relevant log/traceback output

```shell
2023-02-24 10:00:02,425: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "C:\path\to\custodian\lib\site-packages\c7n\policy.py", line 364, in run
    results = a.process(resources)
  File "C:\path\to\custodian\lib\site-packages\c7n\tags.py", line 412, in process
    self.interpolate_values(tags)
  File "C:\path\to\custodian\lib\site-packages\c7n\tags.py", line 442, in interpolate_values
    t['Value'] = self.interpolate_single_value(t['Value'])
  File "C:\path\to\custodian\lib\site-packages\c7n\tags.py", line 436, in interpolate_single_value
    return tag.format(**params)
  File "C:\path\to\custodian\lib\site-packages\c7n\utils.py", line 674, in __getattr__
    return getattr(self._d, k)
AttributeError: 'datetime.datetime' object has no attribute 'format'
```

**Comment by ajkerrigan** [comment]
Thanks for the report, makes it easy to reproduce :+1: . As an immediate workaround, I'd suggest using doubled braces in your tag value:

```yaml
    actions:
      - type: tag
        key: unattached
        value: "{{now}}"
```

Because when #7532 landed we started having two variable interpolation passes: one [during the policy load](https://github.com/cloud-custodian/cloud-custodian/blob/ec229450512d7efb375262775c3d9cf9a0d32cc6/c7n/commands.py#L125), and another [during the tag action](https://github.com/cloud-custodian/cloud-custodian/blob/ec229450512d7efb375262775c3d9cf9a0d32cc6/c7n/tags.py#L868).

That wouldn't have caused this error until #7832, where we started trying to preserve variable types through format passes.

I'm not actually sure the best way to "fix" this :thinking: . One way would be to explicitly produce a string for `{now}` during that first pass rather than passing the date object through, but that may be flawed in another way.

**Comment by kapilt** [comment]
this feels like a regression / release blocker, I'll try and dig before the next release, thanks for the analysis @ajkerrigan

**Comment by kapilt** [comment]
a better more portable work around then double wrapping (which might break if we fix this) is going to be applying a format string to the value https://pyformat.info/#datetime  ie. `"{now:%Y-%m-%d}"`
