### ISSUE TITLE
`AttributeError: region` since 0.9.22.0

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#8414]
### Describe the bug

Reported via Slack...

> Any ideas why I keep getting this error. This happens when copying the logs to S3 and it happens in 0.9.24 and the two versions before

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.22.0 - 0.9.24.0
```

### Policy

```shell
mode_trail: &cloudtrail
  type: cloudtrail
  execution-options:
    region: us-west-2
    metrics: 'aws://?namespace=test'
    log_group: 'test'
    output_dir: 's3://test-infs-artifacts-nonprod-pdx/logs/{account_id}/{policy_name}/{now:%Y-%m-%d-%H-%M}'
  timeout: 200
  function-prefix: 'test-pol-'
  role: 'arn:aws:iam::{account_id}:role/{lambda_role}'
  tags:
    <<: *lambda_tags
```

### Relevant log/traceback output

```shell
[ERROR]	2023-03-22T04:03:07.268Z	99ce7cbe-33e2-4a5b-b383-26b4129ec402	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/config.py", line 12, in __getattr__
    return self[k]
KeyError: 'region'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1290, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 504, in run
    return self.run_resource_set(event, resources)
  File "/var/task/c7n/policy.py", line 539, in run_resource_set
    ctx.output.write_file("action-%s" % action.name, utils.dumps(results))
  File "/var/task/c7n/ctx.py", line 103, in __exit__
    self.output.__exit__(exc_type, exc_value, exc_traceback)
  File "/var/task/c7n/output.py", line 524, in __exit__
    self.upload()
  File "/var/task/c7n/output.py", line 534, in upload
    self.upload_file(os.path.join(root, f), key)
  File "/var/task/c7n/resources/aws.py", line 702, in upload_file
    self.transfer.upload_file(
  File "/var/task/c7n/resources/aws.py", line 696, in transfer
    bucket_region = self.config.region or None
  File "/var/task/c7n/config.py", line 14, in __getattr__
    raise AttributeError(k)
AttributeError: region
[ERROR] 2023-03-22T04:03:07.268Z 99ce7cbe-33e2-4a5b-b383-26b4129ec402 error during policy execution Traceback (most recent call last): File "/var/task/c7n/config.py", line 12, in __getattr__ return self[k] KeyError: 'region' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/var/task/c7n/handler.py", line 165, in dispatch_event p.push(event, context) File "/var/task/c7n/policy.py", line 1290, in push return mode.run(event, lambda_ctx) File "/var/task/c7n/policy.py", line 504, in run return self.run_resource_set(event, resources) File "/var/task/c7n/policy.py", line 539, in run_resource_set ctx.output.write_file("action-%s" % action.name, utils.dumps(results)) File "/var/task/c7n/ctx.py", line 103, in __exit__ self.output.__exit__(exc_type, exc_value, exc_traceback) File "/var/task/c7n/output.py", line 524, in __exit__ self.upload() File "/var/task/c7n/output.py", line 534, in upload self.upload_file(os.path.join(root, f), key) File "/var/task/c7n/resources/aws.py", line 702, in upload_file self.transfer.upload_file( File "/var/task/c7n/resources/aws.py", line 696, in transfer bucket_region = self.config.region or None File "/var/task/c7n/config.py", line 14, in __getattr__ raise AttributeError(k) AttributeError: region
```

**Comment by ajkerrigan** [comment]
> I was able to figure it out - when I passed ?region=us-west-2, I got an access denied message to the S3 Bucket KMS Key. The original message was just not useful.

That suggests this is more of an error-handling issue.

**Comment by JonGilmore** [comment]
hey @ajkerrigan - we recently upgraded to c7n 0.9.24 and I think we're seeing similar a error when trying to upload logs to s3. I'd have to check to see what version we upgraded from. Wondering what I can do to help you dig further and get more info on this.

```
[ERROR]	2023-04-06T14:00:07.813Z	64b9a9ac-0d32-4972-a515-e201b7a94b4c	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/config.py", line 12, in __getattr__
    return self[k]
KeyError: 'region'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 165, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1290, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 584, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 355, in run
    return []
  File "/var/task/c7n/ctx.py", line 103, in __exit__
    self.output.__exit__(exc_type, exc_value, exc_traceback)
  File "/var/task/c7n/output.py", line 524, in __exit__
    self.upload()
  File "/var/task/c7n/output.py", line 534, in upload
    self.upload_file(os.path.join(root, f), key)
  File "/var/task/c7n/resources/aws.py", line 702, in upload_file
    self.transfer.upload_file(
  File "/var/task/c7n/resources/aws.py", line 696, in transfer
    bucket_region = self.config.region or None
  File "/var/task/c7n/config.py", line 14, in __getattr__
    raise AttributeError(k)
AttributeError: region
```

**Comment by JonGilmore** [comment]
confirmed that reverting to `0.9.22` resolves this issue. Here's a policy that we're deploying: 

```
vars:
  run_mode: &run_mode
    type: periodic
    # daily at 14:00 UTC
    schedule: "cron(0 14 * * ? *)"
    tags:
      app: "c7n"
      account: "{account_id}"
    execution-options:
      output_dir: "{s3_bucket}/logs/{account_id}/{region}/"
    memory: 1024
  run_conditions: &run_conditions
    conditions:
      - type: value
        key: account_id
        op: in
        value:
          - "123123123123"

policies:
  - name: ami-app-snapshots-cleanup
    resource: ami
    <<: *run_conditions
    filters:
      - "tag:app": present
      - "tag:releaseStatus": "snapshot"
      - type: reduce
        sort-by: "CreationDate"
        group-by: "tag:app"
        order: desc
        discard: 20
    mode:
      <<: *run_mode
    actions:
      - type: deregister
        delete-snapshots: true

```

**Comment by ajkerrigan** [comment]
Thanks for the detail @JonGilmore , it was helpful for reproducing the problem locally :+1: . Got a PR up that I think should take care of it.
