### ISSUE TITLE
Azure set-public-access does not work on azure.storage-container

### ISSUE THREAD

**Issue by ikraemer-dd** [cloud-custodian/cloud-custodian#8512]
### Describe the bug

I use this policy to identify azure.storage-container that have publicAccess enabled, and to remove any existing public access. This policy is almost exactly the one from the [doc](https://cloudcustodian.io/docs/azure/resources/storage-container.html).

```
policies:
  - name: named-public-storage-container
    description: |
      Find all containers with public access enabled, based on the container name and update their policies.
    resource: azure.storage-container
    filters:
      - and:
        - type: value
          key: properties.publicAccess
          op: not-equal
          value: None   # Possible values: Blob, Container, None
        - type: value
          key: name
          op: equal
          value: dummy
    actions:
      - type: set-public-access
        value: None
```

When running it, I encounter the following error:
```
poetry run custodian run az_named-storage-container-public.yml
2023-04-20 10:56:29,385: custodian.azure.session:INFO Authenticated [Azure CLI | REDACTED]
2023-04-20 10:56:39,399: custodian.policy:INFO policy:named-public-storage-container resource:azure.storage-container region:AzureCloud count:1 time:10.01
2023-04-20 10:56:39,414: custodian.azure.AzureBaseAction:ERROR set-public-access failed for 'dummy'.
Traceback (most recent call last):
  File "/Users/isabelle.kraemer/private-github/cloud-custodian-forked/tools/c7n_azure/c7n_azure/actions/base.py", line 69, in _process_resources
    result = self._process_resource(r)
  File "/Users/isabelle.kraemer/private-github/cloud-custodian-forked/tools/c7n_azure/c7n_azure/resources/storage_container.py", line 108, in _process_resource
    self.client.blob_containers.update(
TypeError: update() missing 1 required positional argument: 'blob_container'
2023-04-20 10:56:39,417: custodian.policy:INFO policy:named-public-storage-container action:storagecontainersetpublicaccessaction resources:1 execution_time:0.01
```

### What did you expect to happen?

I expected the targeted Storage container to be updated into being private, which is not the case.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.26
Python:      3.9.9 (main, Jul 26 2022, 18:58:42)
             [Clang 13.1.6 (clang-1316.0.21.2.5)]
Platform:    posix.uname_result(sysname='Darwin', release='22.4.0', version='Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed:

PyJWT==2.6.0
PyYAML==6.0
adal==1.2.7
appdirs==1.4.4
applicationinsights==0.11.10
apscheduler==3.10.1
argcomplete==3.0.5
attrs==22.2.0
azure-common==1.1.28
azure-core==1.26.4
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.13.3
azure-graphrbac==0.61.1
azure-identity==1.12.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.7.0
azure-keyvault-keys==4.8.0
azure-keyvault-secrets==4.7.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.1
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redhatopenshift==1.2.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.15.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.11.1
azure-storage-queue==12.6.0
boto3==1.26.109
botocore==1.29.109
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
cryptography==40.0.1
decorator==5.1.1
distlib==0.3.6
docutils==0.18.1
dogpile.cache==1.1.8
google-api-core==2.11.0
google-api-python-client==2.84.0
google-auth==2.17.2
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.3.0
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.2
google-cloud-logging==3.5.0
google-cloud-monitoring==2.14.2
google-cloud-storage==2.8.0
google-crc32c==1.5.0
google-resumable-media==2.4.1
googleapis-common-protos==1.59.0
grpc-google-iam-v1==0.12.6
grpcio==1.53.0
httplib2==0.22.0
idna==3.4
importlib-metadata==5.2.0
iso8601==1.1.0
isodate==0.6.1
jmespath==1.0.1
jsonpatch==1.32
jsonpointer==2.3
jsonschema==4.17.3
keystoneauth1==5.1.2
kubernetes==26.1.0
mock==4.0.3
msal==1.21.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
munch==2.5.0
netaddr==0.7.20
netifaces==0.11.0
oauthlib==3.2.2
openstacksdk==0.52.0
os-service-types==1.7.0
pbr==5.11.1
portalocker==2.7.0
proto-plus==1.22.2
protobuf==4.22.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyparsing==3.0.9
pyrate-limiter==2.10.0
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
pyyaml==6.0
requests==2.28.2
requests-oauthlib==1.3.1
requestsexceptions==1.4.0
retrying==1.3.4
rsa==4.9
s3transfer==0.6.0
setuptools==67.6.1
six==1.16.0
stevedore==3.5.2
tabulate==0.9.0
typing-extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
uritemplate==4.1.1
urllib3==1.26.15
websocket-client==1.5.1
zipp==3.15.0
```

### Policy

```shell
policies:
  - name: named-public-storage-container
    description: |
      Find all containers with public access enabled, based on the container name and update their policies.
    resource: azure.storage-container
    filters:
      - and:
        - type: value
          key: properties.publicAccess
          op: not-equal
          value: None   # Possible values: Blob, Container, None
        - type: value
          key: name
          op: equal
          value: dummy
    actions:
      - type: set-public-access
        value: None
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/Users/isabelle.kraemer/private-github/cloud-custodian-forked/tools/c7n_azure/c7n_azure/actions/base.py", line 69, in _process_resources
    result = self._process_resource(r)
  File "/Users/isabelle.kraemer/private-github/cloud-custodian-forked/tools/c7n_azure/c7n_azure/resources/storage_container.py", line 108, in _process_resource
    self.client.blob_containers.update(
TypeError: update() missing 1 required positional argument: 'blob_container'
2023-04-20 10:56:39,417: custodian.policy:INFO policy:named-public-storage-container action:storagecontainersetpublicaccessaction resources:1 execution_time:0.01
```

**Comment by anandramapathy** [comment]
@ikraemer-dd - Were you able to get this resolved.
I too am facing the same exact issue. @kapilt - Do you know why this could be happening.
In my case i too am trying to list the exact name of the container.


policies:
  - name: storage-container-public-remediate
    description: |
      Find all containers with public access enabled
    resource: azure.storage-container
    filters:
      - type: value
        key: name
        value: testcontainer    
        key: properties.publicAccess
        op: not-equal
        value: None   # Possible values: Blob, Container, None
    actions:
      - type: set-public-access
        value: None
