### ISSUE TITLE
configure EphemeralStorage when running in Lambda mode

### ISSUE THREAD

**Issue by sean-zou** [cloud-custodian/cloud-custodian#8577]
### Describe the bug

Got following errors from cloudwatch logs:

```
[ERROR]	2023-05-21T04:13:37.173Z	243407d3-531f-4ff8-a26c-963908d520b6	error during policy execution
Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 167, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1293, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 584, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 320, in run
    with self.policy.ctx as ctx:
  File "/var/task/c7n/ctx.py", line 74, in __enter__
    self.initialize()
  File "/var/task/c7n/ctx.py", line 48, in initialize
    self.output = blob_outputs.select(self.options.output_dir, self)
  File "/var/task/c7n/output.py", line 54, in select
    return self[k](ctx, parse_url_config(selector))
  File "/var/task/c7n/resources/aws.py", line 689, in __init__
    super().__init__(ctx, config)
  File "/var/task/c7n/output.py", line 503, in __init__
    self.root_dir = tempfile.mkdtemp()
  File "/var/lang/lib/python3.9/tempfile.py", line 363, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 28] No space left on device: '/tmp/tmpugx_e30y'
```

### What did you expect to happen?

I expected that it shouldn't fail.
The default 512MB of EphemeralStorage (/tmp) is too small for some of my custodian lambdas, so I'd like to configure EphemeralStorage when running in Lambda mode

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.26.0
```

### Relevant log/traceback output

```shell
[ERROR] OSError: [Errno 28] No space left on device: '/tmp/tmpugx_e30y'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 167, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1293, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 584, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 320, in run
    with self.policy.ctx as ctx:
  File "/var/task/c7n/ctx.py", line 74, in __enter__
    self.initialize()
  File "/var/task/c7n/ctx.py", line 48, in initialize
    self.output = blob_outputs.select(self.options.output_dir, self)
  File "/var/task/c7n/output.py", line 54, in select
    return self[k](ctx, parse_url_config(selector))
  File "/var/task/c7n/resources/aws.py", line 689, in __init__
    super().__init__(ctx, config)
  File "/var/task/c7n/output.py", line 503, in __init__
    self.root_dir = tempfile.mkdtemp()
  File "/var/lang/lib/python3.9/tempfile.py", line 363, in mkdtemp
    _os.mkdir(file, 0o700)
```

**Comment by kapilt** [comment]
is this using a periodic policy? can you provide a sample policy? periodic policies have known issues if applied to arbitrary resources, specific to lambda environments (timeouts, etc), lack of reused cache when dealing with multiple periodic against the same resource type, etc. the recommend is generally not to use them with any bulk resource cardinalities versus any other form of compute.

**Comment by kapilt** [comment]
its conceivable though on an event lambda, of having enough transient storage consumption in a given process lifetime (~15m) to overflow temp with high disk read. alternatively we could cleanup temp output dir storage at the end of execution.

**Comment by sean-zou** [comment]
Hi @kapilt, Thanks for the response.

Yes it is using a periodic trigger. The policy is quick simple basically pulling the ec2 inventory everyday, however the region is huge like having 100k+ EC2 instances.

```
policies:
  - name: ec2-inventory
    resource: aws.ec2
    mode:
      <<: *mode-var-day-end
```

**Comment by kapilt** [comment]
with that type of resource cardinality/volume, using a periodic mode is really not recommended, versus a dedicated compute facility (container, instance, ci, etc), as it will also run into issues on time limits as well if doing api calls per resource, that seems preferable to trying to configure storage for the lambda that will timeout with this cardinality anyways.
