### ISSUE TITLE
aws - unused sg filter eni evaluation

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#8594]
### Describe the bug

When a subnet is shared cross account via RAM, ENI shows up in both the accounts i.e account that owns the subnet and the account that owns the ENI. The unused SG filter pulls down all the eni to evaluate the SGs and runs into an issue such that it doesn't contain all the metadata referenced in the code

### What did you expect to happen?

For the filter `unused` re: security-group resource type ENI should potentially only be evaluated in the parent account since SGs cannot be shared. 

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
policies:
   - name: sg-unused
     resource: aws.security-group
     filters:
       - unused
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/c7n/policy.py", line 331, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 550, in resources
    resources = self.filter_resources(resources)
  File "/usr/local/lib/python3.9/dist-packages/c7n/manager.py", line 112, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.9/dist-packages/c7n/resources/vpc.py", line 952, in process
    enis = self._get_eni_attributes()
  File "/usr/local/lib/python3.9/dist-packages/c7n/resources/vpc.py", line 931, in _get_eni_attributes
    instance_owner_id = nic['Attachment']['InstanceOwnerId']
KeyError: 'InstanceOwnerId'
```

### Extra information or context

A describe command on network interface id in both the parent account and the shared account gets the following responses

aws ec2 describe-network-interfaces --network-interface-ids eni-0XXXXXXXXXXXXXXX

Producer account (owner of the vpc/subnet)
```
{
    "NetworkInterfaces": [
        {
            "Attachment": {
                "Status": "attached"
            },
            "AvailabilityZone": "us-east-1b",
            "Description": "AWS Lambda VPC",
            "Groups": [
                {
                    "GroupName": "test-1",
                    "GroupId": "sg-123"
                },
                {
                    "GroupName": "test-2",
                    "GroupId": "sg-456"
                },
                {
                    "GroupName": "test-2",
                    "GroupId": "sg-789"
                }
            ],
            "InterfaceType": "lambda",
            "Ipv6Addresses": [],
            "MacAddress": "XX:XX:XX:XX:XX:XX",
            "NetworkInterfaceId": "eni-0XXXXXXXXXXXXXXX",
            "OwnerId": "012345678910",
            "PrivateDnsName": "ip-X-X-X-X.ec2.internal",
            "PrivateIpAddress": "X.X.X.X",
            "PrivateIpAddresses": [
                {
                    "Primary": true,
                    "PrivateDnsName": "ip-X-X-X-X.ec2.internal",
                    "PrivateIpAddress": "X.X.X.X"
                }
            ],
            "RequesterManaged": false,
            "SourceDestCheck": true,
            "Status": "in-use",
            "SubnetId": "subnet-0xxxxxxxxxxxde4c0",
            "TagSet": [],
            "VpcId": "vpc-xxxxxx"
        }
    ]
}
```
Consumer account (owner of the ENI):
```
{
    "NetworkInterfaces": [
        {
            "Attachment": {
                "AttachmentId": ela-attach-xxxxxx,
                "DeleteOnTermination": false,
                "DeviceIndex": 1,
                "InstanceOwnerId": "amazon-aws",
                "Status": "attached"
            },
            "AvailabilityZone": "us-east-1a",
            "Description": "AWS Lambda VPC",
            "Groups": [
                {
                    "GroupName": "test-1",
                    "GroupId": "sg-123"
                },
                {
                    "GroupName": "test-2",
                    "GroupId": "sg-456"
                },
                {
                    "GroupName": "test-2",
                    "GroupId": "sg-789"
                }
            ],
            "InterfaceType": "lambda",
            "Ipv6Addresses": [],
            "MacAddress": "XX:XX:XX:XX:XX:XX",
            "NetworkInterfaceId": "eni-0XXXXXXXXXXXXXXX",
            "OwnerId": "012345678910",
            "PrivateDnsName": "ip-X-X-X-X.ec2.internal",
            "PrivateIpAddress": "X.X.X.X",
            "PrivateIpAddresses": [
                {
                    "Primary": true,
                    "PrivateDnsName": "ip-X-X-X-X.ec2.internal",
                    "PrivateIpAddress": "X.X.X.X"
                }
            ],
            "RequesterId": "AXXXXXXXXXXXXXX"
            "RequesterManaged": false,
            "SourceDestCheck": true,
            "Status": "in-use",
            "SubnetId": "subnet-0xxxxxxxxxxxde4c0",
            "TagSet": [],
            "VpcId": "vpc-xxxxxx"
        }
    ]
}
```
This [line](https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/resources/vpc.py#L1007) seems to be trying to reference a key that's not present in the metadata

**Comment by kapilt** [comment]
hmmm.. in this context your running the policy in the ram "producer" account or the consumer account.

**Comment by PratMis** [comment]
Consumer account (subnet shared via RAM) owns the ENI, but it also shows up in the producer account. Correct @kapilt . In my context the policy is running in the producer account where the issue seems to be happening. The describe network interface id responses posted above is from both the producer account and the consumer account. I went ahead and edited the captions to make it more clear. Thanks
