### ISSUE TITLE
has-statement filter running into "list index out of range" error

### ISSUE THREAD

**Issue by timmygrable** [cloud-custodian/cloud-custodian#8603]
### Describe the bug

When running a policy using filter `has-statement`, in cases where there is a list of actions, it will error when the action in the list is of length 1 after the .split(":"). 

[Link to code here](https://github.com/cloud-custodian/cloud-custodian/blob/9d4c21783f93fb0e91aba86865579235baad806e/c7n/filters/policystatement.py#L78)

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
- name: policy-xyz
  resource: aws.efs
  description: 'Policy'
  filters:
  - not:
    - type: has-statement
      statements:
      - Action: elasticfilesystem:*
        Condition:
          Bool:
            aws:SecureTransport: 'false'
        Effect: Deny
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/c7n/policy.py", line 331, in run
resources = self.policy.resource_manager.resources()
File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 550, in resources
resources = self.filter_resources(resources)
File "/usr/local/lib/python3.9/dist-packages/c7n/manager.py", line 112, in filter_resources
resources = f.process(resources, event)
File "/usr/local/lib/python3.9/dist-packages/c7n/filters/core.py", line 389, in process
return self.process_set(resources, event)
File "/usr/local/lib/python3.9/dist-packages/c7n/filters/core.py", line 413, in process_set
resources = f.process(resources, event)
File "/usr/local/lib/python3.9/dist-packages/c7n/resources/efs.py", line 324, in process
return super().process(resources, event)
File "/usr/local/lib/python3.9/dist-packages/c7n/filters/policystatement.py", line 65, in process
return list(filter(None, map(self.process_resource, resources)))
File "/usr/local/lib/python3.9/dist-packages/c7n/filters/policystatement.py", line 105, in process_resource
== self.action_resource_case_insensitive(statement[key]):
File "/usr/local/lib/python3.9/dist-packages/c7n/filters/policystatement.py", line 78, in action_resource_case_insensitive
action.split(':')[1]))
IndexError: list index out of range
```

**Comment by timmygrable** [comment]
Looking more at this, it is because `Action: elasticfilesystem:*` in the policy.

**Comment by timmygrable** [comment]
Closing, looking into the specific file system policy, this account had a typo that was causing this to error out.

```
Action: [
"elasticfilesystem:*",
"testing"
]
```
