### ISSUE TITLE
Error message improvement

### ISSUE THREAD

**Issue by nikunj-badjatya** [cloud-custodian/cloud-custodian#8709]
### Describe the bug

Make error message friendly with mitigation options.
Seeing "sqlite3.OperationalError: database is locked" when running multiple c7n in subprocess in a single node.
Please see below for stack trace.

### What did you expect to happen?

Better error message with possible mitigation options.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.27
```

### Policy

```shell
Applicable for any policy.
```

### Relevant log/traceback output

```shell
2023-07-06 08:10:02,091: custodian.commands:ERROR Error while executing policy rds-resize-down, continuing
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/c7n/commands.py", line 307, in run
    policy()
  File "/usr/local/lib/python3.11/site-packages/c7n/policy.py", line 1352, in __call__
    resources = PullMode(self).run()
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c7n/resources/rds.py", line 135, in resources
    return super(RDS, self).resources(query=query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c7n/query.py", line 545, in resources
    self._cache.save(cache_key, resources)
  File "/usr/local/lib/python3.11/site-packages/c7n/cache.py", line 160, in save
    cursor.execute(
sqlite3.OperationalError: database is locked
2023-07-06 08:10:02,092: custodian.commands:ERROR The following policies had errors while executing
 - rds-resize-down
```

### Extra information or context

Running c7n as multiple subprocesses in a single node. 

Slack thread: https://cloud-custodian.slack.com/archives/CAL4P6YE6/p1688684562836899

**Comment by kapilt** [comment]
fair re better error message, c7n-org is intended for concurrent usage, alternatively passing different --cache file locations on the cli
