### ISSUE TITLE
OCI provider does not make use of instance principal

### ISSUE THREAD

**Issue by Hotpirsch** [cloud-custodian/cloud-custodian#8946]
### Describe the bug

I wanted to run the c7n-oci on an instance deployed in an OCI compartment. For added security I created a dynamic group and made sure the OCI CLI commands run on that instance make use of the instance_principal authentication.

### What did you expect to happen?

When I run cloud custodian with policies for OCI resources I expected the underlying implementation to make use of the OCI_CLI_AUTH environment variable which is used to signal the instance_principal authentication. Instead this caused an error. The c7n is searching for the `.oci/config` file that is used when local credentials are used for authentication.

### Cloud Provider

Oracle Cloud (OCI)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.31
Python:      3.9.16 (main, May 29 2023, 00:00:00)
             [GCC 11.3.1 20221121 (Red Hat 11.3.1-4.3.0.1)]
Platform:    posix.uname_result(sysname='Linux', nodename='custodian-host', release='5.15.0-104.119.4.2.el9uek.x86_64', version='#2 SMP Fri Aug 18 20:03:32 PDT 2023', machine='x86_64')
Using venv:  False
Docker: False
Installed:

argcomplete==3.1.1
attrs==23.1.0
boto3==1.28.41
botocore==1.31.41
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.30.2
rpds-py==0.10.2
s3transfer==0.6.2
six==1.16.0
tabulate==0.9.0
typing-extensions==4.7.1
urllib3==1.26.16
zipp==3.16.2
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/home/opc/.local/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/cli.py", line 363, in main
    command(config)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/commands.py", line 52, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/policy.py", line 68, in load
    collection = PolicyCollection.from_data(data, options)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/policy.py", line 88, in from_data
    policies = [Policy(p, options, session_factory=sf)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/policy.py", line 88, in <listcomp>
    policies = [Policy(p, options, session_factory=sf)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/policy.py", line 1153, in __init__
    session_factory = get_session_factory(self.provider_name, options)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n/policy.py", line 1033, in get_session_factory
    return clouds[provider_name]().get_session_factory(options)
  File "/home/opc/.local/lib/python3.9/site-packages/c7n_oci/provider.py", line 93, in get_session_factory
    session_factory = SessionFactory(profile=options["profile"], region=options["region"])
  File "/home/opc/.local/lib/python3.9/site-packages/c7n_oci/session.py", line 25, in __init__
    self._config = self._set_oci_config()
  File "/home/opc/.local/lib/python3.9/site-packages/c7n_oci/session.py", line 40, in _set_oci_config
    config = oci.config.from_file()
  File "/home/opc/.local/lib/python3.9/site-packages/oci/config.py", line 107, in from_file
    raise ConfigFileNotFound("Could not find config file at {}, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm".format(expanded_file_location))
oci.exceptions.ConfigFileNotFound: Could not find config file at /home/opc/.oci/config, please follow the instructions in the link to setup the config file https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm
```

**Comment by mashariqk** [comment]
I’m taking a look at this and will keep you updated!

**Comment by mashariqk** [comment]
@Hotpirsch There is an open PR [8998](https://github.com/cloud-custodian/cloud-custodian/pull/8998) for this bugfix

**Comment by kapilt** [comment]
fix merged
