### ISSUE TITLE
auto-tag aws userName on resources has botocore.errorfactory.InvalidParameterValueException

### ISSUE THREAD

**Issue by alberttwong** [cloud-custodian/cloud-custodian#8986]
### Describe the bug

Have this in my custodian.yml
```
policies:
- name: ec2-auto-tag-user
  resource: ec2
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/custodian-auto-tagger
    # note {account_id} is optional. If you put that there instead of
    # your actual account number, when the policy is provisioned it
    # will automatically inherit the account_id properly
    events:
      - RunInstances
  filters:
    - tag:CreatorName: absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
      principal_id_tag: CreatorId
```

got this error. 
```
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2023-09-26 18:04:15,474: custodian.commands:ERROR Error while executing policy ec2-auto-tag-user, continuing
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/c7n/commands.py", line 307, in run
    policy()
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/c7n/policy.py", line 1356, in __call__
    resources = mode.provision()
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/c7n/policy.py", line 581, in provision
    return manager.publish(
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/c7n/mu.py", line 388, in publish
    result, changed = self._create_or_update(
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/c7n/mu.py", line 507, in _create_or_update
    result = self.client.create_function(**params)
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/custodian/lib64/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
2023-09-26 18:04:15,476: custodian.commands:ERROR The following policies had errors while executing
 - ec2-auto-tag-user
```

### What did you expect to happen?

it should have worked since I followed the instructions at https://cloudcustodian.io/docs/aws/examples/ec2-auto-tag-user.html

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
(custodian) [ec2-user@ip-172-31-25-81 ~]$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.31
Python:      3.9.16 (main, Sep  8 2023, 00:00:00)
             [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-172-31-25-81.us-west-2.compute.internal', release='6.1.52-71.125.amzn2023.x86_64', version='#1 SMP PREEMPT_DYNAMIC Tue Sep 12 21:41:38 UTC 2023', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.1.1
attrs==23.1.0
boto3==1.28.41
botocore==1.31.41
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.30.2
rpds-py==0.10.2
s3transfer==0.6.2
six==1.16.0
tabulate==0.9.0
urllib3==1.26.16
zipp==3.16.2
```
```


### Policy

```shell
(custodian) [ec2-user@ip-172-31-25-81 ~]$ cat custodian.yml
policies:
  - name: ec2-tag-compliance-mark
    resource: aws.ec2
    comment: |
      Mark non-compliant, Non-ASG EC2 instances with stoppage in 1 days
    filters:
      - "State.Name": running
      - "tag:aws:autoscaling:groupName": absent
      - "tag:c7n_status": absent
      - or:
        - "tag:Owner": absent
        - "tag:Project": absent
    actions:
      - type: mark-for-op
        op: stop
        days: 4
  - name: ec2-auto-tag-user
    resource: ec2
    mode:
      type: cloudtrail
      role: arn:aws:iam::{account_id}:role/custodian-auto-tagger
    # note {account_id} is optional. If you put that there instead of
    # your actual account number, when the policy is provisioned it
    # will automatically inherit the account_id properly
      events:
        - RunInstances
    filters:
      - tag:CreatorName: absent
    actions:
      - type: auto-tag-user
        tag: Owner
        principal_id_tag: CreatorId
```

**Comment by alberttwong** [comment]
What I need is what type of AWS policy and role do I need?
