### ISSUE TITLE
[ERROR] InvalidOutputConfig: could not determine region for output bucket, use explicit ?region=region_name. s3://{bucket_name}/ap-northeast-2/

### ISSUE THREAD

**Issue by sla-1** [cloud-custodian/cloud-custodian#9073]
### Describe the bug

Intermittently we would get these errors in our lambda logs in 2 different regions `ap-northeast-2` and `ap-south-1`. All other regions are working just fine. These would come randomly like every ~3 days but recover after a few hours. We get alerted for these error every time they come up. So wondering if we can find the root cause.

### What did you expect to happen?

Not to see any errors

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n = 0.9.2
c7n-org = 0.6.1
```

### Policy

```shell
- name: mark-noncompliant-ebs-volumes-detached
    comment: Delete EBS volumes that are available (not attached)
    resource: ebs
    mode:
      type: periodic
      schedule: "cron(15 * * * ? *)"
      memory: 2048
      role: arn:aws:iam::{account_id}:role/{role_name} # rolename removed
      execution-options:
        log_group: custodian-logs
        output_dir: s3://{bucket_name}/{region}/ # bucketname removed
      tags:
          # Tags removed
    filters:
      - Attachments: []
      - State: available
      - "tag:custodian_status_delete": absent
      - "tag:aws:cloudformation:stack-id": absent
      - type: value
        key: "tag:tag:tag"
        op: not-in
        value: ["value1", "value2", "value3"]
      - or:
          - "tag:tag1": absent
          - "tag:tag2": absent
          - "tag:tag3": absent
      - or:
          - "tag:tag4": absent
          - not:
            - type: value
              key: "tag:tag5:Expiration"
              op: less-than
              value_type: expiration
              value: 0
    actions:
      - type: mark-for-op
        tag: custodian_status_delete
        op: delete
        days: 1
      - type: notify
        template: .html
        template_format: 'html'
        priority_header: '5'
        violation_desc: "The following detached EBS volumes didn't have the mandatory tags"
        action_desc: "they were marked for deletion after 1 day"
        subject: "Policy Report: Delete detached EBS volumes with missing tags on {{ account }} ({{ account_id }}) - {{ region }}"
        to:
          - "email@email.com"
        transport:
          type: sqs
          queue: "{mailer_queue}"
```
```


### Relevant log/traceback output

```shell
Full stack trace:

[ERROR] InvalidOutputConfig: could not determine region for output bucket, use explicit ?region=region_name. s3://{bucket_name}/ap-northeast-2/
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 151, in dispatch_event
    policy_config = init_config(policy_data)
  File "/var/task/c7n/handler.py", line 133, in init_config
    return AWS().initialize(config)
  File "/var/task/c7n/resources/aws.py", line 738, in initialize
    _default_bucket_region(options)
  File "/var/task/c7n/resources/aws.py", line 146, in _default_bucket_region
    raise invalid_output
```
```


### Extra information or context

_No response_

**Comment by kapilt** [comment]
which region is the output bucket in?

**Comment by sla-1** [comment]
@kapilt the region of the output bucket is located in `us-west-2`. The documentation here says that it'll auto detect https://cloudcustodian.io/docs/aws/usage.html#s3-logs-records Majority of the time we don't get this error but its popping up from time to time.

**Comment by ajkerrigan** [comment]
Based on your log output, it sounds like intermittently when Custodian tries to guess a region it gets a response that isn't an error (otherwise it would die or retry inside `inspect_bucket_region()`) but also doesn't include a helpful region header :thinking: . I've tried spamming HTTP HEAD requests from ap-northeast-2 for a us-west-2 bucket just in case that might eventually reproduce it, but I haven't been able to.

The error message does give good advice - adding `?region=us-west-2` to the end of your output path will keep Custodian from needing to guess the region. But it would still be nice to figure out what's going on during those failure windows.
