### ISSUE TITLE
c7n-policystream dependency conflict with c7n 0.9.35

### ISSUE THREAD

**Issue by scolebrook** [cloud-custodian/cloud-custodian#9341]
### Describe the bug

`pip install c7n c7n-policystream` results in dependency conflicts and pip downgrades `c7n-policystream`.

```
$ pip list | grep c7n
c7n                       0.9.35
c7n_policystream          0.3.1
```

`c7n_policystream` should be 0.4.33.

This is a clean python 3.12 installation with no previous c7n installations.

Here's the start of the pip install output until the first time it downgrades `c7n_policystream` in an attempt to find a version without a dependency conflict. It repeats this over and over until it gets to `0.3.1`.

```
Collecting c7n
  Downloading c7n-0.9.35-py3-none-any.whl.metadata (15 kB)
Collecting c7n-policystream
  Downloading c7n_policystream-0.4.33-py3-none-any.whl.metadata (7.5 kB)
Collecting boto3==1.34.55 (from c7n)
  Downloading boto3-1.34.55-py3-none-any.whl.metadata (6.6 kB)
Collecting jsonschema==4.21.1 (from c7n)
  Downloading jsonschema-4.21.1-py3-none-any.whl.metadata (7.8 kB)
Collecting argcomplete==3.2.2 (from c7n)
  Downloading argcomplete-3.2.2-py3-none-any.whl.metadata (16 kB)
Collecting python-dateutil==2.9.0.post0 (from c7n)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pyyaml==6.0.1 (from c7n)
  Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_aarch[64](https://gitlab.ippon.fr/ops-tools/cloud-custodian/-/jobs/469081#L64).manylinux2014_aarch64.whl.metadata (2.1 kB)
Collecting tabulate==0.9.0 (from c7n)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting importlib-metadata==6.11.0 (from c7n)
  Downloading importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Collecting docutils==0.18.1 (from c7n)
  Downloading docutils-0.18.1-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting urllib3==1.26.18 (from c7n)
  Downloading urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 9.1 MB/s eta 0:00:00
Collecting referencing==0.31.1 (from c7n)
  Downloading referencing-0.31.1-py3-none-any.whl.metadata (2.7 kB)
Collecting botocore==1.34.55 (from c7n)
  Downloading botocore-1.34.55-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath==1.0.1 (from c7n)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer==0.10.0 (from c7n)
  Downloading s3transfer-0.10.0-py3-none-any.whl.metadata (1.7 kB)
Collecting attrs==23.2.0 (from c7n)
  Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting jsonschema-specifications==2023.12.1 (from c7n)
  Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting rpds-py==0.18.0 (from c7n)
  Downloading rpds_py-0.18.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.1 kB)
Collecting six==1.16.0 (from c7n)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting zipp==3.17.0 (from c7n)
  Downloading zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting c7n
  Downloading c7n-0.9.34-py3-none-any.whl.metadata (15 kB)
Collecting click==8.1.7 (from c7n-policystream)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pygit2==1.13.3 (from c7n-policystream)
  Downloading pygit2-1.13.3-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (3.6 kB)
INFO: pip is looking at multiple versions of c7n-policystream to determine which version is compatible with other requirements. This could take a while.
```

### What did you expect to happen?

For pip to install the correct version of policystream and for it to generate a diff.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Running in a ci env so can't get interactive access but these are the versions installed by pip

c7n                       0.9.35
c7n_policystream          0.3.1
```

### Relevant log/traceback output

```shell
$ c7n-policystream diff --repo-uri ./ --output ./diff.yaml --source ${SOURCE} --target ${TARGET} --verbose
Traceback (most recent call last):
  File "/builds/ops-tools/cloud-custodian/venv/bin/c7n-policystream", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/policystream.py", line 865, in diff
    load_resources()
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/c7n/resources/__init__.py", line 20, in load_resources
    load_providers(set(pmap))
  File "/builds/ops-tools/cloud-custodian/venv/lib/python3.12/site-packages/c7n/resources/__init__.py", line 73, in load_providers
    from c7n_awscc.entry import initialize_awscc
ModuleNotFoundError: No module named 'c7n_awscc'
```
```


### Extra information or context

_No response_

**Comment by ajkerrigan** [comment]
It looked like `0.4.34` was built but didn't previously make it to PyPI. It's up there now, and should install alongside c7n 0.9.35. Let me know if you have any lingering issues though.

**Comment by scolebrook** [comment]
Finally got a chance to try this again. It installed 0.4.34 this time. Thanks for having a look at this.
