### ISSUE TITLE
Unable to use cloudtrail based lambda execute for EBS volumes

### ISSUE THREAD

**Issue by gravops** [cloud-custodian/cloud-custodian#9366]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/9365

<div type='discussions-op-text'>

<sup>Originally posted by **gravops** March 19, 2024</sup>
I am using below policy to trigger a lambda on behalf of cloud trail event:
`policies:
  - name: custodian-ebs-monitor-tag
    resource: ebs
    mode:
      type: cloudtrail
      role: CustodianLamdaRole
      events:
        - source: 'ec2.amazonaws.com'
          event: 'AttachVolume'
          ids: 'requestParameters.volumeId'
    filters:
      - "tag:custodian": present
    actions:
      - type: mark-for-op
        op: delete
        days: 30`

while the lambda I am running, getting below error:

Test Event Name
(unsaved) test event

Response
{
  "errorMessage": "name 'event' is not defined",
  "errorType": "NameError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1204, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
    "  File \"/var/task/custodian_policy.py\", line 7, in <module>\n    event_name = event['detail']['eventName']\n"
  ]
}

Function Logs
[ERROR] NameError: name 'event' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/custodian_policy.py", line 7, in <module>
    event_name = event['detail']['eventName']INIT_REPORT Init Duration: 561.46 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
[ERROR] NameError: name 'event' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/custodian_policy.py", line 7, in <module>
    event_name = event['detail']['eventName']INIT_REPORT Init Duration: 769.42 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: 32488f0b-ec83-4552-a45e-c238f7060c4b Version: $LATEST
Unknown application error occurred
Runtime.Unknown
END RequestId: 32488f0b-ec83-4552-a45e-c238f7060c4b
REPORT RequestId: 32488f0b-ec83-4552-a45e-c238f7060c4b	Duration: 784.36 ms	Billed Duration: 785 ms	Memory Size: 1024 MB	Max Memory Used: 34 MB

Request ID
32488f0b-ec83-4552-a45e-c238f7060c4b

Any help on this please?</div>

**Comment by gravops** [comment]
I am using c7n version 0.9.34. I think monitoring events from cloud trail is broken. Can someone suggest a solution on this?

**Comment by gravops** [comment]
This event I am trying to catch from the policy but it is giving error:
`    "requestParameters": {
        "volumeId": "vol-049981d477c756c98",
        "instanceId": "i-0316ff13c58ccd507",
        "device": "/dev/sdb",
        "deleteOnTermination": false
    }`

**Comment by gravops** [comment]
Lambda i have created is event based and i was trying to trigger it manually which was not working. events based triggers are working fine with desired results.
