### ISSUE TITLE
Error when getting max Percentage CPU on Azure VM

### ISSUE THREAD

**Issue by novatelli** [cloud-custodian/cloud-custodian#9410]
### Describe the bug

This is simple policy I used.

```
policies:
    - name: vm-with-cpu-spikes
      resource: azure.vm
      filters:
         - type: metric
           metric: Percentage CPU
           aggregation: maximum
           op: lt
           threshold: 50
           timeframe: 24
```

When I execute it it shows error:
```

Traceback (most recent call last):
  File "/.local/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/.local/lib/python3.10/site-packages/c7n_azure/query.py", line 288, in resources
    resources = self.filter_resources(resources)
  File "/.local/lib/python3.10/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 172, in process
    processed = list(w.map(self.process_resource, resources))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 245, in process_resource
    return resource if self.passes_op_filter(resource) else None
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 241, in passes_op_filter
    aggregate_value = self.func(m_data)
  File "/.local/lib/python3.10/site-packages/c7n_azure/utils.py", line 214, in max
    return float(max(clean_numbers))
ValueError: max() arg is an empty sequence
2024-04-08 09:49:56,870: custodian.commands:ERROR Error while executing policy vm-with-cpu-spikes, continuing
Traceback (most recent call last):
  File "/.local/lib/python3.10/site-packages/c7n/commands.py", line 302, in run
    policy()
  File "/.local/lib/python3.10/site-packages/c7n/policy.py", line 1326, in __call__
    resources = PullMode(self).run()
  File "/.local/lib/python3.10/site-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/.local/lib/python3.10/site-packages/c7n_azure/query.py", line 288, in resources
    resources = self.filter_resources(resources)
  File "/.local/lib/python3.10/site-packages/c7n/manager.py", line 111, in filter_resources
    resources = f.process(resources, event)
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 172, in process
    processed = list(w.map(self.process_resource, resources))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 245, in process_resource
    return resource if self.passes_op_filter(resource) else None
  File "/.local/lib/python3.10/site-packages/c7n_azure/filters.py", line 241, in passes_op_filter
    aggregate_value = self.func(m_data)
  File "/.local/lib/python3.10/site-packages/c7n_azure/utils.py", line 214, in max
    return float(max(clean_numbers))
ValueError: max() arg is an empty sequence
2024-04-08 09:49:56,871: custodian.commands:ERROR The following policies had errors while executing
 - vm-with-cpu-spikes
```

```
python3.12 --version
Python 3.12.2
```

I try this in couple of subscription always with same result.

### What did you expect to happen?

To be fixed.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.22
Python:      3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='MN-DTP0797', release='5.15.146.1-microsoft-standard-WSL2', version='#1 SMP Thu Jan 11 04:09:03 UTC 2024', machine='x86_64')
Using venv:  False
Docker: False
Installed:

PyJWT==2.6.0
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.9.1.post1
argcomplete==2.0.0
attrs==22.2.0
azure-common==1.1.28
azure-core==1.26.2
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.12.0
azure-graphrbac==0.61.1
azure-identity==1.12.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.6.0
azure-keyvault-keys==4.7.0
azure-keyvault-secrets==4.6.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.3.2
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.0.1
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.14.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.10.1
azure-storage-queue==12.5.0
boto3==1.26.51
botocore==1.29.51
c7n==0.9.22
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
click==8.1.3
cryptography==39.0.0
distlib==0.3.6
docutils==0.17.1
idna==3.4
importlib-metadata==4.13.0
importlib-resources==5.10.2
isodate==0.6.1
jmespath==1.0.1
jsonschema==4.17.3
msal==1.20.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.2.2
pkgutil-resolve-name==1.3.10
portalocker==2.6.0
pycparser==2.21
pyjwt==2.6.0
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
pyyaml==6.0
requests==2.28.2
requests-oauthlib==1.3.1
s3transfer==0.6.0
setuptools==66.0.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
urllib3==1.26.14
zipp==3.11.0
```

### Policy

```shell
policies:
    - name: vm-with-cpu-spikes
      resource: azure.vm
      filters:
         - type: metric
           metric: Percentage CPU
           aggregation: maximum
           op: lt
           threshold: 50
           timeframe: 24
```

**Comment by novatelli** [comment]
Can I get update on this? With latest version 0.9.35 error still occurs.

**Comment by ajkerrigan** [comment]
This looks similar to #6085, where certain resources (like stopped VMs) were not returning metric data. The solution from that issue was to add something like `no_data_action: to_zero` to the metric filter to treat those missing metrics as zero values. In a case like stopped instances, you might want to also/instead filter instances by state. But having a defined `no_data_action` seems like a good backup in either case.

**Comment by novatelli** [comment]
thanks @ajkerrigan that was it. It solved my issue. Maybe is mention about this problem somewhere in output or into wiki? https://cloudcustodian.io/docs/azure/examples/metrics-general.html So there is easy chance to find it out without googling.

**Comment by ajkerrigan** [comment]
> thanks @ajkerrigan that was it. It solved my issue. Maybe is mention about this problem somewhere in output or into wiki? https://cloudcustodian.io/docs/azure/examples/metrics-general.html So there is easy chance to find it out without googling.

Agreed - as of https://github.com/cloud-custodian/cloud-custodian/pull/9579 the page you linked has an example policy with `no_data_action: to_zero` and a note about why.
