### ISSUE TITLE
rds-snapshot instance filter not does not work

### ISSUE THREAD

**Issue by mrvalterhugo** [cloud-custodian/cloud-custodian#9415]
### Describe the bug

When using this policy:

```
policies:
  - name: rds-snapshot-orphan
    resource: aws.rds-snapshot
    filters:
     - type: instance
       value: 0
       value_type: resource_count
```

I get error **Failed to validate policy 'instance' is not one of ['age']**

### What did you expect to happen?

I expected the filter instance to work.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.14
Python:      3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Platform:    posix.uname_result(sysname='Darwin', nodename='f4d4887244a8', release='23.4.0', version='Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.12.3
attrs==23.1.0
boto3==1.26.134
botocore==1.29.134
cffi==1.16.0
cryptography==40.0.2
importlib-metadata==6.6.0
jmespath==1.0.1
jsonschema==3.2.0
pycparser==2.22
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==5.4.1
s3transfer==0.6.1
setuptools==68.2.2
six==1.16.0
tabulate==0.8.10
typing-extensions==4.8.0
urllib3==1.26.9
zipp==3.15.0
```

### Policy

```shell
policies:
  - name: rds-snapshot-orphan
    resource: aws.rds-snapshot
    filters:
     - type: instance
       value: 0
       value_type: resource_count
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/c7n/schema.py", line 51, in validate
    resp = policy_error_scope(specific_error(errors[0]), data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/c7n/schema.py", line 123, in specific_error
    return specific_error(e)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/c7n/schema.py", line 133, in specific_error
    elif 'type' in v and t in v['properties']['type']['enum']:
                              ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
2024-04-09 11:29:14,838: custodian.commands:ERROR invalid policy file: policies/rds-snapshopt.yml error: Failed to validate policy 'instance' is not one of ['age']

Failed validating 'enum' in schema[0]['properties']['type']:
    {'enum': ['age']}

On instance['type']:
    'instance' 
 {'name': 'rds-snapshot-orphan', 'resource': 'aws.rds-snapshot', 'filters': [{'type': 'instance', 'value': 0, 'value_type': 'resource_count'}]} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/aws.rds-snapshot/policy'}]}

On instance['policies'][0]:
    {'filters': [{'type': 'instance',
                  'value': 0,
                  'value_type': 'resource_count'}],
     'name': 'rds-snapshot-orphan',
     'resource': 'aws.rds-snapshot'}
```

**Comment by zkarpinski** [comment]
That filter was added in v0.9.30.0. Please upgrade from your version of **0.9.14**

https://github.com/cloud-custodian/cloud-custodian/releases/tag/0.9.30.0
https://github.com/cloud-custodian/cloud-custodian/pull/8764

**Comment by mrvalterhugo** [comment]
Thank you, the new version has worked.
