### ISSUE TITLE
aws - glueconnection subnet not found

### ISSUE THREAD

**Issue by timmygrable** [cloud-custodian/cloud-custodian#9474]
### Describe the bug

Error when a subnet doesn't exist on a GlueConnection - I'll follow up with a PR

### What did you expect to happen?

Pass

### Cloud Provider

Amazon Web Services (AWS)

### Relevant log/traceback output

```shell
2024-04-30 10:09:09,755 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/c7n/resources/vpc.py", line 602, in get_resources
    return super().get_resources(resource_ids)
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 228, in get_resources
    return self.query.get(self.manager, ids)
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 98, in get
    resources = self.filter(resource_manager, **params)
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 77, in filter
    return self._invoke_client_enum(
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 55, in _invoke_client_enum
    data = results.build_full_result()
  File "/usr/local/lib/python3.9/dist-packages/botocore/paginate.py", line 479, in build_full_result
    for response in self:
  File "/usr/local/lib/python3.9/dist-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 768, in _make_request
    return self.retry(self._method, **current_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/c7n/utils.py", line 454, in _retry
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSubnetID.NotFound) when calling the DescribeSubnets operation: The subnet ID '['subnet-0a71719e859b86c38']' does not exist
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/c7n/policy.py", line 330, in run
    resources = self.policy.resource_manager.resources()
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 550, in resources
    resources = self.filter_resources(resources)
  File "/usr/local/lib/python3.9/dist-packages/c7n/manager.py", line 112, in filter_resources
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.9/dist-packages/c7n/filters/core.py", line 397, in process
    return self.process_set(resources, event)
  File "/usr/local/lib/python3.9/dist-packages/c7n/filters/core.py", line 421, in process_set
    resources = f.process(resources, event)
  File "/usr/local/lib/python3.9/dist-packages/c7n/filters/vpc.py", line 98, in process
    related = self.get_related(resources)
  File "/usr/local/lib/python3.9/dist-packages/c7n/filters/related.py", line 46, in get_related
    related = resource_manager.get_resources(list(related_ids))
  File "/usr/local/lib/python3.9/dist-packages/c7n/query.py", line 586, in get_resources
    resources = self.source.get_resources(ids)
  File "/usr/local/lib/python3.9/dist-packages/c7n/resources/vpc.py", line 608, in get_resources
    resource_ids.remove(sid)
ValueError: list.remove(x): x not in list
```

**Comment by timmygrable** [comment]
Closing, issue at the resource configuration level
