### ISSUE TITLE
VPC `set-flow-log` action fails when using the new `attrs` key

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#9583]
### Describe the bug

The VPC `set-flow-log` action got a refactor to handle additional parameter keys via shape validation rather than hardcoding a schema into Custodian. But at runtime, it seems like the schema conversion effectively discard those `attrs` keys.

### What did you expect to happen?

I _think_ the action should probably allow the legacy schema keys or new `attrs` key, and prioritize the latter in case of a conflict.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.38
Python:      3.12.4 (main, Jun  6 2024, 18:26:44) [GCC 11.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='mosa', release='6.8.8-060808-generic', version='#202404271536 SMP PREEMPT_DYNAMIC Sat Apr 27 15:54:17 UTC 2024', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

PyJWT==2.8.0
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.10.4
argcomplete==3.4.0
attrs==23.2.0
azure-common==1.1.28
azure-core==1.30.1
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.19.0
azure-graphrbac==0.61.1
azure-identity==1.16.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.8.0
azure-keyvault-keys==4.9.0
azure-keyvault-secrets==4.8.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-appconfiguration==0.7.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-appplatform==8.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-automation==0.1.1
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==12.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-analytics==0.5.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-desktopvirtualization==1.1.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==11.0.0
azure-mgmt-frontdoor==1.2.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-kusto==2.2.0
azure-mgmt-logic==9.0.0
azure-mgmt-machinelearningservices==1.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-recoveryservices==2.5.0
azure-mgmt-recoveryservicesbackup==7.0.0
azure-mgmt-redhatopenshift==1.4.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicebus==8.2.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-signalr==0.4.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-streamanalytics==1.0.0
azure-mgmt-subscription==1.0.0
azure-mgmt-synapse==2.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.19.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.15.0
azure-storage-queue==12.9.0
boto3==1.34.128
botocore==1.34.128
c7n==0.9.38
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cryptography==42.0.5
distlib==0.3.8
docutils==0.18.1
google-api-core==2.17.1
google-api-python-client==2.121.0
google-auth==2.28.1
google-auth-httplib2==0.2.0
google-cloud-appengine-logging==1.4.2
google-cloud-audit-log==0.2.5
google-cloud-core==2.4.1
google-cloud-logging==3.9.0
google-cloud-monitoring==2.19.2
google-cloud-storage==2.15.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.62.0
grpc-google-iam-v1==0.13.0
grpcio==1.62.0
grpcio-status==1.62.0
httplib2==0.22.0
idna==3.7
importlib-metadata==6.11.0
isodate==0.6.1
jmespath==1.0.1
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
msal==1.28.0
msal-extensions==1.1.0
msrest==0.7.1
msrestazure==0.6.4.post1
netaddr==0.7.20
oauthlib==3.2.2
packaging==24.0
portalocker==2.8.2
proto-plus==1.23.0
protobuf==4.25.3
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.22
pyjwt==2.8.0
pyparsing==3.1.1
pyrate-limiter==2.10.0
python-dateutil==2.9.0.post0
pytz==2024.1
pyyaml==6.0.1
referencing==0.31.1
requests==2.31.0
requests-oauthlib==2.0.0
retrying==1.3.4
rpds-py==0.18.1
rsa==4.9
s3transfer==0.10.1
six==1.16.0
tabulate==0.9.0
typing-extensions==4.11.0
tzlocal==5.2
uritemplate==4.1.1
urllib3==1.26.19
zipp==3.19.2
```

### Policy

```shell
policies:
  - name: aws-vpc-flow-logs
    resource: aws.vpc
    filters:
      - type: value
        key: tag:Name
        value: dev
    actions:
      - type: set-flow-log
        LogGroupName: bad-dest
        attrs:
          TrafficType: ALL
          LogDestinationType: cloud-watch-logs
          LogGroupName: ajtest-vpc-logs
          DeliverLogsPermissionArn: arn:aws:iam::111111111111:role/AWSControlTower_VPCFlowLogsRole
          TagSpecifications:
            - ResourceType: vpc-flow-log
              Tags:
                - Key: Owner
                  Value: me
```

### Relevant log/traceback output

```shell
Traceback (most recent call last):                                                                                                                           [0/35039]
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/resources/vpc.py", line 3020, in process
    self.run_client_op(
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/resources/vpc.py", line 2977, in run_client_op
    results = op(**params)
              ^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameter) when calling the CreateFlowLogs operation: DeliverLogsPermissionArn can't be empty if LogDestina
tionType is cloud-watch-logs.
2024-06-24 10:55:31,554: custodian.commands:ERROR Error while executing policy aws-vpc-flow-logs, continuing
Traceback (most recent call last):
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/commands.py", line 308, in run
    policy()
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/policy.py", line 1388, in __call__
    resources = mode.run()
                ^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/resources/vpc.py", line 3020, in process
    self.run_client_op(
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/c7n/resources/vpc.py", line 2977, in run_client_op
    results = op(**params)
              ^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aj/.local/pipx/venvs/c7n/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameter) when calling the CreateFlowLogs operation: DeliverLogsPermissionArn can't be empty if LogDestina
tionType is cloud-watch-logs.
2024-06-24 10:55:31,558: custodian.commands:ERROR The following policies had errors while executing
 - aws-vpc-flow-logs
```

**Comment by kapilt** [comment]
right it was all or nothing on config style, not intended at the time to support hybrid, ie. given a conflict, what wins. ie, what would you have expected to happen in the case where you have conflicting log names in both attrs and top level?

**Comment by ajkerrigan** [comment]
Initially I would have expected `attrs` to win, but I can see how that could lead to confusion/surprises. I'll tweak the PR to fail validation if a policy includes legacy and current syntax, that seems clearer and more explicit :+1: .
