### ISSUE TITLE
Kubernetes Controller Mode installation failes

### ISSUE THREAD

**Issue by anna-shcherbak** [cloud-custodian/cloud-custodian#9588]
### Describe the bug

When I tried to install Cloud Custodian for Kubernetes using Controller Mode by following your documentation for installation using Helm, the pod from the **c7n-kube** deployment always failed.
About a month ago everything worked fine with the same configuration, when I started to dig deeper, the only variable that changed was a version of the docker c7n image that set to the 'latest'.

I started rolling back versions for the image and installing the version  **cloudcustodian/c7n:0.9.36.0** solved the problem, the 0.9.37.0 version failed the same way as the 'latest'.

### What did you expect to happen?

I expected a pod to be successfully deployed.

### Cloud Provider

Kubernetes (Alpha)

### Relevant log/traceback output

```shell
2024-06-25 19:05:46,506: c7n_kube.server:INFO Loaded 4 policies
Traceback (most recent call last):
  File "/usr/local/bin/c7n-kates", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/src/tools/c7n_kube/c7n_kube/cli.py", line 128, in cli
    init(
  File "/src/tools/c7n_kube/c7n_kube/server.py", line 196, in init
    server.socket = ssl.wrap_socket(
                    ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

**Comment by kapilt** [comment]
Thanks for reporting, does feel like we need some e2e release testing here
