### ISSUE TITLE
AWS Lambda function are failing with the latest version 0.9.38

### ISSUE THREAD

**Issue by ahmadzaikk** [cloud-custodian/cloud-custodian#9625]
### Describe the bug

When I deploy custodian policy using the latest version 0.9.38, it fails with the following error.

{
  "errorMessage": "'detail'",
  "errorType": "KeyError",
  "requestId": "dd855b4c-c3f6-4995-8909-7ba774e3d046",
  "stackTrace": [
    "  File \"/var/task/custodian_policy.py\", line 6, in run\n    return handler.dispatch_event(event, context)\n",
    "  File \"/var/task/c7n/handler.py\", line 142, in dispatch_event\n    event['detail'] = {} if event.get('detail') == '{}' else event['detail']\n"
  ]
}

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
When I deploy custodian policy using the latest version 0.9.38, it fails with the following error.

{
  "errorMessage": "'detail'",
  "errorType": "KeyError",
  "requestId": "dd855b4c-c3f6-4995-8909-7ba774e3d046",
  "stackTrace": [
    "  File \"/var/task/custodian_policy.py\", line 6, in run\n    return handler.dispatch_event(event, context)\n",
    "  File \"/var/task/c7n/handler.py\", line 142, in dispatch_event\n    event['detail'] = {} if event.get('detail') == '{}' else event['detail']\n"
  ]
}
```

### Policy

```shell
All Policies
```

### Relevant log/traceback output

```shell
START RequestId: dd855b4c-c3f6-4995-8909-7ba774e3d046 Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] KeyError: 'detail'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 6, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 142, in dispatch_event
    event['detail'] = {} if event.get('detail') == '{}' else event['detail']END RequestId: dd855b4c-c3f6-4995-8909-7ba774e3d046
REPORT RequestId: dd855b4c-c3f6-4995-8909-7ba774e3d046	Duration: 3.04 ms	Billed Duration: 4 ms	Memory Size: 512 MB	Max Memory Used: 75 MB	Init Duration: 570.38 ms
```

**Comment by kapilt** [comment]
there's a fix in trunk, will be resolved in next release (0.9.39) hopefully today/tomorrow.

**Comment by kapilt** [comment]
this is specific to config rule periodic policies afaik

**Comment by kapilt** [comment]
fix release

**Comment by ahmadzaikk** [comment]
@kapilt Thanks
