### ISSUE TITLE
ParamValidationError for S3Control s3-access-point

### ISSUE THREAD

**Issue by 232161233642** [cloud-custodian/cloud-custodian#9669]
### Describe the bug

Trying to use a policy based on aws.s3-access-point to notify and/or delete on CreateAccessPoint events if matching the filter but instead fails with an unhandled ParamValidationError that "AccountId is required but not set". I've tried nuking and recreating the environment/control/lambda and redeploying, multiple variants on the policy, and I've gone poking through the source, but I can't figure out why it thinks AccountId isn't set.

### What did you expect to happen?

Using the [s3control resources](https://cloudcustodian.io/docs/aws/resources/group-s3control.html) for [aws.s3-access-point](https://cloudcustodian.io/docs/aws/resources/s3-access-point.html) I should be able to implement policies against access points, as with any other resource. 

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.36
Python:      3.10.2 (main, Jun 10 2024, 11:17:48) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]
Platform:    posix.uname_result(sysname='Linux', nodename='blah.ec2.internal', release='4.14.336-257.568.amzn2.x86_64', version='#1 SMP Sat Mar 23 09:49:55 UTC 2024', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.3.0
attrs==23.2.0
boto3==1.34.92
botocore==1.34.92
docutils==0.18.1
importlib-metadata==6.11.0
jmespath==1.0.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
python-dateutil==2.9.0.post0
pyyaml==6.0.1
referencing==0.31.1
rpds-py==0.18.0
s3transfer==0.10.1
six==1.16.0
tabulate==0.9.0
urllib3==1.26.18
zipp==3.18.1
```

### Policy

```shell
---
policies:
  - name: check-noncompliant-s3-access-point
    resource: aws.s3-access-point
    description: |
      s3 access point policy
    mode:
      type: cloudtrail
      events:
        - source: s3.amazonaws.com
          event: CreateAccessPoint
          ids: "additionalEventData.accessPointName"
      role: arn:aws:iam::{account_id}:role/c7nLambdaRole
      execution-options:
        metrics: aws
      member-role: arn:aws:iam::{account_id}:role/c7nRemediation
    actions:
      - type: notify
        template: default.html
        priority_header: 3
        subject: "Non-compliant S3 access point created in {{ account }}"
        severity_desc: Warning
        to:
          - test@example.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/{account_id}/c7nMailQueue
```

### Relevant log/traceback output

```shell
[DEBUG]	2024-08-14T15:52:42.949Z	<...>	using default region:us-east-1 from boto
[INFO]	2024-08-14T15:52:43.288Z	<...>	Processing event
 
{
    "version": "0",
    "id": "",
    "detail-type": "AWS API Call via CloudTrail",
    "source": "aws.s3",
    "account": "123456789012",
    "time": "2024-08-14T15:52:32Z",
    "region": "us-east-1",
    "resources": [],
    "detail": {
        "eventVersion": "1.09",
        "userIdentity": {
            "type": "AssumedRole",
            "principalId": "AROAVX753F5QDEXAMPLE:bob@example.com",
            "arn": "arn:aws:sts::123456789012:assumed-role/TestRole/bob@example.com",
            "accountId": "123456789012",
            "accessKeyId": "ASIAVX753F5EXAMPLE",
            "sessionContext": {
                "sessionIssuer": {
                    "type": "Role",
                    "principalId": "AROAVX753F5QDEXAMPLE",
                    "arn": "arn:aws:iam::123456789012:role/aws-reserved/sso.amazonaws.com/TestRole",
                    "accountId": "123456789012",
                    "userName": "TestRole"
                },
                "attributes": {
                    "creationDate": "2024-08-14T15:17:13Z",
                    "mfaAuthenticated": "false"
                }
            }
        },
        "eventTime": "2024-08-14T15:52:32Z",
        "eventSource": "s3.amazonaws.com",
        "eventName": "CreateAccessPoint",
        "awsRegion": "us-east-1",
        "sourceIPAddress": "174.138.224.239",
        "userAgent": "[PotatoAgent]",
        "requestParameters": {
            "Host": "123456789012.s3-control.us-east-1.amazonaws.com",
            "CreateAccessPointRequest": {
                "PublicAccessBlockConfiguration": {
                    "RestrictPublicBuckets": true,
                    "BlockPublicPolicy": true,
                    "BlockPublicAcls": true,
                    "IgnorePublicAcls": true
                },
                "xmlns": "http://awss3control.amazonaws.com/doc/2018-08-20/",
                "Bucket": "example-bucket-name",
                "VpcConfiguration": {
                    "VpcId": "vpc-0468b0bexample"
                }
            }
        },
        "responseElements": null,
        "additionalEventData": {
            "SignatureVersion": "SigV4",
            "accessPointName": "random-test-ap",
            "CipherSuite": "TLS_AES_128_GCM_SHA256",
            "bytesTransferredIn": 459,
            "AuthenticationMethod": "AuthHeader",
            "x-amz-id-2": "",
            "bytesTransferredOut": 226
        },
        "requestID": "",
        "eventID": "",
        "readOnly": false,
        "eventType": "AwsApiCall",
        "managementEvent": true,
        "recipientAccountId": "123456789012",
        "vpcEndpointId": "vpce-f40dexample",
        "eventCategory": "Management",
        "tlsDetails": {
            "tlsVersion": "TLSv1.3",
            "cipherSuite": "TLS_AES_128_GCM_SHA256",
            "clientProvidedHostHeader": "123456789012.s3-control.us-east-1.amazonaws.com"
        }
    },
    "debug": true
}

[DEBUG]	2024-08-14T15:52:43.289Z	<...>	Disabling cache
[WARNING]	2024-08-14T15:52:43.289Z	<...>	Custodian reserves policy lambda tags starting with custodian - policy specifies custodian-info
[INFO]	2024-08-14T15:52:43.289Z	<...>	Found resource ids:['random-test-ap']
[ERROR]	2024-08-14T15:52:43.529Z	<...>	error during policy execution
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/site-packages/botocore/regions.py", line 502, in construct_endpoint
    provider_result = self._provider.resolve_endpoint(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/utils.py", line 1496, in inner
    return func_with_weakref(weakref.ref(self), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/utils.py", line 1492, in func_with_weakref
    return func(weakref_to_self(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 714, in resolve_endpoint
    endpoint = self.ruleset.evaluate(input_parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 694, in evaluate
    evaluation = rule.evaluate(input_parameters.copy(), self.rule_lib)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 546, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 546, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 546, in evaluate
    rule_result = rule.evaluate(scope_vars.copy(), rule_lib)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/endpoint_provider.py", line 522, in evaluate
    raise EndpointResolutionError(msg=error)
botocore.exceptions.EndpointResolutionError: AccountId is required but not set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/c7n/handler.py", line 167, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1316, in push
    return mode.run(event, lambda_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/policy.py", line 502, in run
    resources = self.resolve_resources(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/policy.py", line 706, in resolve_resources
    return super().resolve_resources(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/policy.py", line 484, in resolve_resources
    resources = self.policy.resource_manager.get_resources(resource_ids)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/query.py", line 586, in get_resources
    resources = self.source.get_resources(ids)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/query.py", line 228, in get_resources
    return self.query.get(self.manager, ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/query.py", line 98, in get
    resources = self.filter(resource_manager, **params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/query.py", line 77, in filter
    return self._invoke_client_enum(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/c7n/query.py", line 58, in _invoke_client_enum
    data = op(**params)
           ^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 955, in _make_api_call
    ) = self._resolve_endpoint_ruleset(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1106, in _resolve_endpoint_ruleset
    endpoint_info = self._ruleset_resolver.construct_endpoint(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/botocore/regions.py", line 512, in construct_endpoint
    raise botocore_exception from ex
botocore.exceptions.ParamValidationError: Parameter validation failed:
AccountId is required but not set
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] ParamValidationError: Parameter validation failed:
AccountId is required but not set
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 5, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 167, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 1316, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 502, in run
    resources = self.resolve_resources(event)
  File "/var/task/c7n/policy.py", line 706, in resolve_resources
    return super().resolve_resources(event)
  File "/var/task/c7n/policy.py", line 484, in resolve_resources
    resources = self.policy.resource_manager.get_resources(resource_ids)
  File "/var/task/c7n/query.py", line 586, in get_resources
    resources = self.source.get_resources(ids)
  File "/var/task/c7n/query.py", line 228, in get_resources
    return self.query.get(self.manager, ids)
  File "/var/task/c7n/query.py", line 98, in get
    resources = self.filter(resource_manager, **params)
  File "/var/task/c7n/query.py", line 77, in filter
    return self._invoke_client_enum(
  File "/var/task/c7n/query.py", line 58, in _invoke_client_enum
    data = op(**params)
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 955, in _make_api_call
    ) = self._resolve_endpoint_ruleset(
  File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1106, in _resolve_endpoint_ruleset
    endpoint_info = self._ruleset_resolver.construct_endpoint(
  File "/var/lang/lib/python3.11/site-packages/botocore/regions.py", line 512, in construct_endpoint
    raise botocore_exception from ex
END RequestId: <...>
```

**Comment by 232161233642** [comment]
I've been digging through the source and it looks like it errors out right before doing what I assume will be a [get_access_point](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3control/client/get_access_point.html) call - seems to stem from `op: <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.S3Control object at 0x7fa8f2705b50>>`, from [L56 in query.py](https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/query.py#L56)

**Comment by 232161233642** [comment]
(I also confirmed that passing in AccountId there does actually fix the prior error - for example if you change it to a junk value you get a validation error, and if a number it errors with `Value (AccountId) is the wrong type. Must be <class 'str'>.`)
