### ISSUE TITLE
encrypt-instance-volumes action failure on unattached volumes

### ISSUE THREAD

**Issue by albertodonato** [cloud-custodian/cloud-custodian#9823]
### Describe the bug

The `encrypt-instance-volumes` fails with the following traceback if an unencrypted EBS volume is not attached, as  the code is assuming that there is an attachment:

```
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
              ^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/c7n/resources/ebs.py", line 1170, in process
    instance_id = v['Attachments'][0]['InstanceId']
                  ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of rangeTraceback (most recent call last):
  File "/var/lang/lib/python3.11/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
              ^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/site-packages/c7n/resources/ebs.py", line 1170, in process
    instance_id = v['Attachments'][0]['InstanceId']
                  ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
 
This happens with `0.9.41`.

### What did you expect to happen?

The action should not fail, and encrypt the unattached volume

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
hmm.. there is an intent that action is only being used on attached volumes. this probably should guard against that by implicitly filtering and warning when used against unattached volumes.

**Comment by kapilt** [comment]
for unattached volumes, the guidance is just delete them.
