### ISSUE TITLE
Support for MSK auto-tagging

### ISSUE THREAD

**Issue by alberttwong** [cloud-custodian/cloud-custodian#9827]
### Describe the feature

I am always frustrated when ... MSK isn't auto-tagged

**Comment by alberttwong** [comment]
```
- name: msk-auto-tag-user
  resource: kafka
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/CloudCustodianRole
    # note {account_id} is optional. If you put that there instead of
    # your actual account number, when the policy is provisioned it
    # will automatically inherit the account_id properly
    events:
      - CreateClusterV2
  filters:
    - tag:Owner: absent
  actions:
    - type: auto-tag-user
      tag: Owner
      principal_id_tag: CreatorId
```

results
```
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/cli.py", line 368, in main
    command(config)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/commands.py", line 53, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/policy.py", line 71, in load
    [p.validate() for p in collection]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/policy.py", line 71, in <listcomp>
    [p.validate() for p in collection]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/policy.py", line 1251, in validate
    m.validate()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/c7n/policy.py", line 722, in validate
    assert e in CloudWatchEvents.trail_events, "event shortcut not defined: %s" % e
AssertionError: event shortcut not defined: CreateClusterV2
```
