### ISSUE TITLE
Azure SQL Database Encryption filters cause policy failure

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#9894]
### Describe the bug

I'm running an event based policy against azure.sql-database resource with only the transparent data encryption filter and it errors out about KeyError: 'c7n:parent-id

```
- name: check-sql-database-encryption-realtime
  resource: azure.sql-database
  description: This policy checks if Azure SQL databases have encryption disabled.
  mode:
    type: azure-event-grid
    events:
    - event: write
      resourceProvider: Microsoft.Sql/servers/databases
    - event: write
      resourceProvider: Microsoft.Sql/servers/databases/transparentDataEncryption
  filters:
    - type: transparent-data-encryption
      enabled: false
   ```

Error when running policy:

```
2024-12-27 21:35:41,881 - custodian.azure.sqldatabase - ERROR - Execution failed with error: 'c7n:parent-id'
2024-12-27 21:35:41,884 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
    File "/var/lang/lib/python3.11/site-packages/c7n_azure/policy.py", line 322, in run_for_event
      resources = policy.resource_manager.filter_resources(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/lang/lib/python3.11/site-packages/c7n/manager.py", line 113, in filter_resources
      resources = f.process(resources, event)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/lang/lib/python3.11/site-packages/c7n/filters/core.py", line 352, in process
      return self.process_set(resources, event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/lang/lib/python3.11/site-packages/c7n/filters/core.py", line 377, in process_set
      r[rtype_id] for r in f.process(resources, event)])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/lang/lib/python3.11/site-packages/c7n_azure/resources/sqldatabase.py", line 121, in process raise exceptions[0] File "/var/lang/lib/python3.11/concurrent/futures/thread.py", line 58, in run
      result = self.fn(*self.args, **self.kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/lang/lib/python3.11/site-packages/c7n_azure/resources/sqldatabase.py", line 129, in _process_resource_set
      server_id = resource[ChildTypeInfo.parent_key]
                  ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'c7n:parent-id'
```

### What did you expect to happen?

I expected it to match my SQL databases as I turned off the TDE

### Cloud Provider

Amazon Web Services (AWS)

**Comment by thisisshi** [comment]
Ah, this is due to the way that event mode policies extract the resource id from the event directly rather than iterating over the parents and then children as we do in pull mode
